import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).parent))
from lib import *
E = []
SN10 = lambda a, b=None: C("snell", 10, a, b)
BK7 = lambda a, b=None: C("berkowitz", 7, a, b)
BK23 = lambda a, b=None: C("berkowitz", 23, a, b)

def bg(id, name, meshes, summary, location, function, arteries, territories, imaging, lesion, exam, pearls, citations, syndromes=(), pitfalls=(), synonyms=(), latin=None, afferents=(), efferents=(), pathways=(), subdivisions=(), relations=None, system="basal-ganglia", sub=None):
    return structure(id, name, system, summary, location, function, arteries, imaging, lesion, exam, pearls, citations, subsystem=sub, meshIds=meshes,
        territories=territories, syndromes=syndromes, pitfalls=pitfalls, synonyms=synonyms, latin=latin, afferents=afferents, efferents=efferents, pathways=pathways, subdivisions=subdivisions, relations=relations, tags=["basal-ganglia"])

E.append(bg("caudate-nucleus", "Caudate nucleus", ["caudate-nucleus-l", "caudate-nucleus-r"], latin="Nucleus caudatus",
 summary="A C-shaped mass of gray matter that follows the lateral ventricle: a bulbous head in the wall of the frontal horn, a body along the floor of the ventricle above the thalamus, and a slender tail curving down into the roof of the temporal horn to end near the amygdala. With the putamen (to which it is joined by gray bridges across the anterior limb of the internal capsule) it forms the striatum, the input stage of the basal ganglia. The head receives prefrontal and association cortex and is the substrate of the cognitive and limbic loops; its atrophy flattens the frontal horns in Huntington disease, and lesions cause abulia, executive dysfunction and sometimes chorea rather than weakness.",
 location="Medial to the anterior limb of the internal capsule and lateral to the frontal horn (head), on the floor of the body of the lateral ventricle lateral to the thalamus (body), and in the roof of the temporal horn (tail); supplied by the recurrent artery of Heubner and the lenticulostriate arteries.",
 subdivisions=[("Head", "prefrontal, orbitofrontal and cingulate input; cognitive and limbic loops"), ("Body", "premotor and parietal association input"), ("Tail", "visual and auditory association input; ends at the amygdala")],
 relations={"medial": "frontal horn and body of the lateral ventricle", "lateral": "anterior limb of the internal capsule and putamen", "inferior": "thalamus (body) and temporal horn (tail)"},
 function="Input nucleus of the basal ganglia for the associative and limbic loops: goal-directed behaviour, learning of habits and reward, cognitive flexibility, eye movement control (caudate → substantia nigra pars reticulata → superior colliculus).",
 arteries=["arteries-lenticulostriate", "artery-aca", "artery-mca"], territories=["territory-lenticulostriate", "territory-aca"],
 imaging=img([view("axial", 14, 12, 12, "caudate head bulging into the frontal horn"), view("coronal", 14, 12, 12, "head of the caudate lateral to the frontal horn, medial to the internal capsule")],
     "The head is the gray matter indenting the lateral wall of the frontal horn on axial and coronal images; the body runs along the ventricular floor. Flattening or concavity of the frontal horn walls (loss of the caudate bulge) is the signature of Huntington disease; symmetric caudate and putamen T2 hyperintensity suggests toxic, metabolic or prion disease.",
     [pathol("Huntington disease", "MRI", "Bilateral caudate head atrophy giving boxcar frontal horns, with putaminal atrophy.", sequence="T1"), pathol("Caudate infarct", "MRI", "Restriction in the caudate head from Heubner's artery or lenticulostriate occlusion; abulia, confusion or contralateral chorea.", sequence="DWI"), pathol("Sporadic CJD", "MRI", "Bilateral caudate and putamen DWI hyperintensity (striatal ribbon) with cortical ribboning.", sequence="DWI"), pathol("Carbon monoxide, hypoglycemia, Wilson disease", "MRI", "Symmetric striatal T2 change; the globus pallidus is the CO target, the striatum the hypoglycemia target.", sequence="T2")],
     "Axial T1 (atrophy), DWI and FLAIR"),
 lesion=[("Abulia, apathy, executive dysfunction", "bilateral", "Prefrontal-caudate loop"), ("Contralateral chorea or dystonia", "contralateral", "Loss of striatal inhibition of the pallidum"), ("Obsessive-compulsive features", "bilateral", "Orbitofrontal-caudate circuit"), ("Impaired saccade initiation", "contralateral", "Caudate-nigral-collicular pathway")],
 exam=["Frontal executive tasks and initiative", "Observe for chorea at rest and with distraction (finger counting)", "Saccades on command", "Family history of movement disorder or dementia"],
 pearls=["Chorea with personality change and a family history: look at the caudate heads on the scan", "Caudate strokes present with behavioural change more than weakness"],
 citations=[SN10(310, 311), SN10(315, 316), BK7(55, 56), BK23(244, 245)], syndromes=["syn-huntington-chorea", "syn-lacunar-pure-motor"], pathways=["pathway-basal-ganglia-loops"], afferents=[("cortex-prefrontal and association cortex", None, "glutamatergic"), ("substantia-nigra (pars compacta)", "nigrostriatal pathway", "dopaminergic"), ("thalamus intralaminar nuclei", None)], efferents=[("globus-pallidus", None, "GABAergic direct and indirect pathways"), ("substantia-nigra (pars reticulata)", None)]))

E.append(bg("putamen", "Putamen", ["putamen-l", "putamen-r"], latin="Putamen",
 summary="The largest and most lateral basal ganglion, a convex shell of gray matter lateral to the globus pallidus (together forming the lentiform nucleus) and separated from the insula by the external capsule, claustrum and extreme capsule. With the caudate it forms the striatum, and its part of the striatum is the motor one: it receives the sensorimotor cortex and dopamine from the substantia nigra and projects to the pallidum through the direct and indirect pathways. It is the first target of Parkinson disease dopamine loss (posterior putamen), the site of the lenticulostriate hypertensive hemorrhage, and a common site of lacunar infarcts and of toxic and metabolic injury.",
 location="Lateral part of the lentiform nucleus, lateral to the external medullary lamina and globus pallidus, medial to the external capsule, claustrum and insula, and lateral to the internal capsule; connected to the caudate head anteriorly across the anterior limb.",
 function="Motor input stage of the basal ganglia: selects and scales movements through the direct (facilitatory) and indirect (inhibitory) pathways under dopaminergic modulation; motor habit learning.",
 arteries=["arteries-lenticulostriate", "artery-mca", "artery-anterior-choroidal"], territories=["territory-lenticulostriate"],
 imaging=img([view("axial", 25, 3, 2, "putamen lateral to the globus pallidus and internal capsule"), view("coronal", 25, 3, 2, "lentiform nucleus with the putamen lateral")],
     "Gray matter lateral to the darker (iron-rich) globus pallidus on axial T2; loses its normal outline early in MCA stroke (obscured lentiform nucleus sign). Bilateral symmetric putaminal signal change points to toxic, metabolic, mitochondrial or prion disease; a putaminal rim of T2 hyperintensity with atrophy suggests multiple system atrophy.",
     [pathol("Hypertensive putaminal hemorrhage", "CT", "Hyperdense hematoma centered on the putamen, extending medially into the capsule or into the ventricle.", sequence="CT non-contrast"), pathol("Lacunar infarct", "MRI", "Small restriction in the putamen or adjacent capsule.", sequence="DWI"), pathol("Multiple system atrophy (parkinsonian type)", "MRI", "Putaminal atrophy with a lateral T2-hyperintense rim and hypointensity of the posterior putamen.", sequence="T2"), pathol("Methanol or Wilson disease", "MRI", "Bilateral putaminal necrosis or T2 change.", sequence="T2"), pathol("Early MCA infarct", "CT", "Obscuration of the lentiform nucleus outline within hours.", sequence="CT non-contrast")],
     "CT for hemorrhage; DWI, T2 and SWI"),
 lesion=[("Contralateral hemiparesis with a large hemorrhage", "contralateral", "Extension into the internal capsule"), ("Parkinsonism", "contralateral", "Loss of dopaminergic input to the posterior putamen"), ("Dystonia, chorea or hemiballismus", "contralateral", "Striatal lesions disrupting the indirect pathway"), ("Bradykinesia and rigidity after bilateral necrosis", "bilateral", "Toxic injury (methanol, CO, Wilson)")],
 exam=["Rest tremor, rigidity with cogwheeling, bradykinesia with decrement on finger tapping", "Observe posture and gait, arm swing", "Look for dystonic posturing and chorea", "Blood pressure and cardiovascular risk"],
 pearls=["The putamen is the striatum's motor department: its disease produces movement disorders, the caudate's produces behavioural change", "Deep hemorrhage in a hypertensive patient is putaminal until proven otherwise"],
 citations=[SN10(310, 311), SN10(315, 318), BK7(55, 56), BK23(243, 250), C("berkowitz", 19, 192, 195)], syndromes=["syn-parkinsonism", "syn-hemiballismus", "syn-lacunar-pure-motor"], pathways=["pathway-basal-ganglia-loops"], afferents=[("gyrus-precentral and gyrus-postcentral", None, "sensorimotor cortex"), ("substantia-nigra (pars compacta)", "nigrostriatal pathway")], efferents=[("globus-pallidus", None, "direct and indirect pathways")]))

E.append(bg("globus-pallidus", "Globus pallidus", ["globus-pallidus-internus-l", "globus-pallidus-internus-r", "globus-pallidus-externus-l", "globus-pallidus-externus-r"], latin="Globus pallidus", synonyms=["pallidum", "paleostriatum"],
 summary="The medial, wedge-shaped part of the lentiform nucleus, paler than the putamen because of its myelinated fibers, divided by the internal medullary lamina into an external segment (GPe), a relay of the indirect pathway to the subthalamic nucleus, and an internal segment (GPi), the main output nucleus of the basal ganglia. GPi tonically inhibits the ventral anterior and ventral lateral thalamus through the ansa and fasciculus lenticularis; movement is released by pausing that inhibition. Its output is too active in Parkinson disease (hence pallidotomy and GPi stimulation help) and too weak in hemiballismus and chorea. It is rich in iron and is the target of carbon monoxide, hepatic disease and iron-accumulation disorders.",
 location="Medial part of the lentiform nucleus, between the putamen laterally and the posterior limb of the internal capsule medially, above the substantia innominata and anterior commissure; GPi lies medial to GPe.",
 subdivisions=[("External segment (GPe)", "receives striatal indirect-pathway input; projects to the subthalamic nucleus"), ("Internal segment (GPi)", "receives direct-pathway striatal input and subthalamic input; tonic GABAergic output to VA/VL thalamus (ansa lenticularis, lenticular fasciculus) and to the pedunculopontine nucleus")],
 function="Final output stage of the motor basal ganglia loop: sets the level of thalamocortical facilitation of movement; also part of the limbic loop through the ventral pallidum.",
 arteries=["arteries-lenticulostriate", "artery-anterior-choroidal"], territories=["territory-lenticulostriate", "territory-anterior-choroidal"],
 imaging=img([view("axial", 18, -2, -2, "globus pallidus medial to the putamen beside the posterior limb"), view("coronal", 18, -2, -2, "internal and external segments separated by the medial medullary lamina")],
     "Darker than the putamen on T2 and SWI because of iron; T1-bright pallidi are seen in liver failure (manganese) and after parenteral nutrition. Symmetric pallidal necrosis after carbon monoxide poisoning and the eye-of-the-tiger sign in pantothenate kinase deficiency are classic patterns.",
     [pathol("Carbon monoxide poisoning", "MRI", "Bilateral symmetric globus pallidus T2 hyperintensity/necrosis, sometimes with delayed white matter injury.", sequence="T2"), pathol("Hepatic encephalopathy / manganese", "MRI", "Bilateral symmetric T1 hyperintensity of the globus pallidus from manganese deposition in chronic liver disease or parenteral nutrition, without T2 change.", sequence="T1"), pathol("Neurodegeneration with brain iron accumulation", "MRI", "Eye-of-the-tiger sign: central T2 bright spot within a hypointense pallidum.", sequence="T2"), pathol("Kernicterus", "MRI", "Bilateral pallidal T2 hyperintensity in neonates.", sequence="T2")],
     "T2, SWI and T1"),
 lesion=[("Parkinsonism, apathy and reduced spontaneous movement", "bilateral", "Bilateral pallidal necrosis (CO, hypoxia)"), ("Dystonia", "contralateral", "Pallidal output disruption"), ("Improvement of parkinsonian rigidity and dyskinesia after GPi lesioning or stimulation", "contralateral", "Reduction of excessive inhibitory output")],
 exam=["Bradykinesia, rigidity, tremor", "Dystonic posturing", "Cognitive and behavioural change (apathy) after CO or anoxia"],
 pearls=["Symmetric pallidal lesions after coma: think carbon monoxide or anoxia", "The pallidum inhibits the thalamus; too much inhibition is parkinsonism, too little is chorea"],
 citations=[SN10(310, 315), BK7(55, 56), BK23(242, 250)], syndromes=["syn-parkinsonism", "syn-hemiballismus"], pathways=["pathway-basal-ganglia-loops"], afferents=[("putamen and caudate-nucleus", None, "GABAergic"), ("subthalamic-nucleus", None, "glutamatergic")], efferents=[("thalamus-va-vl", "ansa lenticularis and lenticular fasciculus (GPi)", "GABAergic"), ("subthalamic-nucleus", None, "from GPe"), ("pedunculopontine-nucleus", None)]))

E.append(bg("substantia-nigra", "Substantia nigra", ["substantia-nigra-l", "substantia-nigra-r", "substantia-nigra-pars-compacta-l", "substantia-nigra-pars-compacta-r", "substantia-nigra-pars-reticulata-l", "substantia-nigra-pars-reticulata-r"], system="brainstem", sub="midbrain", latin="Substantia nigra",
 summary="A pigmented band of neurons between the crus cerebri and the tegmentum of the midbrain, black in fresh specimens because its dopaminergic neurons contain neuromelanin. The pars compacta sends dopamine to the striatum (nigrostriatal pathway) and dies in Parkinson disease; the pars reticulata is a GABAergic output nucleus like the internal pallidum, controlling the thalamus and, through the superior colliculus, saccades. Its loss produces bradykinesia, rigidity, rest tremor and postural instability, and it is the site of the swallow-tail sign lost on susceptibility-weighted MRI.",
 location="Ventral midbrain tegmentum along the whole length of the midbrain, dorsal to the crus cerebri and ventral to the red nucleus and medial lemniscus, extending rostrally to the subthalamus.",
 subdivisions=[("Pars compacta", "densely packed dopaminergic neurons projecting to the striatum; degenerates in Parkinson disease, ventrolateral tier first"), ("Pars reticulata", "GABAergic output neurons projecting to the thalamus and superior colliculus; functionally continuous with the internal pallidum")],
 function="Dopaminergic modulation of striatal activity enabling movement initiation and reward learning (pars compacta); tonic inhibition of thalamus and superior colliculus controlling movement and saccades (pars reticulata).",
 arteries=["artery-pca", "arteries-thalamoperforating", "artery-basilar"], territories=["territory-pca", "territory-basilar-paramedian"],
 imaging=img([view("axial", 10, -20, -14, "substantia nigra behind the crus cerebri at the level of the red nucleus"), view("coronal", 10, -20, -14, "pigmented band between crus and tegmentum")],
     "A dark band behind the crus on T2 and SWI (iron), best seen at the level of the red nucleus; the dorsolateral nigral hyperintensity (swallow tail) on high-resolution SWI is lost in Parkinson disease, and neuromelanin-sensitive T1 shows reduced signal. Structural MRI is otherwise normal in idiopathic disease.",
     [pathol("Parkinson disease", "MRI", "Loss of the swallow-tail sign on SWI and of neuromelanin signal in the pars compacta; dopamine transporter SPECT shows reduced putaminal uptake.", sequence="SWI"), pathol("Midbrain infarct or hemorrhage", "MRI", "Paramedian midbrain lesion involving the nigra and adjacent structures: contralateral parkinsonism or hemiballismus with a third nerve palsy (Benedikt).", sequence="DWI"), pathol("Progressive supranuclear palsy", "MRI", "Midbrain atrophy (hummingbird sign) with nigral involvement.", sequence="T1")],
     "Axial SWI and T2 through the midbrain; dopamine transporter imaging"),
 lesion=[("Bradykinesia, rigidity, rest tremor, postural instability", "contralateral", "Loss of dopaminergic pars compacta neurons (symptoms appear after ~60% loss)"), ("Hemiparkinsonism after a unilateral lesion", "contralateral", "Unilateral nigral damage"), ("Anhedonia and reduced motivation", "bilateral", "Mesolimbic dopamine from the adjacent ventral tegmental area"), ("Hemiballismus or dystonia with tegmental lesions", "contralateral", "Adjacent subthalamic and pallidothalamic pathways")],
 exam=["Finger tapping with decrement, rapid alternating movements, foot tapping", "Rigidity at the wrist with activation", "Rest tremor with distraction", "Pull test and gait with arm swing", "Ask about anosmia, REM sleep behaviour disorder and constipation"],
 pearls=["Asymmetric onset of bradykinesia with rest tremor and a good levodopa response is Parkinson disease; symmetric onset with early falls suggests an atypical syndrome", "Neuroleptics block the same dopamine receptors and mimic nigral loss"],
 citations=[C("snell", 5, 212, 213), SN10(312), SN10(315, 318), BK7(55, 56), BK23(243, 250)], syndromes=["syn-parkinsonism", "syn-benedikt", "syn-weber"], pathways=["pathway-basal-ganglia-loops"], afferents=[("putamen and caudate-nucleus", None, "striatonigral GABAergic"), ("subthalamic-nucleus", None, "to pars reticulata")], efferents=[("putamen and caudate-nucleus", "nigrostriatal pathway", "dopamine"), ("thalamus-va-vl", None, "from pars reticulata"), ("superior-colliculus", None, "saccade gating")]))

E.append(bg("subthalamic-nucleus", "Subthalamic nucleus", ["subthalamic-nucleus-l", "subthalamic-nucleus-r"], latin="Nucleus subthalamicus", synonyms=["corpus Luysi", "STN"],
 summary="A small lens-shaped nucleus below the thalamus, above the substantia nigra and medial to the internal capsule as it becomes the crus. It is the only glutamatergic (excitatory) nucleus of the basal ganglia: it receives inhibitory input from the external pallidum in the indirect pathway and direct cortical input (the hyperdirect pathway), and drives the internal pallidum and nigral pars reticulata. Its destruction, classically by a lacunar infarct from posterior perforators, releases wild flinging movements of the opposite limbs (hemiballismus); its stimulation is the most widely used deep brain stimulation target for Parkinson disease.",
 location="Ventral to the thalamus and zona incerta, dorsomedial to the internal capsule and crus cerebri, rostral and dorsolateral to the substantia nigra, at the mesodiencephalic junction; about 12 mm lateral to the midline and 4 mm below the AC–PC line.",
 function="Excitatory driver of the basal ganglia output nuclei; braking and stopping of movement, selection among competing motor programs, and (through limbic and associative subregions) impulse control and mood.",
 arteries=["arteries-thalamoperforating", "artery-pcom", "artery-anterior-choroidal"], territories=["territory-pca", "territory-anterior-choroidal"],
 imaging=img([view("axial", 12, -12, -6, "subthalamic nucleus dorsomedial to the internal capsule at the mesodiencephalic junction"), view("coronal", 12, -12, -6, "STN above the substantia nigra, below the thalamus")],
     "A small hypointense (iron) oval on T2 and SWI dorsolateral to the red nucleus and above the nigra, best seen on coronal or axial 3 T images; it is the target on stereotactic planning MRI. The MASSP mesh in this atlas outlines it.",
     [pathol("Subthalamic infarct with hemiballismus", "MRI", "Small restricted-diffusion lesion in the subthalamic region from a posterior perforator.", sequence="DWI"), pathol("Deep brain stimulation electrode", "CT", "Electrode tip in the dorsolateral STN on post-operative CT fused to MRI.", sequence="CT non-contrast"), pathol("Non-ketotic hyperglycemia", "MRI", "Striatal T1 hyperintensity with hemichorea-hemiballismus (the striatum rather than the STN).", sequence="T1")],
     "DWI; T2/SWI for targeting"),
 lesion=[("Hemiballismus: violent flinging movements of the contralateral limbs", "contralateral", "Loss of subthalamic excitation of the internal pallidum reduces inhibition of the thalamus"), ("Improvement of bradykinesia, tremor and rigidity with stimulation", "contralateral", "Suppression of the overactive nucleus in Parkinson disease"), ("Impulse control disorders, mood change, weight gain after stimulation", "n/a", "Spread to limbic and associative subregions")],
 exam=["Observe for large-amplitude proximal flinging movements, worse with action", "Cardinal parkinsonian signs on and off stimulation", "Mood, impulsivity and gambling history in stimulated patients"],
 pearls=["Hemiballismus is a subthalamic lesion until proven otherwise; it usually settles over weeks and responds to dopamine blockers", "The STN is the brake: lose it and the limb flies, stimulate it and the parkinsonian brake is released"],
 citations=[SN10(312, 314), SN10(320), BK7(56), BK23(242, 245)], syndromes=["syn-hemiballismus", "syn-parkinsonism"], pathways=["pathway-basal-ganglia-loops"], afferents=[("globus-pallidus (external segment)", None, "GABAergic indirect pathway"), ("cortex-premotor-sma and gyrus-precentral", None, "hyperdirect pathway")], efferents=[("globus-pallidus (internal segment)", None, "glutamatergic"), ("substantia-nigra (pars reticulata)", None)]))

E.append(bg("claustrum", "Claustrum", ["claustrum-l", "claustrum-r"], latin="Claustrum",
 summary="A thin sheet of gray matter between the putamen and the insular cortex, separated from the putamen by the external capsule and from the insula by the extreme capsule. It is reciprocally connected with almost the entire cortex and has been proposed as a coordinator of cortical activity and of consciousness, but its clinical signature is meagre: it is involved in autoimmune and febrile encephalitides (the claustrum sign) and in some cases of status epilepticus, and its stimulation can suspend consciousness.",
 location="Deep to the insula, lateral to the putamen, a vertical plate of gray matter stretching from the level of the anterior commissure to the posterior end of the lentiform nucleus; the external capsule lies medial, the extreme capsule lateral.",
 function="Widespread reciprocal cortical connections suggesting a role in multisensory integration, attention and the binding of conscious experience; ventral claustrum connects with the amygdala and limbic cortex.",
 arteries=["artery-mca", "arteries-lenticulostriate"], territories=["territory-mca"],
 imaging=img([view("axial", 32, 2, 4, "thin gray sheet between the putamen and the insula"), view("coronal", 32, 2, 4, "claustrum between the external and extreme capsules")],
     "A thin vertical gray line between the external and extreme capsules on axial T1/T2, easiest to see on high-resolution 3 T images; symmetric FLAIR hyperintensity is the claustrum sign of encephalitis.",
     [pathol("Febrile infection-related epilepsy syndrome / autoimmune encephalitis", "MRI", "Bilateral symmetric claustrum FLAIR hyperintensity ('claustrum sign') with refractory status epilepticus.", sequence="FLAIR"), pathol("Insular-opercular infarct", "MRI", "Restriction of the insula and claustrum in an MCA branch occlusion.", sequence="DWI")],
     "Axial FLAIR"),
 lesion=[("Refractory seizures and altered consciousness with encephalitis", "bilateral", "Bilateral claustral inflammation"), ("No consistent focal syndrome", "n/a", "Diffuse connectivity; deficits attributed to adjacent insula and putamen")],
 exam=["Level of consciousness and seizure semiology in encephalitis", "Insular signs: taste, autonomic changes"],
 pearls=["Bilateral bright claustra on FLAIR in a febrile patient with refractory seizures is a recognized encephalitis pattern", "The claustrum is anatomy that outruns clinical knowledge; keep expectations modest"],
 citations=[SN10(312), SN10(310, 311)], pathways=[], afferents=[("widespread cortex", None)], efferents=[("widespread cortex", None)]))

E.append(bg("nucleus-accumbens", "Nucleus accumbens", ["nucleus-accumbens-l", "nucleus-accumbens-r"], latin="Nucleus accumbens", synonyms=["ventral striatum"],
 summary="The ventral striatum, where the head of the caudate and the putamen merge beneath the anterior limb of the internal capsule, next to the septal area. It receives dopamine from the ventral tegmental area (mesolimbic pathway) and input from the amygdala, hippocampus and prefrontal cortex, and projects to the ventral pallidum. It encodes reward prediction and motivation, is the substrate of addiction and of apathy, and is a target of deep brain stimulation for obsessive-compulsive disorder and depression.",
 location="Ventromedial striatum at the junction of the caudate head and putamen beneath the anterior limb of the internal capsule, lateral to the septal nuclei and above the olfactory tubercle, at the level of the anterior commissure.",
 subdivisions=[("Core", "motor aspects of motivated behaviour; projects to the ventral pallidum"), ("Shell", "limbic, connected with the hypothalamus and extended amygdala; drug reward")],
 function="Reward processing, motivation and incentive salience, reinforcement learning, integration of limbic drive into action.",
 arteries=["artery-aca", "arteries-lenticulostriate", "artery-acom"], territories=["territory-aca", "territory-lenticulostriate"],
 imaging=img([view("coronal", 10, 10, -8, "ventral striatum below the anterior limb of the internal capsule"), view("axial", 10, 10, -8, "junction of caudate head and putamen at the level of the anterior commissure")],
     "Gray matter bridging the caudate and putamen ventrally on coronal T1 at the level of the anterior commissure; the MASSP mesh in this atlas outlines it. Rarely abnormal on routine imaging.",
     [pathol("Ventral striatal infarct (Heubner's artery)", "MRI", "Restriction of the caudate head and ventral striatum; abulia and apathy.", sequence="DWI"), pathol("Deep brain stimulation for OCD", "CT", "Electrode in the ventral striatum/anterior limb.", sequence="CT non-contrast")],
     "DWI; coronal T1"),
 lesion=[("Apathy, anhedonia, loss of motivation", "bilateral", "Loss of reward signalling"), ("Addiction and compulsive behaviours (dysfunction rather than lesion)", "n/a", "Sensitized mesolimbic dopamine"), ("Improvement of obsessive-compulsive symptoms with stimulation", "n/a", "Modulation of the cortico-striatal loop")],
 exam=["Motivation and interest on history from patient and family", "Screen for substance use and compulsive behaviours", "Frontal executive tasks"],
 pearls=["Apathy after a caudate or ventral striatal stroke is a lesion, not depression; it responds poorly to antidepressants and better to dopaminergic drugs", "Dopamine agonists can produce compulsive gambling through this circuit"],
 citations=[SN10(311), C("snell", 9, 305, 306), BK7(55, 56)], pathways=["pathway-basal-ganglia-loops"], afferents=[("ventral-tegmental-area", "mesolimbic pathway", "dopamine"), ("amygdala", None), ("hippocampus", None), ("cortex-prefrontal", None)], efferents=[("ventral pallidum", None), ("hypothalamus", None)]))

write(E)
