import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).parent))
from lib import *
E = []

def pw(id, name, type_, modality, summary, origin, chain, decussation, waypoints, termination, lesions, pearls, citations, somatotopy=None, meshes=(), syndromes=(), synonyms=(), imaging=None):
    d = {"kind": "pathway", "id": id, "name": name, "synonyms": list(synonyms), "type": type_, "modality": modality, "summary": summary,
         "origin": {"structures": origin[0], "note": origin[1]},
         "neuronChain": [{"order": i + 1, "cellBody": a, "synapse": b} for i, (a, b) in enumerate(chain)],
         "decussation": ({"level": decussation[0], **({"structureId": decussation[1]} if decussation[1] else {}), "note": decussation[2]} if decussation else None),
         "waypoints": [{"order": i + 1, "structureId": w[0], **({"meshId": w[1]} if w[1] else {}), "sideRelativeToOrigin": w[2], **({"note": w[3]} if len(w) > 3 else {})} for i, w in enumerate(waypoints)],
         "termination": termination, "meshIds": list(meshes),
         "lesionEffectsByLevel": [{"level": a, "effects": b, "side": c} for a, b, c in lesions],
         "clinical": {"pearls": list(pearls), "syndromes": list(syndromes)}, "citations": citations, "status": "draft"}
    if somatotopy: d["somatotopy"] = somatotopy
    if imaging: d["imaging"] = imaging
    return d

E.append(pw("pathway-lateral-corticospinal", "Lateral corticospinal tract", "descending", "voluntary skilled movement of the limbs",
 "The main voluntary motor pathway. Pyramidal neurons of the motor and premotor cortex send axons through the corona radiata, the posterior limb of the internal capsule, the middle of the crus cerebri and the basis pontis to the medullary pyramid, where about 85–90% cross in the pyramidal decussation to descend in the lateral funiculus of the cord as the lateral corticospinal tract, ending on interneurons and, for the hand, directly on motor neurons of the anterior horn. Because the crossing happens at the cervicomedullary junction, a lesion anywhere above it weakens the opposite side of the body and a lesion below it the same side, and the accompanying signs of the neighbours (face, cranial nerves, sensation) give the level.",
 (["gyrus-precentral", "cortex-premotor-sma", "gyrus-postcentral"], "Roughly a third each from the primary motor cortex, premotor/SMA and the somatosensory cortex; Betz cells contribute a small fraction of the fibers."),
 [("Upper motor neuron: pyramidal cells in cortical layer V", "on spinal interneurons and directly on alpha motor neurons (corticomotoneuronal, hand)"), ("Lower motor neuron: anterior horn cell", "at the neuromuscular junction")],
 ("Pyramidal decussation, cervicomedullary junction", "pyramid", "About 85–90% of fibers cross; the arm fibers cross rostral to the leg fibers, the basis of cruciate paralysis."),
 [("gyrus-precentral", "gyrus-precentral-l", "ipsilateral", "origin in the motor cortex, somatotopic"), ("corona-radiata", "cerebral-white-matter-l", "ipsilateral"), ("internal-capsule", "internal-capsule-l", "ipsilateral", "posterior limb: face at the genu, arm anterior, leg posterior"), ("cerebral-peduncle-crus", "brainstem", "ipsilateral", "middle three-fifths of the crus"), ("pontine-nuclei", "brainstem", "ipsilateral", "dispersed bundles among the pontine nuclei in the basis pontis"), ("pyramid", "brainstem", "ipsilateral", "compact tract on the ventral medulla"), ("level-medulla-pyramidal-decussation", "brainstem", "contralateral", "pyramidal decussation"), ("spinal-white-columns", "spinal-cord", "contralateral", "lateral funiculus, medial to the spinocerebellar tract; leg fibers lateral"), ("spinal-grey-anterior-horn", "spinal-cord", "contralateral", "termination on interneurons and motor neurons")],
 "Interneurons of the intermediate gray and alpha motor neurons of the anterior horn at every level of the cord, most densely in the cervical and lumbosacral enlargements.",
 [("Cortex or corona radiata", "Contralateral weakness following the homunculus (face and arm on the convexity, leg medially), often with cortical signs; seizures", "contralateral"), ("Internal capsule", "Dense contralateral hemiparesis of face, arm and leg with no cortical signs (pure motor stroke)", "contralateral"), ("Midbrain crus", "Contralateral hemiparesis with ipsilateral third nerve palsy (Weber)", "contralateral"), ("Pons", "Contralateral hemiparesis with ipsilateral VI or VII palsy (Millard–Gubler, Foville); bilateral: locked-in", "contralateral"), ("Medulla above the decussation", "Contralateral hemiparesis sparing the face with ipsilateral tongue weakness (medial medullary)", "contralateral"), ("Spinal cord below the decussation", "Ipsilateral upper motor neuron weakness below the level (Brown-Séquard)", "ipsilateral")],
 ["Upper motor neuron signs (spasticity, hyperreflexia, Babinski, clonus) mark the tract; lower motor neuron signs mark the anterior horn or nerve", "Weakness with a cranial nerve palsy on the opposite side is the brainstem; with a sensory level and no face involvement, the cord", "Fine independent finger movements are the first and last casualty of corticospinal lesions because the direct corticomotoneuronal connections serve them"],
 [R("sp-lateral-corticospinal-tract"), R("sp-pyramidal-tract"), R("sp-pyramidal-tract-lesions")], somatotopy="Cortex: leg medial, arm and face lateral. Internal capsule: face anterior (genu), then arm, then leg. Crus: face medial, leg lateral. Cord: arm fibers medial, leg fibers lateral within the tract, so an expanding central cord lesion hits the arms first and extrinsic compression the legs first.",
 meshes=["tract-corticospinal-l", "tract-corticospinal-r"], syndromes=["syn-lacunar-pure-motor", "syn-weber", "syn-millard-gubler", "syn-dejerine-medial-medullary", "syn-brown-sequard", "syn-locked-in"], synonyms=["pyramidal tract"],
 imaging=img([view("axial", 20, -10, 10, "posterior limb of the internal capsule"), view("axial", 8, -20, -12, "middle of the crus cerebri"), view("axial", 4, -46, -48, "pyramid on the ventral medulla")], "The tract is followed on the HCP1065 mesh in this atlas from the motor cortex through the capsule, crus, pons and pyramid. Wallerian degeneration after a stroke makes it T2-bright and atrophic along its whole length below the lesion; in ALS it is symmetrically T2-bright in the posterior limb and crus.", [pathol("Wallerian degeneration", "MRI", "T2 hyperintensity and atrophy of the ipsilateral capsule, crus and pyramid weeks after a large hemispheric infarct.", sequence="T2"), pathol("Amyotrophic lateral sclerosis", "MRI", "Bilateral symmetric T2/FLAIR hyperintensity of the corticospinal tracts from the corona radiata to the brainstem with precentral iron on SWI.", sequence="FLAIR")])))

E.append(pw("pathway-anterior-corticospinal", "Anterior corticospinal tract", "descending", "axial and proximal muscle control",
 "The 10–15% of pyramidal fibers that do not cross in the medulla continue down the anterior funiculus beside the anterior median fissure as the anterior (ventral) corticospinal tract. Most of them cross at their segment of termination through the anterior white commissure to reach motor neurons of the trunk and proximal limb muscles, and some end bilaterally, so axial muscles have bilateral cortical control. This is why trunk and neck strength are relatively preserved in hemiplegia and why bilateral corticospinal lesions are needed to paralyse the trunk.",
 (["gyrus-precentral", "cortex-premotor-sma"], "Mainly from the trunk and proximal limb areas of the motor cortex and the supplementary motor area."),
 [("Pyramidal cell in the motor cortex", "on spinal interneurons and medial motor neurons after crossing in the anterior white commissure"), ("Anterior horn cell (medial motor column)", "neuromuscular junction")],
 ("Anterior white commissure at the segmental level", "spinal-white-columns", "Uncrossed in the medulla; crosses segmentally, some fibers remain uncrossed."),
 [("gyrus-precentral", "gyrus-precentral-l", "ipsilateral"), ("internal-capsule", "internal-capsule-l", "ipsilateral"), ("pyramid", "brainstem", "ipsilateral", "passes the decussation uncrossed"), ("spinal-white-columns", "spinal-cord", "ipsilateral", "anterior funiculus beside the anterior median fissure, cervical and upper thoracic segments mainly"), ("spinal-grey-anterior-horn", "spinal-cord", "bilateral", "medial motor column via the anterior white commissure")],
 "Medial motor neurons and interneurons of the cervical and upper thoracic cord for the neck, trunk and proximal limb muscles, bilaterally.",
 [("Unilateral lesion anywhere", "Little detectable deficit because of the bilateral projection", "bilateral"), ("Bilateral lesions (bilateral strokes, cervical myelopathy)", "Loss of trunk control and postural stability with truncal weakness", "bilateral")],
 ["Axial muscles have bilateral cortical control; unilateral strokes spare trunk and neck strength", "The tract mostly ends in the cervical and upper thoracic cord and is often absent below"],
 [R("sp-corticospinal-cord-tract"), R("sp-pyramidal-tract")], meshes=["tract-corticospinal-l", "tract-corticospinal-r"], syndromes=["syn-complete-transection-spinal-shock"], synonyms=["ventral corticospinal tract", "uncrossed pyramidal tract"]))

E.append(pw("pathway-corticobulbar", "Corticobulbar tract", "descending", "voluntary control of the face, tongue, jaw, palate, pharynx and larynx",
 "Corticobulbar fibers arise from the face and mouth areas of the motor cortex, descend with the corticospinal tract through the genu of the internal capsule and the medial crus, and peel off in the brainstem to the motor nuclei of V, VII, IX, X, XI and XII. The projection is bilateral to most nuclei, but mainly contralateral to the lower facial subnucleus and the hypoglossal nucleus (genioglossus), which is why a hemispheric stroke gives lower-face weakness with a spared forehead and a tongue that deviates away from the lesion, while bilateral lesions produce pseudobulbar palsy with a brisk jaw jerk, spastic dysarthria, dysphagia and emotional lability.",
 (["gyrus-precentral", "cortex-premotor-sma"], "Lower part of the precentral gyrus (face, tongue, larynx areas) and the frontal operculum."),
 [("Pyramidal cell in the lateral motor cortex", "on interneurons around and on the cranial nerve motor nuclei"), ("Cranial nerve motor neuron", "neuromuscular junction")],
 ("At the level of each nucleus", None, "Bilateral to V, upper VII, IX, X, XI; mainly contralateral to lower VII and XII."),
 [("gyrus-precentral", "gyrus-precentral-l", "ipsilateral", "face area above the Sylvian fissure"), ("internal-capsule", "internal-capsule-l", "ipsilateral", "genu"), ("cerebral-peduncle-crus", "brainstem", "ipsilateral", "medial to the corticospinal fibers"), ("trigeminal-nuclei", "brainstem", "bilateral", "motor nucleus of V"), ("facial-motor-nucleus", "brainstem", "bilateral", "upper face bilateral, lower face contralateral"), ("nucleus-ambiguus", "brainstem", "bilateral"), ("hypoglossal-nucleus", "brainstem", "contralateral", "mainly contralateral to genioglossus")],
 "Motor nuclei of the trigeminal, facial, glossopharyngeal, vagus, accessory and hypoglossal nerves.",
 [("Unilateral hemispheric or capsular lesion", "Contralateral lower facial weakness with spared forehead; tongue deviates away from the lesion; mild dysarthria; no dysphagia", "contralateral"), ("Bilateral lesions (bilateral strokes, ALS, MS)", "Pseudobulbar palsy: spastic dysarthria, dysphagia, brisk jaw jerk and gag, emotional lability", "bilateral"), ("Pontine lesion below the facial nucleus", "Not corticobulbar: lower motor neuron facial palsy with contralateral limb weakness", "n/a")],
 ["Forehead sparing is the fingerprint of a corticobulbar (upper motor neuron) facial palsy", "Pseudobulbar palsy needs two lesions: look for bilateral capsular or pontine strokes, or motor neuron disease", "Emotional facial movements survive corticobulbar lesions because they use a separate limbic-brainstem route"],
 [R("sp-corticobulbar-tract")], meshes=["tract-corticobulbar-l", "tract-corticobulbar-r"], syndromes=["syn-facial-palsy-peripheral-vs-central", "syn-bulbar-vs-pseudobulbar", "syn-lacunar-dysarthria-clumsy-hand"], synonyms=["corticonuclear tract"]))

E.append(pw("pathway-dcml", "Dorsal column–medial lemniscus pathway", "ascending", "discriminative touch, vibration, conscious proprioception",
 "Large myelinated fibers from mechanoreceptors and proprioceptors enter through the dorsal root and ascend uncrossed in the posterior columns (fasciculus gracilis for the leg and lower trunk, fasciculus cuneatus for the arm) to the gracile and cuneate nuclei in the lower medulla. Second-order axons cross as the internal arcuate fibers (sensory decussation) to form the medial lemniscus, which ascends through the brainstem to the ventral posterolateral nucleus of the thalamus, whose neurons project through the posterior limb of the internal capsule to the postcentral gyrus. The pathway crosses in the medulla, so cord lesions give ipsilateral loss and brainstem lesions contralateral loss, and its separation from the spinothalamic tract in the cord explains dissociated sensory loss.",
 (["dorsal-root-ganglion"], "Pacinian and Meissner corpuscles, muscle spindles, Golgi tendon organs and joint receptors; cell bodies in the dorsal root ganglia."),
 [("Dorsal root ganglion cell", "gracile or cuneate nucleus"), ("Gracile/cuneate nucleus neuron", "VPL of the thalamus after crossing in the medial lemniscus"), ("VPL thalamic neuron", "layer IV of the postcentral gyrus")],
 ("Sensory (lemniscal) decussation, lower medulla", "level-medulla-sensory-decussation", "Internal arcuate fibers cross just above the pyramidal decussation."),
 [("dorsal-root-ganglion", None, "ipsilateral", "first-order neuron"), ("spinal-white-columns", "spinal-cord", "ipsilateral", "posterior funiculus: gracilis medial (leg), cuneatus lateral (arm)"), ("nucleus-gracilis-cuneatus", "brainstem", "ipsilateral", "second-order neurons"), ("level-medulla-sensory-decussation", "brainstem", "contralateral", "internal arcuate fibers cross"), ("medial-lemniscus", "tract-medial-lemniscus-l", "contralateral", "ascends through pons and midbrain, rotating from vertical to horizontal"), ("thalamus-vpl", "thalamus-ventral-posterior-ventrolateral-l", "contralateral", "third-order relay"), ("internal-capsule", "internal-capsule-l", "contralateral", "posterior limb, superior thalamic radiation"), ("gyrus-postcentral", "gyrus-postcentral-l", "contralateral", "primary somatosensory cortex, areas 3b, 1, 2")],
 "Primary somatosensory cortex of the postcentral gyrus, somatotopically, with onward projection to the parietal association cortex.",
 [("Peripheral nerve or dorsal root", "Loss of vibration and position sense in the nerve or dermatome distribution with areflexia", "ipsilateral"), ("Posterior columns (B12 deficiency, tabes, MS, posterior cord infarct)", "Ipsilateral loss below the level, sensory ataxia, Romberg positive, Lhermitte sign", "ipsilateral"), ("Medulla above the decussation, pons, midbrain", "Contralateral loss of vibration and proprioception, usually with other brainstem signs", "contralateral"), ("Thalamus (VPL)", "Contralateral loss of all modalities including pain and temperature", "contralateral"), ("Parietal cortex", "Loss of discriminative functions (two-point, graphesthesia, stereognosis) with preserved primary modalities", "contralateral")],
 ["Vibration and position sense lost on the same side as the lesion means the cord; on the opposite side, the brainstem or above", "Sensory ataxia gets dramatically worse with the eyes closed (Romberg); cerebellar ataxia does not", "The posterior columns are where B12 deficiency, HIV and copper deficiency strike; check them in every ataxic patient"],
 [R("sp-posterior-column"), R("sp-medial-lemniscus"), R("sp-spinocerebellar-dorsal-tract")], somatotopy="Cord: sacral fibers medial, cervical lateral (gracilis medial, cuneatus lateral). Medulla: leg ventral, arm dorsal in the forming lemniscus. Pons and midbrain: arm medial, leg lateral. Thalamus and cortex: standard homunculus.",
 meshes=["tract-medial-lemniscus-l", "tract-medial-lemniscus-r"], syndromes=["syn-posterior-cord-subacute-combined", "syn-brown-sequard", "syn-dejerine-medial-medullary", "syn-lacunar-pure-sensory"], synonyms=["posterior column pathway", "lemniscal system"]))

E.append(pw("pathway-lateral-spinothalamic", "Lateral spinothalamic tract", "ascending", "pain and temperature",
 "Small myelinated and unmyelinated pain and temperature fibers end in the dorsal horn (laminae I, II and V) within a segment or two of their entry; second-order neurons cross in the anterior white commissure over one to two segments and ascend in the anterolateral funiculus as the spinothalamic tract, joined in the brainstem by spinoreticular and spinomesencephalic fibers, to the ventral posterolateral thalamus and then the somatosensory cortex and insula. The early crossing is the key: cord lesions cause contralateral loss beginning one or two segments below the lesion, and a central cord lesion catches the crossing fibers of both sides for a band of dissociated loss.",
 (["dorsal-root-ganglion", "spinal-grey-posterior-horn"], "Free nerve endings (nociceptors and thermoreceptors); A-delta and C fibers; cell bodies in the dorsal root ganglia; second-order cells in the dorsal horn."),
 [("Dorsal root ganglion cell", "dorsal horn laminae I, II and V (via Lissauer's tract)"), ("Dorsal horn projection neuron", "VPL thalamus (also intralaminar nuclei and reticular formation)"), ("VPL thalamic neuron", "postcentral gyrus and insula")],
 ("Anterior white commissure, 1–2 segments above entry", "spinal-white-columns", "Second-order axons cross obliquely; a syrinx damages them here."),
 [("dorsal-root-ganglion", None, "ipsilateral", "first-order neuron"), ("spinal-grey-posterior-horn", "spinal-cord", "ipsilateral", "synapse in the substantia gelatinosa and nucleus proprius"), ("spinal-white-columns", "spinal-cord", "contralateral", "crosses in the anterior white commissure; ascends in the anterolateral funiculus, sacral fibers lateral"), ("level-medulla-olive", "brainstem", "contralateral", "lateral medulla, dorsal to the olive"), ("level-pons-caudal", "brainstem", "contralateral", "lateral tegmentum with the spinal lemniscus"), ("level-midbrain-superior-colliculus", "brainstem", "contralateral", "lateral tegmentum beside the medial lemniscus"), ("thalamus-vpl", "thalamus-ventral-posterior-ventrolateral-l", "contralateral"), ("gyrus-postcentral", "gyrus-postcentral-l", "contralateral", "with projections to the insula and cingulate for the affective dimension of pain")],
 "Ventral posterolateral nucleus of the thalamus (discriminative pain), intralaminar nuclei and reticular formation (arousal and affect), periaqueductal gray (descending modulation).",
 [("Peripheral nerve or root", "Loss in the nerve or dermatome distribution, often with pain", "ipsilateral"), ("Central cord (syrinx)", "Bilateral cape-like dissociated loss of pain and temperature at the involved segments with preserved touch and vibration", "bilateral"), ("Hemicord (Brown-Séquard)", "Contralateral loss starting one to two segments below the lesion", "contralateral"), ("Lateral medulla (Wallenberg)", "Contralateral body loss with ipsilateral facial loss (spinal trigeminal tract)", "contralateral"), ("Pons and midbrain lateral tegmentum", "Contralateral hemianalgesia of face and body", "contralateral"), ("Thalamus", "Contralateral loss of all modalities, later central pain", "contralateral")],
 ["Pain and temperature loss on the opposite side to weakness and proprioceptive loss is the hemicord", "The sensory level for pin-prick is one to two segments below the true lesion", "Sacral sparing means an intramedullary lesion: the sacral fibers lie most laterally"],
 [R("sp-spinothalamic-tract")], somatotopy="Cord: sacral fibers lateral and superficial, cervical medial (the reverse of the posterior columns). Brainstem: leg lateral, arm medial.",
 meshes=["brainstem"], syndromes=["syn-brown-sequard", "syn-central-cord-syringomyelia", "syn-wallenberg-lateral-medullary", "syn-anterior-cord"], synonyms=["anterolateral system", "spinal lemniscus"]))

E.append(pw("pathway-anterior-spinothalamic", "Anterior spinothalamic tract", "ascending", "crude (non-discriminative) touch and pressure",
 "Fibers carrying light touch and pressure that do not require fine localization end in the dorsal horn, cross in the anterior white commissure and ascend in the anterior funiculus as the anterior spinothalamic tract, merging with the lateral spinothalamic tract in the brainstem as the spinal lemniscus. Because crude touch travels both here and in the posterior columns, touch is rarely lost completely by a single cord lesion, which is why pain and temperature (single route) and vibration and position (single route) are the discriminating modalities in cord examination.",
 (["dorsal-root-ganglion", "spinal-grey-posterior-horn"], "Low-threshold mechanoreceptors; second-order cells in the nucleus proprius."),
 [("Dorsal root ganglion cell", "dorsal horn (nucleus proprius)"), ("Dorsal horn neuron", "VPL thalamus after crossing"), ("VPL neuron", "postcentral gyrus")],
 ("Anterior white commissure over several segments", "spinal-white-columns", "Crosses less abruptly than the pain fibers."),
 [("dorsal-root-ganglion", None, "ipsilateral"), ("spinal-grey-posterior-horn", "spinal-cord", "ipsilateral"), ("spinal-white-columns", "spinal-cord", "contralateral", "anterior funiculus"), ("medial-lemniscus", "tract-medial-lemniscus-l", "contralateral", "joins the spinal lemniscus and runs beside the medial lemniscus in the brainstem"), ("thalamus-vpl", "thalamus-ventral-posterior-ventrolateral-l", "contralateral"), ("gyrus-postcentral", "gyrus-postcentral-l", "contralateral")],
 "Ventral posterolateral nucleus of the thalamus and the somatosensory cortex.",
 [("Hemicord lesion", "Crude touch largely preserved on both sides because of the dual pathway", "n/a"), ("Anterior cord infarct", "Loss of pain, temperature and crude touch below the level with preserved posterior column function", "bilateral")],
 ["Test pain and vibration, not light touch, when localizing a cord lesion: touch has two routes and stays", "The anterior spinothalamic tract is the reason 'sensory loss' after a cord lesion is rarely total"],
 [R("sp-spinothalamic-tract")], meshes=["brainstem"], syndromes=["syn-anterior-cord"], synonyms=["ventral spinothalamic tract"]))

E.append(pw("pathway-trigeminothalamic", "Trigeminal sensory pathways", "ascending", "touch, pain, temperature and proprioception of the face",
 "Facial sensation uses the same logic as body sensation but with the trigeminal nuclei standing in for the dorsal horn and dorsal column nuclei. Touch fibers end in the principal sensory nucleus in the pons; pain and temperature fibers descend in the spinal trigeminal tract to the spinal nucleus in the medulla and upper cervical cord; jaw proprioception has its cell bodies in the mesencephalic nucleus. Second-order axons cross to form the trigeminal lemniscus (ventral trigeminothalamic tract), which ascends beside the medial lemniscus to the ventral posteromedial thalamus and then to the face area of the postcentral gyrus. The long descending tract is why facial pain loss is ipsilateral in lateral medullary lesions and why it is the face, not the body, that gives the crossed pattern.",
 (["ganglion-trigeminal"], "Cell bodies of all modalities except jaw proprioception in the trigeminal ganglion; jaw spindle afferents in the mesencephalic nucleus."),
 [("Trigeminal ganglion cell (or mesencephalic nucleus)", "principal sensory nucleus (touch) or spinal trigeminal nucleus (pain, temperature)"), ("Trigeminal nuclear neuron", "VPM thalamus after crossing in the trigeminal lemniscus"), ("VPM neuron", "face area of the postcentral gyrus")],
 ("Pons and medulla, at the level of each nucleus", "brainstem", "Most second-order fibers cross; a small dorsal trigeminothalamic bundle from the principal nucleus stays ipsilateral."),
 [("ganglion-trigeminal", "ophthalmic-nerve-l", "ipsilateral", "first-order neurons"), ("cn-05-trigeminal", "cn-05-trigeminal-l", "ipsilateral", "root entry at the mid-pons"), ("trigeminal-nuclei", "brainstem", "ipsilateral", "touch to the principal nucleus"), ("spinal-trigeminal-nucleus-tract", "brainstem", "ipsilateral", "pain and temperature descend to the spinal nucleus (pars caudalis)"), ("medial-lemniscus", "tract-medial-lemniscus-l", "contralateral", "trigeminal lemniscus ascends medial to the spinothalamic tract"), ("thalamus-vpm", "thalamus-ventral-posterior-ventrolateral-l", "contralateral"), ("gyrus-postcentral", "gyrus-postcentral-l", "contralateral", "lower part of the postcentral gyrus")],
 "Ventral posteromedial nucleus of the thalamus and the face region of the primary somatosensory cortex.",
 [("Nerve, ganglion or root", "Ipsilateral loss of all modalities in the divisions involved", "ipsilateral"), ("Lateral medulla", "Ipsilateral loss of facial pain and temperature with preserved touch; contralateral body loss", "ipsilateral"), ("Upper cervical cord (C2–C3)", "Onion-skin loss over the posterior face and scalp", "ipsilateral"), ("Rostral pons (principal nucleus or lemniscus)", "Loss of facial touch; above the pons all facial modalities are lost contralaterally with the body", "n/a"), ("Thalamus (VPM) or cortex", "Contralateral facial numbness together with the body, same side", "contralateral")],
 ["Face and body numb on the same side: thalamus or cortex. Face one side, body the other: lateral brainstem", "Dissociated facial sensory loss (pain lost, touch kept) puts the lesion in the descending trigeminal system", "The corneal reflex tests the trigeminal pathway at its most sensitive point"],
 [R("sp-trigeminal-nucleus"), R("sp-cranial-nerve-5"), R("sp-spinothalamic-tract")], somatotopy="Spinal nucleus: onion-skin arrangement with perioral regions rostral and peripheral face caudal; divisions inverted (V3 dorsal, V1 ventral) in the tract.",
 meshes=["cn-05-trigeminal-l", "cn-05-trigeminal-r"], syndromes=["syn-wallenberg-lateral-medullary", "syn-trigeminal-neuralgia", "syn-central-cord-syringomyelia"], synonyms=["trigeminal lemniscus", "ventral and dorsal trigeminothalamic tracts"]))

E.append(pw("pathway-posterior-spinocerebellar", "Posterior spinocerebellar tract", "ascending", "unconscious proprioception from the leg and lower trunk",
 "Proprioceptive fibers from muscle spindles, tendon organs and joints of the leg and trunk end in Clarke's column (nucleus dorsalis, C8–L3); its neurons send uncrossed axons up the lateral funiculus as the posterior spinocerebellar tract into the inferior cerebellar peduncle to the vermis and paravermis. The arm equivalent is the cuneocerebellar tract from the accessory cuneate nucleus. The pathway is uncrossed and carries information the cerebellum uses to coordinate the same-side limb, so lesions produce ipsilateral ataxia without conscious sensory loss.",
 (["dorsal-root-ganglion", "spinal-grey-posterior-horn"], "Muscle spindle and Golgi tendon organ afferents from the leg and lower trunk; second-order neurons in Clarke's column (lamina VII)."),
 [("Dorsal root ganglion cell", "Clarke's column (nucleus dorsalis)"), ("Clarke's column neuron", "cerebellar cortex of the vermis and intermediate zone as mossy fibers")],
 None,
 [("dorsal-root-ganglion", None, "ipsilateral"), ("spinal-grey-posterior-horn", "spinal-cord", "ipsilateral", "Clarke's column at the base of the dorsal horn, C8–L3 (fibers from below L3 ascend in the fasciculus gracilis first)"), ("spinal-white-columns", "spinal-cord", "ipsilateral", "posterior part of the lateral funiculus, superficial"), ("inferior-cerebellar-peduncle", "inferior-cerebellar-peduncle-l", "ipsilateral"), ("cerebellar-vermis", "cerebellar-vermis-vi", "ipsilateral", "anterior lobe and paravermis")],
 "Cerebellar cortex of the ipsilateral vermis and intermediate zone (spinocerebellum) as mossy fibers, with collaterals to the deep nuclei.",
 [("Lateral funiculus of the cord (Friedreich ataxia, hemicord lesion)", "Ipsilateral limb ataxia without conscious sensory loss (in Friedreich the posterior columns are also lost)", "ipsilateral"), ("Inferior cerebellar peduncle or medulla", "Ipsilateral limb and gait ataxia (part of the lateral medullary syndrome)", "ipsilateral")],
 ["Spinocerebellar tracts are uncrossed: ataxia from cord or medullary lesions is ipsilateral", "Friedreich ataxia destroys both the spinocerebellar tracts and the posterior columns, giving mixed cerebellar and sensory ataxia"],
 [R("sp-spinocerebellar-dorsal-tract"), R("sp-posterior-column")], meshes=["inferior-cerebellar-peduncle-l", "inferior-cerebellar-peduncle-r"], syndromes=["syn-wallenberg-lateral-medullary", "syn-cerebellar-hemispheric"], synonyms=["dorsal spinocerebellar tract", "Flechsig's tract"]))

E.append(pw("pathway-anterior-spinocerebellar", "Anterior spinocerebellar tract", "ascending", "proprioceptive and interneuronal feedback from the lower limb",
 "Neurons at the base of the dorsal horn and in the intermediate gray of the lumbosacral cord send axons that mostly cross in the anterior white commissure, ascend in the anterolateral funiculus in front of the posterior spinocerebellar tract, pass through the medulla and pons, and enter the cerebellum through the superior cerebellar peduncle, where most cross back so that each side of the cerebellum still receives information from its own side of the body. It carries less pure proprioception and more information about the activity of spinal interneurons, telling the cerebellum what the spinal circuits are doing with the descending commands.",
 (["spinal-grey-posterior-horn"], "Spinal border cells and intermediate gray of the lumbosacral segments; input from Golgi tendon organs, flexor reflex afferents and descending tracts."),
 [("Dorsal root ganglion cell", "spinal border cells"), ("Spinal border cell", "cerebellar cortex of the anterior lobe (vermis and paravermis) via the superior cerebellar peduncle, crossing twice")],
 ("Anterior white commissure (crosses) and superior cerebellar peduncle (crosses back)", "spinal-white-columns", "Double crossing makes the net projection ipsilateral."),
 [("spinal-grey-posterior-horn", "spinal-cord", "ipsilateral", "spinal border cells, L1–S2"), ("spinal-white-columns", "spinal-cord", "contralateral", "anterolateral funiculus, anterior to the posterior spinocerebellar tract"), ("level-medulla-olive", "brainstem", "contralateral", "lateral medulla"), ("superior-cerebellar-peduncle", "superior-cerebellar-peduncle", "contralateral", "enters through the superior peduncle at the upper pons"), ("cerebellar-vermis", "cerebellar-vermis-vi", "ipsilateral", "anterior lobe, after recrossing")],
 "Cerebellar anterior lobe vermis and intermediate zone, ipsilateral to the origin after the second crossing.",
 [("Spinal cord anterolateral funiculus", "Ipsilateral leg ataxia (net effect after double crossing), usually mixed with spinothalamic signs", "ipsilateral"), ("Superior cerebellar peduncle", "Ataxia with the cerebellar outflow signs dominating", "ipsilateral")],
 ["This is the only spinocerebellar tract that enters through the superior peduncle", "It monitors spinal interneurons rather than joints: a copy of what the cord is doing"],
 [R("sp-spinocerebellar-dorsal-tract"), R("sp-cerebellum"), R("sp-spinal-cord-morphology")], meshes=["superior-cerebellar-peduncle"], syndromes=["syn-cerebellar-hemispheric"], synonyms=["ventral spinocerebellar tract", "Gowers' tract"]))

E.append(pw("pathway-rubrospinal", "Rubrospinal tract", "descending", "flexor facilitation of the upper limb",
 "Neurons of the magnocellular red nucleus send axons that cross immediately in the ventral tegmental decussation of the midbrain and descend in the lateral funiculus of the cord just in front of the lateral corticospinal tract, ending on interneurons that excite flexor and inhibit extensor motor neurons, mainly of the arm. Small in humans, it matters clinically in two ways: it is one reason cerebellar and red nucleus lesions affect limb movement, and its preserved flexor drive to the arms after lesions above the red nucleus produces decorticate posturing, while lesions below the red nucleus remove it and leave extensor (decerebrate) posturing.",
 (["red-nucleus"], "Magnocellular part of the red nucleus, driven by the motor cortex and the interposed nuclei of the cerebellum."),
 [("Red nucleus neuron", "spinal interneurons in the intermediate gray of the cervical cord"), ("Interneuron", "flexor motor neurons")],
 ("Ventral tegmental decussation, midbrain", "red-nucleus", "Crosses at once beneath the red nucleus."),
 [("red-nucleus", "red-nucleus-l", "ipsilateral", "origin"), ("level-midbrain-superior-colliculus", "brainstem", "contralateral", "ventral tegmental decussation"), ("level-pons-caudal", "brainstem", "contralateral", "lateral tegmentum"), ("spinal-white-columns", "spinal-cord", "contralateral", "lateral funiculus, anterior to the corticospinal tract, cervical segments mainly")],
 "Interneurons of the cervical cord facilitating flexors of the upper limb.",
 [("Above the red nucleus (hemispheric mass, thalamus)", "Decorticate posture: arms flexed, legs extended (rubrospinal flexor drive intact)", "bilateral"), ("Below the red nucleus (pons)", "Decerebrate posture: arms and legs extended (only vestibulospinal and reticulospinal extensor drive remains)", "bilateral")],
 ["The posture of a comatose patient tells you whether the red nucleus is still connected to the cord: flexed arms above, extended arms below", "In humans the corticospinal tract has taken over most of what the rubrospinal tract does in cats"],
 [R("sp-red-nucleus"), R("sp-decerebrate-and-decorticate-posturing")], meshes=["red-nucleus-l", "red-nucleus-r"], syndromes=["syn-central-transtentorial-herniation", "syn-claude"]))

E.append(pw("pathway-vestibulospinal", "Vestibulospinal tracts", "descending", "postural tone and balance",
 "Two tracts carry vestibular information to the cord. The lateral vestibulospinal tract from the lateral (Deiters) nucleus descends uncrossed the whole length of the cord in the anterior funiculus and excites extensor (antigravity) motor neurons, driven by the otoliths and by the cerebellar vermis and fastigial nucleus; the medial vestibulospinal tract from the medial nucleus descends in the MLF to the cervical cord, bilaterally, to coordinate head and neck position with eye movements. Together with the reticulospinal tracts they make up the medial (ventromedial) descending system for posture, and their unopposed extensor drive is what produces decerebrate rigidity.",
 (["vestibular-nuclei"], "Lateral vestibular nucleus (lateral tract) and medial vestibular nucleus (medial tract), receiving the vestibular nerve and cerebellar input."),
 [("Vestibular nuclear neuron", "spinal interneurons and directly on extensor motor neurons"), ("Motor neuron", "antigravity muscles")],
 None,
 [("vestibular-nuclei", "brainstem", "ipsilateral", "lateral and medial nuclei at the pontomedullary junction"), ("level-medulla-olive", "brainstem", "ipsilateral", "lateral tract in the ventrolateral medulla; medial tract in the MLF"), ("spinal-white-columns", "spinal-cord", "ipsilateral", "anterior funiculus; the medial tract ends in the cervical cord, the lateral runs to the sacral cord"), ("spinal-grey-anterior-horn", "spinal-cord", "ipsilateral", "extensor motor neurons and interneurons")],
 "Extensor motor neurons of the trunk and limbs (lateral tract) and neck motor neurons (medial tract, bilateral).",
 [("Vestibular nerve or nuclei (unilateral)", "Falling and past-pointing toward the side of the lesion, lateropulsion", "ipsilateral"), ("Brainstem transection between the vestibular nuclei and the red nucleus", "Decerebrate rigidity: unopposed extensor drive", "bilateral"), ("Cerebellar vermis (anterior lobe)", "Loss of inhibition of the lateral vestibular nucleus: increased extensor tone and gait ataxia", "bilateral")],
 ["The lateral vestibulospinal tract is the extensor engine of decerebrate posturing", "Patients with acute vestibular lesions fall toward the lesion; the tract has lost its push on that side"],
 [R("sp-vestibular-pathways"), R("sp-nucleus-vestibular"), R("sp-decerebrate-and-decorticate-posturing")], meshes=["brainstem"], syndromes=["syn-vestibular-neuritis", "syn-central-transtentorial-herniation"]))

E.append(pw("pathway-reticulospinal", "Reticulospinal tracts", "descending", "posture, locomotion, tone and autonomic modulation",
 "The pontine and medullary reticular formation send two tracts to the cord: the pontine (medial) reticulospinal tract, uncrossed in the anterior funiculus, which facilitates extensors and axial muscles, and the medullary (lateral) reticulospinal tract, partly crossed in the lateral funiculus, which inhibits extensor tone and modulates reflexes and pain transmission. Driven by the cortex, they form the main route for postural adjustments, anticipatory postural control and locomotor commands, and their imbalance after upper motor neuron lesions (loss of the cortical drive to the inhibitory medullary tract) contributes to spasticity more than the loss of the corticospinal tract itself.",
 (["reticular-formation"], "Pontine reticular nuclei (nucleus reticularis pontis oralis and caudalis) and the medullary gigantocellular reticular nucleus, driven by the premotor cortex."),
 [("Reticular formation neuron", "spinal interneurons and gamma and alpha motor neurons over many segments"), ("Motor neuron", "axial and proximal muscles")],
 ("Partly crossed (medullary tract)", None, "Pontine tract uncrossed; medullary tract bilateral."),
 [("reticular-formation", "brainstem", "ipsilateral", "pontine and medullary reticular nuclei"), ("level-medulla-olive", "brainstem", "bilateral", "medullary tract descends in the lateral tegmentum"), ("spinal-white-columns", "spinal-cord", "bilateral", "pontine tract in the anterior funiculus, medullary tract in the lateral funiculus"), ("spinal-grey-anterior-horn", "spinal-cord", "bilateral", "interneurons and motor neurons of axial and proximal muscles; also autonomic neurons")],
 "Interneurons and motor neurons throughout the cord, especially for axial and proximal muscles; sympathetic preganglionic neurons; dorsal horn (pain modulation).",
 [("Cortical or capsular lesion (loss of drive to the medullary inhibitory tract)", "Spasticity, clasp-knife tone and hyperreflexia below the lesion", "contralateral"), ("Pontine tegmental lesion", "Loss of anticipatory postural adjustments; contributes to decerebrate posturing when combined with vestibulospinal release", "bilateral"), ("Medullary lesion", "Loss of descending pain inhibition and of autonomic modulation (blood pressure lability)", "bilateral")],
 ["Spasticity is largely a reticulospinal problem: the corticospinal tract alone produces weakness and clumsiness, not hypertonia", "Reticulospinal pathways explain why patients with corticospinal lesions can still walk with a stiff gait: the medial descending systems drive locomotion"],
 [R("sp-reticular-formation"), R("sp-decerebrate-and-decorticate-posturing"), R("sp-spasticity")], meshes=["tract-reticulospinal-l", "tract-reticulospinal-r"], syndromes=["syn-complete-transection-spinal-shock", "syn-central-transtentorial-herniation"]))

E.append(pw("pathway-tectospinal", "Tectospinal tract", "descending", "reflex turning of the head toward stimuli",
 "Neurons of the deep layers of the superior colliculus send axons that cross in the dorsal tegmental decussation just below the periaqueductal gray, descend near the MLF through the brainstem and end in the cervical cord, where they drive neck motor neurons to turn the head toward a visual, auditory or somatosensory stimulus. It is the spinal component of the orienting response and works with the tectobulbar fibers that move the eyes toward the same target, so that gaze and head turn arrive together and the fovea lands on whatever attracted attention.",
 (["superior-colliculus"], "Deep and intermediate layers of the superior colliculus, driven by retinal, auditory and cortical input."),
 [("Superior colliculus neuron", "cervical interneurons and motor neurons"), ("Motor neuron", "neck muscles")],
 ("Dorsal tegmental decussation, midbrain", "superior-colliculus", "Crosses beneath the periaqueductal gray at the level of the colliculi."),
 [("superior-colliculus", "superior-colliculus-l", "ipsilateral", "origin"), ("level-midbrain-superior-colliculus", "brainstem", "contralateral", "dorsal tegmental decussation"), ("medial-longitudinal-fasciculus", "brainstem", "contralateral", "descends beside the MLF"), ("spinal-white-columns", "spinal-cord", "contralateral", "anterior funiculus, cervical segments only")],
 "Motor neurons and interneurons of the upper cervical cord for neck muscles.",
 [("Superior colliculus", "Impaired reflex orienting of the head and eyes to the contralateral side; rarely isolated", "contralateral"), ("Dorsal midbrain compression", "Orienting deficits merge with the vertical gaze palsy of the Parinaud syndrome", "bilateral")],
 ["This tract is why a sudden sound makes you turn your head before you know why", "Isolated tectospinal lesions are a textbook concept rather than a clinical entity; think of it as part of the dorsal midbrain"],
 [R("sp-tectospinal-tract")], meshes=["superior-colliculus-l", "superior-colliculus-r"], syndromes=["syn-parinaud-dorsal-midbrain"]))

write(E)
