import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).parent))
from lib import *
from batch03_brainstem_structures import bs
E = []
SN5 = lambda a, b=None: C("snell", 5, a, b)
SN11 = lambda a, b=None: C("snell", 11, a, b)
BK9 = lambda a, b=None: C("berkowitz", 9, a, b)
BK11 = lambda a, b=None: C("berkowitz", 11, a, b)

E.append(bs("medial-longitudinal-fasciculus", "Medial longitudinal fasciculus", "pons", "pons", ["brainstem"], latin="Fasciculus longitudinalis medialis", synonyms=["MLF"],
 summary="A paired paramedian bundle running the length of the brainstem just beneath the aqueduct and the floor of the fourth ventricle. Its clinically decisive contents are the axons of abducens internuclear neurons crossing to the contralateral oculomotor nucleus, which yoke the medial rectus to the opposite lateral rectus for conjugate horizontal gaze; it also carries vestibular fibers to the eye movement nuclei and descends as the medial vestibulospinal tract. A lesion produces internuclear ophthalmoplegia: the eye on the side of the lesion fails to adduct while the other eye abducts with nystagmus.",
 location="Dorsal paramedian tegmentum from the rostral midbrain (interstitial nucleus of Cajal) down through the pons and medulla into the cervical cord, ventral to the periaqueductal gray and the hypoglossal and abducens nuclei.",
 function="Coordinates conjugate horizontal and vertical eye movements between the III, IV and VI nuclei and links them to the vestibular nuclei; carries the medial vestibulospinal tract for head-eye coordination.",
 arteries=["arteries-pontine", "artery-basilar"], territories=["territory-basilar-paramedian"],
 imaging=img([view("axial", 2, -32, -34, "paramedian dorsal pontine tegmentum in front of the fourth ventricle"), view("sagittal", 2, -30, -25, "dorsal paramedian bundle from midbrain to medulla")],
     "Not resolved on routine MRI; lesions show as small paramedian dorsal tegmental spots. In multiple sclerosis a bilateral INO usually comes with a small FLAIR-bright lesion straddling the midline under the ventricular floor.",
     [pathol("Demyelinating INO", "MRI", "Small T2/FLAIR-bright lesion in the dorsal paramedian pontine tegmentum, often bilateral in multiple sclerosis; may be invisible on 5 mm slices.", sequence="FLAIR", pitfalls="Use thin axial FLAIR or sagittal 3D FLAIR; a normal routine MRI does not exclude a demyelinating INO"), pathol("Ischemic INO", "MRI", "Unilateral paramedian tegmental restricted diffusion from a small perforator in older patients with vascular risk factors.", sequence="DWI")],
     "Thin FLAIR and DWI through the pons and midbrain"),
 lesion=[("Failure of adduction of the eye on the side of the lesion with abducting nystagmus of the other eye (INO)", "ipsilateral", "Interneuron axons from the contralateral abducens nucleus to the ipsilateral medial rectus subnucleus"), ("Convergence preserved", "n/a", "Convergence uses a separate midbrain pathway"), ("Skew deviation and vertical nystagmus", "n/a", "Vestibular fibers in the MLF"), ("One-and-a-half syndrome when combined with an abducens nucleus or PPRF lesion", "ipsilateral", "Ipsilateral gaze palsy plus INO")],
 exam=["Ask the patient to look far to each side and watch the adducting eye for slowing or failure; look for nystagmus in the abducting eye", "Test convergence to show that the medial rectus itself works", "Check vertical gaze and for skew"],
 pearls=["INO in a young adult is multiple sclerosis until proven otherwise; in an older patient it is usually a small stroke", "The lesion side is the side of the eye that cannot adduct"],
 citations=[SN5(203, 213), C("snell", 4, 157), SN11(331), BK9(75, 80), BK11(96, 101)], syndromes=["syn-ino", "syn-one-and-a-half"], pathways=["pathway-horizontal-gaze", "pathway-vestibular-vor"]))

E.append(bs("abducens-nucleus", "Abducens nucleus", "pons", "pons", ["brainstem"], latin="Nucleus nervi abducentis",
 summary="The abducens nucleus lies under the facial colliculus in the caudal pons and is the horizontal gaze center's output stage: its motor neurons supply the ipsilateral lateral rectus, and its internuclear neurons cross in the MLF to drive the contralateral medial rectus. Because both cell types live together, a nuclear lesion causes a conjugate gaze palsy toward the side of the lesion, not an isolated lateral rectus palsy. The facial nerve fibers loop around it, so a nuclear lesion often adds an ipsilateral facial palsy.",
 location="Dorsal caudal pons beneath the facial colliculus of the fourth ventricular floor, paramedian, with the PPRF just anterior and lateral to it and the MLF medial to it.",
 function="Abduction of the ipsilateral eye and, through internuclear neurons, conjugate horizontal gaze to the ipsilateral side; final common pathway for saccades, pursuit and the vestibulo-ocular reflex in the horizontal plane.",
 arteries=["arteries-pontine", "artery-basilar"], territories=["territory-basilar-paramedian"],
 imaging=img([view("axial", 4, -34, -36, "facial colliculus level of the caudal pons"), view("sagittal", 3, -34, -36, "floor of the fourth ventricle at the facial colliculus")],
     "Not resolved on routine MRI; the facial colliculus is the paramedian bump on the floor of the fourth ventricle at the caudal pons. Small lesions here are best seen on thin axial FLAIR or DWI.",
     [pathol("Pontine tegmental infarct or demyelination at the facial colliculus", "MRI", "Small paramedian dorsal pontine lesion with ipsilateral gaze palsy and lower motor neuron facial weakness.", sequence="FLAIR"), pathol("Pontine glioma or cavernoma", "MRI", "Mass in the dorsal pons displacing the ventricular floor; sixth nerve and gaze palsies are early signs.", sequence="T2")],
     "Thin FLAIR/DWI through the pons"),
 lesion=[("Conjugate horizontal gaze palsy toward the side of the lesion", "ipsilateral", "Loss of both motor and internuclear neurons"), ("Ipsilateral lower motor neuron facial palsy", "ipsilateral", "Facial nerve genu looping over the nucleus"), ("Isolated lateral rectus palsy", "ipsilateral", "Abducens fascicle or nerve, not the nucleus")],
 exam=["Ask the patient to follow a target to each side: nuclear lesions stop both eyes at the midline", "Test the vestibulo-ocular reflex (doll's eyes) — absent toward the lesion side in nuclear lesions, preserved in PPRF lesions", "Facial movement including the forehead"],
 pearls=["A gaze palsy that cannot be overcome by the oculocephalic reflex is nuclear; one that can is supranuclear (PPRF or cortex)", "Gaze palsy plus peripheral facial palsy equals the facial colliculus"],
 citations=[SN5(205, 207), SN11(335, 337), BK9(79, 80), BK11(93, 98)], syndromes=["syn-horizontal-gaze-palsy-pontine", "syn-foville", "syn-one-and-a-half", "syn-cn6-palsy"], pathways=["pathway-horizontal-gaze"], efferents=[("lateral rectus", "cn-06-abducens"), ("oculomotor-nucleus (contralateral medial rectus subnucleus)", "medial-longitudinal-fasciculus")], afferents=[("pprf", None, "saccadic burst"), ("vestibular-nuclei", None, "vestibulo-ocular reflex")]))

E.append(bs("facial-motor-nucleus", "Facial motor nucleus", "pons", "pons", ["brainstem"], latin="Nucleus nervi facialis",
 summary="The facial motor nucleus sits in the ventrolateral tegmentum of the caudal pons. Its axons take a remarkable detour: they run dorsomedially, loop over the abducens nucleus as the internal genu (raising the facial colliculus), and then pass ventrolaterally to leave the pontomedullary junction. The nucleus supplies all muscles of facial expression plus the stapedius, stylohyoid and posterior belly of the digastric. Its corticobulbar input is bilateral for the upper face but mainly contralateral for the lower face, which is the anatomical basis for distinguishing central from peripheral facial weakness.",
 location="Ventrolateral pontine tegmentum at the level of the facial colliculus, dorsal to the superior olivary complex and ventrolateral to the abducens nucleus; the internal genu lies dorsal to the abducens nucleus.",
 subdivisions=[("Dorsal (upper face) part", "frontalis and orbicularis oculi; bilateral cortical input"), ("Ventral (lower face) part", "perioral muscles; contralateral cortical input"), ("Medial and intermediate groups", "stapedius, stylohyoid, posterior digastric, platysma")],
 function="Lower motor neurons for facial expression, eye closure, and the stapedius reflex that dampens loud sounds; efferent limb of the corneal and blink reflexes.",
 arteries=["arteries-pontine", "artery-aica"], territories=["territory-basilar-paramedian", "territory-aica"],
 imaging=img([view("axial", 14, -34, -38, "ventrolateral caudal pontine tegmentum"), view("axial", 4, -34, -36, "internal genu over the abducens nucleus")],
     "Not resolved on routine MRI. The intrapontine facial fibers and the nerve in the cerebellopontine angle and internal acoustic meatus are seen on high-resolution T2; enhancement of the nerve in the canal is seen in Bell palsy.",
     [pathol("Pontine infarct with facial palsy", "MRI", "Restricted diffusion in the ventrolateral or paramedian caudal pons; peripheral-type facial weakness with contralateral hemiparesis (Millard–Gubler).", sequence="DWI"), pathol("Bell palsy", "MRI", "Enhancement of the labyrinthine and geniculate segments of the facial nerve on contrast T1 in the temporal bone; the pons is normal.", sequence="T1+Gd")],
     "DWI for pontine lesions; T1+Gd of the temporal bone when a peripheral cause is suspected"),
 lesion=[("Weakness of the whole ipsilateral face including the forehead", "ipsilateral", "Nucleus or nerve: lower motor neuron lesion"), ("Weakness of the lower face only, forehead spared", "contralateral", "Supranuclear corticobulbar lesion: the upper face has bilateral cortical input"), ("Hyperacusis", "ipsilateral", "Loss of stapedius motor neurons"), ("Incomplete eye closure with Bell phenomenon", "ipsilateral", "Orbicularis oculi weakness")],
 exam=["Raise eyebrows, close eyes tightly, show teeth, puff cheeks; compare the forehead with the mouth", "Corneal reflex and blink to threat", "Ask about loud-sound intolerance and taste change (taste points to the nerve distal to the pons)"],
 pearls=["Forehead involved: nucleus or nerve. Forehead spared: cortex or corticobulbar tract", "A peripheral facial palsy with hemiparesis of the opposite limbs is a pontine lesion, not Bell palsy"],
 citations=[SN5(205, 207), SN11(337, 339), BK9(79, 80), C("berkowitz", 13, 120, 124)], syndromes=["syn-facial-palsy-peripheral-vs-central", "syn-millard-gubler", "syn-aica-lateral-pontine"], pathways=["pathway-corticobulbar"], efferents=[("muscles of facial expression", "cn-07-facial")], afferents=[("gyrus-precentral", "pathway-corticobulbar", "bilateral to upper face, contralateral to lower face")]))

E.append(bs("pprf", "Paramedian pontine reticular formation", "pons", "pons", ["brainstem"], synonyms=["PPRF", "pontine horizontal gaze center"],
 summary="A cluster of burst neurons in the pontine reticular formation adjacent to the abducens nucleus that generates horizontal saccades. It receives commands from the contralateral frontal eye field and the ipsilateral superior colliculus and fires the abducens nucleus on its own side, so the eyes jump toward the side of the active PPRF. A unilateral lesion abolishes voluntary and reflex saccades toward the lesion, but because the vestibular pathways bypass it, the oculocephalic reflex can still drive the eyes there.",
 location="Ventral and lateral to the abducens nucleus in the paramedian tegmentum of the caudal pons, extending rostrally toward the trochlear level.",
 function="Saccade generation in the horizontal plane; integrates cortical, collicular and cerebellar commands and feeds the abducens nucleus.",
 arteries=["arteries-pontine", "artery-basilar"], territories=["territory-basilar-paramedian"],
 imaging=img([view("axial", 5, -32, -35, "paramedian caudal pontine tegmentum anterior to the abducens nucleus")],
     "Not resolved on routine MRI; localized to the paramedian tegmentum of the caudal pons. Lesions here produce the same imaging as abducens nuclear lesions: small paramedian tegmental spots on FLAIR or DWI.",
     [pathol("Paramedian pontine tegmental infarct", "MRI", "Small restricted-diffusion lesion in the paramedian tegmentum with ipsilateral saccadic gaze palsy.", sequence="DWI")],
     "Thin FLAIR/DWI"),
 lesion=[("Loss of horizontal saccades toward the side of the lesion, with the eyes deviated away", "ipsilateral", "Burst neurons for ipsilateral gaze"), ("Preserved vestibulo-ocular reflex toward the lesion", "ipsilateral", "Vestibular input reaches the abducens nucleus directly"), ("Wrong-way gaze deviation compared with a hemispheric lesion", "contralateral", "Pontine lesion: eyes look away from the lesion and toward the hemiparesis")],
 exam=["Voluntary saccades and pursuit to each side", "Oculocephalic (doll's eye) maneuver to separate PPRF from nuclear lesions", "Note the direction of resting gaze deviation relative to the hemiparesis"],
 pearls=["Hemispheric lesion: eyes look toward the lesion, away from the weak limbs. Pontine lesion: eyes look away from the lesion, toward the weak limbs", "A gaze palsy overcome by head turning is supranuclear (PPRF); one that is not is nuclear (abducens)"],
 citations=[SN11(331), BK9(79, 80), BK11(96, 98)], syndromes=["syn-horizontal-gaze-palsy-pontine", "syn-one-and-a-half"], pathways=["pathway-horizontal-gaze"], afferents=[("frontal-eye-field", None, "contralateral"), ("superior-colliculus", None, "ipsilateral")], efferents=[("abducens-nucleus", None, "ipsilateral")]))

E.append(bs("pontine-nuclei", "Pontine nuclei and transverse pontine fibers", "pons", "pons", ["brainstem"], latin="Nuclei pontis",
 summary="The basis pontis is packed with pontine nuclei, the relay through which the cerebral cortex talks to the cerebellum. Corticopontine fibers from the frontal, parietal, temporal and occipital lobes descend in the crus cerebri and end here; the pontine neurons send their axons across the midline as the transverse pontine fibers into the contralateral middle cerebellar peduncle. Scattered among them run the corticospinal and corticobulbar bundles, which is why basis pontis lesions combine hemiparesis with ataxia.",
 location="Ventral pons (basis pontis) on both sides of the midline, between the corticospinal bundles, from the pontomedullary junction to the pontomesencephalic junction; the transverse fibers form the bulk of the ventral pontine surface.",
 function="Cortico-ponto-cerebellar relay: transmits motor plans and sensory context from the cortex to the cerebellum for coordination of skilled movement and, through the crossed projection, gives the cerebellum its contralateral cortical connection.",
 arteries=["arteries-pontine", "artery-basilar"], territories=["territory-basilar-paramedian"],
 imaging=img([view("axial", 6, -26, -30, "basis pontis in front of the tegmentum"), view("sagittal", 0, -26, -28, "ventral bulge of the pons over the basilar artery")],
     "The basis pontis is homogeneous white matter with slightly grayer punctate nuclei on T1; the transverse fibers give the ventral pons a striated look on high-resolution axial images. Central pontine myelinolysis spares the peripheral rim and the corticospinal bundles.",
     [pathol("Paramedian basis pontis infarct", "MRI", "Wedge-shaped restricted diffusion in one half of the basis pontis: pure motor hemiparesis, ataxic hemiparesis or dysarthria–clumsy hand.", sequence="DWI"), pathol("Osmotic demyelination", "MRI", "Central symmetric T2 hyperintensity of the basis pontis with a trident or bat-wing shape sparing the periphery, after rapid correction of hyponatremia.", sequence="T2", timing="Lesion appears 1–2 weeks after the osmotic shift")],
     "DWI and T2 through the pons"),
 lesion=[("Contralateral ataxic hemiparesis", "contralateral", "Corticospinal bundles plus corticopontine and pontocerebellar fibers"), ("Dysarthria and clumsy hand", "contralateral", "Basis pontis at the level of facial and hand corticobulbar/corticospinal projections"), ("Bilateral ataxia and pseudobulbar signs", "bilateral", "Bilateral basis pontis disease, e.g. osmotic demyelination")],
 exam=["Compare limb weakness with coordination: ataxia out of proportion to weakness suggests the pons", "Speech and fine hand movements", "Look for pseudobulbar affect and dysphagia in bilateral disease"],
 pearls=["Ataxic hemiparesis localizes to the contralateral basis pontis (or the internal capsule/corona radiata)", "Pontine crossing fibers explain why each cerebellar hemisphere works with the opposite cerebral cortex but the same-side limbs"],
 citations=[SN5(204, 208), C("snell", 6, 236, 239), BK9(75, 79), C("berkowitz", 7, 60)], syndromes=["syn-lacunar-ataxic-hemiparesis", "syn-lacunar-dysarthria-clumsy-hand", "syn-locked-in"], pathways=["pathway-cerebellar-circuits"], afferents=[("cerebral cortex", "corticopontine fibers in the crus cerebri")], efferents=[("cerebellum (contralateral)", "middle-cerebellar-peduncle")]))

E.append(bs("middle-cerebellar-peduncle", "Middle cerebellar peduncle", "peduncles", "pons", ["middle-cerebellar-peduncle"], latin="Pedunculus cerebellaris medius", synonyms=["brachium pontis"],
 summary="The largest of the three peduncles, a massive purely afferent bundle carrying the transverse pontine fibers from the contralateral pontine nuclei into the cerebellar hemisphere. It forms the lateral surface of the pons, with the trigeminal root emerging at its junction with the basis pontis. Infarcts here (AICA territory) or demyelination give ipsilateral limb ataxia, and bilateral lesions of the peduncles are a recognized pattern in multiple system atrophy and fragile X-associated tremor/ataxia syndrome.",
 location="Lateral pons, sweeping backward and laterally from the basis pontis into the white matter of the cerebellar hemisphere, lateral to the superior and inferior peduncles.",
 function="Delivers the cortico-ponto-cerebellar input that lets the cerebellar hemispheres coordinate skilled limb movement planned by the contralateral cortex.",
 arteries=["artery-aica", "arteries-pontine", "artery-sca"], territories=["territory-aica"],
 imaging=img([view("axial", 25, -38, -32, "lateral pons at the trigeminal root entry, peduncle entering the cerebellum"), view("coronal", 25, -40, -30, "middle peduncle from pons to hemisphere")],
     "A thick band of white matter on the lateral pons on axial T2 and FLAIR; symmetrical T2 hyperintensity of both peduncles is a clue to multiple system atrophy (with the pontine 'hot cross bun') or FXTAS.",
     [pathol("AICA infarct", "MRI", "Restricted diffusion in the middle cerebellar peduncle and adjacent lateral pons and cerebellum.", sequence="DWI"), pathol("Bilateral MCP sign", "MRI", "Symmetrical T2/FLAIR hyperintensity of both peduncles in multiple system atrophy (cerebellar type) or fragile X tremor/ataxia syndrome.", sequence="FLAIR"), pathol("Demyelination", "MRI", "Peduncular plaque with ipsilateral ataxia, a common multiple sclerosis site.", sequence="FLAIR")],
     "FLAIR and DWI through the pons and cerebellum"),
 lesion=[("Ipsilateral limb ataxia and dysmetria", "ipsilateral", "Loss of pontocerebellar input to the ipsilateral hemisphere"), ("Gait ataxia", "bilateral", "Bilateral peduncular disease"), ("Facial numbness or trigeminal signs", "ipsilateral", "Trigeminal root at the entry zone next to the peduncle")],
 exam=["Finger-nose, heel-shin, rapid alternating movements", "Tandem gait", "Corneal reflex and facial sensation"],
 pearls=["Bilateral symmetric bright middle peduncles in an older man with tremor and ataxia: think FXTAS", "AICA infarcts typically cut the peduncle, so ataxia accompanies the deafness and facial palsy"],
 citations=[SN5(205, 207), C("snell", 6, 236), BK9(77), C("berkowitz", 8, 67, 70)], syndromes=["syn-aica-lateral-pontine"], pathways=["pathway-cerebellar-circuits"], afferents=[("pontine-nuclei", "transverse pontine fibers", "crossed")]))

E.append(bs("superior-cerebellar-peduncle", "Superior cerebellar peduncle", "peduncles", "pons", ["superior-cerebellar-peduncle"], latin="Pedunculus cerebellaris superior", synonyms=["brachium conjunctivum"],
 summary="The main outflow of the cerebellum. Axons of the dentate and interposed nuclei ascend in the superior peduncle along the lateral wall of the upper fourth ventricle, cross completely in the caudal midbrain (decussation of the superior cerebellar peduncles), and end in the contralateral red nucleus and the ventral lateral thalamus, which relays to the motor cortex. This double crossing (cerebellum → contralateral thalamus/cortex → contralateral corticospinal tract → back to the original side) is why cerebellar signs are ipsilateral to the lesion. A smaller afferent component, the anterior spinocerebellar tract, enters through this peduncle.",
 location="Dorsolateral upper pons forming the lateral boundary of the rostral fourth ventricle, running upward and medially into the tegmentum of the caudal midbrain where the two sides decussate ventral to the aqueduct at the level of the inferior colliculus.",
 function="Carries the dentatorubrothalamic and interposito-rubral outflow that shapes cortical motor commands and drives the rubrospinal tract; receives the anterior spinocerebellar tract.",
 arteries=["artery-sca", "arteries-pontine"], territories=["territory-sca", "territory-basilar-paramedian"],
 imaging=img([view("axial", 8, -34, -26, "dorsolateral upper pons beside the fourth ventricle"), view("axial", 2, -30, -16, "decussation in the caudal midbrain tegmentum"), view("coronal", 8, -34, -24, "peduncle climbing from the dentate nucleus to the midbrain")],
     "The peduncles are the two white-matter walls of the upper fourth ventricle on axial T2; the decussation is a subtle central band in the caudal midbrain tegmentum. The HCP dentatorubrothalamic tract mesh in this atlas shows the full course to the thalamus.",
     [pathol("Midbrain tegmental infarct at the decussation", "MRI", "Small restricted-diffusion lesion in the central caudal midbrain tegmentum; bilateral ataxia because both crossing bundles are hit.", sequence="DWI"), pathol("Peduncular demyelination", "MRI", "FLAIR-bright plaque on the lateral wall of the fourth ventricle, with ipsilateral limb ataxia and intention tremor.", sequence="FLAIR")],
     "FLAIR and DWI through the upper pons and midbrain"),
 lesion=[("Ipsilateral limb ataxia and intention tremor", "ipsilateral", "Lesion below the decussation"), ("Contralateral limb ataxia", "contralateral", "Lesion above the decussation (red nucleus, thalamus)"), ("Holmes (rubral) tremor", "contralateral", "Dentatorubrothalamic fibers after the crossing, near the red nucleus")],
 exam=["Finger-nose with attention to terminal tremor", "Heel-shin", "Look for a coarse rest-postural-intention tremor (Holmes) after midbrain lesions"],
 pearls=["Which side the ataxia falls on tells you whether the lesion is below or above the midbrain decussation", "Claude syndrome is a third nerve palsy with contralateral ataxia: the lesion catches the crossed peduncle at the red nucleus"],
 citations=[SN5(207, 213), C("snell", 6, 239, 240), BK9(77), C("berkowitz", 8, 67, 70), BK11(94, 95)], syndromes=["syn-claude", "syn-benedikt", "syn-sca-infarct"], pathways=["pathway-cerebellar-circuits", "pathway-anterior-spinocerebellar"], afferents=[("dentate-nucleus", None), ("interposed-nucleus", None)], efferents=[("red-nucleus (contralateral)", None), ("thalamus-va-vl (contralateral)", "dentatorubrothalamic tract")]))

E.append(bs("trigeminal-nuclei", "Trigeminal sensory and motor nuclei", "pons", "pons", ["brainstem"], synonyms=["principal sensory nucleus of V", "motor nucleus of V", "mesencephalic nucleus of V"],
 summary="The trigeminal nerve has the longest nuclear column in the brainstem. The principal (chief) sensory nucleus in the rostral pons receives discriminative touch from the face; the spinal nucleus below it receives pain and temperature; the mesencephalic nucleus above it is the only place where primary sensory cell bodies sit inside the central nervous system, serving jaw proprioception; and the motor nucleus, medial to the principal nucleus, drives the muscles of mastication. Together they let a single pontine lesion produce facial numbness with a weak jaw deviating toward the lesion.",
 location="Principal sensory and motor nuclei: lateral tegmentum of the mid-pons at the level of the trigeminal root entry. Mesencephalic nucleus: a slender column along the lateral edge of the periaqueductal gray up to the superior colliculus. Spinal nucleus: descending through the medulla to C2–C3.",
 subdivisions=[("Principal sensory nucleus", "fine touch and pressure from the face; projects in the trigeminal lemniscus, mostly crossed, to VPM"), ("Motor nucleus", "masseter, temporalis, pterygoids, mylohyoid, anterior digastric, tensor tympani, tensor veli palatini; bilateral corticobulbar input"), ("Mesencephalic nucleus", "proprioception from jaw muscles and periodontal ligament; afferent limb of the jaw jerk"), ("Spinal nucleus", "pain, temperature and crude touch (see the spinal trigeminal entry)")],
 function="All facial somatic sensation, the sensory side of the corneal, blink and jaw-jerk reflexes, and motor control of chewing.",
 arteries=["arteries-pontine", "artery-sca", "artery-aica"], territories=["territory-basilar-paramedian", "territory-sca"],
 imaging=img([view("axial", 22, -30, -28, "lateral mid-pontine tegmentum at the trigeminal root entry"), view("axial", 28, -28, -30, "root leaving the pons toward Meckel's cave")],
     "The trigeminal root is a well-seen band on axial T2 crossing the prepontine cistern; the nuclei are not resolved. Pontine plaques at the root entry zone are a frequent cause of trigeminal symptoms in multiple sclerosis.",
     [pathol("Root entry zone demyelination", "MRI", "FLAIR-bright lesion at the lateral pons where the root enters; trigeminal neuralgia or facial numbness.", sequence="FLAIR"), pathol("Lateral pontine infarct", "MRI", "Restricted diffusion in the lateral mid-pons with ipsilateral facial sensory loss and contralateral body sensory loss.", sequence="DWI"), pathol("Trigeminal schwannoma", "MRI", "Dumbbell enhancing mass along the root and Meckel's cave.", sequence="T1+Gd")],
     "Thin axial T2/FLAIR of the pons; CISS/FIESTA and T1+Gd for the root"),
 lesion=[("Ipsilateral loss of facial touch", "ipsilateral", "Principal sensory nucleus"), ("Jaw deviates toward the lesion on opening with masseter wasting", "ipsilateral", "Motor nucleus or motor root: the intact lateral pterygoid pushes the jaw to the weak side"), ("Absent jaw jerk with an otherwise brisk reflex pattern", "ipsilateral", "Mesencephalic nucleus afferents"), ("Brisk jaw jerk", "bilateral", "Bilateral supranuclear (pseudobulbar) lesions")],
 exam=["Light touch and pin-prick in V1, V2, V3 on each side", "Palpate the masseters while the patient clenches; watch jaw opening for deviation", "Jaw jerk and corneal reflex"],
 pearls=["Loss of touch but preserved pain on the face means the principal nucleus (pons), whereas the reverse means the spinal nucleus (medulla)", "A brisk jaw jerk with a brisk everything else points to a lesion above the pons"],
 citations=[SN5(207, 208), SN11(333, 335), BK9(75, 80), C("berkowitz", 13, 117, 120)], syndromes=["syn-trigeminal-neuralgia", "syn-bulbar-vs-pseudobulbar"], pathways=["pathway-trigeminothalamic"], afferents=[("ganglion-trigeminal", "cn-05-trigeminal")], efferents=[("thalamus-vpm", "trigeminal lemniscus", "crossed")]))

E.append(bs("superior-olivary-complex", "Superior olivary complex and lateral lemniscus", "pons", "pons", ["brainstem"], synonyms=["superior olive", "trapezoid body"],
 summary="The first binaural station of the auditory pathway. Axons from the cochlear nuclei cross in the trapezoid body of the caudal pons and converge on the superior olivary complex of both sides, whose neurons compare timing (medial superior olive) and intensity (lateral superior olive) between the two ears to localize sound. Output ascends in the lateral lemniscus to the inferior colliculus. The complex also gives rise to the olivocochlear bundle that tunes the outer hair cells and to the efferent limb of the stapedius reflex through the facial nucleus.",
 location="Ventral tegmentum of the caudal pons, dorsal to the trapezoid body and lateral to the medial lemniscus, just ventromedial to the facial motor nucleus; the lateral lemniscus climbs along the lateral surface of the pontine tegmentum to the inferior colliculus.",
 function="Sound localization by interaural time and level differences, the acoustic stapedius reflex, and efferent control of the cochlea.",
 arteries=["arteries-pontine", "artery-aica"], territories=["territory-basilar-paramedian", "territory-aica"],
 imaging=img([view("axial", 10, -34, -38, "ventral caudal pontine tegmentum behind the trapezoid body"), view("axial", 18, -30, -22, "lateral lemniscus on the lateral upper pons")],
     "Not resolved on routine MRI; localized to the ventral tegmentum of the caudal pons. Pontine lesions here rarely cause deafness because the pathway is already bilateral.",
     [pathol("Pontine tegmental lesion with hyperacusis or poor localization", "MRI", "Tegmental infarct or plaque in the caudal pons; hearing is preserved but sound localization and the stapedius reflex are impaired.", sequence="FLAIR")],
     "FLAIR/DWI; audiometry with stapedius reflex testing"),
 lesion=[("Impaired sound localization without deafness", "bilateral", "Binaural comparison neurons"), ("Hyperacusis", "ipsilateral", "Efferent limb of the stapedius reflex"), ("Central auditory processing deficits", "bilateral", "Ascending lateral lemniscus fibers")],
 exam=["Hearing thresholds are normal; test localization of a sound source with eyes closed", "Stapedius reflex on tympanometry", "Facial movement and corneal reflex for neighboring structures"],
 pearls=["Unilateral deafness never comes from the pons or above", "Brainstem auditory evoked potentials map lesions of this pathway wave by wave"],
 citations=[SN5(205, 208), SN11(338, 339), C("berkowitz", 12, 105, 107)], pathways=["pathway-auditory"], afferents=[("cochlear-nuclei", "trapezoid body", "bilateral")], efferents=[("inferior-colliculus", "lateral lemniscus")]))

E.append(bs("cerebral-peduncle-crus", "Crus cerebri (cerebral peduncle)", "midbrain", "midbrain", ["brainstem"], latin="Crus cerebri", synonyms=["basis pedunculi", "cerebral peduncle"],
 summary="The paired ventral pillars of the midbrain, made entirely of descending fibers: corticospinal and corticobulbar fibers occupy the middle three-fifths, flanked by frontopontine fibers medially and parieto-temporo-occipitopontine fibers laterally. The oculomotor nerve emerges from the medial edge into the interpeduncular fossa, and the uncus of the temporal lobe lies against the lateral edge, so a crus lesion produces the Weber syndrome and a herniating uncus produces contralateral hemiparesis or, when it pushes the opposite crus against the tentorium, a falsely localizing ipsilateral hemiparesis (Kernohan notch).",
 location="Ventral midbrain on each side of the interpeduncular fossa, separated from the tegmentum by the substantia nigra, continuous below with the basis pontis and above with the posterior limb of the internal capsule.",
 subdivisions=[("Medial fifth", "frontopontine fibers"), ("Middle three-fifths", "corticobulbar (medial) and corticospinal (lateral) fibers, arm medial to leg"), ("Lateral fifth", "parieto-temporo-occipitopontine fibers")],
 function="Conducts all corticofugal motor traffic from the internal capsule to the pons and spinal cord.",
 arteries=["artery-pca", "arteries-thalamoperforating", "artery-anterior-choroidal", "artery-basilar"], territories=["territory-pca", "territory-anterior-choroidal", "territory-basilar-paramedian"],
 imaging=img([view("axial", 10, -18, -12, "crura as the two anterior bulges of the midbrain flanking the interpeduncular fossa"), view("coronal", 10, -18, -12, "crus continuing up into the internal capsule")],
     "The crura are dark compact white matter on T2 forming the anterior contour of the midbrain; the substantia nigra behind them is darker still on T2*. Wallerian degeneration after a hemispheric stroke thins and brightens the ipsilateral crus.",
     [pathol("Weber syndrome infarct", "MRI", "Paramedian restricted diffusion in the medial crus including the emerging oculomotor fibers.", sequence="DWI"), pathol("Uncal herniation with Kernohan notch", "MRI", "Medial temporal lobe displaced over the tentorial edge compressing the ipsilateral crus and pushing the midbrain so the contralateral crus is notched by the tentorium; T2 signal in the compressed peduncle.", sequence="T2"), pathol("Wallerian degeneration", "MRI", "Atrophy and T2 hyperintensity of the crus months after a large MCA infarct.", sequence="T2", timing="From about 4–10 weeks after the stroke")],
     "DWI and T2 through the midbrain"),
 lesion=[("Contralateral hemiparesis including the lower face and tongue", "contralateral", "Corticospinal and corticobulbar fibers in the middle of the crus"), ("Ipsilateral third nerve palsy with the hemiparesis (Weber)", "ipsilateral", "Oculomotor fascicle exiting through the medial crus"), ("Ipsilateral hemiparesis in uncal herniation", "ipsilateral", "Contralateral crus compressed against the tentorial edge (Kernohan notch, false localizing)")],
 exam=["Limb power, facial and tongue movement on the side opposite the lesion", "Pupils and eye movements", "In a comatose patient with a dilated pupil, remember the hemiparesis may be on the same side as the pupil"],
 pearls=["Third nerve palsy plus contralateral hemiparesis is the crus (Weber)", "A dilated pupil with ipsilateral hemiparesis means the herniation is on the side of the pupil, not the weakness"],
 citations=[SN5(209, 214), SN5(217, 218), BK9(75, 80), C("berkowitz", 4, 34), BK11(94), C("berkowitz", 25, 270)], syndromes=["syn-weber", "syn-uncal-herniation"], pathways=["pathway-lateral-corticospinal", "pathway-corticobulbar"]))

write(E)
