import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).parent))
from lib import *
from batch10_pns_upper import pn, NOIMG
E = []
SN3 = lambda a, b=None: C("snell", 3, a, b)
SN14 = lambda a, b=None: C("snell", 14, a, b)
SN11 = lambda a, b=None: C("snell", 11, a, b)
SNA = lambda a, b=None: C("snell", 19, a, b)
BK15 = lambda a, b=None: C("berkowitz", 15, a, b)
BK17 = lambda a, b=None: C("berkowitz", 17, a, b)

E.append(pn("plexus-lumbosacral", "Lumbar and sacral plexuses", sub="lower-limb", latin="Plexus lumbosacralis",
 summary="The ventral rami of L1–S4 form two linked plexuses in the posterior abdominal wall and pelvis. The lumbar plexus (L1–L4) lies within psoas major and gives the iliohypogastric, ilioinguinal, genitofemoral and lateral femoral cutaneous nerves, the obturator nerve (medial thigh) and the femoral nerve (anterior thigh). The lumbosacral trunk (L4–L5) joins the sacral plexus (S1–S4) on piriformis in the pelvis to give the sciatic nerve (posterior thigh and everything below the knee), the superior and inferior gluteal nerves and the pudendal nerve. Plexopathies here come from diabetes (painful proximal diabetic neuropathy), pelvic tumors, retroperitoneal hematoma and radiation, and are recognized by deficits that span more than one nerve and more than one root.",
 location="Lumbar plexus within the substance of psoas major in front of the lumbar transverse processes; lumbosacral trunk crossing the pelvic brim; sacral plexus on the anterior surface of piriformis in the pelvis behind the internal iliac vessels.",
 subdivisions=[("Lumbar plexus L1–L4", "iliohypogastric, ilioinguinal, genitofemoral, lateral femoral cutaneous (L2–L3), femoral (L2–L4, posterior divisions), obturator (L2–L4, anterior divisions)"), ("Lumbosacral trunk L4–L5", "joins the sacral plexus"), ("Sacral plexus L4–S4", "superior gluteal (L4–S1), inferior gluteal (L5–S2), sciatic (L4–S3), posterior femoral cutaneous, pudendal (S2–S4)")],
 function="Motor and sensory supply of the lower limb, pelvic floor and perineum.",
 imaging=img([view("axial", 0, -48, -65, "upper cervical cord; the lumbosacral plexus lies in the abdomen and pelvis")],
     NOIMG + " Pelvic MRI with STIR and contrast shows the plexus in psoas and on piriformis; infiltration, hematoma or thickening identify the cause.",
     [pathol("Neoplastic lumbosacral plexopathy", "MRI", "Enhancing mass in the pelvis or psoas infiltrating the plexus, usually painful and progressive.", sequence="T1+Gd"), pathol("Retroperitoneal hematoma", "CT", "Psoas hematoma in an anticoagulated patient compressing the lumbar plexus and femoral nerve.", sequence="CT non-contrast"), pathol("Diabetic lumbosacral radiculoplexus neuropathy", "MRI", "Often normal or mild plexus T2 change; the diagnosis is clinical and electrophysiological.", sequence="STIR")],
     "Pelvic MRI; CT for hematoma; EMG/NCS"),
 lesion=[("Weak hip flexion, knee extension and adduction with anterior and medial thigh numbness", "ipsilateral", "Lumbar plexus: femoral and obturator territories together"), ("Foot drop with weak hip extension and abduction, and sole numbness", "ipsilateral", "Sacral plexus: sciatic and gluteal territories together"), ("Severe asymmetric thigh pain, weakness and weight loss in a diabetic", "ipsilateral", "Diabetic lumbosacral radiculoplexus neuropathy (amyotrophy)"), ("Perineal numbness and incontinence", "bilateral", "Sacral plexus and pudendal involvement")],
 exam=["Hip flexion, extension, abduction and adduction; knee extension and flexion; ankle movements", "Knee and ankle reflexes", "Sensory map of the thigh, leg and perineum", "Abdominal and rectal examination for a mass; check for a psoas sign"],
 pearls=["Weakness that crosses the femoral–sciatic boundary or the L4–S1 boundary is the plexus", "Gluteal muscle weakness distinguishes a sacral plexopathy from a sciatic neuropathy"],
 citations=[SN3(81, 83), BK17(157, 159), BK17(163)], syndromes=["syn-lumbosacral-plexopathy", "syn-femoral-neuropathy", "syn-sciatic-neuropathy"]))

E.append(pn("nerve-femoral", "Femoral nerve", sub="lower-limb", latin="Nervus femoralis",
 summary="The largest branch of the lumbar plexus (L2–L4), the femoral nerve emerges from the lateral border of psoas, passes under the inguinal ligament lateral to the femoral artery (outside the femoral sheath) and divides in the femoral triangle into branches to iliacus, pectineus, sartorius and the four heads of quadriceps and into cutaneous branches for the anterior thigh and, through the saphenous nerve, the medial leg and foot. Its lesions (retroperitoneal hematoma, diabetes, hip surgery, lithotomy position) cause the knee to give way, an absent knee jerk and anteromedial thigh and medial leg numbness.",
 location="Within psoas from L2–L4, emerging at its lateral border to run between psoas and iliacus, beneath the inguinal ligament into the femoral triangle lateral to the femoral artery, dividing within a few centimetres; the saphenous nerve continues through the adductor canal to the medial leg.",
 subdivisions=[("Muscular branches", "iliacus and psoas (hip flexion), pectineus, sartorius, quadriceps femoris (knee extension)"), ("Anterior cutaneous branches", "anterior and medial thigh"), ("Saphenous nerve", "medial leg and foot to the great toe; purely sensory")],
 function="Hip flexion and knee extension; sensation of the anterior thigh and medial leg.",
 imaging=img([view("axial", 0, -48, -65, "cervical cord; the femoral nerve arises from L2–L4")],
     NOIMG + " Pelvic CT or MRI reveals a psoas or iliacus hematoma or mass; MRI of the thigh shows quadriceps denervation.",
     [pathol("Iliacus hematoma", "CT", "Hyperdense hematoma within iliacus or psoas in an anticoagulated patient compressing the nerve.", sequence="CT non-contrast"), pathol("Femoral neuropathy after surgery or lithotomy", "MRI", "Denervation edema of quadriceps with a normal plexus.", sequence="STIR")],
     "EMG (quadriceps and iliopsoas; adductors spared) and femoral nerve conduction; pelvic CT"),
 lesion=[("Knee buckling and difficulty climbing stairs; wasted quadriceps; absent knee jerk", "ipsilateral", "Quadriceps paralysis"), ("Weak hip flexion", "ipsilateral", "Iliacus involvement (lesion above the inguinal ligament)"), ("Numbness of the anterior thigh and medial leg", "ipsilateral", "Cutaneous branches and saphenous nerve"), ("Preserved hip adduction", "n/a", "Obturator nerve intact, distinguishing nerve from L2–L4 root or plexus lesions")],
 exam=["Knee extension against resistance and quadriceps bulk", "Knee reflex", "Hip flexion (iliopsoas) to place the lesion above or below the ligament", "Hip adduction (obturator) to exclude a plexus or root lesion", "Sensation on the medial leg"],
 pearls=["Weak knee extension with an absent knee jerk and normal adduction is the femoral nerve; weak adduction too means L2–L4 roots or the lumbar plexus", "Groin pain and quadriceps weakness in an anticoagulated patient: CT the pelvis for a hematoma"],
 citations=[SN3(112), BK17(157, 164)], syndromes=["syn-femoral-neuropathy", "syn-lumbosacral-plexopathy"]))

E.append(pn("nerve-obturator", "Obturator nerve", sub="lower-limb", latin="Nervus obturatorius",
 summary="Formed from the anterior divisions of L2–L4 inside psoas, the obturator nerve runs along the pelvic side wall and leaves through the obturator canal to supply the adductor muscles of the thigh (adductor longus, brevis and magnus, gracilis, obturator externus) and a patch of skin on the medial thigh. It is injured by pelvic tumors, obstetric trauma and pelvic surgery, and its lesion produces a wide-based, circumducting gait with weak adduction and medial thigh numbness; hip joint pain referred to the knee travels in its articular branches.",
 location="Medial border of psoas, along the lateral pelvic wall below the pelvic brim, through the obturator foramen in the obturator canal, dividing into anterior and posterior branches around adductor brevis.",
 function="Hip adduction and part of medial rotation; sensation of the medial thigh; sensory fibers to the hip and knee joints.",
 imaging=img([view("axial", 0, -48, -65, "cervical cord; the obturator nerve arises from L2–L4")],
     NOIMG + " Pelvic MRI shows a mass or endometriosis along the pelvic side wall or at the obturator canal, with adductor denervation.",
     [pathol("Obturator neuropathy", "MRI", "STIR-bright adductor muscles with a pelvic side wall mass or post-surgical change.", sequence="STIR")],
     "EMG of the adductors; pelvic MRI"),
 lesion=[("Weak hip adduction with a circumducting gait", "ipsilateral", "Adductor paralysis"), ("Numbness of the medial thigh", "ipsilateral", "Cutaneous branch"), ("Referred knee pain from hip disease", "ipsilateral", "Articular branches to hip and knee")],
 exam=["Hip adduction against resistance in the supine position", "Sensation over the medial thigh", "Combine with femoral testing: both weak means root or plexus"],
 pearls=["Isolated adductor weakness after pelvic surgery is the obturator nerve", "Knee pain with a normal knee and a limited hip is obturator-referred hip disease"],
 citations=[SN3(112), BK17(157, 164)], syndromes=["syn-lumbosacral-plexopathy"]))

E.append(pn("nerve-lateral-femoral-cutaneous", "Lateral femoral cutaneous nerve", sub="lower-limb", latin="Nervus cutaneus femoris lateralis",
 summary="A purely sensory branch of the lumbar plexus (L2–L3) that crosses iliacus and passes under or through the inguinal ligament just medial to the anterior superior iliac spine to supply the skin of the anterolateral thigh. Its entrapment at the ligament by obesity, pregnancy, tight belts or prolonged hip flexion produces meralgia paresthetica: burning, tingling and numbness over the lateral thigh with no weakness and no reflex change.",
 location="Lateral border of psoas, across iliacus deep to its fascia, under the lateral end of the inguinal ligament about 1 cm medial to the anterior superior iliac spine, then over sartorius into the thigh, dividing into anterior and posterior branches.",
 function="Sensation of the anterolateral thigh from the greater trochanter to the knee; no motor fibers.",
 imaging=img([view("axial", 0, -48, -65, "cervical cord; the nerve arises from L2–L3")],
     NOIMG + " Ultrasound identifies the nerve at the inguinal ligament for diagnostic block; imaging is otherwise unnecessary unless a pelvic mass is suspected.",
     [pathol("Meralgia paresthetica", "US", "Swollen nerve at the inguinal ligament; a diagnostic local anesthetic block relieves the symptoms.", sequence="n/a")],
     "Clinical diagnosis; nerve block; sensory conduction studies if available"),
 lesion=[("Burning pain, tingling and numbness over the lateral thigh, worse on standing and walking", "ipsilateral", "Entrapment at the inguinal ligament"), ("No weakness, normal knee jerk", "n/a", "Purely sensory nerve")],
 exam=["Map the sensory loss on the lateral thigh (does not cross the midline of the thigh or reach the knee joint)", "Confirm normal quadriceps power and knee reflex to exclude L3 root or femoral lesions", "Tenderness or Tinel at the inguinal ligament"],
 pearls=["A patch of lateral thigh numbness with normal power and reflexes is meralgia paresthetica, not a radiculopathy", "Ask about weight gain, pregnancy, belts and hip surgery"],
 citations=[BK17(157), BK17(164)], syndromes=["syn-meralgia-paresthetica"]))

E.append(pn("nerve-sciatic", "Sciatic nerve", sub="lower-limb", latin="Nervus ischiadicus",
 summary="The thickest nerve in the body, formed from L4–S3 in the sacral plexus, leaves the pelvis through the greater sciatic foramen below piriformis, runs down the posterior thigh between the ischial tuberosity and the greater trochanter deep to gluteus maximus, supplies the hamstrings and the ischial part of adductor magnus, and divides above the knee into the tibial and common peroneal nerves, which together supply everything below the knee. Its two divisions are already separate bundles within the trunk, and the lateral (peroneal) division is more vulnerable to stretch and compression, so sciatic lesions often look like peroneal palsies with subtle tibial involvement.",
 location="From the sacral plexus on piriformis through the infrapiriform part of the greater sciatic foramen, midway between the ischial tuberosity and greater trochanter, down the posterior thigh on adductor magnus under the long head of biceps femoris, dividing at the apex of the popliteal fossa.",
 subdivisions=[("Tibial division (L4–S3)", "hamstrings (except short head of biceps), adductor magnus, all posterior leg and sole muscles"), ("Common peroneal division (L4–S2)", "short head of biceps femoris, anterior and lateral leg muscles, dorsum of the foot")],
 function="Knee flexion, hip extension (with the gluteals) and all movements of the ankle and foot; sensation of the posterior thigh (via the posterior femoral cutaneous nerve travelling with it) and the whole leg and foot below the knee except the medial (saphenous) strip.",
 imaging=img([view("axial", 0, -48, -65, "cervical cord; the sciatic nerve arises from L4–S3")],
     NOIMG + " MR neurography of the pelvis and thigh shows the nerve at the sciatic notch and along the thigh; hematoma, tumor, piriformis anomalies and injection injury are identified.",
     [pathol("Sciatic neuropathy after hip surgery or injection", "MRI", "Thickened T2-bright nerve at the sciatic notch or gluteal region with denervation of hamstrings and leg muscles.", sequence="STIR"), pathol("Piriformis syndrome", "MRI", "Asymmetric piriformis or nerve variant passing through the muscle; controversial diagnosis.", sequence="T1")],
     "EMG (short head of biceps femoris distinguishes sciatic from peroneal lesions); pelvic and thigh MRI"),
 lesion=[("Foot drop with weak plantar flexion, knee flexion and an absent ankle jerk", "ipsilateral", "Complete sciatic lesion: both divisions"), ("Foot drop with subtle weakness of foot inversion and plantar flexion", "ipsilateral", "Partial sciatic lesion, peroneal division more affected"), ("Numbness of the whole foot and lateral leg", "ipsilateral", "Both tibial and peroneal sensory territories"), ("Preserved hip abduction and extension", "n/a", "Gluteal nerves leave the plexus separately, unlike in a plexopathy")],
 exam=["Knee flexion (hamstrings) and ankle jerk to separate sciatic from common peroneal lesions", "Ankle inversion (tibial) versus eversion and dorsiflexion (peroneal)", "Sensation of the sole and lateral leg", "Hip abduction (superior gluteal) to exclude a plexopathy", "Straight-leg raise; palpate the sciatic notch"],
 pearls=["Foot drop plus a lost ankle jerk or weak knee flexion is the sciatic nerve, not the peroneal nerve", "Gluteal weakness means the lesion is in the plexus or roots, above the sciatic nerve"],
 citations=[SN3(112), BK17(157, 165)], syndromes=["syn-sciatic-neuropathy", "syn-peroneal-palsy-foot-drop", "syn-radiculopathy-lumbosacral"], pitfalls=["An L5 radiculopathy also gives foot drop with inversion weakness; back pain, a positive straight-leg raise and paraspinal EMG changes point to the root"]))

E.append(pn("nerve-tibial", "Tibial nerve", sub="lower-limb", latin="Nervus tibialis", synonyms=["medial popliteal nerve"],
 summary="The larger terminal division of the sciatic nerve (L4–S3) runs straight through the popliteal fossa and down the back of the leg deep to soleus with the posterior tibial artery, supplying the plantar flexors and invertors (gastrocnemius, soleus, tibialis posterior, flexor digitorum longus, flexor hallucis longus), then passes behind the medial malleolus through the tarsal tunnel to divide into the medial and lateral plantar nerves for the sole. Sensation of the sole and heel and the ankle reflex belong to it. It is well protected and rarely injured proximally; distal entrapment in the tarsal tunnel causes burning sole pain.",
 location="Popliteal fossa in the midline superficial to the popliteal vessels, then between the superficial and deep posterior compartments of the leg on tibialis posterior, behind the medial malleolus under the flexor retinaculum (tarsal tunnel) between the flexor digitorum longus and flexor hallucis longus tendons.",
 subdivisions=[("Muscular branches in the leg", "gastrocnemius, soleus, plantaris, popliteus, tibialis posterior, flexor digitorum longus, flexor hallucis longus"), ("Sural nerve (with a peroneal contribution)", "posterolateral leg and lateral foot"), ("Medial calcaneal branch", "heel"), ("Medial and lateral plantar nerves", "intrinsic muscles of the sole and plantar sensation (medial plantar: medial three and a half toes, like the median nerve; lateral plantar: lateral one and a half, like the ulnar)")],
 function="Plantar flexion, foot inversion, toe flexion and the intrinsic foot muscles; sensation of the sole, heel and lateral foot; the ankle (S1) reflex.",
 imaging=img([view("axial", 0, -48, -65, "cervical cord; the tibial nerve derives from L4–S3")],
     NOIMG + " Ankle MRI shows the tarsal tunnel with a ganglion, varicosity or accessory muscle compressing the nerve and denervation of the plantar muscles.",
     [pathol("Tarsal tunnel syndrome", "MRI", "Space-occupying lesion under the flexor retinaculum with STIR-bright abductor hallucis and plantar muscles.", sequence="STIR"), pathol("Popliteal fossa lesion (Baker cyst, aneurysm)", "US", "Cyst or popliteal artery aneurysm compressing the nerve.", sequence="n/a")],
     "EMG/NCS including plantar nerves; ankle MRI or ultrasound"),
 lesion=[("Weak plantar flexion and inversion, cannot stand on toes, absent ankle jerk", "ipsilateral", "Proximal tibial lesion"), ("Burning pain and numbness of the sole worse at night, with weak toe flexion", "ipsilateral", "Tarsal tunnel entrapment"), ("Clawing of the toes with intrinsic wasting", "ipsilateral", "Plantar nerve lesions")],
 exam=["Toe-stand and heel-stand", "Ankle jerk", "Foot inversion (tibialis posterior)", "Sole sensation and Tinel behind the medial malleolus"],
 pearls=["Foot drop with weak inversion but preserved plantar flexion and ankle jerk is peroneal or L5; add plantar flexion weakness and a lost ankle jerk and it is sciatic or S1", "Sole numbness with normal dorsum sensation is the tibial nerve or its plantar branches"],
 citations=[SN3(112), BK17(157, 166)], syndromes=["syn-tarsal-tunnel", "syn-sciatic-neuropathy", "syn-radiculopathy-lumbosacral"]))

E.append(pn("nerve-common-peroneal", "Common (and deep/superficial) peroneal nerve", sub="lower-limb", latin="Nervus fibularis communis", synonyms=["common fibular nerve", "lateral popliteal nerve"],
 summary="The smaller lateral division of the sciatic nerve (L4–S2) runs along the medial border of biceps femoris to the lateral side of the popliteal fossa, winds around the neck of the fibula (where it lies on bone under thin skin) and divides into the deep peroneal nerve, which supplies the anterior compartment (tibialis anterior, extensor digitorum longus, extensor hallucis longus) and the first web space skin, and the superficial peroneal nerve, which supplies the evertors (peroneus longus and brevis) and the dorsum of the foot. Compression at the fibular neck by crossed legs, casts, weight loss or squatting is the commonest cause of foot drop.",
 location="Lateral popliteal fossa along the tendon of biceps femoris, around the neck of the fibula deep to peroneus longus (the fibular tunnel), where it divides; the deep branch runs on the interosseous membrane with the anterior tibial artery, the superficial branch in the lateral compartment.",
 subdivisions=[("Common peroneal nerve", "short head of biceps femoris (in the thigh, from the sciatic trunk), lateral sural cutaneous nerve"), ("Deep peroneal nerve", "tibialis anterior, extensor digitorum longus and brevis, extensor hallucis longus, peroneus tertius; first dorsal web space"), ("Superficial peroneal nerve", "peroneus longus and brevis (eversion); dorsum of the foot and lateral leg")],
 function="Ankle dorsiflexion and toe extension (deep), foot eversion (superficial), and sensation of the dorsum of the foot and the lateral leg.",
 imaging=img([view("axial", 0, -48, -65, "cervical cord; the peroneal nerve derives from L4–S2")],
     NOIMG + " Ultrasound and MRI at the fibular neck show nerve swelling, an intraneural ganglion from the tibiofibular joint, or a fibular head fracture, with denervation of the anterior and lateral compartments.",
     [pathol("Peroneal neuropathy at the fibular neck", "US", "Enlarged nerve at the fibular neck; nerve conduction shows conduction block across the fibular head.", sequence="n/a"), pathol("Intraneural ganglion", "MRI", "Cystic expansion of the nerve tracking from the superior tibiofibular joint.", sequence="T2"), pathol("Anterior compartment syndrome", "MRI", "Swollen anterior compartment muscles with deep peroneal nerve involvement after trauma or exertion.", sequence="STIR")],
     "Nerve conduction across the fibular neck; EMG including short head of biceps femoris; ultrasound"),
 lesion=[("Foot drop with weak eversion, steppage gait, numbness of the dorsum of the foot", "ipsilateral", "Common peroneal nerve at the fibular neck"), ("Foot drop with preserved eversion and numbness limited to the first web space", "ipsilateral", "Deep peroneal nerve"), ("Weak eversion with dorsal foot numbness and normal dorsiflexion", "ipsilateral", "Superficial peroneal nerve"), ("Preserved inversion and ankle jerk", "n/a", "Tibial nerve and S1 intact, distinguishing it from sciatic and L5 lesions")],
 exam=["Dorsiflexion, toe extension and eversion against resistance; inversion (should be normal)", "Ankle jerk (normal)", "Sensation of the dorsum, first web space and lateral leg", "Tinel at the fibular neck; look for a habit of crossing the legs, recent weight loss or a cast"],
 pearls=["Foot drop with normal inversion is peroneal; with weak inversion it is L5 or sciatic", "Weight loss plus foot drop: the nerve has lost its fat cushion at the fibular neck"],
 citations=[SN3(112), BK17(163, 166)], syndromes=["syn-peroneal-palsy-foot-drop", "syn-sciatic-neuropathy", "syn-radiculopathy-lumbosacral"]))

E.append(pn("roots-l2-s1", "Lumbosacral roots L2–S1", sub="lower-limb", latin="Radices L2–S1",
 summary="The lumbosacral roots descend obliquely from the conus as the cauda equina before leaving through their foramina, so a posterolateral disc at one level compresses the root that has not yet exited (the L4–L5 disc compresses L5, the L5–S1 disc compresses S1) while a far-lateral disc catches the root above. Each root has a bedside signature: L2–L3 hip flexion and anterior thigh; L4 knee extension, foot inversion, the knee jerk and the medial leg; L5 dorsiflexion, great toe extension, hip abduction and the dorsum of the foot; S1 plantar flexion, hip extension, the ankle jerk and the lateral foot and sole. L5 and S1 radiculopathies account for most sciatica.",
 location="Roots leaving the conus at T12–L1 and descending in the cauda equina to their foramina; the exiting root passes below the pedicle of the same-numbered vertebra, the traversing root of the next level crosses the disc.",
 subdivisions=[("L2–L3", "iliopsoas, adductors, quadriceps (partly); anterior and medial thigh"), ("L4", "quadriceps, tibialis anterior (inversion component); knee reflex; medial leg to the medial malleolus"), ("L5", "extensor hallucis longus, tibialis anterior, peroneals, gluteus medius, hamstrings (partly); no reliable reflex (medial hamstring); dorsum of the foot, great toe, lateral leg"), ("S1", "gastrocnemius, soleus, gluteus maximus, hamstrings; ankle reflex; lateral foot, sole, posterior calf"), ("S2–S4", "pelvic floor, sphincters; perineum")],
 function="Segmental motor, sensory and autonomic supply to the lower limb and perineum.",
 imaging=img([view("sagittal", 0, -48, -65, "cord (the lumbosacral roots lie in the lumbar canal, below the MNI volume)")],
     NOIMG + " Lumbar MRI shows the disc herniation, lateral recess or foraminal stenosis and its relation to the exiting and traversing roots; root enhancement suggests inflammation.",
     [pathol("Lumbar disc herniation", "MRI", "Posterolateral L4–L5 or L5–S1 protrusion compressing the traversing L5 or S1 root in the lateral recess.", sequence="T2"), pathol("Foraminal stenosis / far-lateral disc", "MRI", "Compression of the exiting root (L4 at L4–L5) in the foramen.", sequence="T2"), pathol("Lumbar canal stenosis", "MRI", "Trefoil canal with crowded roots and neurogenic claudication.", sequence="T2")],
     "Lumbar MRI; EMG including paraspinal muscles"),
 lesion=[("Sciatica to the great toe, weak dorsiflexion and great toe extension, weak hip abduction (Trendelenburg), reflexes preserved", "ipsilateral", "L5 radiculopathy (L4–L5 disc)"), ("Sciatica to the lateral foot, weak plantar flexion and absent ankle jerk", "ipsilateral", "S1 radiculopathy (L5–S1 disc)"), ("Anterior thigh pain, weak knee extension and absent knee jerk", "ipsilateral", "L3–L4 radiculopathy (femoral stretch test positive)"), ("Bilateral leg pain on walking relieved by sitting", "bilateral", "Lumbar canal stenosis compressing several roots")],
 exam=["Straight-leg raise (L5, S1) and femoral stretch (L2–L4)", "Key muscles: extensor hallucis longus (L5), toe-stand (S1), knee extension (L4)", "Knee and ankle reflexes", "Dermatomes: medial leg L4, dorsum L5, lateral foot S1", "Hip abduction for L5 (gluteus medius, spared in peroneal palsy)"],
 pearls=["Foot drop with weak hip abduction and inversion is L5; with normal abduction and inversion it is the peroneal nerve", "The ankle jerk belongs to S1 and the knee jerk to L4; L5 has no convenient reflex"],
 citations=[SN3(98, 100), SNA(510, 511), BK17(157, 163), BK15(130, 133)], syndromes=["syn-radiculopathy-lumbosacral", "syn-lumbar-stenosis", "syn-conus-vs-cauda-equina", "syn-peroneal-palsy-foot-drop"]))

E.append(pn("neuromuscular-junction", "Neuromuscular junction", sub="neuromuscular", latin="Junctio neuromuscularis", synonyms=["motor end plate"],
 summary="The chemical synapse between a motor axon terminal and a skeletal muscle fiber. Acetylcholine released in quanta from the terminal crosses the cleft, binds nicotinic receptors on the folded post-synaptic membrane to produce an end-plate potential and a muscle action potential, and is hydrolysed by acetylcholinesterase. Disease of the junction produces fatigable weakness without sensory loss, wasting or reflex change: post-synaptic antibodies in myasthenia gravis, pre-synaptic calcium-channel antibodies in the Lambert–Eaton syndrome, and toxins (botulinum, organophosphates, neuromuscular blockers) at various steps.",
 location="Motor end plates near the middle of each muscle fiber where the terminal branches of the motor axon end; one junction per fiber, many per motor unit.",
 subdivisions=[("Presynaptic terminal", "voltage-gated calcium channels, acetylcholine vesicles; target of Lambert–Eaton antibodies and botulinum toxin"), ("Synaptic cleft", "acetylcholinesterase in the basal lamina; target of organophosphates and pyridostigmine"), ("Postsynaptic membrane", "junctional folds with nicotinic acetylcholine receptors and MuSK; target of myasthenia gravis antibodies and of non-depolarizing blockers")],
 function="Reliable one-to-one transmission of the motor neuron action potential to the muscle fiber with a large safety factor, which disease erodes to produce fatigability.",
 imaging=img([view("axial", 0, -48, -65, "cervical cord; the junction is in the muscles, not imaged")],
     "Not imaged directly. The imaging task in junction disease is the thymus: CT of the chest for thymoma or hyperplasia in myasthenia gravis, and a search for small-cell lung cancer in the Lambert–Eaton syndrome.",
     [pathol("Thymoma in myasthenia gravis", "CT", "Anterior mediastinal soft-tissue mass; thymic hyperplasia in younger patients.", sequence="CT contrast"), pathol("Small-cell lung cancer in Lambert–Eaton syndrome", "CT", "Central lung mass with mediastinal nodes; repeat imaging for two years if negative.", sequence="CT contrast")],
     "Chest CT; repetitive nerve stimulation and single-fiber EMG; antibody testing"),
 lesion=[("Fatigable ptosis, diplopia, dysarthria, dysphagia and proximal weakness worse through the day", "bilateral", "Postsynaptic receptor loss (myasthenia gravis)"), ("Proximal leg weakness that improves briefly with exercise, dry mouth, absent reflexes that return after exercise", "bilateral", "Presynaptic calcium channel antibodies (Lambert–Eaton)"), ("Descending paralysis with dilated pupils and dry mouth", "bilateral", "Botulinum toxin blocking release"), ("Weakness with fasciculations, salivation and miosis", "bilateral", "Cholinesterase inhibition (organophosphates)")],
 exam=["Sustained up-gaze for ptosis, repeated arm abduction, count to 50 for dysarthria", "Ice pack test on a ptotic lid", "Reflexes: normal in myasthenia, absent then facilitated in Lambert–Eaton", "Pupils: normal in myasthenia, dilated in botulism", "Respiratory function (vital capacity, single breath count)"],
 pearls=["Fluctuating weakness with normal sensation and normal reflexes is the junction", "Never give aminoglycosides or magnesium to a myasthenic without thinking; check vital capacity, not oxygen saturation, in a myasthenic crisis"],
 citations=[SN3(91, 93), BK15(129), C("berkowitz", 29, 293, 298), C("berkowitz", 20, 219, 220)], syndromes=["syn-myasthenia-gravis", "syn-lambert-eaton"]))

E.append(pn("motor-unit", "Motor unit and skeletal muscle", sub="neuromuscular", synonyms=["lower motor neuron unit"],
 summary="A motor unit is one anterior horn cell, its axon and all the muscle fibers it innervates, from a few fibers in the extraocular muscles to over a thousand in gastrocnemius. Force is graded by recruiting units in order of size and by increasing their firing rate. This is the framework of electromyography: neurogenic disease loses units and enlarges the survivors by collateral reinnervation (large, long, polyphasic potentials with reduced recruitment), while myopathic disease loses fibers within units (small, short, polyphasic potentials with early recruitment). Clinically, the motor unit is the lower motor neuron, and its failure produces weakness with wasting, fasciculations, hypotonia and lost reflexes.",
 location="Anterior horn cell in the spinal gray matter or brainstem motor nucleus, axon in the ventral root and peripheral nerve, terminal branches at the end plates of muscle fibers scattered through the muscle.",
 subdivisions=[("Type I (slow, oxidative) units", "small, fatigue-resistant, recruited first; postural muscles"), ("Type II (fast) units", "large, glycolytic, recruited later for power"), ("Muscle spindle and Golgi tendon organ", "sensory feedback that sets tone and the stretch reflex; gamma motor neurons adjust spindle sensitivity")],
 function="Generation of muscle force under voluntary and reflex control; the size principle of recruitment; maintenance of tone through the stretch reflex loop.",
 imaging=img([view("axial", 0, -48, -65, "cervical cord: anterior horn cells are the motor unit's origin")],
     "Muscle MRI (T1 for fatty replacement, STIR for edema) shows the pattern of involvement: selective muscles in dystrophies and myopathies, diffuse edema in myositis, denervation edema in the territory of a nerve or root; muscle ultrasound shows increased echogenicity.",
     [pathol("Inflammatory myopathy", "MRI", "Symmetric STIR-bright edema of proximal muscles, later fatty atrophy; guides biopsy site.", sequence="STIR"), pathol("Muscular dystrophy", "MRI", "Selective fatty replacement of specific muscles (e.g. adductors and hamstrings) on T1 with characteristic patterns per gene.", sequence="T1"), pathol("Denervation", "MRI", "STIR edema of muscles sharing a nerve or root, then atrophy.", sequence="STIR")],
     "Muscle MRI; EMG; creatine kinase; biopsy"),
 lesion=[("Weakness with wasting, fasciculations, hypotonia and reduced reflexes", "n/a", "Loss of motor units (neurogenic)"), ("Proximal weakness with preserved reflexes and no fasciculations", "bilateral", "Loss of fibers within units (myopathic)"), ("Cramps and fasciculations", "n/a", "Irritable motor units in neurogenic disease")],
 exam=["Distribution: proximal (myopathy) versus distal (neuropathy) versus mixed asymmetric (motor neuron disease)", "Look for fasciculations at rest in several muscles", "Reflexes relative to weakness", "Gower sign and neck flexion power", "Creatine kinase"],
 pearls=["Proximal symmetric weakness with normal sensation and preserved reflexes is muscle; distal weakness with sensory loss is nerve; asymmetric weakness with fasciculations and brisk reflexes is motor neuron disease", "EMG asks one question: are the units big and few (nerve) or small and many (muscle)?"],
 citations=[SN3(93), SN3(101, 102), BK15(129), BK15(136, 140), C("berkowitz", 30, 299, 305)], syndromes=["syn-myopathy-pattern", "syn-als-pattern", "syn-poliomyelitis"]))

# ---------------- autonomic
def au(id, name, summary, location, function, imaging, lesion, exam, pearls, citations, syndromes=(), pitfalls=(), synonyms=(), latin=None, subdivisions=(), afferents=(), efferents=(), meshes=(), pathways=()):
    return structure(id, name, "autonomic", summary, location, function, ["regional arteries"], imaging, lesion, exam, pearls, citations, meshIds=list(meshes), level={"region": "peripheral"},
        syndromes=syndromes, pitfalls=pitfalls, synonyms=synonyms, latin=latin, subdivisions=subdivisions, afferents=afferents, efferents=efferents, pathways=pathways, tags=["autonomic"])

E.append(au("autonomic-cranial-parasympathetic", "Cranial parasympathetic outflow", latin="Pars parasympathica: nervi craniales III, VII, IX, X",
 summary="The craniosacral parasympathetic system leaves the brainstem in four cranial nerves, each with its own brainstem nucleus and peripheral ganglion: the oculomotor nerve (Edinger–Westphal nucleus → ciliary ganglion) constricts the pupil and accommodates; the facial nerve (superior salivatory nucleus → pterygopalatine and submandibular ganglia) drives lacrimation, nasal secretion and submandibular and sublingual salivation; the glossopharyngeal nerve (inferior salivatory nucleus → otic ganglion) drives the parotid; and the vagus (dorsal motor nucleus and nucleus ambiguus → ganglia in the walls of the viscera) slows the heart, constricts the bronchi and drives gut secretion and motility down to the splenic flexure. Long preganglionic and short postganglionic fibers, acetylcholine at both synapses and muscarinic receptors at the target are its pharmacological fingerprints.",
 location="Nuclei in the midbrain (Edinger–Westphal), pons (superior salivatory) and medulla (inferior salivatory, dorsal vagal, ambiguus); preganglionic fibers in CN III, VII, IX and X; ganglia in the orbit (ciliary), pterygopalatine fossa, submandibular region, below the foramen ovale (otic) and within the thoracic and abdominal viscera.",
 subdivisions=[("Oculomotor (III)", "Edinger–Westphal → ciliary ganglion → sphincter pupillae, ciliary muscle"), ("Facial (VII)", "superior salivatory nucleus → greater petrosal nerve → pterygopalatine ganglion (lacrimal, nasal, palatine glands); chorda tympani → submandibular ganglion (submandibular, sublingual glands)"), ("Glossopharyngeal (IX)", "inferior salivatory nucleus → tympanic plexus, lesser petrosal nerve → otic ganglion → parotid via the auriculotemporal nerve"), ("Vagus (X)", "dorsal motor nucleus and ambiguus → cardiac, pulmonary, esophageal and abdominal plexuses → intramural ganglia")],
 function="Rest-and-digest control of the head and thoracoabdominal viscera: pupillary constriction and accommodation, secretion of tears and saliva, cardiac slowing, bronchoconstriction, gut secretion and peristalsis.",
 imaging=img([view("axial", 2, -24, -6, "Edinger–Westphal region of the midbrain"), view("axial", 5, -46, -44, "dorsal vagal nucleus region in the medulla")],
     "Nuclei and ganglia are not resolved on routine MRI; the relevant imaging is of the nerves along their courses (orbit for the ciliary ganglion region, temporal bone for the facial nerve, skull base for IX and X).",
     [pathol("Compressive third nerve palsy with pupil involvement", "CTA", "PComm aneurysm compressing the superficial parasympathetic fibers.", sequence="CT contrast"), pathol("Facial nerve lesion proximal to the geniculate ganglion", "MRI", "Enhancement of the labyrinthine segment with reduced tearing and salivation on that side.", sequence="T1+Gd")],
     "Imaging of the relevant cranial nerve; pharmacological pupil tests; Schirmer test"),
 lesion=[("Dilated, unreactive pupil with loss of accommodation", "ipsilateral", "Preganglionic fibers in CN III or the ciliary ganglion"), ("Dry eye and reduced nasal secretion", "ipsilateral", "Greater petrosal nerve or pterygopalatine ganglion (facial nerve lesion at or above the geniculate ganglion)"), ("Reduced salivation", "ipsilateral", "Chorda tympani (VII) or otic ganglion pathway (IX)"), ("Tachycardia, gastroparesis", "n/a", "Vagal denervation (diabetes, surgery)")],
 exam=["Pupil reaction to light and near; dilute pilocarpine test for denervation supersensitivity", "Schirmer test for tearing", "Heart rate variability with breathing and Valsalva", "Salivary flow"],
 pearls=["The pupillary fibers travel on the surface of the third nerve: compression hits them first, ischemia spares them", "A facial palsy with dry eye and loss of taste is proximal (geniculate or above); with normal tearing it is distal"],
 citations=[SN14(387, 392), SN14(396, 399), SN11(329, 331), SN11(337, 345), C("berkowitz", 10, 83, 85), C("berkowitz", 13, 120, 124)], syndromes=["syn-cn3-palsy", "syn-adie-tonic-pupil", "syn-facial-palsy-peripheral-vs-central"], pathways=["pathway-pupillary-light-reflex"]))

E.append(au("autonomic-sacral-parasympathetic", "Sacral parasympathetic outflow and bladder control", latin="Nervi splanchnici pelvici (S2–S4)",
 summary="The sacral parasympathetic neurons in the S2–S4 segments of the conus send preganglionic fibers through the pelvic splanchnic nerves to ganglia in the walls of the bladder, rectum and genitals, driving detrusor contraction, rectal emptying and erection. Micturition is a reflex coordinated in the pontine micturition center and released or withheld by the frontal lobes: bladder filling is sensed, the pons switches detrusor contraction on and the sphincter (pudendal, Onuf's nucleus) off, and the cortex decides when. Lesions above the sacral cord give a spastic, small, reflexic bladder with urgency; lesions of the conus, cauda equina or pelvic nerves give a flaccid, large, areflexic bladder with retention and overflow.",
 location="Sacral parasympathetic nucleus in the intermediolateral region of S2–S4 in the conus medullaris; pelvic splanchnic nerves joining the inferior hypogastric plexus; intramural ganglia in the pelvic viscera; pudendal nerve (S2–S4, somatic) to the external sphincters and perineum.",
 subdivisions=[("Sacral parasympathetic nucleus (S2–S4)", "detrusor contraction, rectal contraction, erection"), ("Onuf's nucleus (S2–S4, somatic)", "external urethral and anal sphincters via the pudendal nerve; spared in ALS, lost in multiple system atrophy"), ("Sympathetic (T11–L2) via the hypogastric nerves", "bladder neck closure, ejaculation, relaxation of the detrusor"), ("Pontine micturition center", "coordinates detrusor and sphincter (detrusor-sphincter synergy)"), ("Medial frontal cortex", "voluntary initiation and inhibition of voiding")],
 function="Emptying of the bladder and rectum, penile and clitoral erection, and, with the sympathetic and somatic components, continence, ejaculation and coordinated voiding.",
 imaging=img([view("sagittal", 0, -48, -65, "cord (the sacral outflow lies in the conus at L1–L2, below the MNI volume)"), view("axial", 0, -34, -36, "pontine tegmentum: the micturition center lies dorsally near the locus coeruleus")],
     "Not imaged directly; the sagittal lumbar MRI shows the conus and cauda equina, and cranial MRI shows the medial frontal and pontine regions. Urodynamics classify the bladder dysfunction.",
     [pathol("Conus or cauda equina lesion", "MRI", "Mass, disc or infarct at the conus or compressing the sacral roots with an areflexic bladder.", sequence="T2"), pathol("Suprasacral cord lesion", "MRI", "Cervical or thoracic myelopathy with detrusor overactivity and detrusor-sphincter dyssynergia.", sequence="T2"), pathol("Normal pressure hydrocephalus / bilateral medial frontal lesions", "MRI", "Ventriculomegaly or medial frontal lesions with urge incontinence and gait apraxia.", sequence="T1")],
     "Spine MRI; post-void residual; urodynamics"),
 lesion=[("Urgency, frequency and reflex incontinence with a small bladder", "bilateral", "Suprasacral cord lesion: detrusor overactivity without inhibition, often with dyssynergia"), ("Retention with overflow, a large painless bladder, absent anal reflex", "bilateral", "Conus, cauda equina or pelvic nerve lesion: detrusor areflexia"), ("Incontinence without concern (frontal)", "bilateral", "Loss of cortical inhibition and awareness"), ("Erectile failure and constipation", "bilateral", "Sacral parasympathetic loss")],
 exam=["Perianal sensation, anal tone, anal and bulbocavernosus reflexes", "Post-void residual by bladder scan", "Lower limb reflexes and plantars to place the lesion above or below the conus", "Gait and cognition if a frontal cause is suspected"],
 pearls=["Retention means the lesion is at or below the conus (or spinal shock); urgency means it is above", "Preserved sphincter control in a patient with wasted hands and brisk legs favors ALS; early incontinence favors multiple system atrophy"],
 citations=[SN14(403, 404), C("berkowitz", 5, 44), C("berkowitz", 5, 45)], syndromes=["syn-conus-vs-cauda-equina", "syn-complete-transection-spinal-shock", "syn-normal-pressure-hydrocephalus"]))

E.append(au("cervical-sympathetic-chain", "Cervical sympathetic chain and stellate ganglion", latin="Ganglia cervicalia; ganglion cervicothoracicum",
 summary="The head and neck receive their sympathetic supply by a three-neuron chain: first-order neurons in the hypothalamus descend through the brainstem and lateral cervical cord to the ciliospinal center at C8–T2; second-order preganglionic fibers leave in the T1 root, cross the apex of the lung and ascend the cervical chain through the stellate and middle ganglia to the superior cervical ganglion; third-order postganglionic fibers travel on the internal carotid artery to the eye (dilator pupillae, Müller's muscle) and on the external carotid to the facial sweat glands. Interruption anywhere gives Horner syndrome, and the level can be inferred from sweating and from pharmacological pupil tests.",
 location="Superior cervical ganglion at C2–C3 behind the carotid sheath; middle ganglion at C6; stellate ganglion in front of the C7 transverse process and the neck of the first rib, behind the subclavian artery at the apex of the pleura.",
 subdivisions=[("First-order (central) neuron", "hypothalamus → brainstem tegmentum → lateral cervical cord; lesions: lateral medullary infarct, cord lesions"), ("Second-order (preganglionic) neuron", "C8–T2 → T1 root → stellate → superior cervical ganglion; lesions: Pancoast tumor, neck and thoracic surgery, trauma"), ("Third-order (postganglionic) neuron", "superior cervical ganglion → internal carotid plexus → cavernous sinus → eye; lesions: carotid dissection, cavernous sinus disease, cluster headache")],
 function="Pupillary dilation, elevation of the upper lid (Müller's muscle), sweating and vasoconstriction of the face, and sympathetic supply to the salivary glands, thyroid, heart and upper limb (stellate).",
 imaging=img([view("axial", 0, -48, -65, "upper cervical cord: descending first-order sympathetic fibers in the lateral funiculus"), view("axial", 12, 5, -18, "cavernous carotid carrying the third-order fibers")],
     "The chain is not seen as such; imaging follows the level suggested by the examination: brain and cervical cord MRI for first-order lesions, chest CT of the lung apex for second-order, and carotid CTA/MRI for third-order lesions.",
     [pathol("Pancoast tumor", "CT", "Apical lung mass invading the stellate ganglion and lower brachial plexus.", sequence="CT contrast"), pathol("Carotid dissection", "MRI", "Crescentic mural hematoma of the internal carotid with a postganglionic Horner syndrome.", sequence="T1"), pathol("Lateral medullary infarct", "MRI", "Dorsolateral medullary restriction with a central Horner syndrome.", sequence="DWI")],
     "Targeted imaging by level: brain/cord MRI, chest CT, carotid CTA"),
 lesion=[("Horner syndrome with anhidrosis of the whole ipsilateral face and body side", "ipsilateral", "First-order lesion (brainstem or cord)"), ("Horner syndrome with anhidrosis of the face only", "ipsilateral", "Second-order lesion (chest apex, neck)"), ("Horner syndrome without anhidrosis", "ipsilateral", "Third-order lesion beyond the superior cervical ganglion (sweat fibers travel with the external carotid)"), ("Harlequin sign: flushing and sweating on one side of the face", "contralateral", "Unilateral sympathetic loss revealed on exertion")],
 exam=["Pupil inequality greater in the dark; dilation lag", "Ptosis of 1–2 mm with 'upside-down' ptosis of the lower lid", "Facial sweating after exertion or heat", "Apraclonidine test (reverses the anisocoria) and hydroxyamphetamine test (fails to dilate a third-order Horner pupil)", "Examine the neck, supraclavicular fossa and hands (T1)"],
 pearls=["Painful Horner syndrome is carotid dissection until proven otherwise; Horner with hand weakness is a Pancoast tumor; Horner with crossed brainstem signs is the medulla", "Congenital Horner syndrome gives iris heterochromia because pigmentation needs sympathetic input"],
 citations=[SN14(388, 391), SN14(406, 408), C("berkowitz", 10, 85, 87)], syndromes=["syn-horner", "syn-wallenberg-lateral-medullary"], pathways=["pathway-oculosympathetic"], afferents=[("hypothalamus", "descending sympathetic fibers"), ("intermediolateral-column (T1)", "white ramus communicans")], efferents=[("dilator pupillae and Müller's muscle", "internal carotid plexus"), ("facial sweat glands", "external carotid plexus")]))

# ---------------- ganglia
def gg(id, name, summary, location, function, imaging, lesion, exam, pearls, citations, syndromes=(), synonyms=(), latin=None, afferents=(), efferents=(), meshes=(), system="cranial-nerves"):
    return structure(id, name, system, summary, location, function, ["regional arteries"], imaging, lesion, exam, pearls, citations, subsystem="ganglia", meshIds=list(meshes), level={"region": "peripheral"},
        syndromes=syndromes, synonyms=synonyms, latin=latin, afferents=afferents, efferents=efferents, tags=["ganglion"])

E.append(gg("ganglion-trigeminal", "Trigeminal ganglion", latin="Ganglion trigeminale (Gasseri)", synonyms=["Gasserian ganglion", "semilunar ganglion"],
 summary="The sensory ganglion of the trigeminal nerve, a crescent of pseudounipolar cell bodies lying in Meckel's cave, a dural pocket on the petrous apex lateral to the cavernous sinus. Its peripheral processes form the ophthalmic, maxillary and mandibular divisions and its central processes form the sensory root entering the pons; the motor root passes beneath it without synapsing. Herpes zoster and herpes simplex lie latent here (zoster ophthalmicus when V1 reactivates), tumors of Meckel's cave (schwannoma, meningioma, perineural spread) produce facial numbness, and the ganglion is the target of radiofrequency and balloon procedures for trigeminal neuralgia.",
 location="Meckel's cave, an evagination of dura and arachnoid on the anterior surface of the petrous temporal bone near its apex, lateral to the cavernous sinus and internal carotid artery, above the foramen ovale, with the temporal lobe above.",
 function="Contains the first-order neurons for touch, pain, temperature and proprioception (except jaw proprioception) of the face, cornea, oral and nasal cavities, teeth, dura and scalp.",
 imaging=img([view("axial", 20, -10, -25, "Meckel's cave on the petrous apex lateral to the cavernous sinus"), view("coronal", 20, -10, -25, "ganglion in its CSF-filled dural cave above the foramen ovale")],
     "Meckel's cave is a CSF-bright pocket on thin coronal and axial T2 with the ganglion as a crescent of tissue; it enhances mildly. Asymmetric enhancement, a mass, or enlargement suggests schwannoma, meningioma, perineural tumor spread or inflammation.",
     [pathol("Trigeminal schwannoma", "MRI", "Dumbbell enhancing mass expanding Meckel's cave and extending into the posterior fossa or the cavernous sinus.", sequence="T1+Gd"), pathol("Perineural spread of head and neck cancer", "MRI", "Thickened enhancing V2 or V3 leading back to an enhancing, enlarged Meckel's cave with loss of the CSF signal.", sequence="T1+Gd"), pathol("Herpes zoster ophthalmicus", "MRI", "Enhancement of the ganglion and V1 with a V1 dermatomal rash; usually a clinical diagnosis.", sequence="T1+Gd")],
     "Thin T2 and T1+Gd through the skull base with fat saturation"),
 lesion=[("Numbness of the whole side of the face with loss of the corneal reflex", "ipsilateral", "Ganglion or sensory root: all three divisions"), ("Facial pain in one division with a vesicular rash", "ipsilateral", "Zoster reactivation in the ganglion"), ("Neurotrophic keratitis", "ipsilateral", "Corneal anesthesia after ganglion or V1 damage")],
 exam=["Light touch and pin-prick in V1, V2 and V3 and the corneal reflex", "Look for vesicles on the nose tip (Hutchinson sign predicting eye involvement in zoster)", "Masseter and pterygoid power (motor root usually spared in ganglion lesions)"],
 pearls=["Facial numbness across all three divisions with a preserved jaw is the ganglion or sensory root, not the brainstem", "Zoster on the tip of the nose means the nasociliary branch of V1 is involved: refer to ophthalmology"],
 citations=[SN11(333, 335), SN11(351), C("berkowitz", 13, 117, 120)], syndromes=["syn-trigeminal-neuralgia", "syn-cavernous-sinus"], efferents=[("trigeminal-nuclei", "sensory root")], meshes=["ophthalmic-nerve-l", "ophthalmic-nerve-r"]))

E.append(gg("ganglion-geniculate", "Geniculate ganglion", latin="Ganglion geniculi",
 summary="The sensory ganglion of the facial nerve, sitting at the sharp bend (genu) of the nerve in the facial canal of the temporal bone where the labyrinthine segment turns into the tympanic segment. It holds the cell bodies for taste from the anterior two-thirds of the tongue (chorda tympani) and for the small cutaneous area of the external ear and gives off the greater petrosal nerve carrying parasympathetic fibers to the lacrimal gland. Varicella zoster reactivation here produces the Ramsay Hunt syndrome (facial palsy with vesicles in the ear canal), and the ganglion region is where Bell palsy enhances on MRI.",
 location="Anterior genu of the facial nerve in the petrous temporal bone, above the cochlea and medial to the middle ear, at the junction of the labyrinthine and tympanic segments; the hiatus of the greater petrosal nerve opens onto the floor of the middle cranial fossa just in front of it.",
 function="First-order neurons for taste from the anterior tongue and palate and for somatic sensation of part of the ear; branch point of the parasympathetic supply to the lacrimal and nasal glands.",
 imaging=img([view("axial", 32, -25, -30, "genu of the facial nerve in the petrous bone above the cochlea"), view("coronal", 32, -25, -30, "geniculate ganglion region medial to the middle ear")],
     "High-resolution temporal bone CT shows the geniculate fossa; MRI shows mild normal enhancement of the ganglion, with asymmetric intense enhancement of the labyrinthine segment and ganglion in Bell palsy and Ramsay Hunt syndrome, and expansion in facial schwannoma or hemangioma.",
     [pathol("Bell palsy", "MRI", "Enhancement of the labyrinthine segment, geniculate ganglion and proximal tympanic segment without a mass.", sequence="T1+Gd"), pathol("Ramsay Hunt syndrome", "MRI", "Similar enhancement, sometimes involving the eighth nerve and labyrinth; vesicles in the ear canal clinically.", sequence="T1+Gd"), pathol("Facial nerve schwannoma or geniculate hemangioma", "CT", "Expansion of the geniculate fossa with bone erosion (hemangioma) or a smooth enlargement (schwannoma).", sequence="CT non-contrast")],
     "Temporal bone CT and MRI with contrast"),
 lesion=[("Lower motor neuron facial palsy with loss of taste, reduced tearing and hyperacusis", "ipsilateral", "Lesion at the ganglion: all facial nerve functions involved"), ("Vesicles in the ear canal and severe ear pain with facial palsy", "ipsilateral", "Zoster of the geniculate ganglion (Ramsay Hunt)"), ("Crocodile tears after recovery", "ipsilateral", "Aberrant regeneration of salivary fibers into the greater petrosal nerve")],
 exam=["Facial movement including the forehead", "Taste on the anterior tongue", "Schirmer test", "Inspect the ear canal and pinna for vesicles; hearing and balance (eighth nerve involvement in Ramsay Hunt)"],
 pearls=["A facial palsy with a dry eye and loss of taste localizes to the geniculate ganglion or the canal proximal to the chorda", "Look in the ear of every facial palsy: Ramsay Hunt needs antivirals and has a worse prognosis than Bell palsy"],
 citations=[SN11(337, 339), SN11(352), C("berkowitz", 13, 120, 124)], syndromes=["syn-facial-palsy-peripheral-vs-central", "syn-ramsay-hunt"], efferents=[("nucleus-solitarius", "nervus intermedius", "taste")]))

E.append(gg("ganglion-ciliary", "Ciliary ganglion", latin="Ganglion ciliare", meshes=["ciliary-ganglion-l", "ciliary-ganglion-r"],
 summary="A parasympathetic ganglion the size of a pinhead in the posterior orbit, lateral to the optic nerve and medial to the lateral rectus, where preganglionic fibers from the Edinger–Westphal nucleus travelling in the inferior division of the oculomotor nerve synapse. Its postganglionic fibers reach the eye in the short ciliary nerves to constrict the pupil and contract the ciliary muscle for accommodation; sympathetic and sensory fibers pass through it without synapsing. Damage to the ganglion or its short ciliary nerves (viral infection, orbital surgery, trauma) produces the Adie tonic pupil, a large pupil that reacts poorly to light but slowly and tonically to near, with denervation supersensitivity to dilute pilocarpine.",
 location="Orbital apex, about 1 cm in front of the superior orbital fissure, between the optic nerve and the lateral rectus, on the lateral side of the ophthalmic artery; connected to the nerve to the inferior oblique (parasympathetic root), the nasociliary nerve (sensory root) and the internal carotid plexus (sympathetic root).",
 function="Relay of parasympathetic outflow to the sphincter pupillae and ciliary muscle; passage of sympathetic fibers to the dilator and of sensory fibers from the cornea and iris.",
 imaging=img([view("axial", 18, 25, -18, "orbital apex lateral to the optic nerve, medial to the lateral rectus")],
     "Not identifiable on routine orbital MRI; the region is the orbital apex lateral to the optic nerve. Orbital MRI is used to exclude a mass or inflammation when a tonic pupil accompanies other orbital signs.",
     [pathol("Orbital apex lesion", "MRI", "Mass or inflammation at the apex affecting the ganglion and the nerves passing through the superior orbital fissure.", sequence="T1+Gd")],
     "Pharmacological pupil testing (0.1% pilocarpine); orbital MRI only if other signs"),
 lesion=[("Adie tonic pupil: large, poorly light-reactive pupil with slow tonic constriction to near and slow redilation", "ipsilateral", "Postganglionic parasympathetic denervation with aberrant regeneration of accommodative fibers into the sphincter"), ("Loss of accommodation and blurred near vision", "ipsilateral", "Ciliary muscle denervation"), ("Absent ankle reflexes with tonic pupils (Holmes–Adie syndrome)", "bilateral", "Associated benign polyneuropathy of unknown cause")],
 exam=["Pupil size in light and dark; slit-lamp for segmental (vermiform) iris contraction", "Light reaction versus near reaction (light-near dissociation)", "Constriction to 0.1% pilocarpine (supersensitivity)", "Ankle reflexes"],
 pearls=["A dilated pupil with light-near dissociation and a normal lid and eye movements is Adie, not a third nerve palsy", "Adie pupils are common, benign and usually in young women; over years they become small"],
 citations=[SN11(329, 331), SN14(397), SN14(408), SN14(414), C("berkowitz", 10, 83), C("berkowitz", 10, 87)], syndromes=["syn-adie-tonic-pupil", "syn-argyll-robertson"], afferents=[("oculomotor-nucleus (Edinger–Westphal)", "cn-03-oculomotor, inferior division")], efferents=[("sphincter pupillae and ciliary muscle", "short ciliary nerves")]))

E.append(gg("ganglion-pterygopalatine", "Pterygopalatine ganglion", latin="Ganglion pterygopalatinum", synonyms=["sphenopalatine ganglion"],
 summary="The largest parasympathetic ganglion of the head, suspended from the maxillary nerve in the pterygopalatine fossa behind the maxilla. Preganglionic fibers from the superior salivatory nucleus arrive by the greater petrosal nerve (facial nerve) after joining the sympathetic deep petrosal nerve in the nerve of the pterygoid canal (vidian nerve); postganglionic fibers travel with maxillary nerve branches to the lacrimal gland (via the zygomatic and lacrimal nerves) and to the glands of the nose, palate and pharynx. It is a target for blocks in cluster headache and facial pain, and perineural spread of sinonasal cancer passes through it.",
 location="Pterygopalatine fossa, a small space behind the maxillary sinus between the pterygoid process and the maxilla, communicating with the orbit (inferior orbital fissure), the nasal cavity (sphenopalatine foramen), the middle cranial fossa (foramen rotundum) and the pterygoid canal.",
 function="Secretomotor supply to the lacrimal gland and the mucous glands of the nasal cavity, palate, pharynx and paranasal sinuses; vasomotor control of the nasal mucosa.",
 imaging=img([view("axial", 25, 20, -30, "pterygopalatine fossa behind the maxillary sinus"), view("coronal", 25, 20, -30, "fossa medial to the pterygoid process")],
     "The fossa is a fat-filled slit behind the maxillary sinus on axial CT and T1; loss of its fat signal or enhancement indicates tumor spread (nasopharyngeal, sinonasal, palatal cancers) or inflammation.",
     [pathol("Perineural tumor spread", "MRI", "Obliteration of the fat in the pterygopalatine fossa with enhancement extending along the vidian nerve or V2 toward Meckel's cave.", sequence="T1+Gd"), pathol("Juvenile angiofibroma", "MRI", "Enhancing mass in the fossa widening the sphenopalatine foramen in an adolescent male.", sequence="T1+Gd")],
     "Skull base CT and fat-saturated T1+Gd"),
 lesion=[("Dry eye and dry nasal mucosa", "ipsilateral", "Loss of parasympathetic secretomotor supply"), ("Facial pain with autonomic features responding to ganglion block", "ipsilateral", "Ganglion involvement in cluster headache and facial pain syndromes"), ("Maxillary numbness with tumor spread", "ipsilateral", "Maxillary nerve in the fossa")],
 exam=["Schirmer test", "Nasal mucosal dryness", "Sensation over the cheek (V2)"],
 pearls=["Reduced tearing on the side of a facial palsy means the lesion is proximal to the greater petrosal nerve, before the ganglion", "The pterygopalatine fossa is a crossroads for tumor spread from the nose, palate and sinuses toward the skull base"],
 citations=[SN14(398), SN11(337, 339), C("berkowitz", 13, 120, 124)], syndromes=["syn-facial-palsy-peripheral-vs-central"], afferents=[("facial-motor-nucleus region (superior salivatory nucleus)", "greater petrosal nerve → nerve of the pterygoid canal")], efferents=[("lacrimal gland", "zygomatic and lacrimal nerves"), ("nasal and palatine glands", "nasopalatine and palatine nerves")]))

E.append(gg("ganglion-otic", "Otic ganglion", latin="Ganglion oticum",
 summary="A small parasympathetic ganglion lying just below the foramen ovale on the medial side of the mandibular nerve, where preganglionic fibers from the inferior salivatory nucleus arriving by the lesser petrosal nerve (glossopharyngeal nerve, via the tympanic plexus) synapse. The postganglionic fibers join the auriculotemporal nerve to reach the parotid gland. Frey syndrome (gustatory sweating over the parotid after parotidectomy) results from aberrant regeneration of these fibers into the sweat glands of the overlying skin.",
 location="Infratemporal fossa immediately below the foramen ovale, medial to the mandibular nerve, lateral to tensor veli palatini and in front of the middle meningeal artery.",
 function="Relay of parasympathetic secretomotor fibers to the parotid gland; passage of sympathetic fibers from the middle meningeal plexus and of motor fibers to tensor tympani and tensor veli palatini.",
 imaging=img([view("axial", 25, -8, -40, "infratemporal fossa below the foramen ovale, medial to V3")],
     "Not identifiable on routine imaging; the foramen ovale and the mandibular nerve are seen on skull base CT and MRI, and perineural spread along V3 passes this region.",
     [pathol("Perineural spread along V3", "MRI", "Enlarged enhancing mandibular nerve through the foramen ovale with denervation atrophy of the masticatory muscles.", sequence="T1+Gd")],
     "Skull base MRI with fat saturation"),
 lesion=[("Reduced parotid secretion", "ipsilateral", "Loss of glossopharyngeal parasympathetic supply"), ("Gustatory sweating and flushing over the cheek (Frey syndrome)", "ipsilateral", "Aberrant regeneration of parasympathetic fibers into cutaneous sweat glands after parotid surgery"), ("Jaw weakness and V3 numbness with a mass", "ipsilateral", "Adjacent mandibular nerve")],
 exam=["Observe the cheek during a meal for sweating", "Masseter and pterygoid power, V3 sensation"],
 pearls=["Sweating over the cheek when eating after parotid surgery is Frey syndrome, a misdirected otic ganglion outflow", "The parotid gets its parasympathetic supply from the ninth nerve, not the seventh, despite the facial nerve running through it"],
 citations=[SN11(342), SN14(399), C("berkowitz", 14, 125)], syndromes=[], afferents=[("nucleus-solitarius region (inferior salivatory nucleus)", "lesser petrosal nerve via cn-09-glossopharyngeal")], efferents=[("parotid gland", "auriculotemporal nerve")]))

E.append(gg("ganglion-submandibular", "Submandibular ganglion", latin="Ganglion submandibulare",
 summary="A small parasympathetic ganglion hanging from the lingual nerve above the deep part of the submandibular gland. Preganglionic fibers from the superior salivatory nucleus travel in the facial nerve, leave it as the chorda tympani in the middle ear, join the lingual nerve in the infratemporal fossa and synapse here; postganglionic fibers supply the submandibular and sublingual glands and the minor glands of the floor of the mouth. The chorda tympani also carries taste from the anterior tongue, so lesions of the facial nerve proximal to it reduce both salivation and taste.",
 location="On the hyoglossus muscle below the lingual nerve, above the deep process of the submandibular gland and lateral to the submandibular duct, in the floor of the mouth.",
 function="Secretomotor supply to the submandibular and sublingual salivary glands.",
 imaging=img([view("axial", 30, 0, -55, "floor of the mouth region; the ganglion sits on hyoglossus (outside the brain volume)")],
     "Not identifiable; the submandibular gland and lingual nerve region are seen on neck MRI. Denervated glands atrophy and show fatty change.",
     [pathol("Submandibular gland denervation", "MRI", "Small fatty gland after chorda tympani or lingual nerve injury.", sequence="T1")],
     "Neck MRI when a mass is suspected"),
 lesion=[("Reduced salivation from the submandibular and sublingual glands", "ipsilateral", "Chorda tympani or ganglion lesion"), ("Loss of taste on the anterior two-thirds of the tongue with the same lesion", "ipsilateral", "Chorda tympani also carries taste"), ("Numbness of the anterior tongue", "ipsilateral", "Lingual nerve injury (dental surgery)")],
 exam=["Taste on the anterior tongue with sugar and salt", "Saliva pooling under the tongue", "Tongue sensation"],
 pearls=["Loss of taste with a facial palsy places the lesion proximal to the chorda tympani, in the mastoid segment or higher", "Lingual nerve injury after third molar extraction numbs the tongue and can reduce salivation and taste"],
 citations=[SN14(398), SN11(337, 339), C("berkowitz", 13, 120, 124)], syndromes=["syn-facial-palsy-peripheral-vs-central"], afferents=[("facial-motor-nucleus region (superior salivatory nucleus)", "chorda tympani via the lingual nerve")], efferents=[("submandibular and sublingual glands", None)]))

E.append(gg("ganglion-superior-cervical", "Superior cervical ganglion", latin="Ganglion cervicale superius", system="autonomic",
 summary="The largest sympathetic ganglion, about 2.5 cm long, lying behind the carotid sheath at the level of C2–C3, where the preganglionic fibers from T1–T3 (having ascended the cervical chain) synapse. Its postganglionic fibers form the internal carotid plexus to the eye, the pupil, the lid, the lacrimal gland and the cavernous sinus region, the external carotid plexus to the facial sweat glands and vessels, gray rami to C1–C4, cardiac nerves, and branches to the pharynx and the pineal gland. It is the third-order relay of the oculosympathetic pathway; lesions distal to it cause Horner syndrome without facial anhidrosis.",
 location="In front of the transverse processes of C2 and C3 (some say C1–C4), behind the internal carotid artery and the carotid sheath, medial to the vagus nerve and in front of longus capitis.",
 function="Sympathetic supply to the head: pupil dilation, lid elevation (Müller's muscle), vasoconstriction, sweating of the face, and innervation of the pineal gland; contributes to cardiac sympathetic supply.",
 imaging=img([view("axial", 20, -20, -60, "upper cervical region behind the carotid sheath (outside the brain volume)")],
     "Seen on neck MRI as a small fusiform structure behind the carotid sheath, easily mistaken for a lymph node; enlargement occurs in schwannoma. Carotid imaging is the key study for postganglionic Horner syndrome.",
     [pathol("Superior cervical ganglion schwannoma", "MRI", "Enhancing fusiform mass behind the carotid displacing the vessels anteriorly, sometimes with a Horner syndrome.", sequence="T1+Gd"), pathol("Internal carotid dissection", "MRI", "Mural hematoma with a postganglionic Horner syndrome (no anhidrosis).", sequence="T1")],
     "Neck MRI; carotid CTA/MRA"),
 lesion=[("Horner syndrome without facial anhidrosis", "ipsilateral", "Postganglionic fibers on the internal carotid; sweat fibers travel with the external carotid"), ("Horner syndrome with facial anhidrosis", "ipsilateral", "Lesion at or proximal to the ganglion (preganglionic)"), ("Failure of the hydroxyamphetamine test to dilate the pupil", "ipsilateral", "Loss of postganglionic terminals (no stored noradrenaline)")],
 exam=["Anisocoria worse in the dark, mild ptosis", "Facial sweating with exercise", "Pharmacological tests to separate pre- from postganglionic lesions", "Palpate the neck and check for carotid bruits"],
 pearls=["The sweat fibers leave the pathway at the ganglion: no anhidrosis means the lesion is beyond it, on the carotid or in the cavernous sinus", "Cluster headache produces a transient postganglionic Horner syndrome through inflammation around the cavernous carotid"],
 citations=[SN14(388, 390), SN14(407, 408), C("berkowitz", 10, 85, 86)], syndromes=["syn-horner"], afferents=[("intermediolateral-column (T1–T3)", "cervical sympathetic trunk")], efferents=[("dilator pupillae, Müller's muscle", "internal carotid plexus"), ("facial sweat glands and vessels", "external carotid plexus"), ("pineal-gland", "nervi conarii")]))

write(E)
