import sys, pathlib, json; sys.path.insert(0, str(pathlib.Path(__file__).parent))
from corlib import *
E = []
S = lambda ch, a, b=None: C("snell", ch, a, b)
B = lambda ch, a, b=None: C("berkowitz", ch, a, b)
UL = [S(3, 111, 120), B(16, 141, 156)]; LL = [S(3, 111, 120), B(17, 157, 166)]
def nerve(id, name, limb, mesh, roots, summary, course, function, views, normal, paths, lesion, exam, pearls, cites, **kw):
    kw.setdefault("parent", "plexus-brachial" if limb == "upper-limb" else "plexus-lumbosacral"); kw.setdefault("tags", ["peripheral nerve", "cutaneous"])
    kw.setdefault("territories", []); kw.setdefault("syndromes", [])
    return cortex(id, name, "x", summary, course, function, kw.pop("arteries", ["vasa nervorum (regional arteries)"]), views, normal, paths, lesion, exam, pearls, cites, system="peripheral", subsystem=limb, mesh_ids=[mesh + "-l", mesh + "-r"], level={"region": "peripheral", "sub": roots}, **kw)

E.append(nerve("nerve-medial-antebrachial-cutaneous", "Medial antebrachial cutaneous nerve", "upper-limb", "medial-antebrachial-cutaneous-nerve", "C8-T1",
 "The medial antebrachial cutaneous nerve is a sensory branch of the medial cord of the brachial plexus (C8, T1) that runs down the medial arm with the basilic vein, pierces the deep fascia at the middle of the arm and divides into anterior and posterior branches that supply the skin of the medial forearm from the elbow to the wrist. It is the sensory territory that distinguishes a lower trunk or medial cord plexus lesion from an ulnar neuropathy: the ulnar nerve does not supply the forearm skin, so numbness of the medial forearm with a weak, numb hand means the lesion is in the plexus (Klumpke palsy, neurogenic thoracic outlet syndrome, Pancoast tumor), not at the elbow. Its sensory potential is the electrophysiological marker of that distinction.",
 "Arises from the medial cord in the axilla, descends medial to the brachial artery and then with the basilic vein, pierces the deep fascia with the vein above the elbow and divides into anterior and posterior branches over the medial epicondyle to supply the medial half of the forearm skin down to the wrist.",
 "Purely sensory, it carries touch, pain and temperature from the medial forearm through the medial cord and lower trunk to the C8 and T1 dorsal root ganglia; its territory is the key to separating lower plexus lesions from ulnar neuropathy, because the ulnar nerve's sensory supply stops at the wrist, and a normal medial antebrachial cutaneous sensory potential with an abnormal ulnar one places the lesion in the ulnar nerve, whereas both abnormal places it in the medial cord or lower trunk. It is injured by axillary surgery and by venepuncture and cannulation of the basilic vein, producing a painful neuroma, and it is harvested as a graft.",
 [mview("coronal", "medial-antebrachial-cutaneous-nerve-l", "medial antebrachial cutaneous nerve along the medial arm"), mview("axial", "medial-antebrachial-cutaneous-nerve-r", "nerve beside the basilic vein above the elbow")],
 "A thin nerve accompanying the basilic vein in the medial arm on ultrasound; not seen on routine imaging. Its territory is the medial forearm skin.",
 [pathol("Lower trunk or medial cord plexopathy", "EMG/NCS", "Absent or reduced medial antebrachial cutaneous sensory potential with abnormal ulnar studies and denervation in C8-T1 muscles of several nerves.", sequence="n/a"),
  pathol("Neurogenic thoracic outlet syndrome", "MRI", "Fibrous band or cervical rib compressing the lower trunk; the medial antebrachial cutaneous potential is characteristically reduced.", sequence="STIR"),
  pathol("Iatrogenic injury at venepuncture", "US", "Neuroma of the nerve beside the basilic vein with a painful Tinel sign at the antecubital fossa.", sequence="n/a")],
 [("Numbness of the medial forearm", "ipsilateral", "Interruption of the nerve or of the medial cord and lower trunk"), ("Painful neuroma after venepuncture", "ipsilateral", "Injury of the nerve where it accompanies the basilic vein"), ("No motor deficit", "n/a", "The nerve is purely sensory")],
 ["Test light touch on the medial forearm as well as the little finger in any patient with an ulnar-pattern hand", "Nerve conduction study of the medial antebrachial cutaneous sensory response", "Look for a cervical rib and a Horner syndrome when the forearm is numb with the hand"],
 ["Numb forearm plus numb little finger means plexus; numb little finger alone means the ulnar nerve", "The medial antebrachial cutaneous potential is the electrophysiologist's plexus test", "A painful lump at the site of a blood test may be this nerve's neuroma"],
 UL, synonyms=["medial cutaneous nerve of the forearm"], syndromes=["syn-klumpke", "syn-neurogenic-thoracic-outlet", "syn-cubital-tunnel"]))

E.append(nerve("nerve-lateral-antebrachial-cutaneous", "Lateral antebrachial cutaneous nerve", "upper-limb", "lateral-antebrachial-cutaneous-nerve", "C5-C6",
 "The lateral antebrachial cutaneous nerve is the sensory termination of the musculocutaneous nerve (C5, C6) that emerges lateral to the biceps tendon at the elbow and supplies the skin of the lateral forearm from the elbow to the base of the thumb. Its loss accompanies musculocutaneous nerve injury and upper trunk plexus lesions (Erb palsy) and its sensory potential separates a C6 radiculopathy (normal potential) from an upper trunk plexopathy (reduced potential); it is compressed by the biceps aponeurosis in athletes and injured during venepuncture of the cephalic vein.",
 "Continues the musculocutaneous nerve after it has supplied the coracobrachialis, biceps and brachialis, emerging between the biceps and brachialis lateral to the biceps tendon just above the elbow, piercing the deep fascia and dividing into anterior and posterior branches that run down the lateral forearm with the cephalic vein to the wrist and the thenar eminence.",
 "Purely sensory, it carries sensation from the lateral forearm through the musculocutaneous nerve, the lateral cord and the upper trunk to the C6 dorsal root ganglion (with a C5 contribution); the dermatome overlap with C6 is close, so its sensory potential is preserved in a C6 root lesion (proximal to the ganglion) and lost in an upper trunk or lateral cord lesion, the electrophysiological basis of localizing lateral arm numbness. It is entrapped where it pierces the fascia beside the biceps tendon, producing lateral forearm pain and numbness with elbow extension and pronation, and it is at risk in cephalic vein cannulation and elbow surgery.",
 [mview("coronal", "lateral-antebrachial-cutaneous-nerve-l", "lateral antebrachial cutaneous nerve emerging beside the biceps tendon"), mview("axial", "lateral-antebrachial-cutaneous-nerve-r", "nerve with the cephalic vein in the lateral forearm")],
 "A small nerve emerging lateral to the biceps tendon at the elbow on ultrasound, running with the cephalic vein; not seen on routine MRI. Territory: lateral forearm skin.",
 [pathol("Musculocutaneous neuropathy", "EMG/NCS", "Reduced lateral antebrachial cutaneous sensory potential with weakness and denervation of the biceps and brachialis; a plexus lesion adds deltoid and supraspinatus involvement.", sequence="n/a"),
  pathol("Upper trunk plexopathy (Erb palsy or neuralgic amyotrophy)", "MRI", "Thickening and signal change of the upper trunk with a reduced lateral antebrachial cutaneous potential distinguishing it from a C5-6 radiculopathy.", sequence="STIR"),
  pathol("Entrapment at the biceps aponeurosis", "US", "Focal swelling of the nerve where it pierces the fascia lateral to the biceps tendon in a patient with lateral forearm pain on pronation.", sequence="n/a")],
 [("Numbness of the lateral forearm", "ipsilateral", "Interruption of the nerve, the musculocutaneous nerve or the lateral cord and upper trunk"), ("Lateral forearm pain provoked by elbow extension and pronation", "ipsilateral", "Entrapment beneath the biceps aponeurosis"), ("No motor deficit from the cutaneous branch itself", "n/a", "The branch is purely sensory; weakness means the musculocutaneous trunk is involved")],
 ["Sensation over the lateral forearm compared with the C6 dermatome on the thumb", "Biceps strength and reflex to detect musculocutaneous or upper trunk involvement", "Sensory nerve conduction study to separate root from plexus"],
 ["A normal lateral antebrachial cutaneous potential with lateral forearm numbness means the lesion is at the C6 root", "Weak biceps and numb lateral forearm is the musculocutaneous nerve; add a weak deltoid and it is the upper trunk", "Lateral forearm pain in a weightlifter is this nerve under the biceps aponeurosis"],
 UL, synonyms=["lateral cutaneous nerve of the forearm"], syndromes=["syn-erb-duchenne", "syn-parsonage-turner", "syn-radiculopathy-cervical"]))

E.append(nerve("nerve-posterior-antebrachial-cutaneous", "Posterior antebrachial cutaneous nerve", "upper-limb", "posterior-antebrachial-cutaneous-nerve", "C5-C8",
 "The posterior antebrachial cutaneous nerve is a sensory branch of the radial nerve given off in the spiral groove of the humerus, together with the inferior lateral brachial cutaneous nerve, supplying the skin of the posterior arm below the deltoid and the posterior forearm to the wrist. Its involvement marks the level of a radial nerve lesion: it is spared in posterior interosseous and superficial radial lesions at the elbow and forearm and lost in lesions at or above the spiral groove, such as the Saturday night palsy and humeral fracture, so posterior forearm numbness with wrist drop places the injury in the arm.",
 "Arises from the radial nerve in the spiral groove, pierces the lateral head of the triceps and the deep fascia with the inferior lateral brachial cutaneous nerve, descends along the lateral arm behind the lateral epicondyle and supplies the posterior forearm skin from the elbow to the wrist; the brachial branch supplies the lower lateral arm.",
 "Purely sensory, it carries sensation from the posterior forearm and lower lateral arm through the radial nerve and the posterior cord to the C5-C8 dorsal root ganglia; because it leaves the radial nerve in the spiral groove, its territory is anesthetic in high radial lesions (axilla, spiral groove, humeral fracture) and spared in lesions below the elbow (posterior interosseous entrapment, superficial radial injury), a bedside way to place the lesion along the radial nerve. It is also the nerve whose territory hurts in lateral epicondylitis mimics and after elbow surgery.",
 [mview("coronal", "posterior-antebrachial-cutaneous-nerve-l", "posterior antebrachial cutaneous nerve leaving the radial nerve at the spiral groove"), mview("axial", "posterior-antebrachial-cutaneous-nerve-r", "nerve descending along the lateral arm to the posterior forearm")],
 "Branches of the radial nerve at the spiral groove on ultrasound; the territory is the posterior forearm and the lower lateral arm.",
 [pathol("Radial neuropathy at the spiral groove", "EMG/NCS", "Reduced radial sensory potentials including the posterior antebrachial cutaneous response with denervation of brachioradialis and wrist extensors but sparing the triceps.", sequence="n/a"),
  pathol("Humeral shaft fracture with radial nerve injury", "MRI", "Nerve discontinuity or entrapment in the fracture at the spiral groove with anesthesia of the posterior forearm and wrist drop.", sequence="STIR"),
  pathol("Posterior interosseous syndrome (for comparison)", "US", "Entrapment at the arcade of Frohse with finger drop and no sensory loss; the posterior antebrachial cutaneous territory is spared.", sequence="n/a")],
 [("Numbness of the posterior forearm and lower lateral arm", "ipsilateral", "Radial nerve lesion at or above the spiral groove"), ("Sparing of the posterior forearm with finger drop", "ipsilateral", "Radial lesion below the branch (posterior interosseous nerve)"), ("No motor deficit from the branch itself", "n/a", "Purely sensory branch")],
 ["Map sensory loss on the posterior forearm and the dorsum of the hand separately", "Triceps strength (spared in spiral groove lesions) and brachioradialis strength", "Radial sensory conduction studies including the posterior antebrachial cutaneous response"],
 ["Posterior forearm numbness with wrist drop puts the radial lesion in the arm; a normal posterior forearm puts it below the elbow", "The Saturday night palsy numbs the back of the forearm; the posterior interosseous syndrome numbs nothing", "Triceps intact and posterior forearm numb: spiral groove"],
 UL, synonyms=["posterior cutaneous nerve of the forearm", "dorsal antebrachial cutaneous nerve"], syndromes=["syn-radial-neuropathy"]))

E.append(nerve("nerve-medial-brachial-cutaneous", "Medial brachial cutaneous nerve", "upper-limb", "medial-brachial-cutaneous-nerve", "T1",
 "The medial brachial cutaneous nerve is the smallest branch of the medial cord (T1, with a T2 contribution through the intercostobrachial nerve) and supplies the skin of the medial arm and the axilla. It is clinically a marker of the T1 root and the lower plexus: numbness of the medial arm accompanies a Pancoast tumor, a lower trunk injury and neurogenic thoracic outlet syndrome, and the intercostobrachial nerve that joins it is cut in axillary dissection for breast cancer, leaving the numb inner arm that patients notice after surgery.",
 "Arises from the medial cord in the axilla, runs medial to the axillary vein, communicates with the intercostobrachial nerve from the second intercostal nerve, pierces the deep fascia in the middle of the arm and supplies the skin of the medial arm from the axilla to the elbow.",
 "Purely sensory, it carries sensation from the medial arm and the floor of the axilla through the medial cord and lower trunk to the T1 (and via the intercostobrachial nerve the T2) dorsal root ganglia, so its territory is the dermatomal marker of the lowest root of the plexus; loss of sensation here with a wasted hand and a Horner syndrome points to a Pancoast tumor at the apex of the lung invading the lower trunk and the sympathetic chain, and loss after axillary surgery reflects section of the intercostobrachial nerve, a benign but permanent numbness. Pain in its territory can be referred cardiac pain, since T1-T2 also receive the heart.",
 [mview("coronal", "medial-brachial-cutaneous-nerve-l", "medial brachial cutaneous nerve in the axilla and medial arm"), mview("axial", "medial-brachial-cutaneous-nerve-r", "nerve medial to the axillary vein")],
 "A tiny nerve medial to the axillary vein; not identifiable on routine imaging. Territory: the medial upper arm and axilla.",
 [pathol("Pancoast tumor", "MRI", "Apical lung tumor invading the lower trunk of the brachial plexus, the T1 root and the stellate ganglion, with medial arm numbness, hand wasting and Horner syndrome.", sequence="T1+Gd"),
  pathol("Post-mastectomy numbness (intercostobrachial injury)", "US", "No imaging finding; numbness of the medial arm and axilla after axillary dissection with a possible neuroma on ultrasound.", sequence="n/a"),
  pathol("Neurogenic thoracic outlet syndrome", "MRI", "Cervical rib or band at the T1 root and lower trunk with medial arm and forearm numbness.", sequence="STIR")],
 [("Numbness of the medial arm and axilla", "ipsilateral", "T1 root, lower trunk or medial cord lesion, or intercostobrachial section"), ("Associated hand wasting and Horner syndrome", "ipsilateral", "Apical lung tumor invading the lower plexus and the sympathetic chain"), ("No motor deficit", "n/a", "Purely sensory nerve")],
 ["Sensation over the medial arm, the medial forearm and the little finger to define the extent of a lower plexus lesion", "Look for ptosis and miosis in any patient with a numb medial arm", "Chest imaging of the apex when the T1 territory is numb and the hand is wasted"],
 ["A numb inner arm with a small pupil is a Pancoast tumor until the chest film says otherwise", "The intercostobrachial nerve is sacrificed in axillary dissection; warn the patient about the numb inner arm", "T1 supplies the medial arm and the heart: arm pain can be angina"],
 UL, synonyms=["medial cutaneous nerve of the arm"], syndromes=["syn-klumpke", "syn-neurogenic-thoracic-outlet", "syn-horner"]))

E.append(nerve("nerve-superficial-radial", "Superficial branch of the radial nerve", "upper-limb", "superficial-radial-nerve", "C6-C7",
 "The superficial branch of the radial nerve is the sensory continuation of the radial nerve after it divides at the elbow, running down the forearm beneath the brachioradialis, emerging between its tendon and the extensor carpi radialis longus in the distal forearm and crossing the anatomical snuffbox to supply the skin of the dorsolateral hand and the dorsum of the thumb, index and middle fingers to the distal joints. It is compressed by tight watch straps and handcuffs (Wartenberg syndrome or cheiralgia paresthetica), injured by wrist surgery, cannulation and de Quervain release, and its sensory potential is the standard radial sensory study that separates a radial nerve lesion from a C6-C7 radiculopathy.",
 "Leaves the radial nerve in front of the lateral epicondyle, descends under the brachioradialis lateral to the radial artery, pierces the deep fascia about eight centimeters above the wrist between the brachioradialis and extensor carpi radialis longus tendons, crosses the snuffbox superficially and divides into dorsal digital nerves for the thumb, index, middle and half of the ring finger over the dorsum of the hand.",
 "Purely sensory, it carries sensation from the radial dorsum of the hand and the dorsum of the lateral fingers through the radial nerve and the posterior cord to the C6 and C7 dorsal root ganglia; its territory is spared in the posterior interosseous syndrome (which separates from it at the elbow) and lost in higher radial lesions, and its conduction study is normal in a C6-C7 radiculopathy because the lesion is proximal to the ganglion. It is entrapped where it pierces the fascia between the brachioradialis and extensor carpi radialis longus, producing pain and paresthesias of the dorsal hand aggravated by pronation and by anything tight around the wrist.",
 [mview("coronal", "superficial-radial-nerve-l", "superficial radial nerve descending under the brachioradialis to the snuffbox"), mview("axial", "superficial-radial-nerve-r", "nerve piercing the fascia above the wrist")],
 "A thin nerve beside the radial artery under the brachioradialis on ultrasound, emerging subcutaneously above the wrist; territory: dorsolateral hand and thumb.",
 [pathol("Wartenberg syndrome (cheiralgia paresthetica)", "US", "Focal enlargement of the superficial radial nerve where it emerges between the brachioradialis and extensor carpi radialis longus tendons, with a Tinel sign and dorsal hand paresthesias.", sequence="n/a"),
  pathol("Radial neuropathy at the spiral groove", "EMG/NCS", "Reduced superficial radial sensory potential with wrist drop; the posterior interosseous syndrome spares the potential.", sequence="n/a"),
  pathol("Iatrogenic injury at the wrist", "US", "Neuroma of the nerve after de Quervain release, cannulation or external fixation, with a painful Tinel over the snuffbox.", sequence="n/a")],
 [("Numbness and paresthesias of the dorsolateral hand and thumb", "ipsilateral", "Superficial radial or higher radial nerve lesion"), ("Pain on pronation and with a tight wrist band", "ipsilateral", "Entrapment where the nerve pierces the forearm fascia"), ("No weakness", "n/a", "Purely sensory branch; weakness means the lesion is at or above the elbow")],
 ["Sensation over the dorsal first web space and the dorsum of the thumb", "Finger and wrist extension to exclude a posterior interosseous or higher radial lesion", "Radial sensory conduction study; normal in radiculopathy, reduced in nerve lesions"],
 ["Numb back of the hand with normal finger extension is the superficial radial nerve; add finger drop and it is the radial trunk", "Handcuffs and watch straps compress this nerve where it surfaces above the wrist", "A normal radial sensory response in a numb thumb means the C6 root"],
 UL, synonyms=["superficial radial nerve", "radial sensory nerve"], syndromes=["syn-radial-neuropathy", "syn-radiculopathy-cervical"]))

E.append(nerve("nerve-dorsal-scapular", "Dorsal scapular nerve", "upper-limb", "dorsal-scapular-nerve", "C5",
 "The dorsal scapular nerve arises from the C5 root (with a C4 contribution) above the upper trunk, pierces the scalenus medius and descends along the medial border of the scapula deep to the levator scapulae and the rhomboids, which it supplies. Because it leaves the root before the plexus forms, rhomboid weakness distinguishes a C5 root lesion from an upper trunk lesion, and its EMG is one of the tests that places a lesion at the root: a C5 radiculopathy denervates the rhomboids, whereas Erb palsy of the upper trunk spares them. It is entrapped in the scalenus medius, producing interscapular pain and scapular winging in a pattern different from that of the long thoracic nerve.",
 "Leaves the C5 anterior ramus in the neck, pierces the scalenus medius, runs beneath the levator scapulae along the medial scapular border with the dorsal scapular artery, deep to the rhomboid minor and major, which it supplies together with the levator scapulae.",
 "Motor to the levator scapulae and the rhomboids, it elevates and retracts the scapula and stabilizes it during arm movement; its loss produces mild lateral winging of the scapula with the inferior angle displaced laterally (the opposite direction from serratus anterior weakness), difficulty bracing the shoulders back and a dull interscapular ache. Its origin proximal to the plexus makes it a root marker: rhomboid denervation on EMG with deltoid and biceps weakness means the C5 root or a preganglionic avulsion (a poor prognosis for repair), whereas spared rhomboids mean a postganglionic upper trunk injury that may regenerate. Entrapment in the scalenus medius accompanies neck trauma and thoracic outlet syndromes.",
 [mview("coronal", "dorsal-scapular-nerve-l", "dorsal scapular nerve along the medial scapular border"), mview("axial", "dorsal-scapular-nerve-r", "nerve piercing the scalenus medius from the C5 root")],
 "A small nerve piercing the scalenus medius and running beneath the levator scapulae on ultrasound; routine MRI shows only its muscles, which show denervation edema or fatty atrophy.",
 [pathol("C5 radiculopathy or root avulsion", "EMG/NCS", "Denervation of the rhomboids with the deltoid, biceps and supraspinatus; a pseudomeningocele on myelography or MRI marks a root avulsion.", sequence="n/a"),
  pathol("Rhomboid denervation", "MRI", "STIR hyperintensity and later fatty atrophy of the rhomboids and levator scapulae with a normal serratus anterior.", sequence="STIR"),
  pathol("Upper trunk plexopathy (for comparison)", "EMG/NCS", "Denervation of deltoid, biceps and supraspinatus with normal rhomboids, placing the lesion distal to the root.", sequence="n/a")],
 [("Lateral scapular winging and weak scapular retraction", "ipsilateral", "Denervation of the rhomboids and levator scapulae"), ("Interscapular ache and neck pain", "ipsilateral", "Entrapment in the scalenus medius or a C5 root lesion"), ("Marker of C5 root (versus upper trunk) lesion", "ipsilateral", "Origin of the nerve proximal to the plexus")],
 ["Ask the patient to brace the shoulders back against resistance and watch for lateral displacement of the inferior scapular angle", "EMG of the rhomboids in any upper plexus or C5 lesion", "Compare with serratus anterior winging on wall push-up"],
 ["Rhomboids weak means the lesion is at the C5 root; rhomboids strong means the trunk", "Two nerves wing the scapula: the long thoracic wings it medially, the dorsal scapular laterally", "A root avulsion cannot be repaired; the rhomboid EMG helps decide before surgery"],
 UL, synonyms=["nerve to the rhomboids"], syndromes=["syn-erb-duchenne", "syn-radiculopathy-cervical", "syn-neurogenic-thoracic-outlet"]))

E.append(nerve("nerve-thoracodorsal", "Thoracodorsal nerve", "upper-limb", "thoracodorsal-nerve", "C6-C8",
 "The thoracodorsal nerve arises from the posterior cord of the brachial plexus (C6, C7, C8) between the subscapular nerves, descends along the posterior axillary wall with the thoracodorsal artery and enters the latissimus dorsi, which it supplies. It is at risk in axillary lymph node dissection and in posterior shoulder surgery, it is the nerve of the latissimus flap used in reconstruction, and its EMG places lesions in the posterior cord: latissimus weakness with radial and axillary signs means the posterior cord, whereas latissimus sparing points to the individual nerves.",
 "Leaves the posterior cord in the axilla between the upper and lower subscapular nerves, descends along the posterior axillary wall on the surface of the subscapularis and teres major with the thoracodorsal artery, and enters the deep surface of the latissimus dorsi near its tendon.",
 "Motor to the latissimus dorsi, it adducts, extends and medially rotates the arm and pulls the body up in climbing and in transfers from a wheelchair, and it contributes to forced expiration and coughing; its loss weakens adduction against resistance (the patient cannot press the arm down against the examiner's hand) and is felt most by athletes and by paraplegics who depend on the latissimus for transfers. Its origin from the posterior cord makes it a cord marker in plexus lesions, and surgeons preserve it during axillary clearance or use it, with its artery, as the pedicle of the latissimus flap for breast and chest wall reconstruction and for restoring elbow flexion after brachial plexus injury.",
 [mview("coronal", "thoracodorsal-nerve-l", "thoracodorsal nerve along the posterior axillary wall to the latissimus dorsi"), mview("axial", "thoracodorsal-nerve-r", "nerve with the thoracodorsal artery on the subscapularis")],
 "A nerve accompanying the thoracodorsal vessels on the posterior axillary wall on ultrasound and MRI; denervation appears as STIR change and atrophy of the latissimus dorsi.",
 [pathol("Posterior cord plexopathy", "EMG/NCS", "Denervation of the latissimus dorsi with the deltoid, teres minor and radial-innervated muscles, placing the lesion in the posterior cord.", sequence="n/a"),
  pathol("Iatrogenic injury at axillary dissection", "MRI", "Latissimus dorsi denervation edema and later atrophy after axillary surgery, with weak adduction.", sequence="STIR"),
  pathol("Latissimus flap harvest", "MRI", "Absent latissimus in the back after reconstruction, with the muscle transposed to the chest wall on its thoracodorsal pedicle.", sequence="T1")],
 [("Weak adduction and extension of the arm", "ipsilateral", "Denervation of the latissimus dorsi"), ("Difficulty with climbing, pulling and wheelchair transfers", "ipsilateral", "Loss of the latissimus contribution to body elevation"), ("Marker of posterior cord involvement", "ipsilateral", "Origin from the posterior cord with the axillary and radial nerves")],
 ["Adduction of the abducted arm against resistance while palpating the latissimus in the posterior axillary fold", "Cough strength in patients with bilateral involvement", "EMG of the latissimus in suspected posterior cord lesions"],
 ["The latissimus is the muscle of climbing and of transfers; its nerve is the one axillary surgeons protect", "Latissimus plus deltoid plus wrist drop means the posterior cord", "The thoracodorsal pedicle carries the latissimus to the chest wall in reconstruction"],
 UL, synonyms=["middle subscapular nerve", "nerve to latissimus dorsi"], syndromes=["syn-radial-neuropathy", "syn-axillary-neuropathy"]))

E.append(nerve("nerves-pectoral", "Medial and lateral pectoral nerves", "upper-limb", "pectoral-nerves", "C5-T1",
 "The lateral pectoral nerve (C5-C7) from the lateral cord and the medial pectoral nerve (C8-T1) from the medial cord cross the axilla to supply the pectoralis major and minor, the lateral nerve the clavicular and upper sternal parts of the major and the medial nerve the lower sternal part and the minor; they are named for the cords they arise from, not for their positions. They are the motor markers of the cords in plexus lesions, they are injured in breast and axillary surgery and by the pectoralis minor in thoracic outlet syndromes, and the pectoral reflex and the palpable contraction of the muscle during adduction give a bedside test of the C5-T1 roots.",
 "The lateral pectoral nerve leaves the lateral cord, crosses the axillary artery and pierces the clavipectoral fascia to enter the deep surface of the pectoralis major; the medial pectoral nerve leaves the medial cord behind the axillary artery, passes through or around the pectoralis minor, supplying it, and ends in the lower pectoralis major; a loop between the two nerves crosses the artery.",
 "Motor to the pectoralis major (adduction, medial rotation and flexion of the arm, with the clavicular head flexing and the sternal head adducting) and the pectoralis minor (depression and protraction of the scapula), they let the arm be pressed against the chest and the body be pushed up from a chair; their two-cord origin makes the pectoralis major a map of the plexus, with clavicular-head weakness indicating the upper roots and lateral cord and sternal-head weakness the lower roots and medial cord. The pectoral reflex, elicited by tapping the tendon with the arm abducted, tests C5-T1 and is brisk in cervical myelopathy. The nerves are divided in radical mastectomy and can be used as donors for nerve transfer.",
 [mview("coronal", "pectoral-nerves-l", "pectoral nerves crossing the axilla to the pectoralis major and minor"), mview("axial", "pectoral-nerves-r", "medial and lateral pectoral nerves around the axillary artery")],
 "Nerves crossing the axillary artery beneath the clavipectoral fascia on ultrasound; pectoralis denervation shows as STIR change and atrophy, and pectoralis major atrophy is visible on chest CT.",
 [pathol("Lateral or medial cord plexopathy", "EMG/NCS", "Denervation of the clavicular head (lateral cord, with musculocutaneous and median signs) or the sternal head (medial cord, with ulnar signs) of the pectoralis major.", sequence="n/a"),
  pathol("Post-mastectomy pectoral denervation", "MRI", "Atrophy of the pectoralis major after axillary surgery with weak adduction and a hollow infraclavicular region.", sequence="T1"),
  pathol("Pectoralis minor syndrome", "US", "Compression of the neurovascular bundle beneath a tight pectoralis minor with pain and paresthesias reproduced by arm elevation; the pectoral nerves themselves are usually spared.", sequence="n/a")],
 [("Weak adduction of the arm across the chest", "ipsilateral", "Denervation of the pectoralis major"), ("Pattern of pectoral weakness marks the cord", "ipsilateral", "Clavicular head from the lateral cord, sternal head from the medial cord"), ("Brisk pectoral reflex", "bilateral", "Cervical myelopathy above C5 with upper motor neuron signs")],
 ["Have the patient press the palms together and palpate both heads of the pectoralis major", "Pectoral reflex with the arm partly abducted", "EMG of the two heads separately in plexus lesions"],
 ["The pectoralis major reads the plexus: clavicular head high roots, sternal head low roots", "A brisk pectoral jerk is an early sign of cervical cord compression", "Named for their cords, not their sides: the medial pectoral nerve lies lateral to the lateral one at first"],
 UL, synonyms=["anterior thoracic nerves"], syndromes=["syn-neurogenic-thoracic-outlet", "syn-cervical-spondylotic-myelopathy", "syn-klumpke"]))

E.append(nerve("nerve-posterior-femoral-cutaneous", "Posterior femoral cutaneous nerve", "lower-limb", "posterior-femoral-cutaneous-nerve", "S1-S3",
 "The posterior femoral cutaneous nerve arises from the sacral plexus (S1, S2, S3), leaves the pelvis through the greater sciatic foramen below the piriformis with the sciatic and inferior gluteal nerves and descends under the gluteus maximus and along the back of the thigh deep to the fascia, supplying the skin of the lower buttock, the perineum, the posterior thigh and the upper calf. It is the sensory nerve that separates a sciatic neuropathy from a sacral plexopathy or radiculopathy: numbness of the posterior thigh with a foot drop means the plexus or the roots, because the sciatic nerve itself supplies no thigh skin; it is injured with the sciatic nerve in hip surgery and injections and is compressed by prolonged sitting and by the hamstring origin.",
 "From the sacral plexus through the infrapiriform part of the greater sciatic foramen, medial to the sciatic nerve, under the gluteus maximus, giving inferior cluneal branches to the buttock and a perineal branch, then descending in the midline of the posterior thigh beneath the fascia lata to the popliteal fossa, where it pierces the fascia and continues to the upper calf.",
 "Purely sensory, it carries sensation from the lower buttock, the perineum and posterior scrotum or labium, the posterior thigh and the upper posterior calf through the sacral plexus to the S1-S3 dorsal root ganglia; its territory is spared in sciatic neuropathy at the thigh, which is why posterior thigh numbness with sciatic-type weakness places the lesion at the sciatic notch, the plexus or the roots (piriformis region, pelvic tumor, sacral fracture, radiation). Its perineal branch explains perineal numbness in sacral plexopathy, and the inferior cluneal branches explain the buttock pain of ischial bursitis and of sitting on a hard seat, sometimes called wallet neuritis when the nerve is compressed against the ischial tuberosity.",
 [mview("coronal", "posterior-femoral-cutaneous-nerve-l", "posterior femoral cutaneous nerve under the gluteus maximus and along the posterior thigh"), mview("axial", "posterior-femoral-cutaneous-nerve-r", "nerve medial to the sciatic nerve below the piriformis")],
 "A nerve medial to the sciatic nerve at the infrapiriform foramen and in the posterior thigh on MR neurography and ultrasound; its territory is the posterior thigh and lower buttock.",
 [pathol("Sacral plexopathy", "MRI", "Thickening or enhancement of the sacral plexus from tumor, radiation or inflammation with posterior thigh numbness, foot drop and gluteal weakness; the posterior femoral cutaneous involvement places the lesion proximal to the sciatic nerve.", sequence="T1+Gd"),
  pathol("Injury at the sciatic notch (hip surgery, injection)", "MRI", "Signal change of the sciatic and posterior femoral cutaneous nerves at the infrapiriform foramen with posterior thigh sensory loss.", sequence="STIR"),
  pathol("Entrapment at the ischial tuberosity", "US", "Compression of the nerve and its cluneal branches at the hamstring origin with buttock and posterior thigh pain on sitting.", sequence="n/a")],
 [("Numbness of the posterior thigh, lower buttock and perineum", "ipsilateral", "Lesion of the nerve, the sacral plexus or the S1-S3 roots"), ("Marker of a proximal (plexus or root) lesion in sciatic-pattern weakness", "ipsilateral", "The sciatic nerve does not supply thigh skin"), ("Pain on sitting", "ipsilateral", "Entrapment against the ischial tuberosity")],
 ["Test sensation on the posterior thigh in every foot drop with sciatic-pattern weakness", "Gluteal strength and hip extension to detect plexus involvement", "Perineal sensation and sphincter function when the S2-S3 territory is numb"],
 ["Numb posterior thigh with a foot drop means the lesion is above the sciatic nerve, in the plexus or the roots", "The sciatic nerve gives no skin in the thigh; that is what makes this nerve useful", "Buttock pain on sitting can be this nerve against the ischium, not a disc"],
 LL, synonyms=["posterior cutaneous nerve of the thigh"], syndromes=["syn-sciatic-neuropathy", "syn-lumbosacral-plexopathy", "syn-radiculopathy-lumbosacral"]))

E.append(nerve("nerve-genitofemoral", "Genitofemoral nerve", "lower-limb", "genitofemoral-nerve", "L1-L2",
 "The genitofemoral nerve arises from the L1 and L2 roots within the psoas major, emerges on its anterior surface and descends behind the peritoneum to divide above the inguinal ligament into a genital branch, which enters the inguinal canal to supply the cremaster and the skin of the scrotum or labium, and a femoral branch, which passes under the inguinal ligament to supply the skin of the upper anterior thigh over the femoral triangle. It is the efferent and part of the afferent limb of the cremasteric reflex, it is entrapped after hernia repair and pelvic surgery, and its territory distinguishes L1-L2 lesions from the more lateral femoral cutaneous and ilioinguinal patterns.",
 "Formed within the psoas from L1 and L2, pierces the anterior surface of the muscle, descends on it beneath the peritoneum and the ureter, crosses the external iliac vessels and divides: the genital branch enters the deep inguinal ring with the spermatic cord (or round ligament) to the cremaster and the scrotal or labial skin; the femoral branch passes lateral to the femoral artery under the inguinal ligament to the skin of the upper thigh.",
 "Its genital branch is motor to the cremaster and sensory to the anterior scrotum or labium majus, forming the efferent limb of the cremasteric reflex (stroking the medial thigh elevates the testis), whose loss indicates an L1-L2 root, plexus or nerve lesion or a corticospinal lesion above; its femoral branch is sensory to the upper anterior thigh below the inguinal ligament. Entrapment or injury by inguinal hernia mesh, varicocelectomy, appendectomy and psoas abscess produces groin, scrotal and upper thigh pain and numbness that is aggravated by hip extension and relieved by flexion, and its blockade is part of the anesthesia for inguinal surgery.",
 [mview("coronal", "genitofemoral-nerve-l", "genitofemoral nerve on the anterior surface of the psoas dividing above the inguinal ligament"), mview("axial", "genitofemoral-nerve-r", "nerve on the psoas beneath the peritoneum")],
 "A small nerve on the anterior surface of the psoas on MR neurography; its branches at the inguinal canal are seen on ultrasound. Territory: anterior scrotum or labium and the upper anterior thigh.",
 [pathol("Post-herniorrhaphy neuralgia", "US", "Entrapment of the genital branch by mesh or suture at the inguinal canal with groin and scrotal pain; ultrasound-guided block confirms and treats.", sequence="n/a"),
  pathol("Psoas abscess or retroperitoneal mass", "CT", "Fluid collection or tumor within or on the psoas involving the nerve, with groin pain, a flexed hip and sensory loss in the femoral triangle.", sequence="CT contrast"),
  pathol("L1-L2 radiculopathy", "MRI", "Upper lumbar disc or foraminal lesion with groin pain and an absent cremasteric reflex.", sequence="T2")],
 [("Groin, scrotal or labial pain and numbness", "ipsilateral", "Entrapment or injury of the genital branch"), ("Numbness of the upper anterior thigh", "ipsilateral", "Femoral branch involvement"), ("Absent cremasteric reflex", "ipsilateral", "Loss of the L1-L2 reflex arc or a corticospinal lesion above it")],
 ["Cremasteric reflex on each side", "Sensation over the femoral triangle and the anterior scrotum or labium", "Pain reproduction with hip extension and relief with flexion; a diagnostic block"],
 ["Groin pain after hernia repair is this nerve or its neighbors; a block sorts them out", "The cremasteric reflex tests L1-L2 and the corticospinal tract at once", "A flexed hip with groin pain and fever is a psoas abscess on the genitofemoral nerve"],
 LL, synonyms=["genitocrural nerve"], syndromes=["syn-lumbosacral-plexopathy", "syn-radiculopathy-lumbosacral"]))

E.append(nerve("nerve-iliohypogastric", "Iliohypogastric nerve", "lower-limb", "iliohypogastric-nerve", "T12-L1",
 "The iliohypogastric nerve is the first branch of the lumbar plexus (L1 with a T12 contribution), emerging from the lateral border of the psoas, crossing the quadratus lumborum and the iliac crest region between the transversus abdominis and the internal oblique, and dividing into a lateral cutaneous branch to the skin of the upper buttock and an anterior cutaneous branch to the skin above the pubis. It supplies the lower abdominal wall muscles with the ilioinguinal nerve, it is injured in appendectomy, hernia repair, iliac crest bone harvest and Pfannenstiel incisions, and its entrapment produces the lower abdominal wall pain that is mistaken for a visceral or spinal cause.",
 "Leaves the upper lateral border of the psoas, crosses the quadratus lumborum behind the kidney, pierces the transversus abdominis above the iliac crest, runs between it and the internal oblique, gives the lateral cutaneous branch over the iliac crest to the gluteal skin and continues forward to pierce the internal and external obliques above the superficial inguinal ring as the anterior cutaneous branch to the suprapubic skin.",
 "Mixed, it supplies the lower fibers of the transversus abdominis and internal oblique that form the conjoint tendon and protect the inguinal region, and sensation to the upper lateral buttock and the hypogastric skin above the pubis; its loss weakens the lower abdominal wall (a factor in direct inguinal hernia) and produces a band of numbness or burning above the groin, and entrapment by sutures, mesh or scar in the abdominal wall produces a chronic pain aggravated by trunk extension and hip extension with a trigger point medial to the anterior superior iliac spine. It shares roots and territory with the ilioinguinal nerve and is blocked together with it for hernia and lower abdominal surgery.",
 [mview("coronal", "iliohypogastric-nerve-l", "iliohypogastric nerve crossing the quadratus lumborum to the abdominal wall"), mview("axial", "iliohypogastric-nerve-r", "nerve between the transversus abdominis and internal oblique above the iliac crest")],
 "A nerve between the transversus abdominis and internal oblique above the anterior superior iliac spine on ultrasound; not seen on routine MRI. Territory: upper buttock and suprapubic skin.",
 [pathol("Abdominal wall nerve entrapment after surgery", "US", "Neuroma or scar around the nerve near the anterior superior iliac spine after appendectomy, hernia repair or Pfannenstiel incision; a block relieves the pain.", sequence="n/a"),
  pathol("Iliac crest bone graft injury", "US", "Injury to the lateral cutaneous branch over the iliac crest with numbness of the upper buttock.", sequence="n/a"),
  pathol("T12-L1 radiculopathy or retroperitoneal disease", "CT", "Lesion of the upper lumbar roots or the retroperitoneum at the psoas border with lower abdominal wall pain and a bulging flank from muscle weakness.", sequence="CT contrast")],
 [("Numbness or burning pain above the pubis and over the upper buttock", "ipsilateral", "Entrapment or injury of the nerve"), ("Weakness of the lower abdominal wall", "ipsilateral", "Denervation of the lower transversus and internal oblique"), ("Contribution to direct inguinal hernia", "ipsilateral", "Weakened conjoint tendon region")],
 ["Sensation over the suprapubic and upper gluteal skin", "Tenderness and Tinel sign medial to the anterior superior iliac spine", "Diagnostic nerve block for chronic post-surgical groin and abdominal wall pain"],
 ["Chronic pain at the edge of a lower abdominal scar is a nerve, not the bowel", "The iliohypogastric and ilioinguinal nerves are blocked together for hernia repair and injured together by it", "A bulging flank with a numb band above the groin is a T12-L1 lesion"],
 LL, synonyms=["iliohypogastric nerve (L1)"], syndromes=["syn-lumbosacral-plexopathy"]))

E.append(nerve("nerve-ilioinguinal", "Ilioinguinal nerve", "lower-limb", "ilioinguinal-nerve", "L1",
 "The ilioinguinal nerve (L1) runs just below the iliohypogastric nerve, emerging from the lateral border of the psoas, crossing the quadratus lumborum and the iliacus, piercing the transversus abdominis near the iliac crest and passing through the inguinal canal with the spermatic cord or round ligament to emerge through the superficial ring and supply the skin of the upper medial thigh, the root of the penis and anterior scrotum or the mons and labium majus. It is the nerve most often injured in inguinal hernia repair and the commonest cause of chronic postoperative groin pain, and its territory distinguishes it from the genitofemoral nerve (which supplies the femoral triangle and the cremaster) and the lateral femoral cutaneous nerve.",
 "From the L1 root, along the lateral border of the psoas and across the quadratus lumborum and iliacus below the iliohypogastric nerve, piercing the transversus abdominis near the anterior part of the iliac crest, running between it and the internal oblique, then entering the inguinal canal below the spermatic cord to leave through the superficial inguinal ring to the skin of the upper medial thigh and the external genitalia.",
 "Mainly sensory to the upper medial thigh, the root of the penis and anterior scrotum or the mons and labium majus, with motor fibers to the lowest fibers of the internal oblique and transversus abdominis; it provides the sensory afferent of the cremasteric reflex from the medial thigh (the efferent runs in the genitofemoral nerve), and its entrapment by suture, mesh or scar after hernia repair, or by the abdominal wall muscles in athletes, produces a burning groin pain radiating to the genitalia and the medial thigh that is aggravated by walking and hip extension and relieved by flexion, with a trigger point medial to the anterior superior iliac spine. Ilioinguinal block is used for hernia surgery, and neurectomy for refractory neuralgia.",
 [mview("coronal", "ilioinguinal-nerve-l", "ilioinguinal nerve crossing the iliacus to the inguinal canal"), mview("axial", "ilioinguinal-nerve-r", "nerve between the transversus abdominis and internal oblique near the iliac crest")],
 "A small nerve between the transversus abdominis and internal oblique near the anterior superior iliac spine and within the inguinal canal on ultrasound. Territory: upper medial thigh and anterior genitalia.",
 [pathol("Post-herniorrhaphy ilioinguinal neuralgia", "US", "Nerve entrapped in mesh or scar in the inguinal canal with a Tinel sign at the superficial ring; ultrasound-guided block confirms.", sequence="n/a"),
  pathol("Athletic groin pain (sportsman's hernia)", "MRI", "Rectus and adductor origin tendinopathy at the pubis with entrapment of the ilioinguinal or genital branch by the external oblique aponeurosis.", sequence="STIR"),
  pathol("L1 radiculopathy or plexus lesion", "MRI", "Upper lumbar root or retroperitoneal lesion with groin and genital numbness and a weak lower abdominal wall.", sequence="T2")],
 [("Burning pain and numbness of the groin, upper medial thigh and anterior genitalia", "ipsilateral", "Entrapment or injury of the nerve, usually in the inguinal canal"), ("Reduced cremasteric reflex", "ipsilateral", "Loss of the afferent limb from the medial thigh"), ("Mild lower abdominal wall weakness", "ipsilateral", "Denervation of the lowest fibers of the oblique muscles")],
 ["Map the sensory loss and compare with the genitofemoral (femoral triangle) and lateral femoral cutaneous (lateral thigh) territories", "Tinel sign medial to the anterior superior iliac spine and at the superficial inguinal ring", "Diagnostic block; neurectomy if it fails"],
 ["Groin pain after hernia surgery is the ilioinguinal nerve until a block says otherwise", "Three nerves supply the groin skin: ilioinguinal medially, genitofemoral in the triangle, lateral femoral cutaneous laterally", "Hip flexion relieves it; walking provokes it"],
 LL, synonyms=["ilioinguinal nerve (L1)"], syndromes=["syn-lumbosacral-plexopathy", "syn-meralgia-paresthetica"]))

E.append(nerve("nerve-superior-gluteal", "Superior gluteal nerve", "lower-limb", "superior-gluteal-nerve", "L4-S1",
 "The superior gluteal nerve (L4, L5, S1) leaves the pelvis through the greater sciatic foramen above the piriformis, the only nerve to do so, and runs between the gluteus medius and minimus with the superior gluteal artery to supply those two muscles and the tensor fasciae latae, the abductors and medial rotators of the hip that hold the pelvis level in single-leg stance. Its loss produces the Trendelenburg sign and a waddling gait, and it is injured by hip replacement through a lateral approach, by intramuscular injections in the wrong quadrant and by L5 radiculopathy; abductor weakness in an L5 lesion is the sign that separates the root from a peroneal neuropathy, which spares the gluteus medius.",
 "From the sacral plexus in the pelvis, through the suprapiriform part of the greater sciatic foramen with the superior gluteal vessels, then laterally between the gluteus medius and minimus, supplying both, and forward to end in the tensor fasciae latae.",
 "Motor to the gluteus medius, gluteus minimus and tensor fasciae latae, which abduct and medially rotate the thigh and, more importantly, stabilize the pelvis on the stance leg during walking; when they are weak the pelvis drops toward the swing side (the Trendelenburg sign) and the trunk lurches over the stance leg, producing a waddling gait when bilateral. The nerve carries L5 fibers predominantly, so abductor weakness is part of the L5 radiculopathy and lumbosacral plexopathy pictures and is absent in a common peroneal palsy at the fibular neck, the key bedside distinction in foot drop; it is also at risk in the lateral and anterolateral approaches to the hip, where the muscle split is limited to protect it, and in gluteal injections given too medially or too high.",
 [mview("coronal", "superior-gluteal-nerve-l", "superior gluteal nerve leaving the greater sciatic foramen above the piriformis"), mview("axial", "superior-gluteal-nerve-r", "nerve between the gluteus medius and minimus")],
 "A nerve with the superior gluteal artery above the piriformis and between the gluteal muscles on MR neurography; denervation shows as STIR change and fatty atrophy of the gluteus medius, minimus and tensor fasciae latae.",
 [pathol("Iatrogenic injury at hip arthroplasty", "MRI", "Denervation edema and later fatty atrophy of the gluteus medius and minimus after a lateral approach, with a Trendelenburg gait.", sequence="STIR"),
  pathol("L5 radiculopathy", "MRI", "L4-5 disc or foraminal lesion; EMG shows denervation of the gluteus medius and tensor fasciae latae as well as the tibialis anterior, placing the lesion at the root rather than the peroneal nerve.", sequence="T2"),
  pathol("Injection injury in the gluteal region", "US", "Nerve injury after a superomedial injection with hip abductor weakness; the safe upper outer quadrant avoids it.", sequence="n/a")],
 [("Trendelenburg sign and waddling gait", "ipsilateral", "Weakness of the gluteus medius and minimus"), ("Weak hip abduction and medial rotation", "ipsilateral", "Denervation of the abductors and tensor fasciae latae"), ("Marker of L5 root or plexus involvement in foot drop", "ipsilateral", "The nerve carries L5 fibers that the peroneal nerve does not test")],
 ["Single-leg stance: watch the opposite hip drop", "Hip abduction strength lying on the side", "Compare abductor strength with dorsiflexion in every foot drop"],
 ["Foot drop with weak hip abduction is an L5 root, not the peroneal nerve", "The Trendelenburg sign is the superior gluteal nerve's signature", "Inject in the upper outer quadrant: the superior gluteal nerve lives above the piriformis"],
 LL, synonyms=["superior gluteal nerve (L4-S1)"], syndromes=["syn-radiculopathy-lumbosacral", "syn-peroneal-palsy-foot-drop", "syn-lumbosacral-plexopathy"]))

E.append(nerve("nerves-dorsal-cutaneous-foot", "Dorsal cutaneous nerves of the foot", "lower-limb", "dorsal-cutaneous-nerves-foot", "L4-S1",
 "The medial and intermediate dorsal cutaneous nerves of the foot are the terminal branches of the superficial peroneal nerve, emerging through the deep fascia of the lower lateral leg and crossing the ankle to supply the skin of the dorsum of the foot and toes, except the first web space (deep peroneal), the lateral border of the foot (sural) and the medial border (saphenous). They are the sensory map of the superficial peroneal nerve and of the L5 dermatome on the dorsum of the foot, they are compressed where they pierce the fascia and at the ankle by tight boots, and they are injured in ankle arthroscopy and surgery, producing numbness and neuroma pain on the top of the foot.",
 "The superficial peroneal nerve pierces the deep fascia in the lower third of the lateral leg and divides into the medial dorsal cutaneous nerve, which crosses the ankle anterior to the lateral malleolus to the medial dorsum, the great toe and the second and third toes, and the intermediate dorsal cutaneous nerve, which runs more laterally to the lateral dorsum and the third to fifth toes; both lie subcutaneously over the extensor retinaculum.",
 "Purely sensory, they carry sensation from the dorsum of the foot and toes through the superficial peroneal nerve to the L5 (medial) and S1 (lateral) dorsal root ganglia; their sparing of the first web space (deep peroneal), the lateral foot (sural) and the medial foot (saphenous) allows the examiner to assign dorsal foot numbness to the superficial peroneal nerve or the L5 root, and the superficial peroneal sensory potential separates the two (normal in a root lesion). They are entrapped where the superficial peroneal nerve pierces the fascia (with pain on plantar flexion and inversion) and compressed by boots at the ankle, and they are cut in anterolateral ankle portals and bunion surgery, leaving a numb dorsum or a painful neuroma.",
 [mview("coronal", "dorsal-cutaneous-nerves-foot-l", "medial and intermediate dorsal cutaneous nerves crossing the ankle to the dorsum of the foot"), mview("axial", "dorsal-cutaneous-nerves-foot-r", "terminal branches of the superficial peroneal nerve over the extensor retinaculum")],
 "Subcutaneous nerves over the anterior ankle on ultrasound, seen with the foot plantar-flexed and inverted; not resolved on routine MRI. Territory: dorsum of the foot except the first web space and the borders.",
 [pathol("Superficial peroneal nerve entrapment", "US", "Focal swelling of the nerve where it pierces the crural fascia in the lower lateral leg, with dorsal foot paresthesias on inversion.", sequence="n/a"),
  pathol("Iatrogenic injury at ankle arthroscopy", "US", "Neuroma of a dorsal cutaneous branch beneath an anterolateral portal scar with a painful Tinel sign.", sequence="n/a"),
  pathol("L5 radiculopathy (for comparison)", "EMG/NCS", "Normal superficial peroneal sensory potential despite a numb dorsum of the foot, placing the lesion at the root.", sequence="n/a")],
 [("Numbness of the dorsum of the foot sparing the first web space", "ipsilateral", "Superficial peroneal nerve or its dorsal cutaneous branches"), ("Painful neuroma on the dorsum after ankle surgery", "ipsilateral", "Section of a dorsal cutaneous branch"), ("Numb dorsum with a normal sensory potential", "ipsilateral", "L5 radiculopathy proximal to the ganglion")],
 ["Test the first web space (deep peroneal) separately from the rest of the dorsum (superficial peroneal)", "Tinel sign over the lower lateral leg where the nerve pierces the fascia and over ankle scars", "Superficial peroneal sensory conduction study"],
 ["Numb top of the foot with a normal first web space is the superficial peroneal nerve; a numb web space alone is the deep peroneal", "Mark the dorsal cutaneous nerves before ankle arthroscopy: they lie under the anterolateral portal", "A normal superficial peroneal sensory response in a numb foot means the L5 root"],
 LL, synonyms=["medial dorsal cutaneous nerve of the foot", "intermediate dorsal cutaneous nerve of the foot"], syndromes=["syn-peroneal-palsy-foot-drop", "syn-radiculopathy-lumbosacral"]))

write(E)
# attach the new meshes to the existing entries
for sid, meshes in {"plexus-lumbosacral": ["lumbosacral-plexus-l", "lumbosacral-plexus-r"], "spinal-grey-anterior-horn": ["spinal-grey-anterior-horn"], "spinal-grey-posterior-horn": ["spinal-grey-posterior-horn"], "spinal-white-columns": ["spinal-white-columns"]}.items():
    p = ROOT / "content" / "data" / "structures" / f"{sid}.json"
    if not p.exists(): print("missing", sid); continue
    d = json.loads(p.read_text()); cur = d.get("meshIds", [])
    d["meshIds"] = cur + [m for m in meshes if m not in cur]
    p.write_text(json.dumps(d, indent=1, ensure_ascii=False) + "\n"); print("patched", sid, d["meshIds"])
