import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).parent))
from synlib import *
E = []
S17 = lambda a, b=None: C("snell", 17, a, b)
B7 = lambda a, b=None: C("berkowitz", 7, a, b)
B6 = lambda a, b=None: C("berkowitz", 6, a, b)
S8 = lambda a, b=None: C("snell", 8, a, b)

def lac(id, name, structures, presentation, deficits, reasoning, site, marker, hint_, causes_extra=(), mimics_extra=(), preset="superior"):
    return syn(id, name, "lacunar", structures, "contralateral", presentation, deficits, reasoning,
        [pathol("Acute lacune", "MRI", f"Small (under 15 mm) focus of restricted diffusion in the {site}; CT is often normal in the first day.", sequence="DWI"),
         pathol("Chronic lacune", "MRI", "Small CSF-intensity cavity with a FLAIR-bright rim, often multiple, with diffuse white matter hyperintensity of small vessel disease.", sequence="FLAIR")],
        ["Hypertensive lipohyalinosis of a single perforating artery", "Microatheroma at the perforator origin", *causes_extra],
        [("Cortical branch infarct", "Cortical signs (aphasia, neglect, field loss, gaze deviation) exclude a lacune"), ("Small hemorrhage", "Hyperdense on CT; same sites"), *mimics_extra],
        ["Antiplatelet therapy, statin and blood pressure control", "Thrombolysis when presenting within the window and disabling", "Early mobilization; prognosis for recovery is good"],
        [S17(474), S17(482), B7(60), B7(63)], marker=marker, imagingHint=hint_, preset=preset)

E.append(lac("syn-lacunar-pure-motor", "Pure motor lacunar stroke", ["internal-capsule", "arteries-lenticulostriate", "pontine-nuclei", "corona-radiata"],
 "A hypertensive patient wakes with weakness of the face, arm and leg on one side, all roughly equally affected, and nothing else: sensation, vision, speech content and awareness are normal, though speech may be slurred by the facial weakness. There is no headache and the patient is fully alert. The weakness may stutter over hours before settling.",
 [D("motor", "contralateral", "face, arm and leg equally", "Hemiparesis with hyperreflexia and extensor plantar", "pathway-lateral-corticospinal"), D("bulbar", "contralateral", "lower face and tongue", "Dysarthria from corticobulbar involvement", "pathway-corticobulbar"), D("sensory-light-touch", "n/a", "none", "Sensation preserved: the hallmark of a pure motor lacune", "pathway-dcml")],
 "The corticospinal and corticobulbar fibers for face, arm and leg are packed into a few square millimeters in the posterior limb and genu of the internal capsule and again in the basis pontis, so a single small perforator infarct removes all of them together, producing a hemiparesis that is proportional across the body rather than following the cortical homunculus. The fibers have not yet crossed at either site, so the paralysis is contralateral, as after a cortical lesion. What distinguishes the lacune is what is missing: the thalamocortical sensory fibers lie a few millimeters posterior in the capsule and in the tegmentum of the pons, the optic radiation is far lateral and the cortex is intact, so there is no sensory loss, no field defect and no aphasia or neglect. A capsular lacune and a pontine lacune are clinically identical; imaging decides. Because the lenticulostriate and paramedian pontine perforators are end arteries damaged by hypertension, the infarct is small and recovery is often good.",
 "posterior limb of the internal capsule or the basis pontis", sphere(-22, -12, 8, 6), hint("axial", -22, -12, 8, "posterior limb of the internal capsule")))

E.append(lac("syn-lacunar-pure-sensory", "Pure sensory lacunar stroke", ["thalamus-vpl", "thalamus-vpm", "arteries-thalamoperforating"],
 "The patient describes numbness or tingling that came on over minutes and involves the face, arm, trunk and leg of one side, sometimes splitting the midline exactly. Strength, coordination, vision and speech are unaffected. The examiner may find surprisingly little objective loss compared with the complaint, or a clear reduction of all modalities on that side.",
 [D("sensory-light-touch", "contralateral", "face, arm, trunk and leg", "Hemihypesthesia to touch, pin and vibration, often splitting the midline", "thalamus-vpl"), D("sensory-pain-temp", "contralateral", "hemibody", "Paresthesias and reduced pin-prick", "pathway-lateral-spinothalamic"), D("motor", "n/a", "none", "No weakness; reflexes symmetric", "pathway-lateral-corticospinal")],
 "The ventral posterior nuclei of the thalamus receive every ascending somatic sensory pathway after it has crossed: the medial lemniscus, which crossed in the medulla, the spinothalamic tract, which crossed in the spinal cord, and the trigeminal lemniscus from the face. A lacune in the thalamogeniculate perforator territory therefore removes all modalities from the whole contralateral half of the body including the face, a combination that a spinal lesion cannot produce and a brainstem lesion produces only with crossed facial involvement. The corticospinal tract lies in the adjacent internal capsule and is spared, so there is no weakness; an infarct big enough to reach it becomes a sensorimotor stroke. A small cortical infarct of the postcentral gyrus can cause a similar restricted hemisensory deficit, but it usually spares some modality and rarely splits the trunk at the midline. Some patients later develop central post-stroke pain, when the syndrome is renamed Dejerine–Roussy.",
 "ventral posterolateral thalamus", sphere(-15, -20, 6, 5), hint("axial", -15, -20, 6, "lateral thalamus"), mimics_extra=[("Parietal cortical infarct", "Discriminative loss (graphesthesia, stereognosis) with sparing of primary modalities; DWI cortical")]))

E.append(lac("syn-lacunar-ataxic-hemiparesis", "Ataxic hemiparesis", ["internal-capsule", "pontine-nuclei", "corona-radiata", "level-pons-caudal"],
 "The patient has a mild hemiparesis, usually worse in the leg, but the striking feature is an incoordination on the same side that is out of proportion to the weakness: the heel-shin test is clumsy, the arm overshoots, and gait is unsteady toward the weak side. Sensation and speech are normal. The combination of pyramidal and cerebellar signs on one side of the body points to a small deep lesion.",
 [D("motor", "contralateral", "leg more than arm", "Mild upper motor neuron hemiparesis", "pathway-lateral-corticospinal"), D("cerebellar", "contralateral", "same limbs as the weakness", "Limb ataxia disproportionate to the weakness", "pathway-cerebellar-circuits"), D("gait", "contralateral", "leg", "Unsteady gait veering toward the weak side", "pathway-cerebellar-circuits")],
 "A single perforator infarct in the posterior limb of the internal capsule, the corona radiata or the basis pontis interrupts two systems that run side by side there: the corticospinal tract and the corticopontocerebellar connections. The corticospinal fibers have not yet crossed, so the weakness is contralateral. The cerebellar signs are on the same side as the weakness because the cerebellar loop crosses twice: corticopontine fibers cross in the pons to the opposite cerebellar hemisphere, and the dentatothalamic output crosses back in the midbrain to the original hemisphere and its motor cortex. Cutting the loop at the capsule or pons on one side therefore produces ataxia of the contralateral limbs, the same limbs weakened by the corticospinal lesion. The lesion is small, so there is no sensory loss or cortical sign. The pontine site is the commoner; leg-predominant weakness is characteristic because the leg fibers lie posteriorly in the capsule and dorsolaterally in the pons.",
 "posterior limb of the internal capsule, corona radiata or basis pontis", sphere(-6, -28, -28, 6), hint("axial", -6, -28, -28, "paramedian basis pontis"), mimics_extra=[("Cerebellar infarct with mass effect", "Ataxia ipsilateral to the cerebellar lesion without pyramidal weakness; headache and vomiting")], preset="anterior"))

E.append(lac("syn-lacunar-dysarthria-clumsy-hand", "Dysarthria–clumsy hand syndrome", ["pontine-nuclei", "internal-capsule", "level-pons-caudal"],
 "Speech becomes slurred and the patient complains that one hand has become clumsy: writing deteriorates and fine tasks are fumbled, although strength is nearly normal. Examination shows facial weakness of the lower face, tongue deviation, mild hand weakness with hyperreflexia and clumsiness, and sometimes an extensor plantar. Sensation is intact.",
 [D("bulbar", "contralateral", "face and tongue", "Dysarthria with lower facial weakness and tongue deviation", "pathway-corticobulbar"), D("motor", "contralateral", "hand", "Clumsiness and mild weakness of the hand with hyperreflexia", "pathway-lateral-corticospinal"), D("cerebellar", "contralateral", "hand", "Impaired fine finger movements and dysmetria", "pathway-cerebellar-circuits")],
 "This is a small-vessel infarct in the paramedian basis pontis or the genu of the internal capsule, where the corticobulbar fibers to the facial and hypoglossal nuclei run beside the corticospinal fibers for the hand. The corticobulbar fibers cross at the level of the nuclei in the pons and medulla, and the corticospinal fibers cross in the pyramidal decussation, so both the facial weakness and the hand signs are contralateral to the lesion. Involvement of the corticopontocerebellar pathway, which crosses twice like all cerebellar loops, adds the clumsiness on the same side as the weakness. The lesion is too small to reach the sensory pathways in the pontine tegmentum or the posterior capsule, and the cortex is intact, so there is no sensory loss, aphasia or field defect. It is really a fragment of the pure motor syndrome in which the face and hand fibers, which lie most anteriorly in the capsule and most medially in the crus and pons, are picked out by an even smaller infarct.",
 "paramedian basis pontis or genu of the internal capsule", sphere(-4, -25, -26, 5), hint("axial", -4, -25, -26, "paramedian pons"), preset="anterior"))

E.append(lac("syn-lacunar-sensorimotor", "Sensorimotor lacunar stroke", ["internal-capsule", "thalamus-vpl", "arteries-thalamoperforating", "arteries-lenticulostriate"],
 "Weakness and numbness of the face, arm and leg on one side develop together in an alert patient who speaks and sees normally. The pattern resembles a large hemispheric stroke but the patient has none of the cortical features and CT is normal or shows only a small deep lesion. It is the commonest of the lacunar syndromes to be over-investigated for a cortical cause.",
 [D("motor", "contralateral", "face, arm and leg", "Hemiparesis with upper motor neuron signs", "pathway-lateral-corticospinal"), D("sensory-light-touch", "contralateral", "hemibody", "Hemihypesthesia to all modalities", "thalamus-vpl"), D("language", "n/a", "none", "No aphasia, neglect or field defect", "area-broca")],
 "The lesion sits at the boundary between the posterior limb of the internal capsule and the lateral thalamus, which is where the descending corticospinal tract and the ascending thalamocortical sensory radiation lie within a few millimeters of one another. It is supplied either by a lateral lenticulostriate branch of the middle cerebral artery or by a thalamogeniculate branch of the posterior cerebral artery, and an infarct slightly larger than the usual lacune spans both. The corticospinal tract has not yet crossed, and the sensory pathways have already crossed below, so both deficits appear on the contralateral side, together. What proves the lesion is deep rather than cortical is the absence of all cortical functions: the language areas, the parietal spatial cortex and the optic radiation are untouched, and the patient is alert with normal gaze. The differential from a small cortical infarct rests on this absence plus imaging, since a pure hemiparesis with hemianesthesia can also follow a striatocapsular infarct or an anterior choroidal artery infarct, the latter usually adding a field defect.",
 "posterior limb of the internal capsule and adjacent thalamus", sphere(-19, -16, 7, 7), hint("axial", -19, -16, 7, "capsulothalamic junction"), mimics_extra=[("Anterior choroidal artery infarct", "Adds a homonymous hemianopia")]))

E.append(syn("syn-gerstmann", "Gerstmann syndrome", "vascular", ["gyrus-angular", "lobe-parietal", "artery-mca-inferior-division"], "left",
 "A right-handed patient is found unable to do simple arithmetic, to write a sentence, to name or point to individual fingers, and to tell left from right, either on themselves or on the examiner, while speaking fluently and understanding well. There may be a mild alexia and constructional difficulty. The combination points to the dominant angular gyrus.",
 [D("cognitive", "n/a", "dominant parietal", "Acalculia", "gyrus-angular"), D("cognitive", "n/a", "dominant parietal", "Agraphia without alexia (or with mild alexia)", "gyrus-angular"), D("cognitive", "n/a", "dominant parietal", "Finger agnosia and right-left disorientation", "gyrus-angular"), D("visual-field", "contralateral", "inferior quadrant (sometimes)", "Inferior quadrantanopia if the parietal optic radiation is caught", "pathway-visual")],
 "The angular gyrus of the dominant hemisphere is a hub where visual, somatosensory and language information converge, at the junction of the parietal, temporal and occipital lobes. It maps the body schema onto language, which is why identifying fingers, telling left from right, manipulating numbers and writing, all of which require translating between spatial and verbal representations, fail together. Each of these functions depends on the intact, uncrossed cortical association network of one hemisphere, so the syndrome is a consequence of a left-sided lesion in right-handed people and has no contralateral or crossed component apart from any accompanying field defect, which is contralateral because the optic radiation on its way to the calcarine cortex carries the opposite hemifield. The supplying vessel is the angular branch of the inferior division of the middle cerebral artery; larger infarcts add Wernicke aphasia or alexia, and the pure tetrad is rare enough that its localizing value is debated, but its presence should always send the examiner to the left parietal lobe.",
 [pathol("Angular gyrus infarct", "MRI", "Restricted diffusion in the left angular gyrus at the parieto-temporo-occipital junction.", sequence="DWI"), pathol("Tumor or focal atrophy", "MRI", "Left parietal mass or focal atrophy (posterior cortical variants of Alzheimer disease) producing a slowly progressive version.", sequence="T1+Gd")],
 ["Infarct of the angular branch of the left middle cerebral artery", "Left parietal tumor", "Posterior cortical atrophy"],
 [("Wernicke aphasia", "Comprehension is impaired; in Gerstmann it is preserved"), ("Developmental Gerstmann", "Lifelong learning difficulty in children, no acute lesion"), ("Global cognitive impairment", "Deficits are not selective")],
 ["Treat the underlying stroke or lesion", "Occupational therapy for calculation and writing", "Screen for a field defect"],
 [B7(53)], marker=sphere(-45, -60, 35, 10), imagingHint=hint("axial", -45, -60, 35, "left angular gyrus"), preset="lateral-l", eponyms=["angular gyrus syndrome"]))

E.append(syn("syn-aphasia-broca", "Broca (expressive, non-fluent) aphasia", "vascular", ["area-broca", "lobe-frontal", "artery-mca-superior-division", "gyrus-precentral"], "left",
 "Speech is effortful, slow and reduced to a few content words with the grammar stripped out ('go... hospital... wife'), and repeating a sentence is as hard as producing one. Comprehension of conversation is good, though complex grammatical sentences ('the lion was killed by the tiger; which animal died?') may defeat the patient. Writing is as impaired as speech. There is usually right facial and arm weakness, and the patient is frustrated and aware of the problem.",
 [D("language", "n/a", "dominant frontal", "Non-fluent, agrammatic speech with impaired repetition and naming, relatively preserved comprehension", "area-broca"), D("motor", "contralateral", "face and arm", "Right brachiofacial weakness from the adjacent motor cortex", "pathway-corticobulbar"), D("cognitive", "n/a", "dominant frontal", "Buccofacial and ideomotor apraxia", "cortex-premotor-sma")],
 "Broca's area occupies the pars opercularis and triangularis of the inferior frontal gyrus of the dominant hemisphere, in front of the face area of the motor cortex, and is supplied by the superior division of the middle cerebral artery. It assembles the motor programs for speech and the grammatical structure of sentences, and its connections to Wernicke's area through the arcuate fasciculus are what repetition requires, so speech output and repetition fail together. Comprehension survives because the posterior temporal cortex is in inferior division territory. Language is lateralized to the left hemisphere in almost all right-handers and most left-handers, and the network is entirely uncrossed at the cortical level, so the aphasia itself has no side; the accompanying weakness is contralateral because the corticobulbar and corticospinal fibers from the neighboring motor cortex cross in the brainstem, and the face and arm are affected because they sit next to Broca's area on the lateral convexity. A lesion confined to Broca's area gives a mild, transient deficit; the full persistent syndrome needs a larger infarct reaching the insula and underlying white matter.",
 [pathol("Superior-division infarct", "MRI", "Restricted diffusion in the left inferior frontal gyrus, frontal operculum and often the insula and precentral gyrus.", sequence="DWI"), pathol("Perfusion deficit", "CT perfusion", "Hypoperfusion of the left frontal operculum with a small core, common when the aphasia is the dominant deficit.")],
 ["Left MCA superior division infarct", "Left frontal hemorrhage", "Tumor or abscess of the left frontal operculum", "Primary progressive aphasia (agrammatic variant)"],
 [("Dysarthria", "Grammar and word choice are normal; only articulation is impaired"), ("Transcortical motor aphasia", "Repetition preserved; lesion in the watershed anterior or superior to Broca's area"), ("Mutism after supplementary motor area lesion", "Recovers within days, no agrammatism")],
 ["Acute stroke treatment", "Early intensive speech and language therapy", "Screen for depression, which is common with awareness of the deficit"],
 [S8(290, 291), B7(54, 56)], marker=sphere(-48, 15, 15, 10), imagingHint=hint("axial", -48, 15, 15, "left inferior frontal gyrus, pars opercularis"), preset="lateral-l", eponyms=["motor aphasia"]))

E.append(syn("syn-aphasia-wernicke", "Wernicke (receptive, fluent) aphasia", "vascular", ["area-wernicke", "lobe-temporal", "artery-mca-inferior-division", "gyrus-heschl"], "left",
 "The patient speaks in long, well-articulated but empty sentences peppered with wrong words and invented words, does not follow commands, cannot repeat, and seems unaware that anything is wrong, sometimes becoming angry when not understood. Strength is normal. A right superior quadrantanopia may be found if the examiner thinks to test the fields. The initial diagnosis is frequently confusion or psychosis.",
 [D("language", "n/a", "dominant temporal", "Fluent paraphasic speech with impaired comprehension and repetition; anosognosia", "area-wernicke"), D("visual-field", "contralateral", "superior quadrant", "Right superior quadrantanopia from Meyer's loop", "pathway-visual"), D("motor", "n/a", "none", "No weakness; the motor cortex is not involved", "pathway-lateral-corticospinal")],
 "Wernicke's area, the posterior part of the superior temporal gyrus of the dominant hemisphere behind Heschl's gyrus, holds the sound representations of words that both comprehension and word selection depend on. When it is destroyed, the incoming speech signal cannot be decoded, and the outgoing speech, produced by an intact Broca's area, is fluent but unmonitored and full of phonemic and semantic errors. Repetition fails because the input side of the arcuate loop is gone. The lesion lies in the inferior division territory of the left middle cerebral artery, far from the motor cortex, so there is no weakness to alert the examiner, while Meyer's loop of the optic radiation runs through the underlying temporal white matter carrying the contralateral upper visual field, giving the right upper quadrantanopia. Like all cortical language disorders the aphasia is uncrossed and simply reflects left hemisphere dominance; only the field defect obeys crossing logic. The anosognosia is intrinsic to the loss of self-monitoring and, together with the absence of weakness, explains why these patients are so often sent to psychiatry.",
 [pathol("Inferior-division infarct", "MRI", "Restricted diffusion in the left posterior superior temporal gyrus, often extending to the supramarginal gyrus.", sequence="DWI"), pathol("Temporal lobe tumor or encephalitis", "MRI", "Left temporal mass or T2 change producing a subacute fluent aphasia.", sequence="FLAIR")],
 ["Left MCA inferior division embolic infarct", "Left temporal hemorrhage", "Herpes simplex encephalitis", "Temporal lobe tumor", "Logopenic or semantic primary progressive aphasia"],
 [("Delirium or psychosis", "Language testing shows paraphasias and failed repetition with a field defect; DWI positive"), ("Transcortical sensory aphasia", "Repetition intact; watershed lesion behind Wernicke's area"), ("Pure word deafness", "Reading and writing preserved; bilateral or deep temporal lesions")],
 ["Acute stroke treatment; the deficit is disabling even without weakness", "Speech therapy focused on comprehension strategies", "Cardiac source evaluation, since the branch occlusion is usually embolic"],
 [S8(290, 291), B7(54, 56)], marker=sphere(-55, -45, 15, 10), imagingHint=hint("axial", -55, -45, 15, "left posterior superior temporal gyrus"), preset="lateral-l", eponyms=["sensory aphasia"]))

E.append(syn("syn-aphasia-conduction-global", "Conduction and global aphasia", "vascular", ["gyrus-supramarginal", "area-broca", "area-wernicke", "insula", "artery-mca"], "left",
 "In conduction aphasia the patient speaks fluently with frequent phonemic slips that they notice and try to correct, understands well, but cannot repeat even short phrases, which is the giveaway. In global aphasia, after a large left middle cerebral artery infarct, speech is reduced to a few stereotyped syllables, comprehension is nearly absent, repetition is impossible, and there is a dense right hemiplegia with hemianopia.",
 [D("language", "n/a", "dominant perisylvian", "Conduction: fluent speech, good comprehension, repetition disproportionately impaired, phonemic paraphasias with self-correction", "gyrus-supramarginal"), D("language", "n/a", "dominant hemisphere", "Global: non-fluent output, poor comprehension, no repetition", "area-broca"), D("motor", "contralateral", "face, arm and leg", "Right hemiplegia in global aphasia", "pathway-lateral-corticospinal"), D("visual-field", "contralateral", "homonymous", "Right hemianopia in global aphasia", "pathway-visual")],
 "Repetition requires that the sound pattern decoded in Wernicke's area be passed forward to Broca's area for articulation, a route that runs through the arcuate fasciculus beneath the supramarginal gyrus and the insula. A lesion of the supramarginal gyrus or the underlying white matter disconnects the two intact language areas: comprehension and fluent production survive, but the transfer fails, so repetition collapses and the patient produces phonemic errors that their intact monitoring detects. Global aphasia is the sum of Broca and Wernicke aphasias, produced when the middle cerebral artery stem is occluded and the whole perisylvian region infarcts; because the infarct also takes the internal capsule and optic radiation, whose fibers serve the opposite side of the body and visual field after crossing in the brainstem and chiasm, the language loss is accompanied by contralateral hemiplegia and hemianopia. Both syndromes are uncrossed at the cortical level and reflect left hemisphere dominance for language. Global aphasia without hemiparesis is a clue to two separate emboli, one anterior and one posterior, sparing the motor strip.",
 [pathol("Supramarginal gyrus infarct", "MRI", "Restricted diffusion in the left supramarginal gyrus and underlying arcuate fasciculus, sparing Broca's and Wernicke's areas.", sequence="DWI"), pathol("Complete MCA infarct", "MRI", "Extensive left perisylvian infarct involving frontal, temporal and parietal opercula and the deep nuclei.", sequence="DWI")],
 ["Left MCA branch embolus (conduction)", "Left MCA stem occlusion (global)", "Left perisylvian hemorrhage"],
 [("Wernicke aphasia", "Comprehension poor in Wernicke, good in conduction aphasia"), ("Anarthria or mutism", "Comprehension and writing preserved in pure anarthria"), ("Transcortical aphasias", "Repetition preserved")],
 ["Acute stroke treatment; global aphasia with M1 occlusion is a thrombectomy indication", "Speech therapy; prognosis of conduction aphasia is good, of global aphasia poor unless it evolves to Broca type", "Assess and support communication with gesture and picture boards"],
 [S8(290, 291), B7(54, 56)], marker=sphere(-50, -35, 30, 10), imagingHint=hint("axial", -50, -35, 30, "left supramarginal gyrus over the arcuate fasciculus"), preset="lateral-l"))

E.append(syn("syn-hemineglect", "Hemispatial neglect", "vascular", ["gyrus-supramarginal", "gyrus-angular", "lobe-parietal", "lobule-superior-parietal", "artery-mca-inferior-division"], "contralateral",
 "After a right hemisphere stroke, the patient ignores the left side of space: they eat from the right half of the plate, shave the right side of the face, bisect lines far to the right, and when asked to draw a clock crowd all the numbers on the right. They may deny that the left arm belongs to them, insist they are not weak, and, when touched on both sides, feel only the right. The head and eyes are turned to the right.",
 [D("neglect", "contralateral", "left hemispace and left body", "Visual, tactile and motor neglect with extinction on double simultaneous stimulation", "gyrus-supramarginal"), D("cognitive", "n/a", "right parietal", "Anosognosia and asomatognosia; constructional apraxia; dressing apraxia", "gyrus-angular"), D("oculomotor", "ipsilateral", "conjugate", "Gaze and head deviation toward the lesion", "frontal-eye-field"), D("motor", "contralateral", "arm and face", "Left hemiparesis when the infarct extends anteriorly", "pathway-lateral-corticospinal")],
 "The right inferior parietal lobule and the adjacent temporoparietal junction direct spatial attention to both halves of space, whereas the left parietal lobe attends mainly to the right; a right lesion therefore leaves nothing to attend to the left, while a left lesion is compensated by the right hemisphere and causes only mild, transient right neglect. This asymmetry, not any decussation, is why neglect is overwhelmingly a right hemisphere sign affecting the contralateral left side. Neglect is not a sensory loss: the visual pathways and somatosensory cortex may be intact, and the deficit is in awareness and orienting, which is why stimuli are perceived when presented alone but extinguished when a competing stimulus is presented on the right. Right frontal and thalamic lesions produce milder versions through the same network. The gaze deviation reflects the unopposed drive of the intact left frontal eye field, which pushes the eyes to the right, and the anosognosia and denial of the left arm belong to the same failure to represent the left side of the body and its state.",
 [pathol("Right MCA infarct", "MRI", "Restricted diffusion in the right supramarginal and angular gyri or the temporoparietal junction, often part of a larger MCA infarct.", sequence="DWI"), pathol("Right hemispheric hemorrhage or tumor", "CT", "Any right parietal mass lesion produces neglect; look for midline shift.", sequence="CT non-contrast")],
 ["Right MCA infarct (stem or inferior division)", "Right parietal hemorrhage", "Right frontal or thalamic infarct (milder)", "Tumor of the right parietal lobe"],
 [("Left homonymous hemianopia", "Hemianopic patients turn to compensate and are aware; neglect patients do not search and deny"), ("Left hemisensory loss", "Sensation is present when tested alone; extinction only with bilateral stimulation"), ("Global inattention or delirium", "No lateralized pattern")],
 ["Acute stroke treatment", "Neglect rehabilitation: prism adaptation, visual scanning training, approaching from the neglected side", "Fall prevention; neglect is a strong predictor of poor functional recovery"],
 [B7(53), B7(56)], marker=sphere(50, -45, 35, 12), imagingHint=hint("axial", 50, -45, 35, "right inferior parietal lobule"), preset="lateral-r", eponyms=["hemi-inattention"]))

E.append(syn("syn-anton", "Anton syndrome (cortical blindness with denial)", "vascular", ["cortex-calcarine", "lobe-occipital", "artery-pca"], "bilateral",
 "A patient who has suffered bilateral occipital infarcts, often after a basilar embolus or a cardiac arrest, walks into furniture and describes objects that are not there, yet insists that they can see, blaming the light or their glasses. The pupils react normally to light, the fundi are normal, and there is no blink to threat. The confabulated descriptions are the clue that the patient is unaware of the blindness.",
 [D("visual-acuity", "bilateral", "entire field", "Cortical blindness: no perception of light, normal pupils, absent blink to threat, preserved optokinetic response absent", "pathway-visual"), D("cognitive", "n/a", "bilateral occipital and parietal", "Anosognosia for blindness with visual confabulation", "cortex-calcarine"), D("cognitive", "n/a", "medial temporal", "Amnesia and agitation when the temporal branches are also involved", "hippocampus")],
 "Both calcarine cortices receive the crossed visual input from the contralateral hemifields, so bilateral destruction abolishes all conscious vision while the retina, optic nerves, chiasm, tracts and pretectal pupillary pathway remain intact; the pupils react because the pupillary light fibers leave the optic tract for the pretectum before reaching the geniculate and cortex. Both occipital lobes are supplied by the posterior cerebral arteries, which arise together from the basilar tip, so an embolus there or a period of profound hypotension affects both at once. The denial is thought to arise when the visual association cortex and its connections to the parietal and frontal monitoring systems are involved along with the primary cortex, so that the absence of visual input is not registered and the patient fills the gap with plausible confabulated scenes, much as a patient with neglect denies the left side. Preserved blink to threat or a startle to a bright light argues for some surviving cortex and a better prognosis.",
 [pathol("Bilateral occipital infarcts", "MRI", "Restricted diffusion in both calcarine cortices and lingual gyri, typically after a basilar tip embolus.", sequence="DWI"), pathol("Posterior reversible encephalopathy", "MRI", "Bilateral parieto-occipital vasogenic edema in hypertension or eclampsia, reversible cortical blindness.", sequence="FLAIR")],
 ["Basilar tip embolism with bilateral PCA occlusion", "Hypoperfusion after cardiac arrest", "Posterior reversible encephalopathy syndrome", "Bilateral occipital trauma"],
 [("Functional (non-organic) visual loss", "Normal imaging; optokinetic nystagmus present; patient is distressed, not indifferent"), ("Bilateral optic neuropathy", "Pupils sluggish or absent light reaction, abnormal fundi"), ("Balint syndrome", "Sees objects but cannot integrate a scene; visual acuity preserved")],
 ["Treat the cause (thrombectomy for basilar occlusion, blood pressure control in PRES)", "Safety measures for a patient who does not know they are blind", "Explain the denial to the family"],
 [B6(47), B6(51)], marker=sphere(0, -85, 5, 20), imagingHint=hint("axial", 0, -85, 5, "both calcarine cortices"), preset="posterior", eponyms=["Anton–Babinski syndrome"]))

E.append(syn("syn-balint", "Balint syndrome", "vascular", ["lobule-superior-parietal", "lobe-parietal", "lobe-occipital", "territory-watershed"], "bilateral",
 "The patient can read individual letters but not a word, describes one object in a picture while missing the scene, cannot reach accurately for a cup that they see, and cannot shift their gaze voluntarily to a new target even though their eyes move freely at random. Acuity and fields may be normal or show lower quadrant defects. The syndrome typically follows bilateral hypotensive watershed infarcts or posterior cortical atrophy.",
 [D("visual-acuity", "bilateral", "dorsal stream", "Simultanagnosia: perceives only one object at a time", "lobule-superior-parietal"), D("oculomotor", "bilateral", "voluntary saccades", "Ocular apraxia (psychic paralysis of gaze): cannot direct gaze voluntarily", "frontal-eye-field"), D("cerebellar", "bilateral", "reaching", "Optic ataxia: misreaching for seen targets with an otherwise coordinated arm", "lobule-superior-parietal")],
 "The dorsal visual stream runs from the occipital lobe up into the superior parietal lobule of each hemisphere and computes where objects are in space, guiding the eyes and hands toward them. Each hemisphere handles the contralateral field, but bilateral damage is needed for the full syndrome, because one intact parietal lobe can crudely cover both sides. The bilateral parieto-occipital cortex lies in the posterior watershed zone between middle and posterior cerebral territories, so the usual cause is a global drop in perfusion. Ventral stream areas in the occipitotemporal cortex are spared, which is why single objects and letters are still recognized: the failure is in binding several objects into a scene (simultanagnosia), in using visual information to program saccades (ocular apraxia, distinct from the motor palsy of a brainstem gaze center lesion) and in using it to program reaching (optic ataxia, distinct from cerebellar ataxia because reaching to a sound or to the patient's own body is accurate). Nothing crosses at this level; the syndrome is bilateral cortical, and the contralateral field defects, when present, come from the adjacent optic radiations.",
 [pathol("Bilateral parieto-occipital infarcts", "MRI", "Symmetric restricted diffusion or established infarcts in the posterior watershed zones of both hemispheres.", sequence="DWI"), pathol("Posterior cortical atrophy", "MRI", "Bilateral parieto-occipital atrophy with a progressive course in an Alzheimer variant.", sequence="T1")],
 ["Bilateral watershed infarcts after hypotension", "Posterior cortical atrophy (Alzheimer disease)", "Posterior reversible encephalopathy syndrome", "Bilateral PCA–MCA borderzone embolism"],
 [("Bilateral hemianopia / cortical blindness", "Fields are absent; Balint patients see objects but cannot integrate them"), ("Cerebellar ataxia", "Reaching to non-visual targets is also inaccurate"), ("Neglect", "Unilateral; Balint is bilateral and symmetric")],
 ["Treat the cause", "Occupational therapy with verbal and tactile cues to replace visual guidance", "Safety supervision for walking and cooking"],
 [B6(47), B6(50)], marker=sphere(0, -65, 45, 20), imagingHint=hint("axial", 0, -65, 45, "bilateral superior parietal lobules"), preset="superior", eponyms=["Balint–Holmes syndrome"]))

E.append(syn("syn-alexia-without-agraphia", "Alexia without agraphia", "vascular", ["cortex-calcarine", "corpus-callosum", "lobe-occipital", "artery-pca", "gyrus-angular"], "left",
 "A patient writes a sentence at the examiner's request and then, a minute later, cannot read what they have written, although they can spell words aloud, understand spoken language and copy letters slowly stroke by stroke. They have a right homonymous hemianopia and often cannot name colors. The combination follows a left posterior cerebral artery infarct that included the splenium of the corpus callosum.",
 [D("cognitive", "n/a", "left occipital plus splenium", "Pure alexia: cannot read words, may read letter by letter; writing and spelling intact", "corpus-callosum"), D("visual-field", "contralateral", "homonymous", "Right homonymous hemianopia", "pathway-visual"), D("cognitive", "n/a", "left occipitotemporal", "Color anomia; sometimes object agnosia", "cortex-calcarine")],
 "Reading requires that visual word forms reach the language areas of the left hemisphere. After a left occipital infarct the left visual cortex is gone, so the right visual field is blind (the fibers from each retina's nasal half cross in the chiasm, so the left calcarine cortex sees the right hemifield). Words can still be seen in the left visual field by the right occipital lobe, but for them to be read the information must cross to the left angular gyrus through the splenium of the corpus callosum. When the same infarct, supplied by the posterior cerebral artery, also destroys the splenium, the intact right visual cortex is disconnected from the language hemisphere: the patient sees the word but cannot read it. Writing, which arises in the left angular gyrus and frontal cortex without needing visual input, is preserved, as is spelling aloud and recognizing words spelled to them. Color anomia has the same disconnection basis, since color perception in the right occipital lobe cannot reach the left naming areas. The syndrome is a disconnection, not a cortical language deficit, and the crossing structure involved is the callosum rather than any brainstem decussation.",
 [pathol("Left PCA infarct with splenial extension", "MRI", "Restricted diffusion in the left calcarine cortex and lingual gyrus extending into the splenium of the corpus callosum.", sequence="DWI"), pathol("Splenial tumor", "MRI", "Enhancing mass of the splenium and left occipital lobe (glioma, lymphoma) producing progressive alexia.", sequence="T1+Gd")],
 ["Left posterior cerebral artery infarct", "Splenial hemorrhage or tumor", "Posterior cortical atrophy"],
 [("Alexia with agraphia", "Writing also impaired; lesion in the left angular gyrus"), ("Hemianopic dyslexia", "Reads slowly because of the field defect but can read when text is placed in the intact field"), ("Aphasic alexia", "Reading loss is part of a broader aphasia")],
 ["Acute stroke treatment", "Reading rehabilitation: letter-by-letter and tactile letter-tracing strategies", "Field defect counseling and driving restriction"],
 [B6(50), B7(54)], marker=sphere(-12, -75, 10, 14), imagingHint=hint("axial", -12, -75, 10, "left calcarine cortex and splenium"), preset="medial-l", eponyms=["pure alexia", "pure word blindness"]))

write(E)
