import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).parent))
from synlib import *
E = []
S11 = lambda a, b=None: C("snell", 11, a, b)
B6 = lambda a, b=None: C("berkowitz", 6, a, b)
B10 = lambda a, b=None: C("berkowitz", 10, a, b)
B12 = lambda a, b=None: C("berkowitz", 12, a, b)
B13 = lambda a, b=None: C("berkowitz", 13, a, b)
B14 = lambda a, b=None: C("berkowitz", 14, a, b)

E.append(syn("syn-jugular-foramen-vernet", "Jugular foramen syndrome (Vernet)", "neoplastic", ["cn-09-glossopharyngeal", "cn-10-vagus", "cn-11-accessory", "nucleus-ambiguus", "sinus-transverse-sigmoid"], "ipsilateral",
 "The patient has become hoarse, chokes on liquids and has lost the ability to shrug one shoulder; the examiner finds that the palate lifts only on one side with the uvula pulled toward the healthy side, the gag is absent on the affected side, the sternocleidomastoid and upper trapezius are wasted, and taste and sensation are gone from the back of the tongue. Pulsatile tinnitus and a red mass behind the eardrum point to a glomus tumor.",
 [D("bulbar", "ipsilateral", "palate, pharynx, larynx", "Palatal droop, uvula deviates to the intact side, dysphagia, hoarseness with vocal cord paralysis, absent gag", "nucleus-ambiguus"), D("sensory-light-touch", "ipsilateral", "posterior tongue, pharynx", "Loss of taste and sensation on the posterior third of the tongue and pharynx", "cn-09-glossopharyngeal"), D("motor", "ipsilateral", "sternocleidomastoid and trapezius", "Weak head turning to the opposite side and shoulder shrug; shoulder droop", "cn-11-accessory"), D("auditory", "ipsilateral", "ear", "Pulsatile tinnitus and conductive hearing loss with glomus jugulare tumors", "sinus-transverse-sigmoid")],
 "The glossopharyngeal, vagus and accessory nerves leave the skull together through the jugular foramen alongside the jugular bulb, so a lesion at the foramen paralyzes all three on the same side; these are uncrossed lower motor neuron and sensory pathways, and every sign is ipsilateral. The vagus supplies the palate, pharynx and larynx through the pharyngeal plexus and the laryngeal nerves, so the palate on the affected side fails to lift and the uvula is drawn toward the intact side by the working muscles, the vocal cord lies in the paramedian position and the pharynx does not clear, hence hoarseness and aspiration. The glossopharyngeal nerve carries sensation and taste from the posterior tongue and is the afferent limb of the gag, which is therefore absent when the affected side is stimulated. The spinal accessory nerve, which has climbed through the foramen magnum to leave with them, supplies the sternocleidomastoid that turns the head to the opposite side and the trapezius that shrugs the shoulder. If the hypoglossal nerve, which exits through the neighboring hypoglossal canal, is added, the syndrome becomes Collet–Sicard, and involvement of the sympathetic chain below the skull base adds a Horner (Villaret): the combination maps the lesion's extent along the skull base. A nuclear lesion in the medulla would add crossed long-tract signs and spare the accessory nerve's spinal root.",
 [pathol("Glomus jugulare paraganglioma", "MRI", "Avidly enhancing mass expanding the jugular foramen with a 'salt and pepper' appearance from flow voids; permeative bone destruction on CT.", sequence="T1+Gd"), pathol("Schwannoma or meningioma of the foramen", "MRI", "Smooth enlargement of the foramen with an enhancing mass; meningiomas show a dural tail and sclerosis.", sequence="T1+Gd"), pathol("Skull base metastasis or nasopharyngeal carcinoma", "CT", "Destructive lesion of the jugular foramen and petrous bone.", sequence="CT contrast")],
 ["Glomus jugulare tumor", "Schwannoma of IX, X or XI", "Meningioma", "Skull base metastasis or nasopharyngeal carcinoma", "Jugular vein thrombosis or internal carotid dissection", "Skull base fracture"],
 [("Medullary infarct (Wallenberg)", "Crossed sensory loss, Horner and ataxia; spinal accessory spared"), ("Vagal palsy alone", "Palatal and laryngeal signs without tongue sensory loss or shoulder weakness"), ("Myasthenia gravis", "Bilateral fatigable bulbar weakness")],
 ["Contrast MRI of the skull base with CT for bone; catheter angiography if a glomus tumor is suspected", "Swallow assessment; laryngoscopy for cord position", "Surgery or radiotherapy according to tumor type"],
 [S11(343, 346), S11(355), B14(126)], marker=sphere(-30, -30, -40, 10), imagingHint=hint("axial", -30, -30, -40, "jugular foramen at the skull base"), preset="inferior", eponyms=["Vernet syndrome", "Collet–Sicard (with XII)", "Villaret (with Horner)"]))

E.append(syn("syn-hypoglossal-palsy", "Hypoglossal nerve palsy", "neoplastic", ["cn-12-hypoglossal", "hypoglossal-nucleus", "artery-internal-carotid", "level-medulla-olive"], "ipsilateral",
 "On protrusion the tongue deviates toward one side, and that half of the tongue is wasted and ripples with fasciculations. The patient has mild slurring of lingual consonants and difficulty moving food around the mouth. In a young patient with neck pain and a Horner syndrome the cause is a carotid dissection pressing on the nerve; in an older patient a skull base tumor; bilateral involvement with a brisk jaw jerk means motor neuron disease.",
 [D("cranial-nerve", "ipsilateral", "half of the tongue", "Tongue deviates toward the lesion on protrusion; atrophy and fasciculation (lower motor neuron)", "cn-12-hypoglossal"), D("bulbar", "n/a", "speech and swallowing", "Mild lingual dysarthria and difficulty manipulating food", "cn-12-hypoglossal"), D("autonomic", "ipsilateral", "eye (with carotid lesions)", "Horner syndrome when the carotid sheath is involved", "pathway-oculosympathetic")],
 "The hypoglossal nucleus in the medulla and its nerve supply the intrinsic and extrinsic muscles of the ipsilateral half of the tongue. Protrusion is performed by the two genioglossus muscles pushing the tongue forward and toward the opposite side, so when one is paralyzed the intact muscle pushes the tongue toward the weak side: the tongue points to the lesion in a lower motor neuron palsy. Wasting and fasciculation confirm that the lesion is nuclear or infranuclear. The nucleus receives corticobulbar input mainly from the contralateral hemisphere, so a capsular stroke produces deviation away from the lesion without atrophy and with associated face and arm weakness on the same side as the tongue deviation. The nerve leaves through the hypoglossal canal and descends in the neck between the internal carotid artery and the internal jugular vein before turning forward over the carotid bifurcation, which is why carotid dissection, carotid endarterectomy and tumors of the carotid space are the commonest peripheral causes and why a Horner syndrome from the sympathetic plexus often accompanies them. A nuclear lesion in the medial medulla adds contralateral hemiparesis and proprioceptive loss (Dejerine). Bilateral lower motor neuron tongue weakness with upper motor neuron limb signs is the hallmark of amyotrophic lateral sclerosis.",
 [pathol("Carotid dissection", "MRA", "Crescentic intramural hematoma in the upper cervical internal carotid artery on fat-saturated T1, with luminal narrowing.", sequence="T1"), pathol("Skull base tumor", "MRI", "Enhancing lesion of the hypoglossal canal or clivus (chordoma, metastasis, meningioma, glomus); CT shows canal widening or erosion.", sequence="T1+Gd"), pathol("Denervation of the tongue", "MRI", "Fatty atrophy and T2 hyperintensity of one half of the tongue on axial images, a useful sign of a chronic lesion.", sequence="T2")],
 ["Internal carotid artery dissection", "Skull base tumor or metastasis", "Carotid endarterectomy or neck surgery", "Medial medullary infarct", "Motor neuron disease (bilateral)", "Radiotherapy to the neck"],
 [("Upper motor neuron tongue weakness", "Deviates away from a hemispheric lesion, no atrophy or fasciculation, associated hemiparesis"), ("Facial palsy", "Apparent tongue deviation from the asymmetric mouth; check with the lips held symmetric"), ("Pseudobulbar palsy", "Spastic, slow tongue without wasting; brisk jaw jerk")],
 ["MRI of the medulla, skull base and neck with MRA of the carotid", "Speech therapy; most dissection-related palsies recover", "Look for fasciculations and limb signs to exclude motor neuron disease"],
 [S11(353), B14(128)], marker=nerve("cn-12-hypoglossal-l"), imagingHint=hint("axial", -12, -35, -50, "hypoglossal nucleus and nerve in the medulla; canal at the skull base"), preset="inferior"))

E.append(syn("syn-bulbar-vs-pseudobulbar", "Bulbar versus pseudobulbar palsy", "degenerative", ["nucleus-ambiguus", "hypoglossal-nucleus", "facial-motor-nucleus", "internal-capsule", "corona-radiata", "gyrus-precentral"], "bilateral",
 "Two patients cannot swallow or speak clearly. The first has a flaccid, wasted, fasciculating tongue, a nasal voice, an absent gag and an absent jaw jerk: bulbar palsy, the lower motor neurons of the medulla have died. The second has a small, spastic tongue that cannot be protruded, strangled slow speech, an exaggerated gag and jaw jerk, and laughs or cries without feeling either: pseudobulbar palsy, the corticobulbar tracts have been cut on both sides.",
 [D("bulbar", "bilateral", "tongue, palate, pharynx, larynx", "Bulbar: flaccid dysarthria, nasal regurgitation, wasted fasciculating tongue, absent gag and jaw jerk", "nucleus-ambiguus"), D("bulbar", "bilateral", "same muscles", "Pseudobulbar: spastic dysarthria, dysphagia, small spastic tongue, brisk gag and jaw jerk", "pathway-corticobulbar"), D("cognitive", "n/a", "limbic-brainstem connections", "Pseudobulbar affect: involuntary laughing and crying", "pathway-corticobulbar"), D("motor", "bilateral", "limbs (ALS)", "Mixed upper and lower motor neuron limb signs when the cause is motor neuron disease", "pathway-lateral-corticospinal")],
 "The muscles of the tongue, palate, pharynx and larynx are driven by lower motor neurons in the hypoglossal nucleus and nucleus ambiguus of the medulla (the 'bulb'), and those neurons in turn receive corticobulbar input from both hemispheres, crossed and uncrossed. Destruction of the medullary nuclei or their nerves gives a lower motor neuron picture of flaccid weakness with wasting, fasciculation and loss of the reflexes whose efferent limb they form; the bilateral cortical input is irrelevant once the final pathway is gone. Because the corticobulbar projection is bilateral, a lesion of the tract on one side causes little more than transient dysarthria; a pseudobulbar palsy requires both corticobulbar tracts to be interrupted, typically by successive lacunar strokes in the two internal capsules or the pons, by bilateral demyelination, or by the upper motor neuron degeneration of amyotrophic lateral sclerosis. The muscles are then weak but spastic, the jaw jerk and gag are exaggerated because the brainstem reflex arcs are released from cortical inhibition, and the loss of cortical control over the brainstem circuits that generate laughing and crying produces the emotional incontinence. In motor neuron disease both mechanisms coexist, giving a wasted fasciculating tongue with a brisk jaw jerk, a combination that is diagnostic.",
 [pathol("Bilateral capsular or pontine lacunes", "MRI", "Multiple old lacunar infarcts in both internal capsules, corona radiata or basis pontis with confluent white matter disease.", sequence="FLAIR"), pathol("Amyotrophic lateral sclerosis", "MRI", "Symmetric corticospinal tract T2 hyperintensity and precentral hypointensity on SWI; tongue atrophy; medulla otherwise normal.", sequence="FLAIR"), pathol("Medullary lesion", "MRI", "Infarct, syrinx, tumor or demyelination involving the nucleus ambiguus and hypoglossal nucleus.", sequence="T2")],
 ["Motor neuron disease (both)", "Bilateral strokes (pseudobulbar)", "Multiple sclerosis (pseudobulbar)", "Brainstem tumor, syringobulbia, Guillain–Barré, myasthenia, polio (bulbar)"],
 [("Myasthenia gravis", "Fatigable bulbar weakness without wasting or reflex change; ptosis; antibody positive"), ("Oculopharyngeal muscular dystrophy or myopathy", "Ptosis and dysphagia with a family history; no fasciculation, normal reflexes"), ("Kennedy disease", "Slowly progressive lower motor neuron bulbar and limb weakness in men with gynecomastia")],
 ["Swallow assessment and aspiration precautions; gastrostomy when oral intake becomes unsafe", "Assess respiration in bulbar motor neuron disease", "Dextromethorphan-quinidine or antidepressants for pseudobulbar affect"],
 [B13(119), B13(121), C("berkowitz", 29, 289)], marker=structs("brainstem"), imagingHint=hint("axial", 0, -40, -48, "medullary motor nuclei"), preset="anterior"))

E.append(syn("syn-vagal-palsy", "Vagus nerve palsy", "neoplastic", ["cn-10-vagus", "nucleus-ambiguus", "dorsal-motor-nucleus-vagus", "artery-internal-carotid"], "ipsilateral",
 "A patient becomes hoarse with a breathy voice and a weak cough, and regurgitates fluid through the nose when drinking. On saying 'ah' the palate rises only on one side and the uvula swings toward the good side; laryngoscopy shows one vocal cord lying still in the paramedian position. A palsy of the recurrent laryngeal branch alone spares the palate and pharynx and points to the chest or thyroid.",
 [D("bulbar", "ipsilateral", "soft palate", "Palatal weakness with nasal speech and regurgitation; uvula deviates to the intact side", "cn-10-vagus"), D("bulbar", "ipsilateral", "vocal cord", "Hoarseness, breathy voice, weak cough; paramedian cord paralysis", "nucleus-ambiguus"), D("bulbar", "ipsilateral", "pharynx", "Dysphagia and pooling on the affected side; reduced gag", "cn-10-vagus"), D("autonomic", "n/a", "heart and gut", "Tachycardia and gastric atony are rare with unilateral lesions", "dorsal-motor-nucleus-vagus")],
 "The vagus carries the motor fibers from the nucleus ambiguus to the palate, pharynx and larynx of its own side, sensation from the pharynx, larynx and external ear, and the parasympathetic outflow from the dorsal motor nucleus to the thoracic and abdominal viscera. It is an uncrossed peripheral nerve, so a palsy is ipsilateral: the levator veli palatini fails on that side and the intact side pulls the uvula across, the pharyngeal constrictors do not clear the bolus and the vocal cord is paralyzed. Where the lesion lies is read from which branches are affected. A lesion at the skull base, in the jugular foramen, or high in the neck involves the pharyngeal branch, the superior laryngeal nerve and the recurrent laryngeal nerve together, so palate, pharynx and larynx are all weak, usually with the neighboring ninth and eleventh nerves. A lesion in the chest or the lower neck, at the aortic arch on the left or the subclavian artery on the right where the recurrent laryngeal nerves loop, or in the thyroid, catches only the recurrent nerve, paralyzing the cord while the palate lifts normally; the left nerve's longer course under the aortic arch makes left-sided cord palsy from mediastinal tumors the commonest pattern. A nuclear lesion in the medulla adds the crossed signs of the lateral medullary syndrome. Bilateral cord palsies cause stridor and are an airway emergency.",
 [pathol("Skull base or carotid space lesion", "MRI", "Enhancing mass at the jugular foramen or along the carotid sheath; look for denervation atrophy of the pharyngeal constrictors and cord.", sequence="T1+Gd"), pathol("Mediastinal tumor (recurrent laryngeal nerve)", "CT", "Left hilar or aortopulmonary window mass, or thyroid mass, in a patient with isolated cord palsy.", sequence="CT contrast"), pathol("Lateral medullary infarct", "MRI", "Dorsolateral medullary restricted diffusion including the nucleus ambiguus.", sequence="DWI")],
 ["Lateral medullary infarct", "Jugular foramen tumor", "Carotid dissection or surgery", "Thyroid surgery, mediastinal and lung tumors (recurrent laryngeal)", "Guillain–Barré, diphtheria (bilateral)"],
 [("Myasthenia gravis", "Bilateral, fatigable, with ptosis"), ("Laryngeal disease", "Cords move; hoarseness from a mass or inflammation on laryngoscopy"), ("Functional dysphonia", "Normal cord movement on coughing")],
 ["Laryngoscopy to document the cord and swallow assessment", "Imaging from the medulla to the mediastinum for an isolated recurrent laryngeal palsy", "Cord medialization procedures for persistent aspiration or dysphonia"],
 [S11(353), B14(126)], marker=nerve("cn-10-vagus-l"), imagingHint=hint("axial", -30, -30, -40, "vagus at the jugular foramen"), preset="inferior"))

E.append(syn("syn-optic-neuritis", "Optic neuritis", "demyelinating", ["cn-02-optic", "optic-chiasm", "lateral-geniculate-nucleus"], "ipsilateral",
 "A young woman notices that vision in one eye has become blurred and dim over two or three days, colors look washed out, and the eye aches when she moves it. Acuity is reduced, there is a central scotoma, the pupil on that side responds less briskly to light than the other (a relative afferent pupillary defect), and the disc is normal in two-thirds of cases or mildly swollen in the rest. Vision recovers over weeks, but the episode may be the first sign of multiple sclerosis.",
 [D("visual-acuity", "ipsilateral", "one eye", "Reduced acuity and color vision with a central or cecocentral scotoma", "cn-02-optic"), D("pupil", "ipsilateral", "afferent", "Relative afferent pupillary defect", "pathway-pupillary-light-reflex"), D("pain", "ipsilateral", "orbit", "Pain on eye movement from traction on the inflamed nerve sheath at the orbital apex", "cn-02-optic"), D("visual-acuity", "ipsilateral", "recovered eye", "Persisting desaturation of red and Uhthoff phenomenon (blurring with heat or exercise)", "cn-02-optic")],
 "Each optic nerve carries the axons of all the ganglion cells of one retina, so a lesion in front of the chiasm produces a monocular deficit, and because the light reflex afferents travel in the same nerve, the pupil of the affected eye constricts less when light swings onto it (the pathway is uncrossed up to the chiasm, so the deficit is strictly ipsilateral), while both pupils stay equal in size because the efferent pathways are intact and bilateral: the relative afferent pupillary defect is the objective sign of a unilateral prechiasmal lesion. Inflammation and demyelination of the nerve, usually behind the disc (retrobulbar), block conduction in the papillomacular bundle first, which is why central vision and color suffer most. The nerve is a tract of the central nervous system with oligodendrocyte myelin and is attacked by the same process that produces multiple sclerosis elsewhere; the risk of MS after a first episode depends largely on whether the brain MRI already shows demyelinating lesions. The recovered nerve conducts slowly, which shows as a delayed visual evoked potential and as Uhthoff's phenomenon when a rise in temperature blocks marginal conduction. Bilateral, severe, poorly recovering or recurrent optic neuritis, especially with a long lesion on MRI, raises neuromyelitis optica spectrum disorder or MOG antibody disease instead, where the treatment and prognosis differ.",
 [pathol("Optic neuritis", "MRI", "T2 hyperintensity and gadolinium enhancement of a short segment of the intraorbital optic nerve on fat-suppressed coronal images.", sequence="T1+Gd"), pathol("Multiple sclerosis", "MRI", "Periventricular, juxtacortical, infratentorial or spinal cord demyelinating lesions on brain and cord MRI that determine the risk and diagnosis.", sequence="FLAIR"), pathol("Neuromyelitis optica spectrum", "MRI", "Long, bilateral or chiasmal optic nerve enhancement with longitudinally extensive transverse myelitis.", sequence="T1+Gd")],
 ["Multiple sclerosis or clinically isolated syndrome", "Neuromyelitis optica spectrum disorder (aquaporin-4)", "MOG antibody-associated disease", "Infectious and parainfectious (syphilis, Lyme, viral)", "Sarcoidosis"],
 [("Anterior ischemic optic neuropathy", "Older patient, painless, altitudinal defect, pale swollen disc; check ESR for giant cell arteritis"), ("Leber hereditary optic neuropathy", "Young man, sequential painless bilateral loss, no recovery"), ("Compressive optic neuropathy", "Slowly progressive, no pain, no recovery; mass on MRI")],
 ["MRI of the brain and orbits with contrast; serum aquaporin-4 and MOG antibodies if atypical", "High-dose intravenous methylprednisolone hastens recovery; oral low-dose steroids alone are avoided", "Discuss disease-modifying therapy when MRI shows MS lesions"],
 [B6(48, 49), C("berkowitz", 21, 224, 227)], marker=nerve("optic-nerve-l"), imagingHint=hint("axial", -25, 30, -10, "intraorbital optic nerve"), preset="anterior"))

E.append(syn("syn-chiasmal-bitemporal", "Chiasmal syndrome (bitemporal hemianopia)", "compressive", ["optic-chiasm", "pituitary-infundibulum", "cn-02-optic", "hypothalamus"], "bilateral",
 "The patient keeps bumping into door frames and has stopped driving because cars appear from nowhere on either side, yet reads normally. Field testing shows loss of the temporal half of the field in each eye, respecting the vertical meridian, worse in the upper quadrants. There may be amenorrhea, galactorrhea, acromegalic features or the fatigue of hypopituitarism, and a large adenoma is found on MRI. Sudden headache and visual loss with ophthalmoplegia mean pituitary apoplexy.",
 [D("visual-field", "bilateral", "temporal fields of both eyes", "Bitemporal hemianopia respecting the vertical midline, upper quadrants first with lesions from below", "pathway-visual"), D("visual-acuity", "bilateral", "variable", "Acuity preserved unless the nerves are involved; junctional scotoma with anterior lesions", "cn-02-optic"), D("other", "n/a", "endocrine", "Hyperprolactinemia, acromegaly, Cushing features or hypopituitarism", "pituitary-infundibulum"), D("oculomotor", "ipsilateral", "cavernous sinus extension", "Ocular motor palsies with lateral extension or apoplexy", "sinus-cavernous")],
 "At the optic chiasm the fibers from the nasal half of each retina, which see the temporal half of the visual field, cross to the opposite optic tract, while the temporal retinal fibers, which see the nasal field, stay on the same side. A lesion of the middle of the chiasm interrupts only the crossing fibers, so each eye loses its temporal field and nothing else: the bitemporal hemianopia is the one field defect that is neither monocular nor homonymous, and it identifies the chiasm with certainty. The chiasm sits about a centimeter above the pituitary fossa, so a pituitary adenoma growing upward through the diaphragma sellae presses on its lower surface first, where the fibers from the inferior nasal retina cross, which serve the upper temporal fields; the defect therefore begins in the superior quadrants and descends. A craniopharyngioma pressing from above does the reverse. The lower nasal fibers make a forward loop (Wilbrand's knee) into the opposite optic nerve, so a lesion at the junction of one nerve and the chiasm causes a central scotoma in that eye with an upper temporal defect in the other, the junctional scotoma. Patients often have normal acuity and pass reading tests, because the intact nasal fields overlap in the center, but the two hemifields no longer overlap for depth perception, so they misjudge distances and cannot fuse images beyond the fixation point.",
 [pathol("Pituitary macroadenoma", "MRI", "Sellar mass with suprasellar extension elevating and flattening the chiasm; 'snowman' shape at the diaphragma; compare its signal with the normal gland.", sequence="T1+Gd"), pathol("Pituitary apoplexy", "MRI", "Hemorrhage or infarction in an adenoma with fluid levels and sudden chiasmal compression; hyperdense on CT.", sequence="T1"), pathol("Craniopharyngioma", "CT", "Suprasellar cystic and calcified mass in a child or an older adult compressing the chiasm from above.", sequence="CT non-contrast")],
 ["Pituitary adenoma", "Craniopharyngioma", "Suprasellar meningioma", "Internal carotid or anterior communicating aneurysm", "Optic chiasm glioma (neurofibromatosis 1)", "Chiasmal neuritis or sarcoidosis"],
 [("Bilateral optic neuropathy", "Defects do not respect the vertical meridian; acuity and color reduced"), ("Tilted discs or nasal retinal disease", "Temporal defects that cross the vertical meridian; fundus abnormal"), ("Bilateral homonymous defects", "Respect the vertical meridian but are homonymous, not bitemporal")],
 ["MRI of the sella with contrast and a full pituitary hormone panel including prolactin", "Dopamine agonists for prolactinomas; transsphenoidal surgery for other compressive adenomas", "Pituitary apoplexy: urgent steroids and neurosurgical review"],
 [S11(349, 350), B6(47, 49), C("berkowitz", 29, 260)], marker=structs("optic-chiasm"), imagingHint=hint("coronal", 0, 2, -18, "optic chiasm above the pituitary fossa"), preset="anterior"))

E.append(syn("syn-homonymous-hemianopia", "Homonymous hemianopia and its variants", "vascular", ["cn-02-optic", "lateral-geniculate-nucleus", "lobe-temporal", "lobe-parietal", "cortex-calcarine"], "contralateral",
 "The patient does not see things on one side, reads only half a line, and has been bumping into objects on that side. Confrontation shows loss of the same half of the visual field in both eyes. Whether the defect is a quadrant or a hemifield, whether the two eyes' defects match exactly, whether the macular region is spared and whether a pupil defect is present together tell the examiner where along the retrochiasmal pathway the lesion lies.",
 [D("visual-field", "contralateral", "same hemifield of both eyes", "Homonymous hemianopia; congruity increases as the lesion moves posteriorly", "pathway-visual"), D("visual-field", "contralateral", "upper quadrant", "Superior quadrantanopia from Meyer's loop in the temporal lobe", "lobe-temporal"), D("visual-field", "contralateral", "lower quadrant", "Inferior quadrantanopia from the parietal radiation", "lobe-parietal"), D("pupil", "contralateral", "afferent", "Relative afferent pupillary defect only with optic tract lesions", "pathway-pupillary-light-reflex")],
 "Behind the chiasm every structure carries the opposite half of the visual world from both eyes, because the crossed nasal fibers of one eye have joined the uncrossed temporal fibers of the other: a lesion of the optic tract, lateral geniculate body, optic radiation or occipital cortex therefore produces a homonymous defect in the contralateral field. Where along that pathway the lesion sits is read from four features. Congruity: in the tract the fibers from the two eyes are not yet aligned, so the defect differs between the eyes, whereas in the calcarine cortex corresponding points are precisely superimposed and the defects are identical. Pupils: the light reflex afferents leave the tract before the geniculate, so only a tract lesion produces a contralateral relative afferent pupillary defect. Shape: the radiation splits after the geniculate, the upper field fibers looping forward through the temporal lobe (Meyer's loop) and the lower field fibers passing through the parietal lobe, so temporal lesions give superior quadrant ('pie in the sky') and parietal lesions inferior quadrant defects, and geniculate lesions give sector defects from its dual blood supply. Macular sparing: the occipital pole receives collateral supply from the middle cerebral artery, so posterior cerebral infarcts often spare the central few degrees. Bilateral occipital lesions produce cortical blindness with normal pupils, and lesions of the occipital tip alone produce a homonymous central scotoma.",
 [pathol("Posterior cerebral artery infarct", "MRI", "Restricted diffusion in the calcarine cortex, the commonest cause of an isolated congruous hemianopia with macular sparing.", sequence="DWI"), pathol("Temporal or parietal lesion", "MRI", "Infarct, hemorrhage, tumor or resection cavity in the optic radiation; quadrantic defect matches the lobe.", sequence="FLAIR"), pathol("Optic tract lesion", "MRI", "Tumor, aneurysm or demyelination around the tract lateral to the hypothalamus; later 'bow-tie' atrophy of the contralateral disc.", sequence="T1+Gd")],
 ["Posterior cerebral artery infarct", "Middle cerebral artery infarct involving the radiation", "Intracerebral hemorrhage", "Tumor", "Temporal lobectomy (superior quadrantanopia)", "Demyelination"],
 [("Hemispatial neglect", "Patient does not search the neglected side but sees a stimulus presented alone; extinction on double stimulation"), ("Bitemporal hemianopia", "Different halves in each eye"), ("Functional visual loss", "Fields tubular or spiraling, inconsistent")],
 ["Formal perimetry to document the defect; imaging directed by the pattern", "Treat the cause; stroke care in most", "Reading and scanning rehabilitation; driving is usually prohibited with a complete hemianopia"],
 [S11(349, 350), B6(47, 51)], marker=structs("tract-optic-radiation-l"), imagingHint=hint("axial", -30, -60, 5, "optic radiation through the temporal and parietal lobes"), preset="lateral-l"))

E.append(syn("syn-rapd", "Relative afferent pupillary defect", "functional-pattern", ["cn-02-optic", "optic-chiasm", "pretectal-area"], "ipsilateral",
 "Both pupils are the same size and both constrict when a light is shone in either eye, but when the light is swung quickly from the good eye to the bad eye, the bad eye's pupil dilates instead of staying small, and when swung back to the good eye both constrict again. This paradoxical dilation is the relative afferent pupillary defect, the most reliable objective sign of a unilateral or asymmetric optic nerve lesion, present even when acuity is normal.",
 [D("pupil", "ipsilateral", "afferent limb", "Paradoxical dilation of the affected pupil on the swinging flashlight test; no anisocoria", "pathway-pupillary-light-reflex"), D("visual-acuity", "ipsilateral", "one eye", "Usually reduced acuity, color desaturation or a field defect in the same eye", "cn-02-optic"), D("visual-field", "contralateral", "homonymous (tract lesions)", "With an optic tract lesion, the RAPD is in the eye with the temporal field loss, contralateral to the lesion", "pathway-visual")],
 "The light reflex has a bilateral afferent input and a bilateral efferent output: light in one eye drives both pretectal nuclei through the crossed and uncrossed fibers of the chiasm, and each pretectal nucleus drives both Edinger–Westphal nuclei, so the direct and consensual responses are normally equal and the two pupils are always the same size. A lesion of one optic nerve reduces the signal from that eye but not the response of either pupil to the other eye, so the pupils remain equal, and the only way to expose the deficit is to compare the two afferent inputs directly by alternating the light between the eyes: when the light moves to the damaged eye the total drive to the pupils falls and both pupils dilate, which the examiner sees in the illuminated eye. This is why an RAPD never causes anisocoria, why it is graded by comparison rather than measured in absolute terms, and why it cannot be detected when both nerves are equally affected. Because the crossing nasal fibers outnumber the uncrossed temporal fibers, a lesion of one optic tract, which contains the crossed fibers of the contralateral eye and the uncrossed fibers of the ipsilateral eye, reduces the input from the contralateral eye more and produces a small RAPD in the eye opposite the lesion, together with a homonymous hemianopia. Lesions beyond the geniculate spare the pupil, so a hemianopia with an RAPD is a tract lesion. Dense cataract, corneal opacity or media disease do not produce an RAPD, since the light scattered through them still reaches the retina.",
 [pathol("Optic neuritis", "MRI", "Enhancing segment of the optic nerve on fat-suppressed orbital images.", sequence="T1+Gd"), pathol("Compressive optic neuropathy", "MRI", "Meningioma, glioma or orbital mass along the nerve; canal narrowing on CT.", sequence="T1+Gd"), pathol("Optic tract lesion", "MRI", "Lesion of the tract lateral to the hypothalamus with a contralateral hemianopia.", sequence="FLAIR")],
 ["Optic neuritis", "Ischemic optic neuropathy", "Compressive optic neuropathy", "Glaucoma with asymmetric damage", "Large retinal detachment or central retinal artery or vein occlusion", "Optic tract lesion"],
 [("Hippus", "Rhythmic oscillation of both pupils unrelated to the side of illumination"), ("Anisocoria of any cause", "An efferent problem; the RAPD test compares constriction, not size"), ("Dense media opacity", "Does not produce an RAPD")],
 ["Perform the swinging flashlight test in every patient with unexplained visual loss or a suspected optic neuropathy", "An RAPD with normal acuity and fundus still requires optic nerve imaging", "Grade with neutral density filters when quantification is needed"],
 [B10(83, 85)], marker=nerve("optic-nerve-l"), imagingHint=hint("axial", -20, 20, -12, "optic nerve from the globe to the chiasm"), preset="anterior", eponyms=["Marcus Gunn pupil"]))

E.append(syn("syn-argyll-robertson", "Argyll Robertson pupils", "infectious", ["pretectal-area", "oculomotor-nucleus", "level-midbrain-superior-colliculus"], "bilateral",
 "Both pupils are small and irregular and do not constrict to even the brightest light, but they constrict promptly when the patient looks at a near target and redilate slowly afterward. Vision is normal and there is no ptosis. The patient may have absent ankle reflexes, lightning pains and a sensory ataxia from tabes dorsalis; the finding was classically a sign of late neurosyphilis and today prompts serological testing.",
 [D("pupil", "bilateral", "both pupils", "Small, irregular pupils that fail to react to light but constrict to near (light-near dissociation)", "pathway-pupillary-light-reflex"), D("visual-acuity", "bilateral", "spared", "Normal acuity and fields; the afferent visual pathway is intact", "pathway-visual"), D("sensory-vibration-proprioception", "bilateral", "legs (tabes)", "Sensory ataxia, absent reflexes and Charcot joints when tabes dorsalis coexists", "pathway-dcml")],
 "The light reflex and the near reflex share the same final pathway from the Edinger–Westphal nucleus through the oculomotor nerve and the ciliary ganglion to the sphincter pupillae, but they reach the nucleus by different routes: the light reflex arrives from the pretectal nuclei, which lie dorsally beneath the posterior commissure and receive bilateral retinal input, whereas the near response is driven from the cortex by fibers descending more ventrally in the midbrain tegmentum. A lesion of the periaqueductal region that damages the pretectal nuclei or their bilateral connections to the Edinger–Westphal nuclei abolishes the light reaction of both pupils while leaving the near reaction intact: light-near dissociation. The pupils are small because the same periaqueductal process is thought to interrupt the supranuclear inhibitory fibers that normally hold the Edinger–Westphal neurons in check, and irregular because of chronic iris damage. Both pupils are involved because the pretectal connections are bilateral and the lesion is midline; there is no ipsilateral or contralateral pattern. Vision is normal because the retinogeniculate fibers to the lateral geniculate leave the tract before the pretectum. The same dissociation with large rather than small pupils occurs in the dorsal midbrain syndrome from a pineal tumor and in the Adie tonic pupil from ciliary ganglion damage with aberrant regeneration, so pupil size and reactivity speed separate the three.",
 [pathol("Neurosyphilis", "LP/CSF", "Positive serum treponemal test with CSF pleocytosis, raised protein and a reactive CSF VDRL.", sequence="n/a"), pathol("Tabes dorsalis", "MRI", "Atrophy and T2 hyperintensity of the posterior columns of the cord.", sequence="T2"), pathol("Dorsal midbrain lesion", "MRI", "Periaqueductal lesion (tumor, demyelination, infarct) when the syndrome is not syphilitic.", sequence="FLAIR")],
 ["Neurosyphilis (tabes dorsalis, general paresis)", "Diabetic autonomic neuropathy (pseudo-Argyll Robertson)", "Dorsal midbrain lesions", "Chronic alcoholism, sarcoidosis, Lyme (rare)"],
 [("Adie tonic pupil", "Usually unilateral, large, with slow tonic near response and denervation supersensitivity to dilute pilocarpine"), ("Parinaud syndrome", "Large pupils with up-gaze palsy and convergence-retraction nystagmus"), ("Pharmacologic miosis (opiates, pilocarpine)", "Both light and near responses reduced")],
 ["Serum treponemal serology and, if positive, lumbar puncture", "Intravenous penicillin for neurosyphilis; test for HIV", "Slit-lamp examination to distinguish iris disease"],
 [S11(357, 358), C("snell", 14, 408), B10(90)], marker=sphere(0, -28, -3, 6), imagingHint=hint("sagittal", 0, -28, -3, "pretectal region and periaqueductal gray"), preset="lateral-l"))

E.append(syn("syn-adie-tonic-pupil", "Adie tonic pupil", "functional-pattern", ["ganglion-ciliary", "cn-03-oculomotor"], "ipsilateral",
 "A young woman notices in the mirror that one pupil is larger than the other. In bright light the difference is obvious and the large pupil barely constricts; when she reads, that pupil slowly narrows and then stays small for a long time after she looks up again. Vision is normal apart from difficulty focusing at near. Her ankle reflexes are absent. There is no ptosis, no diplopia and no headache.",
 [D("pupil", "ipsilateral", "one pupil", "Dilated pupil with absent or segmental (vermiform) light reaction and slow tonic constriction to near with slow redilation", "ganglion-ciliary"), D("visual-acuity", "ipsilateral", "near vision", "Blurred near vision from tonic accommodation and ciliary muscle paresis", "ganglion-ciliary"), D("reflex", "bilateral", "ankles and knees", "Absent deep tendon reflexes in Holmes–Adie syndrome", "dorsal-root-ganglion")],
 "The ciliary ganglion in the orbit contains the postganglionic parasympathetic neurons for the sphincter pupillae and the ciliary muscle, and receives its preganglionic input from the Edinger–Westphal nucleus through the oculomotor nerve. Damage to the ganglion or the short ciliary nerves, usually a benign idiopathic denervation and occasionally viral or traumatic, removes the final pathway to the iris sphincter and ciliary muscle of that eye, so the pupil dilates, fails to react to light and accommodation is lost; the deficit is ipsilateral because the ganglion serves only its own eye. Over the following weeks the surviving fibers sprout. About thirty times more ganglion cells serve the ciliary muscle than the sphincter, so the regenerating fibers that reach the iris are mostly accommodative ones, and the sphincter comes to be driven by the near effort rather than by light: light-near dissociation with a slow, tonic near response and slow redilation, because the misdirected fibers fire tonically. The denervated sphincter also develops receptor supersensitivity, so dilute pilocarpine that does not affect the normal pupil constricts the tonic pupil, the diagnostic test. Segments of the iris still innervated produce the worm-like segmental contractions seen at the slit lamp. The associated areflexia, which makes it the Holmes–Adie syndrome, reflects a wider loss of peripheral neurons and is benign. Over years the pupil becomes small and the other eye may follow.",
 [pathol("Denervation supersensitivity", "MRI", "Imaging is normal; the diagnosis rests on constriction of the affected pupil to 0.125% pilocarpine with no effect on the normal pupil, so MRI is reserved for atypical cases.", sequence="n/a"), pathol("Orbital or ganglion lesion (atypical cases)", "MRI", "Orbital apex or ciliary ganglion lesion; imaging is reserved for painful or progressive cases.", sequence="T1+Gd")],
 ["Idiopathic (young women)", "Viral ganglionitis", "Orbital trauma or surgery", "Autonomic neuropathies (diabetes, amyloid, Sjögren)", "Paraneoplastic autonomic neuropathy"],
 [("Third nerve palsy", "Ptosis and ophthalmoplegia accompany the large pupil"), ("Pharmacologic mydriasis", "Fixed pupil that does not constrict to full-strength pilocarpine; history of exposure"), ("Argyll Robertson pupils", "Small, bilateral, brisk near response")],
 ["Confirm with dilute pilocarpine; reassure", "Reading glasses or low-dose pilocarpine for symptomatic accommodative loss", "Test the reflexes and consider autonomic evaluation if other autonomic symptoms are present"],
 [C("snell", 14, 408), C("snell", 14, 414), B10(87)], marker=structs("ciliary-ganglion-l"), imagingHint=hint("axial", -30, 35, -12, "ciliary ganglion behind the globe"), preset="anterior", eponyms=["Holmes–Adie syndrome"]))

E.append(syn("syn-bppv", "Benign paroxysmal positional vertigo", "otologic", ["cn-08-vestibulocochlear", "vestibular-nuclei", "flocculonodular-lobe"], "ipsilateral",
 "The patient wakes, rolls over in bed and the room spins violently for twenty seconds, then settles; the same thing happens when looking up to a shelf or bending to tie shoes. There is no hearing loss and no vertigo when still. The Dix–Hallpike test with the affected ear down reproduces the vertigo after a few seconds' latency, with a torsional upbeating nystagmus that fatigues and reverses on sitting up.",
 [D("vestibular", "ipsilateral", "posterior semicircular canal", "Brief positional vertigo with latency, torsional-upbeat nystagmus on Dix–Hallpike, fatigability", "cn-08-vestibulocochlear"), D("auditory", "n/a", "spared", "Normal hearing; no tinnitus", "pathway-auditory"), D("gait", "bilateral", "mild", "Mild unsteadiness between attacks; no ataxia", "pathway-vestibular-vor")],
 "Otoconia dislodged from the utricular macula fall into the posterior semicircular canal, the most dependent canal, where they float in the endolymph. When the head moves into the plane of that canal the debris sinks, dragging the endolymph and deflecting the cupula, which the brain interprets as sustained rotation in the plane of the canal; the deflection stops once the particles settle, hence the latency of a few seconds while the debris starts to move and the short duration. The posterior canal projects through the vestibular nerve and nuclei to the ipsilateral superior oblique and the contralateral inferior rectus, so the nystagmus is torsional toward the affected (lower) ear and upbeating, an exact fingerprint of the canal involved, and reverses when the patient sits up and the debris moves back. Repeating the maneuver disperses the debris, so the response fatigues, and the cerebellum suppresses it with repetition. The horizontal canal variant gives a horizontal geotropic or apogeotropic nystagmus on rolling in bed. The peripheral origin is confirmed by the latency, the brevity, the fatigability and the absence of any other neurological sign; positional nystagmus that is purely vertical, persistent, without latency or unfatigable points instead to the cerebellar nodulus or the fourth ventricle region, and requires imaging.",
 [pathol("Benign paroxysmal positional vertigo", "MRI", "Diagnosis is clinical by Dix–Hallpike or supine roll test; imaging is normal and unnecessary in typical cases.", sequence="n/a"), pathol("Central positional vertigo (mimic)", "MRI", "Nodular or fourth ventricular lesion (tumor, Chiari, demyelination) when nystagmus is downbeat, persistent or without latency.", sequence="FLAIR")],
 ["Idiopathic otolith degeneration (age)", "Head trauma", "After vestibular neuritis or prolonged bed rest", "Ménière disease (secondary)"],
 [("Central positional vertigo", "No latency, no fatigue, downbeat or direction-changing nystagmus, other signs"), ("Orthostatic hypotension", "Lightheadedness on standing, no spinning, no nystagmus"), ("Vestibular migraine", "Longer attacks with headache or photophobia; positional nystagmus atypical")],
 ["Epley (canalith repositioning) maneuver for the posterior canal; barbecue roll for the horizontal canal", "Avoid vestibular suppressants beyond a few days", "Image only when the pattern is atypical or repositioning fails repeatedly"],
 [B12(112, 114)], marker=nerve("cn-08-vestibulocochlear-l"), imagingHint=hint("axial", -40, -30, -30, "vestibular nerve entering the internal acoustic meatus"), preset="inferior"))

E.append(syn("syn-vestibular-neuritis", "Vestibular neuritis", "infectious", ["cn-08-vestibulocochlear", "vestibular-nuclei"], "ipsilateral",
 "Over a few hours a previously well adult develops continuous, severe rotatory vertigo with vomiting, and lies still because every head movement makes it worse. There is no hearing loss, no headache and no other neurological complaint. The eyes show a horizontal-torsional nystagmus beating away from one ear that increases on looking in the direction of the fast phase and is suppressed by fixation, and rapid head turning toward that ear produces a catch-up saccade. Symptoms settle over days to weeks.",
 [D("vestibular", "ipsilateral", "vestibular nerve (superior division)", "Acute prolonged vertigo with unidirectional horizontal-torsional nystagmus beating away from the lesion", "cn-08-vestibulocochlear"), D("vestibular", "ipsilateral", "vestibulo-ocular reflex", "Positive head impulse test toward the affected ear", "pathway-vestibular-vor"), D("gait", "ipsilateral", "trunk and gait", "Veering and falling toward the affected side; able to stand unaided", "pathway-vestibulospinal"), D("auditory", "n/a", "spared", "Normal hearing (labyrinthitis if hearing is lost)", "pathway-auditory")],
 "The two labyrinths send a balanced tonic discharge to the vestibular nuclei, and the brain reads any asymmetry between them as rotation. Inflammation of one vestibular nerve, an uncrossed peripheral nerve whose signs are therefore ipsilateral, usually its superior division which carries the horizontal and anterior canal and utricular afferents, silences one side, so the intact side's discharge is unopposed: the brain perceives rotation toward the healthy ear, the slow phase of the vestibulo-ocular reflex drives the eyes toward the lesion and the corrective fast phase beats away from it, and the vestibulospinal system tilts the body toward the lesion. The nystagmus follows Alexander's law, growing when gaze is directed toward the fast phase, is suppressed by visual fixation because the cerebellum can override a peripheral imbalance, and stays unidirectional whatever the direction of gaze: these three features separate a peripheral from a central lesion, along with the head impulse test, in which turning the head toward the dead labyrinth fails to generate the reflex eye movement and the patient makes a visible catch-up saccade. A normal head impulse test in a patient with acute vertigo is the alarming finding, because it means the reflex is intact and the vertigo is central. Recovery depends on cerebellar compensation, which requires movement, so vestibular suppressants are stopped early.",
 [pathol("Vestibular neuritis", "MRI", "Usually normal; occasionally enhancement of the vestibular nerve in the internal acoustic meatus. Imaging is done to exclude stroke when the examination is not clearly peripheral.", sequence="T1+Gd"), pathol("Stroke mimic", "MRI", "Restricted diffusion in the lateral medulla, cerebellar peduncle or inferior cerebellum; DWI may be falsely negative in the first 48 h for small posterior fossa infarcts.", sequence="DWI")],
 ["Presumed viral (herpes simplex reactivation) inflammation of the vestibular nerve", "Post-viral", "Labyrinthine ischemia in vasculopaths (with hearing loss)"],
 [("Cerebellar or lateral medullary stroke", "Normal head impulse, direction-changing or vertical nystagmus, skew deviation, inability to stand; HINTS 'central' pattern"), ("Labyrinthitis", "Same vertigo with acute hearing loss"), ("Vestibular migraine", "Recurrent, shorter, with migraine features"), ("Ménière disease", "Episodic, with fluctuating hearing loss and fullness")],
 ["Apply the HINTS examination; a central pattern or any other neurological sign requires urgent MRI", "Short course of antiemetics and vestibular suppressants, then early mobilization and vestibular rehabilitation", "Corticosteroids within 3 days may hasten recovery"],
 [B12(109, 112)], marker=nerve("cn-08-vestibulocochlear-l"), imagingHint=hint("axial", -40, -30, -30, "vestibular nerve in the internal acoustic meatus"), preset="inferior", eponyms=["vestibular neuronitis"]))

E.append(syn("syn-meniere", "Ménière disease", "otologic", ["cn-08-vestibulocochlear", "cochlear-nuclei", "vestibular-nuclei"], "ipsilateral",
 "A middle-aged patient describes attacks of spinning vertigo lasting from twenty minutes to several hours, preceded by a feeling of fullness in one ear, a roaring tinnitus and muffled hearing, with vomiting and unsteadiness during the attack. Between attacks hearing in that ear gradually declines, first for low tones and then across frequencies. Over years the vertigo burns out as the labyrinth is destroyed, leaving a deaf ear and occasional drop attacks.",
 [D("vestibular", "ipsilateral", "labyrinth", "Episodic vertigo of 20 minutes to 12 hours with peripheral-type nystagmus during attacks", "cn-08-vestibulocochlear"), D("auditory", "ipsilateral", "one ear", "Fluctuating then progressive low-frequency sensorineural hearing loss with aural fullness and tinnitus", "pathway-auditory"), D("gait", "bilateral", "drop attacks", "Tumarkin otolithic crises: sudden falls without loss of consciousness in late disease", "pathway-vestibulospinal")],
 "The membranous labyrinth is filled with endolymph, produced by the stria vascularis and absorbed in the endolymphatic sac. In Ménière disease absorption fails and endolymph accumulates, distending the cochlear duct and the saccule (endolymphatic hydrops). The distended membranes stretch the hair cells, and periodic ruptures or leaks mix potassium-rich endolymph with perilymph, depolarizing and temporarily paralyzing the hair cells and their nerve fibers; the sudden loss of one labyrinth's output creates an acute imbalance between the two sides, perceived as rotation with nystagmus initially toward and then away from the affected ear as the labyrinth first fires excessively and then fails. Because the cochlea and vestibular labyrinth share the same fluid, hearing and balance are affected together, and the low-frequency apex of the cochlea, where the duct is most distensible, suffers first, producing the characteristic low-tone loss and fullness. Each attack leaves a little permanent hair cell damage, so hearing declines stepwise and the vestibular function is eventually lost, at which point the vertigo stops. The disorder is peripheral and unilateral in most patients, with no central or crossed signs, and the length of the attacks separates it from the seconds of BPPV and the days of neuritis. About a third of patients eventually develop disease in the other ear.",
 [pathol("Endolymphatic hydrops", "MRI", "Delayed post-gadolinium 3D-FLAIR of the inner ear shows an enlarged non-enhancing endolymphatic space in the cochlea and vestibule; otherwise the MRI is normal.", sequence="FLAIR"), pathol("Exclusion of a retrocochlear lesion", "MRI", "Normal internal acoustic meatus and cerebellopontine angle; imaging is done once to exclude a schwannoma in any unilateral sensorineural loss.", sequence="T1+Gd")],
 ["Idiopathic endolymphatic hydrops", "Post-traumatic or post-infectious hydrops", "Autoimmune inner ear disease", "Otosclerosis and syphilis (rare secondary)"],
 [("Vestibular migraine", "Attacks with headache or photophobia; hearing preserved"), ("Vestibular schwannoma", "Progressive, non-fluctuating loss with poor discrimination; MRI"), ("BPPV", "Seconds-long positional attacks; hearing normal"), ("Transient ischemic attack of the labyrinth", "Vasculopath, brief, with other posterior circulation symptoms")],
 ["Audiometry and MRI to exclude a retrocochlear cause", "Salt restriction and a diuretic; vestibular suppressants during attacks", "Intratympanic steroids or gentamicin, or endolymphatic sac surgery, for intractable vertigo"],
 [S11(353), B12(109), B12(112)], marker=nerve("cn-08-vestibulocochlear-l"), imagingHint=hint("axial", -45, -30, -32, "inner ear and vestibulocochlear nerve"), preset="inferior", eponyms=["endolymphatic hydrops"]))

E.append(syn("syn-central-vs-peripheral-vertigo", "Central versus peripheral vertigo", "functional-pattern", ["vestibular-nuclei", "cn-08-vestibulocochlear", "flocculonodular-lobe", "inferior-cerebellar-peduncle", "medial-longitudinal-fasciculus"], "n/a",
 "A patient arrives with acute vertigo, vomiting and nystagmus. The question is whether the labyrinth or the brainstem is at fault, and three bedside tests answer it better than an early scan: the head impulse test, the direction of nystagmus on gaze to each side, and the cover test for skew deviation. A peripheral lesion gives an abnormal head impulse, unidirectional nystagmus and no skew; any one of a normal head impulse, direction-changing nystagmus or skew deviation means the lesion is central.",
 [D("vestibular", "ipsilateral", "labyrinth or nerve (peripheral)", "Abnormal head impulse toward the lesion, unidirectional horizontal-torsional nystagmus suppressed by fixation, hearing may be affected", "pathway-vestibular-vor"), D("vestibular", "n/a", "vestibular nuclei, cerebellum, MLF (central)", "Normal head impulse, gaze-evoked direction-changing or vertical nystagmus not suppressed by fixation, skew deviation", "vestibular-nuclei"), D("gait", "n/a", "trunk", "Central: cannot stand unaided; peripheral: veers but stands", "pathway-vestibulospinal"), D("cranial-nerve", "ipsilateral", "brainstem neighbours (central)", "Diplopia, dysarthria, dysphagia, facial numbness, Horner or limb ataxia", "level-medulla-olive")],
 "The vestibulo-ocular reflex is a three-neuron arc from the semicircular canals through the vestibular nuclei to the ocular motor nuclei, and its speed and gain depend on the peripheral input. When one labyrinth or nerve fails, the reflex cannot follow a rapid head turn toward that side and the patient makes a corrective saccade, so a positive head impulse test proves the periphery is at fault; central lesions leave the reflex intact, so a normal head impulse in a patient with continuous vertigo means the imbalance arises in the vestibular nuclei, the cerebellar flocculus or their connections, and the commonest such lesion is a posterior circulation stroke. The direction of peripheral nystagmus is fixed by the side of the dead labyrinth and stays the same in all gaze positions, whereas cerebellar and brainstem lesions impair gaze-holding so the fast phase reverses when the patient looks the other way, and fixation, which uses cerebellar pathways, suppresses only peripheral nystagmus. Vertical (downbeat, upbeat) or purely torsional nystagmus arises from the vertical canal pathways in the MLF and cerebellum and is always central. Skew deviation, a vertical misalignment of the eyes with head tilt, results from an imbalance of the otolith pathways after they have crossed in the brainstem and is a central sign. The crossed sensory loss, Horner, dysphagia or limb ataxia of a lateral medullary or cerebellar infarct confirm the localization. Hearing loss, in contrast, favors a peripheral cause, because the cochlear and vestibular labyrinths share the labyrinthine artery and the eighth nerve, with the important exception of AICA territory infarction.",
 [pathol("Posterior circulation stroke", "MRI", "Restricted diffusion in the lateral medulla, inferior cerebellum or peduncles; early DWI misses up to a fifth of small brainstem infarcts, so repeat if the examination is central.", sequence="DWI", pitfalls="CT is nearly useless for acute posterior fossa ischemia"), pathol("Vertebrobasilar occlusion or dissection", "CTA", "Vertebral artery dissection or basilar stenosis in a patient with central signs."), pathol("Peripheral lesion", "MRI", "Normal brain; occasionally nerve enhancement or a schwannoma.", sequence="T1+Gd")],
 ["Peripheral: vestibular neuritis, BPPV, Ménière, labyrinthitis", "Central: cerebellar or lateral medullary infarct, vertebrobasilar dissection, multiple sclerosis, cerebellar hemorrhage, vestibular migraine"],
 [("Vestibular migraine", "Recurrent, with migraine features; examination between attacks normal"), ("Cardiac presyncope", "No spinning, no nystagmus; orthostatic or exertional"), ("Intoxication (alcohol, anticonvulsants)", "Bilateral gaze-evoked nystagmus with ataxia; history and levels")],
 ["HINTS examination in every patient with an acute vestibular syndrome; central pattern or any vascular risk factor with an atypical examination: MRI with DWI and vessel imaging", "Peripheral pattern: symptomatic treatment and vestibular rehabilitation", "Do not rely on a negative early CT or on the absence of headache to exclude stroke"],
 [B12(110, 112)], marker=structs("brainstem"), imagingHint=hint("axial", -10, -42, -46, "vestibular nuclei at the pontomedullary junction"), preset="posterior", exam=["Head impulse test to each side", "Nystagmus direction in primary gaze, right gaze and left gaze", "Alternate cover test for vertical skew", "Can the patient stand unaided?", "Hearing to finger rub; the rest of the cranial nerves", "Finger-nose and heel-shin"]))

E.append(syn("syn-hearing-loss", "Conductive versus sensorineural hearing loss", "otologic", ["cn-08-vestibulocochlear", "cochlear-nuclei", "gyrus-heschl"], "ipsilateral",
 "A patient cannot hear well in one ear. A tuning fork placed on the forehead is heard louder in the affected ear if the problem is in the ear canal, drum or ossicles, and louder in the good ear if the cochlea or nerve is at fault; placed on the mastoid and then held beside the ear, it is heard longer through the bone than the air in conductive loss and longer through the air in sensorineural loss. Unilateral sensorineural loss needs an MRI; conductive loss needs an otoscope.",
 [D("auditory", "ipsilateral", "external or middle ear (conductive)", "Weber lateralizes to the affected ear, Rinne negative (bone > air); low-frequency loss on audiometry", "cn-08-vestibulocochlear"), D("auditory", "ipsilateral", "cochlea or nerve (sensorineural)", "Weber lateralizes to the good ear, Rinne positive (air > bone); high-frequency or all-frequency loss with reduced discrimination in nerve lesions", "cochlear-nuclei"), D("vestibular", "ipsilateral", "labyrinth (with cochlear disease)", "Vertigo or imbalance accompanies labyrinthine and nerve lesions but not middle ear disease", "pathway-vestibular-vor"), D("auditory", "n/a", "central (rare)", "Bilateral central lesions cause cortical deafness or word deafness; unilateral central lesions never cause deafness", "pathway-auditory")],
 "Sound reaches the cochlea by two routes: through the ear canal, drum and ossicles (air conduction) or directly through the skull bones (bone conduction). A conductive lesion blocks the air route and leaves bone conduction intact, so the affected ear hears the forehead fork better than the good ear, which is distracted by ambient noise entering through its open air route, and hears the mastoid fork longer than the fork beside the canal. A sensorineural lesion of the cochlea or the cochlear nerve reduces both routes equally, so the fork on the forehead is heard better by the healthy cochlea and the normal air-over-bone advantage persists. Above the cochlear nuclei the auditory pathway crosses partially at several levels, in the trapezoid body, the lateral lemniscus and the inferior colliculus, so each auditory cortex receives input from both ears and a unilateral brainstem, thalamic or cortical lesion causes at most subtle localization or discrimination deficits, never deafness in one ear: unilateral hearing loss is always peripheral, in the ear or the eighth nerve. Nerve (retrocochlear) lesions are distinguished from cochlear ones by speech discrimination far worse than the pure-tone loss predicts, absent acoustic reflexes and prolonged interpeak latencies on brainstem auditory evoked potentials, and require MRI for a schwannoma. Sudden sensorineural loss is an emergency treated with steroids; a conductive loss with a normal drum in a young adult suggests otosclerosis.",
 [pathol("Vestibular schwannoma", "MRI", "Enhancing mass in the internal acoustic meatus in any asymmetric sensorineural loss.", sequence="T1+Gd"), pathol("Otosclerosis or ossicular disease", "CT", "Lucent otospongiotic focus at the fissula ante fenestram, ossicular erosion by cholesteatoma or discontinuity after trauma on temporal bone CT.", sequence="CT non-contrast"), pathol("Labyrinthine infarct or labyrinthitis", "MRI", "Enhancement of the cochlea and vestibule, or AICA territory infarct on DWI.", sequence="T1+Gd")],
 ["Conductive: wax, otitis media with effusion, perforation, otosclerosis, cholesteatoma", "Sensorineural: presbycusis, noise, ototoxic drugs, Ménière, sudden idiopathic loss, schwannoma, AICA infarct, meningitis"],
 [("Functional hearing loss", "Inconsistent audiometry; normal otoacoustic emissions and evoked potentials"), ("Auditory neuropathy", "Present emissions, absent brainstem responses"), ("Cortical deafness", "Bilateral temporal lesions; patient responds to sounds inconsistently")],
 ["Otoscopy, Weber and Rinne, then audiometry with speech discrimination", "MRI of the internal auditory meatus for any unexplained asymmetric sensorineural loss", "Urgent oral or intratympanic steroids for sudden sensorineural loss; hearing aids or implants for chronic loss"],
 [B12(105, 107)], marker=nerve("cn-08-vestibulocochlear-l"), imagingHint=hint("axial", -45, -30, -32, "cochlea and cochlear nerve"), preset="inferior"))

write(E)
