import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).parent))
from lib import *
E = []

def pw(id, name, type_, modality, summary, origin, chain, decussation, waypoints, termination, lesions, pearls, citations, somatotopy=None, meshes=(), syndromes=(), synonyms=(), imaging=None):
    d = {"kind": "pathway", "id": id, "name": name, "synonyms": list(synonyms), "type": type_, "modality": modality, "summary": summary,
         "origin": {"structures": origin[0], "note": origin[1]},
         "neuronChain": [{"order": i + 1, "cellBody": a, "synapse": b} for i, (a, b) in enumerate(chain)],
         "decussation": ({"level": decussation[0], **({"structureId": decussation[1]} if decussation[1] else {}), "note": decussation[2]} if decussation else None),
         "waypoints": [{"order": i + 1, "structureId": w[0], **({"meshId": w[1]} if w[1] else {}), "sideRelativeToOrigin": w[2], **({"note": w[3]} if len(w) > 3 else {})} for i, w in enumerate(waypoints)],
         "termination": termination, "meshIds": list(meshes),
         "lesionEffectsByLevel": [{"level": a, "effects": b, "side": c} for a, b, c in lesions],
         "clinical": {"pearls": list(pearls), "syndromes": list(syndromes)}, "citations": citations, "status": "draft"}
    if somatotopy: d["somatotopy"] = somatotopy
    if imaging: d["imaging"] = imaging
    return d

E.append(pw("pathway-visual", "Visual pathway", "visual", "vision",
 "Light falling on the retina is converted by photoreceptors, bipolar cells and ganglion cells into action potentials that leave the eye in the optic nerve. At the chiasm the fibers from the nasal retina (temporal field) cross so that each optic tract carries the opposite hemifield from both eyes to the lateral geniculate body. Geniculate neurons project as the optic radiation: fibers for the upper field loop forward into the temporal lobe (Meyer's loop) and fibers for the lower field pass through the parietal lobe, all ending in the calcarine cortex with the macula at the pole. The pathway is the most precisely localizable in neurology: the shape of the field defect, its congruity, macular sparing and the pupils together give the level.",
 (["cn-02-optic"], "Retinal ganglion cells (third-order neurons of the retina) form the optic nerve; the pathway is CNS from the retina onward."),
 [("Photoreceptor and bipolar cell", "retinal ganglion cell"), ("Retinal ganglion cell", "lateral geniculate nucleus (also pretectum, superior colliculus, suprachiasmatic nucleus)"), ("Lateral geniculate neuron", "layer IV of the striate cortex via the optic radiation")],
 ("Optic chiasm", "optic-chiasm", "Nasal retinal fibers (about 53%) cross; temporal fibers remain uncrossed."),
 [("cn-02-optic", "optic-nerve-l", "ipsilateral", "optic nerve from the disc through the optic canal"), ("optic-chiasm", "optic-chiasm", "bilateral", "partial decussation above the sella"), ("cn-02-optic", "optic-tract-l", "contralateral", "optic tract around the cerebral peduncle carrying the contralateral hemifield"), ("lateral-geniculate-nucleus", "lateral-geniculate-nucleus-l", "contralateral", "six-layered relay; pupillary fibers leave before it"), ("lobe-temporal", "tract-optic-radiation-l", "contralateral", "Meyer's loop through the temporal lobe (upper field)"), ("lobe-parietal", "tract-optic-radiation-l", "contralateral", "parietal fibers (lower field)"), ("cortex-calcarine", "cortex-intracalcarine-l", "contralateral", "striate cortex; macula at the pole")],
 "Primary visual cortex lining the calcarine sulcus, with onward projection to extrastriate areas (V2–V5), the ventral stream (temporal) and the dorsal stream (parietal).",
 [("Retina or optic nerve", "Monocular loss (central scotoma, altitudinal or arcuate defects) with an RAPD and reduced acuity/colour", "ipsilateral"), ("Chiasm", "Bitemporal hemianopia (or junctional scotoma); acuity preserved unless the nerves are involved", "bilateral"), ("Optic tract", "Incongruous contralateral homonymous hemianopia with a contralateral RAPD and later bow-tie optic atrophy", "contralateral"), ("Lateral geniculate body", "Congruous sectoranopia or quadrantic defects with normal pupils", "contralateral"), ("Meyer's loop (temporal lobe)", "Contralateral superior quadrantanopia ('pie in the sky')", "contralateral"), ("Parietal radiation", "Contralateral inferior quadrantanopia, often with neglect or asymmetric optokinetic nystagmus", "contralateral"), ("Calcarine cortex", "Highly congruous contralateral hemianopia with macular sparing; pupils normal", "contralateral"), ("Bilateral occipital cortex", "Cortical blindness with normal pupils and, in Anton syndrome, denial", "bilateral")],
 ["Monocular = in front of the chiasm; bitemporal = chiasm; homonymous = behind the chiasm, and the more congruous the more posterior", "An RAPD localizes to the nerve, chiasm or tract; geniculate, radiation and cortical lesions spare the pupil", "Macular sparing means occipital cortex with collateral MCA supply"],
 [R("sp-visual-pathway"), R("sp-visual-cortex"), R("sp-visual-discrimination")], somatotopy="Retinotopic throughout: upper retina (lower field) stays superior in the tract, radiation (parietal) and cortex (cuneus); lower retina (upper field) runs inferiorly (Meyer's loop, lingual gyrus); macula central in the nerve, posterior in the chiasm, occupying the occipital pole.",
 meshes=["optic-nerve-l", "optic-nerve-r", "optic-chiasm", "optic-tract-l", "optic-tract-r", "tract-optic-radiation-l", "tract-optic-radiation-r"], syndromes=["syn-optic-neuritis", "syn-chiasmal-bitemporal", "syn-homonymous-hemianopia", "syn-pca-infarct", "syn-anton", "syn-alexia-without-agraphia"], synonyms=["retinogeniculocalcarine pathway", "geniculostriate pathway"]))

E.append(pw("pathway-pupillary-light-reflex", "Pupillary light reflex pathway", "reflex", "pupillary constriction to light",
 "Light in either eye constricts both pupils because the pathway is bilateral at two points. Retinal ganglion cell axons leave the optic tract before the lateral geniculate body and reach the pretectal nuclei of both sides (via the brachium of the superior colliculus and the posterior commissure); each pretectal nucleus projects to both Edinger–Westphal nuclei; each Edinger–Westphal nucleus sends preganglionic fibers in the oculomotor nerve to the ciliary ganglion, whose postganglionic fibers reach the sphincter pupillae through the short ciliary nerves. Asymmetric afferent lesions produce the relative afferent pupillary defect, efferent lesions a fixed dilated pupil, and pretectal lesions light-near dissociation.",
 (["cn-02-optic"], "Intrinsically photosensitive retinal ganglion cells (melanopsin) and conventional ganglion cells."),
 [("Retinal ganglion cell", "pretectal olivary nucleus (both sides)"), ("Pretectal neuron", "Edinger–Westphal nuclei of both sides via the posterior commissure"), ("Edinger–Westphal preganglionic neuron", "ciliary ganglion via CN III"), ("Ciliary ganglion postganglionic neuron", "sphincter pupillae via the short ciliary nerves")],
 ("Chiasm (afferent) and posterior commissure (pretectal)", "pretectal-area", "Bilateral at the chiasm and again between the pretectal and Edinger–Westphal nuclei, giving the consensual response."),
 [("cn-02-optic", "optic-nerve-l", "ipsilateral", "afferent limb in the optic nerve and tract"), ("optic-chiasm", "optic-chiasm", "bilateral"), ("pretectal-area", "brainstem", "bilateral", "fibers leave the optic tract before the LGN via the brachium of the superior colliculus"), ("oculomotor-nucleus", "brainstem", "bilateral", "Edinger–Westphal nuclei, both sides"), ("cn-03-oculomotor", "cn-03-oculomotor-l", "ipsilateral", "preganglionic fibers on the surface of the nerve"), ("ganglion-ciliary", "ciliary-ganglion-l", "ipsilateral"), ("cn-02-optic", "optic-nerve-l", "ipsilateral", "short ciliary nerves to the sphincter pupillae (represented by the orbital region)")],
 "Sphincter pupillae of both eyes (direct and consensual constriction).",
 [("Optic nerve (unilateral or asymmetric)", "Relative afferent pupillary defect: the affected pupil dilates when the light swings onto it; both pupils are equal in size", "ipsilateral"), ("Optic tract", "Contralateral RAPD with a homonymous hemianopia", "contralateral"), ("Pretectum / posterior commissure", "Light-near dissociation of both pupils (Parinaud, Argyll Robertson)", "bilateral"), ("Oculomotor nerve (compressive)", "Fixed dilated pupil with ptosis and ophthalmoplegia", "ipsilateral"), ("Ciliary ganglion or short ciliary nerves", "Adie tonic pupil: large, slow to near, supersensitive to dilute pilocarpine", "ipsilateral"), ("Iris (pharmacological, trauma)", "Fixed dilated pupil that does not constrict to full-strength pilocarpine", "ipsilateral")],
 ["Both pupils are always the same size in an afferent lesion; anisocoria means an efferent (or iris) problem", "The swinging flashlight test is the only bedside test that can detect an asymmetric optic nerve lesion in a patient with good acuity", "Light-near dissociation localizes to the pretectum or to the ciliary ganglion with aberrant regeneration"],
 [R("sp-pupillary-light-reflex"), R("sp-pupillary-light-reflexes-and-pathway")], meshes=["optic-nerve-l", "optic-nerve-r", "optic-chiasm", "cn-03-oculomotor-l", "cn-03-oculomotor-r", "ciliary-ganglion-l", "ciliary-ganglion-r"], syndromes=["syn-rapd", "syn-cn3-palsy", "syn-adie-tonic-pupil", "syn-argyll-robertson", "syn-parinaud-dorsal-midbrain"]))

E.append(pw("pathway-oculosympathetic", "Oculosympathetic pathway", "autonomic", "pupillary dilation, lid elevation, facial sweating",
 "The sympathetic supply to the eye is a three-neuron chain that travels a remarkable distance: from the hypothalamus down the brainstem tegmentum and lateral cervical cord to the ciliospinal center at C8–T2; out through the T1 root over the lung apex and up the cervical chain to the superior cervical ganglion; and finally along the internal carotid artery through the cavernous sinus and the ophthalmic division to the dilator pupillae and Müller's muscle, with the sweat fibers leaving on the external carotid. A lesion anywhere along this route gives Horner syndrome, and the company it keeps (brainstem signs, hand weakness, neck pain, cavernous sinus nerves) plus the sweating pattern tells you where.",
 (["hypothalamus"], "Posterolateral hypothalamus (first-order neuron)."),
 [("Hypothalamic neuron", "intermediolateral column at C8–T2 (ciliospinal center)"), ("Preganglionic neuron in the ciliospinal center", "superior cervical ganglion"), ("Superior cervical ganglion neuron", "dilator pupillae, Müller's muscle, facial sweat glands")],
 None,
 [("hypothalamus", "hypothalamus-posterior-l", "ipsilateral", "first-order neuron"), ("level-midbrain-superior-colliculus", "brainstem", "ipsilateral", "lateral tegmentum"), ("level-medulla-olive", "brainstem", "ipsilateral", "lateral medulla (Wallenberg)"), ("intermediolateral-column", "spinal-cord", "ipsilateral", "ciliospinal center C8–T2"), ("sympathetic-trunk", None, "ipsilateral", "T1 root, stellate ganglion, lung apex, cervical chain"), ("ganglion-superior-cervical", None, "ipsilateral", "third-order synapse"), ("artery-internal-carotid", "artery-internal-carotid-l", "ipsilateral", "internal carotid plexus"), ("sinus-cavernous", "dura-mater-cranial", "ipsilateral", "briefly joins the abducens nerve then V1"), ("cn-05-trigeminal", "ophthalmic-nerve-l", "ipsilateral", "nasociliary nerve and long ciliary nerves to the dilator")],
 "Dilator pupillae, superior tarsal (Müller's) muscle, orbital vessels and the sweat glands of the face.",
 [("Hypothalamus, brainstem or cervical cord (first-order)", "Horner syndrome with anhidrosis of the whole side of the face and body; accompanied by brainstem or cord signs", "ipsilateral"), ("Ciliospinal center, T1 root, lung apex, cervical chain (second-order)", "Horner with facial anhidrosis; hand weakness or pain (Pancoast), neck surgery or trauma", "ipsilateral"), ("Superior cervical ganglion, carotid, cavernous sinus (third-order)", "Horner without anhidrosis; neck pain (dissection), sixth nerve palsy (cavernous), cluster headache", "ipsilateral")],
 ["Small pupil, mild ptosis, anisocoria greater in the dark: Horner. Where? Sweating and the neighbours decide", "Painful Horner is carotid dissection until proven otherwise", "Hydroxyamphetamine dilates a preganglionic Horner pupil but not a postganglionic one"],
 [R("sp-horner-syndrome"), R("sp-superior-cervical-ganglion"), R("sp-sympathetic-nervous-system")], meshes=["artery-internal-carotid-l", "artery-internal-carotid-r", "ophthalmic-nerve-l", "ophthalmic-nerve-r"], syndromes=["syn-horner", "syn-wallenberg-lateral-medullary", "syn-cavernous-sinus", "syn-klumpke"]))

E.append(pw("pathway-horizontal-gaze", "Horizontal gaze pathway", "oculomotor", "conjugate horizontal eye movements",
 "Looking to the left requires the left lateral rectus and the right medial rectus to contract together. The command starts in the right frontal eye field (for voluntary saccades) or the parieto-occipital cortex (for pursuit), descends to the left paramedian pontine reticular formation, which fires the left abducens nucleus; that nucleus contains both the motor neurons for the left lateral rectus and the interneurons whose axons cross and ascend in the right MLF to the right medial rectus subnucleus of the oculomotor nucleus. Lesions of the frontal eye field, the PPRF, the abducens nucleus and the MLF each produce a characteristic and localizable pattern.",
 (["frontal-eye-field", "lobule-superior-parietal"], "Frontal eye field (saccades) and parieto-temporo-occipital cortex (pursuit); also the superior colliculus and vestibular nuclei."),
 [("Frontal eye field neuron", "contralateral PPRF (directly and via the superior colliculus)"), ("PPRF burst neuron", "ipsilateral abducens nucleus"), ("Abducens motor neuron", "ipsilateral lateral rectus"), ("Abducens internuclear neuron", "contralateral oculomotor nucleus (medial rectus subnucleus) via the MLF"), ("Oculomotor motor neuron", "medial rectus")],
 ("Cortex to PPRF (crossed in the midbrain–pons) and abducens interneurons to the contralateral MLF", "medial-longitudinal-fasciculus", "Double crossing: the cortex drives the contralateral PPRF, whose abducens nucleus drives the contralateral medial rectus through the MLF."),
 [("frontal-eye-field", "gyrus-middle-frontal-l", "ipsilateral", "voluntary saccade command"), ("internal-capsule", "internal-capsule-l", "ipsilateral", "descends with corticobulbar fibers"), ("pprf", "brainstem", "contralateral", "paramedian pontine reticular formation"), ("abducens-nucleus", "brainstem", "contralateral", "motor neurons to the lateral rectus; interneurons to the MLF"), ("medial-longitudinal-fasciculus", "brainstem", "ipsilateral", "interneuron axons cross and ascend in the MLF"), ("oculomotor-nucleus", "brainstem", "ipsilateral", "medial rectus subnucleus")],
 "Lateral rectus (abducens nerve) of one eye and medial rectus (oculomotor nerve) of the other.",
 [("Frontal eye field (destructive)", "Eyes deviate toward the lesion; cannot look voluntarily to the opposite side; vestibulo-ocular reflex intact; recovers in days", "contralateral"), ("Frontal eye field (irritative, seizure)", "Eyes and head turn away from the focus", "contralateral"), ("PPRF", "Loss of ipsilateral saccades; eyes deviate away from the lesion; oculocephalic reflex can still bring the eyes across", "ipsilateral"), ("Abducens nucleus", "Complete ipsilateral gaze palsy not overcome by the oculocephalic reflex, usually with an ipsilateral facial palsy", "ipsilateral"), ("MLF", "Internuclear ophthalmoplegia: the ipsilateral eye fails to adduct, the contralateral eye shows abducting nystagmus, convergence spared", "ipsilateral"), ("Abducens nucleus plus ipsilateral MLF", "One-and-a-half syndrome: only abduction of the contralateral eye survives", "ipsilateral")],
 ["Hemisphere: eyes look toward the lesion. Pons: eyes look away from the lesion", "A gaze palsy that head turning overcomes is supranuclear; one it cannot overcome is nuclear", "INO is the MLF; bilateral INO in a young adult is multiple sclerosis"],
 [R("sp-abducens-nucleus"), R("sp-internuclear-ophthalmoplegia"), R("sp-reticular-formation")], meshes=["brainstem"], syndromes=["syn-ino", "syn-one-and-a-half", "syn-horizontal-gaze-palsy-pontine", "syn-foville", "syn-mca-stem-infarct"]))

E.append(pw("pathway-vertical-gaze", "Vertical gaze pathway", "oculomotor", "conjugate vertical eye movements",
 "Vertical saccades are generated by the rostral interstitial nucleus of the MLF in the rostral midbrain, which drives the oculomotor and trochlear nuclei of both sides; up-gaze commands cross through the posterior commissure, which is why dorsal midbrain compression abolishes up-gaze first. The interstitial nucleus of Cajal holds vertical gaze position, and vestibular input from the anterior and posterior canals reaches the same nuclei through the MLF. Because the vestibular route bypasses the riMLF, a supranuclear vertical gaze palsy (progressive supranuclear palsy, Parinaud) can be overcome by the oculocephalic reflex.",
 (["frontal-eye-field", "superior-colliculus"], "Frontal eye fields bilaterally and the superior colliculus; vestibular nuclei for reflex movements."),
 [("Frontal eye field neuron", "riMLF (bilateral)"), ("riMLF burst neuron", "oculomotor nucleus (elevators and depressors) and trochlear nucleus, via the posterior commissure for up-gaze"), ("Oculomotor/trochlear motor neuron", "superior rectus, inferior oblique (up); inferior rectus, superior oblique (down)")],
 ("Posterior commissure (up-gaze fibers)", "pretectal-area", "Up-gaze pathways cross in the posterior commissure; down-gaze projections are mainly ipsilateral."),
 [("frontal-eye-field", "gyrus-middle-frontal-l", "bilateral"), ("rimlf", "brainstem", "bilateral", "rostral interstitial nucleus of the MLF at the mesodiencephalic junction"), ("pretectal-area", "brainstem", "bilateral", "posterior commissure for up-gaze; interstitial nucleus of Cajal for gaze holding"), ("oculomotor-nucleus", "brainstem", "bilateral", "superior and inferior rectus, inferior oblique subnuclei"), ("trochlear-nucleus", "brainstem", "bilateral", "superior oblique for down-gaze")],
 "Vertical extraocular muscles of both eyes through the oculomotor and trochlear nerves.",
 [("Posterior commissure / pretectum (pineal tumor, hydrocephalus, top of basilar)", "Up-gaze palsy with convergence-retraction nystagmus, lid retraction and light-near dissociation (Parinaud)", "bilateral"), ("riMLF (bilateral paramedian thalamomesencephalic infarct)", "Loss of down-gaze (and up-gaze) saccades with somnolence", "bilateral"), ("Progressive supranuclear palsy", "Slow then absent vertical saccades, down-gaze first, overcome by the oculocephalic reflex", "bilateral"), ("Oculomotor and trochlear nuclei or nerves", "Nuclear or infranuclear palsy: not overcome by head movement, with ptosis or diplopia", "n/a")],
 ["Up-gaze palsy: think dorsal midbrain compression. Down-gaze palsy: think riMLF or PSP", "A vertical gaze palsy overcome by the doll's-head maneuver is supranuclear", "Elderly patients often have limited up-gaze normally; down-gaze limitation is never normal"],
 [R("sp-parinaud-syndrome"), R("sp-mesencephalon-midbrain"), R("sp-cranial-nerve-3")], meshes=["brainstem"], syndromes=["syn-parinaud-dorsal-midbrain", "syn-top-of-basilar"]))

E.append(pw("pathway-auditory", "Auditory pathway", "auditory", "hearing",
 "Hair cells of the organ of Corti excite spiral ganglion neurons whose axons form the cochlear nerve to the dorsal and ventral cochlear nuclei. From there the pathway becomes bilateral almost immediately: fibers cross in the trapezoid body to the contralateral superior olivary complex and lateral lemniscus, others ascend ipsilaterally, and further crossings occur at the inferior colliculus. All fibers relay in the inferior colliculus, then the medial geniculate body, and reach Heschl's gyrus through the acoustic radiation. The extensive crossing means a unilateral central lesion never causes deafness; unilateral deafness is always the cochlea, nerve or cochlear nuclei.",
 (["cn-08-vestibulocochlear"], "Inner hair cells of the cochlea; bipolar spiral ganglion neurons."),
 [("Spiral ganglion neuron", "dorsal and ventral cochlear nuclei"), ("Cochlear nuclear neuron", "superior olivary complex (both sides) and inferior colliculus via the lateral lemniscus"), ("Superior olive / lateral lemniscus neuron", "inferior colliculus"), ("Inferior colliculus neuron", "medial geniculate body via its brachium"), ("Medial geniculate neuron", "Heschl's gyrus via the acoustic radiation")],
 ("Trapezoid body (caudal pons), lateral lemniscus commissure, inferior colliculus commissure", "superior-olivary-complex", "Multiple partial crossings; the pathway is bilateral above the cochlear nuclei."),
 [("cn-08-vestibulocochlear", "cn-08-vestibulocochlear-l", "ipsilateral", "cochlear nerve"), ("cochlear-nuclei", "brainstem", "ipsilateral", "at the lateral recess of the fourth ventricle"), ("superior-olivary-complex", "brainstem", "bilateral", "trapezoid body crossing; binaural comparison"), ("inferior-colliculus", "inferior-colliculus-l", "bilateral", "lateral lemniscus ends here"), ("medial-geniculate-nucleus", "medial-geniculate-nucleus-l", "bilateral", "thalamic relay"), ("internal-capsule", "tract-acoustic-radiation-l", "bilateral", "acoustic radiation in the sublenticular capsule"), ("gyrus-heschl", "gyrus-heschl-l", "bilateral", "primary auditory cortex")],
 "Primary auditory cortex on Heschl's gyrus, tonotopically organized, with onward projection to the auditory association cortex and Wernicke's area.",
 [("Cochlea", "Ipsilateral sensorineural deafness (noise, ototoxicity, presbycusis, Ménière)", "ipsilateral"), ("Cochlear nerve or nuclei", "Ipsilateral deafness with poor speech discrimination and tinnitus (schwannoma, AICA infarct)", "ipsilateral"), ("Superior olive, lateral lemniscus, inferior colliculus", "Impaired sound localization and central auditory processing without deafness", "bilateral"), ("Medial geniculate or acoustic radiation (unilateral)", "Subtle contralateral deficits only", "contralateral"), ("Bilateral Heschl's gyri or radiations", "Cortical deafness or pure word deafness", "bilateral")],
 ["Deafness in one ear is peripheral; the brainstem and cortex cannot deafen a single ear", "Brainstem auditory evoked potentials track the pathway wave by wave: I nerve, II cochlear nucleus, III superior olive, IV lateral lemniscus, V inferior colliculus"],
 [R("sp-auditory-pathway"), R("sp-auditory-hallucinations"), R("sp-auditory-brainstem-response")], somatotopy="Tonotopic at every level: high frequencies at the base of the cochlea and in the ventral cochlear nucleus, mapped systematically through the colliculus and geniculate to Heschl's gyrus (low frequencies anterolateral, high posteromedial).",
 meshes=["cn-08-vestibulocochlear-l", "cn-08-vestibulocochlear-r", "inferior-colliculus-l", "inferior-colliculus-r", "medial-geniculate-nucleus-l", "medial-geniculate-nucleus-r", "tract-acoustic-radiation-l", "tract-acoustic-radiation-r"], syndromes=["syn-hearing-loss", "syn-cerebellopontine-angle", "syn-aica-lateral-pontine"]))

E.append(pw("pathway-vestibular-vor", "Vestibular pathways and vestibulo-ocular reflex", "vestibular", "balance, spatial orientation and gaze stabilization",
 "Hair cells of the semicircular canals and otolith organs excite the vestibular ganglion neurons whose axons form the vestibular nerve to the four vestibular nuclei and directly to the flocculonodular lobe. The nuclei send excitatory and inhibitory projections through the MLF to the abducens, trochlear and oculomotor nuclei, producing the vestibulo-ocular reflex that moves the eyes opposite to head rotation with a latency of a few milliseconds, descend as the vestibulospinal tracts for posture, and ascend through the thalamus to the vestibular cortex in the posterior insula and temporoparietal junction. Because the two labyrinths are balanced, a unilateral loss creates a bias interpreted as rotation (vertigo) with nystagmus beating away from the lesion.",
 (["cn-08-vestibulocochlear"], "Hair cells of the three semicircular canal cristae and the utricular and saccular maculae; bipolar neurons of Scarpa's ganglion."),
 [("Vestibular ganglion neuron", "vestibular nuclei (superior, lateral, medial, inferior) and cerebellar flocculonodular lobe"), ("Vestibular nuclear neuron", "ocular motor nuclei via the MLF; spinal cord via the vestibulospinal tracts; thalamus (VPL/VPI) for perception; cerebellum"), ("Ocular motor neuron", "extraocular muscles")],
 ("MLF at the level of the vestibular nuclei", "medial-longitudinal-fasciculus", "Each horizontal canal excites the contralateral abducens nucleus and, via its interneurons, the ipsilateral medial rectus."),
 [("cn-08-vestibulocochlear", "cn-08-vestibulocochlear-l", "ipsilateral", "vestibular nerve"), ("vestibular-nuclei", "brainstem", "ipsilateral", "medial and superior nuclei for the VOR, lateral for posture"), ("flocculonodular-lobe", "cerebellar-lobule-x-l", "ipsilateral", "direct and indirect vestibulocerebellar fibers; VOR calibration"), ("medial-longitudinal-fasciculus", "brainstem", "bilateral", "ascending to the ocular motor nuclei"), ("abducens-nucleus", "brainstem", "contralateral", "horizontal VOR"), ("oculomotor-nucleus", "brainstem", "bilateral", "vertical and torsional VOR"), ("spinal-white-columns", "spinal-cord", "ipsilateral", "vestibulospinal tracts"), ("insula", "insula-l", "contralateral", "vestibular cortex in the posterior insula (parieto-insular vestibular cortex) via the thalamus")],
 "Extraocular motor nuclei (vestibulo-ocular reflex), spinal motor neurons (vestibulospinal reflexes), cerebellum, and the parieto-insular vestibular cortex for the perception of motion and verticality.",
 [("Labyrinth or vestibular nerve (unilateral)", "Acute vertigo, nausea, unidirectional horizontal-torsional nystagmus beating away from the lesion, positive head impulse toward the lesion, falling toward the lesion", "ipsilateral"), ("Bilateral vestibular loss (ototoxicity)", "Oscillopsia with head movement and imbalance in the dark, no vertigo", "bilateral"), ("Vestibular nuclei (lateral medulla)", "Central vertigo with direction-changing or vertical nystagmus, skew deviation, normal head impulse, other medullary signs", "ipsilateral"), ("MLF", "Internuclear ophthalmoplegia with skew and vertical nystagmus", "ipsilateral"), ("Cerebellum (flocculus, nodulus)", "Gaze-evoked, downbeat or positional nystagmus, impaired pursuit and VOR cancellation", "n/a"), ("Vestibular cortex / thalamus", "Tilt of the perceived vertical, lateropulsion, room-tilt illusion", "contralateral")],
 ["HINTS beats early MRI for separating vestibular neuritis from stroke: normal head impulse, direction-changing nystagmus or skew means central", "Nystagmus from a peripheral lesion obeys Alexander's law and is suppressed by fixation; central nystagmus is not", "The VOR is fast enough to keep your eyes on this text while you shake your head; a damaged VOR makes the world jump"],
 [R("sp-vestibulo-ocular-reflex"), R("sp-vestibular-pathways"), R("sp-nucleus-vestibular")], meshes=["cn-08-vestibulocochlear-l", "cn-08-vestibulocochlear-r", "cerebellar-lobule-x-l", "cerebellar-lobule-x-r"], syndromes=["syn-vestibular-neuritis", "syn-central-vs-peripheral-vertigo", "syn-bppv", "syn-wallenberg-lateral-medullary", "syn-ino"]))

E.append(pw("pathway-cerebellar-circuits", "Cerebellar afferent and efferent circuits", "cerebellar", "coordination, timing and motor learning",
 "Information enters the cerebellum as mossy fibers (from the pontine nuclei carrying cortical plans, the spinal cord carrying proprioception, and the vestibular nuclei) and climbing fibers (from the contralateral inferior olive), both exciting the Purkinje cells through the granule cell layer; Purkinje cells inhibit the deep nuclei, which provide the only output. The lateral hemisphere talks to the dentate nucleus, the superior cerebellar peduncle, the contralateral red nucleus and the ventral lateral thalamus, and so to the motor cortex; the vermis talks to the fastigial nucleus and the vestibular and reticular nuclei. Because the outflow crosses in the midbrain and the corticospinal tract crosses again in the medulla, the cerebellum controls the same side of the body, and the pontine input crosses once, so it works with the opposite cortex.",
 (["cerebellum", "pontine-nuclei", "inferior-olivary-nucleus", "spinal-cord", "vestibular-nuclei"], "Afferents from the pontine nuclei (crossed), inferior olive (crossed), spinal cord (uncrossed) and vestibular system; output from the deep nuclei."),
 [("Pontine nucleus (mossy fiber) / inferior olive (climbing fiber)", "granule cells / Purkinje cells"), ("Granule cell (parallel fibers)", "Purkinje cell"), ("Purkinje cell (inhibitory)", "deep cerebellar nuclei"), ("Dentate/interposed nucleus", "contralateral red nucleus and VL thalamus via the superior cerebellar peduncle"), ("VL thalamic neuron", "motor and premotor cortex")],
 ("Pontocerebellar fibers (pons), olivocerebellar fibers (medulla), superior cerebellar peduncle decussation (midbrain)", "superior-cerebellar-peduncle", "Input from the cortex crosses once (pons); output crosses once (midbrain); the corticospinal tract crosses again, so the cerebellum is ipsilateral to the limb it controls."),
 [("gyrus-precentral", "gyrus-precentral-l", "ipsilateral", "cortical origin of corticopontine fibers"), ("pontine-nuclei", "brainstem", "ipsilateral", "relay; transverse fibers cross"), ("middle-cerebellar-peduncle", "middle-cerebellar-peduncle", "contralateral", "mossy fibers to the contralateral hemisphere"), ("inferior-olivary-nucleus", "brainstem", "ipsilateral", "climbing fibers cross to the contralateral cerebellum"), ("inferior-cerebellar-peduncle", "inferior-cerebellar-peduncle-l", "contralateral", "olivocerebellar and spinocerebellar input"), ("cerebellar-hemisphere", "cerebellar-hemisphere-l", "contralateral", "cerebellar cortex: Purkinje cells"), ("dentate-nucleus", "dentate-nucleus-l", "contralateral", "output nucleus"), ("superior-cerebellar-peduncle", "superior-cerebellar-peduncle", "contralateral", "decussates in the caudal midbrain"), ("red-nucleus", "red-nucleus-l", "ipsilateral", "back on the side of the cortex"), ("thalamus-va-vl", "thalamus-ventrolateral-l", "ipsilateral", "ventral lateral nucleus"), ("gyrus-precentral", "gyrus-precentral-l", "ipsilateral", "closing the loop to the motor cortex")],
 "Motor and premotor cortex (via VL thalamus), red nucleus (rubrospinal), vestibular and reticular nuclei (via the fastigial nucleus), and the inferior olive (via the central tegmental tract, completing the Guillain–Mollaret triangle).",
 [("Cerebellar hemisphere or dentate nucleus", "Ipsilateral limb ataxia, dysmetria, intention tremor, dysdiadochokinesia, hypotonia", "ipsilateral"), ("Vermis and fastigial nucleus", "Truncal and gait ataxia, nystagmus, little limb ataxia", "bilateral"), ("Middle cerebellar peduncle or pontine nuclei", "Ipsilateral limb ataxia (input from the contralateral cortex)", "ipsilateral"), ("Superior cerebellar peduncle below its decussation", "Ipsilateral ataxia", "ipsilateral"), ("Superior cerebellar peduncle above its decussation, red nucleus, VL thalamus", "Contralateral ataxia and Holmes tremor", "contralateral"), ("Inferior olive or central tegmental tract", "Palatal tremor after olivary hypertrophy", "n/a")],
 ["Cerebellar signs are ipsilateral unless the lesion is above the midbrain decussation", "The cerebellum does not initiate movement, so cerebellar lesions never cause paralysis; they make movement inaccurate", "A dentate lesion and a contralateral thalamic lesion give the same limb ataxia; the neighbours tell them apart"],
 [R("sp-cerebellum"), R("sp-purkinje-cells"), R("sp-dentate-nucleus")], meshes=["middle-cerebellar-peduncle", "superior-cerebellar-peduncle", "inferior-cerebellar-peduncle-l", "inferior-cerebellar-peduncle-r", "dentate-nucleus-l", "dentate-nucleus-r", "tract-dentatorubrothalamic-l", "tract-dentatorubrothalamic-r"], syndromes=["syn-cerebellar-hemispheric", "syn-cerebellar-vermian-midline", "syn-claude", "syn-lacunar-ataxic-hemiparesis"]))

E.append(pw("pathway-basal-ganglia-loops", "Basal ganglia direct and indirect loops", "basal-ganglia", "selection and scaling of movement",
 "The basal ganglia form loops from the cortex through the striatum, pallidum and thalamus back to the cortex. In the direct pathway, cortical excitation of striatal neurons inhibits the internal pallidum and substantia nigra reticulata, releasing the thalamus and facilitating movement; in the indirect pathway, striatal neurons inhibit the external pallidum, which disinhibits the subthalamic nucleus, whose excitation of the internal pallidum suppresses the thalamus and movement. Dopamine from the substantia nigra compacta excites the direct (D1) and inhibits the indirect (D2) pathway, so its loss tips the balance toward inhibition (parkinsonism), while loss of striatal indirect neurons (Huntington) or of the subthalamic nucleus (hemiballismus) tips it toward excess movement.",
 (["gyrus-precentral", "cortex-premotor-sma", "cortex-prefrontal", "putamen", "caudate-nucleus"], "Glutamatergic input from the whole cortex to the striatum (motor cortex to the putamen, association cortex to the caudate, limbic cortex to the accumbens)."),
 [("Cortical pyramidal cell", "striatal medium spiny neurons (glutamate)"), ("Direct pathway striatal neuron (D1)", "internal pallidum / substantia nigra reticulata (GABA)"), ("Indirect pathway striatal neuron (D2)", "external pallidum (GABA)"), ("External pallidal neuron", "subthalamic nucleus (GABA)"), ("Subthalamic neuron", "internal pallidum (glutamate)"), ("Internal pallidal neuron", "VA/VL thalamus (GABA, tonic inhibition)"), ("Thalamic neuron", "motor and premotor cortex (glutamate)")],
 None,
 [("gyrus-precentral", "gyrus-precentral-l", "ipsilateral", "cortical input"), ("putamen", "putamen-l", "ipsilateral", "striatal input stage (motor loop)"), ("globus-pallidus", "globus-pallidus-externus-l", "ipsilateral", "external segment (indirect pathway)"), ("subthalamic-nucleus", "subthalamic-nucleus-l", "ipsilateral", "excitatory node of the indirect pathway"), ("globus-pallidus", "globus-pallidus-internus-l", "ipsilateral", "internal segment: output"), ("substantia-nigra", "substantia-nigra-l", "ipsilateral", "pars compacta (dopamine to the striatum) and pars reticulata (output)"), ("thalamus-va-vl", "thalamus-ventral-anterior-l", "ipsilateral", "ventral anterior and ventral lateral nuclei"), ("cortex-premotor-sma", "cortex-supplementary-motor-l", "ipsilateral", "return to the cortex")],
 "Motor, premotor and supplementary motor cortex (motor loop), prefrontal cortex (associative loop) and anterior cingulate/orbitofrontal cortex (limbic loop) via the thalamus; brainstem targets (superior colliculus, pedunculopontine nucleus) via the nigra reticulata and pallidum.",
 [("Substantia nigra pars compacta (dopamine loss)", "Parkinsonism: bradykinesia, rigidity, rest tremor, postural instability", "contralateral"), ("Striatum (Huntington disease, indirect pathway neurons lost first)", "Chorea, later rigidity and dementia", "bilateral"), ("Subthalamic nucleus (lacunar infarct)", "Contralateral hemiballismus", "contralateral"), ("Globus pallidus (CO poisoning, kernicterus)", "Parkinsonism or dystonia", "bilateral"), ("Putamen (Wilson disease, methanol)", "Dystonia, parkinsonism", "bilateral"), ("Caudate / associative loop", "Apathy, executive dysfunction, obsessive-compulsive features", "bilateral")],
 ["Too little dopamine or too much pallidal output: hypokinesia. Too little pallidal output: hyperkinesia", "The subthalamic nucleus is the brake; the internal pallidum is the gate; dopamine sets the threshold", "Basal ganglia lesions do not cause weakness, sensory loss or reflex change: they change the quality of movement"],
 [R("sp-basal-ganglia")], meshes=["putamen-l", "putamen-r", "caudate-nucleus-l", "caudate-nucleus-r", "globus-pallidus-internus-l", "globus-pallidus-internus-r", "globus-pallidus-externus-l", "globus-pallidus-externus-r", "subthalamic-nucleus-l", "subthalamic-nucleus-r", "substantia-nigra-l", "substantia-nigra-r"], syndromes=["syn-parkinsonism", "syn-hemiballismus", "syn-huntington-chorea"]))

E.append(pw("pathway-papez-limbic", "Papez circuit and limbic connections", "limbic", "declarative memory and emotion",
 "The classical memory circuit runs from the hippocampus through the fornix to the mammillary bodies, from there by the mammillothalamic tract to the anterior thalamic nuclei, on to the cingulate gyrus, and back through the cingulum bundle and entorhinal cortex to the hippocampus. Every station is a site of clinical amnesia: the hippocampus in Alzheimer disease, anoxia and herpes encephalitis, the fornix in surgery, the mammillary bodies in thiamine deficiency, the anterior and mediodorsal thalamus in stroke, and the cingulate in tumors. The amygdala, orbitofrontal cortex and mediodorsal thalamus form a parallel limbic loop for emotion and social behaviour.",
 (["hippocampus", "gyrus-parahippocampal-uncus"], "Hippocampal formation (subiculum) with input from the entorhinal cortex, which collects from the association cortices."),
 [("Hippocampal (subicular) pyramidal neuron", "mammillary body via the fornix"), ("Mammillary body neuron", "anterior thalamic nuclei via the mammillothalamic tract"), ("Anterior thalamic neuron", "cingulate gyrus via the anterior limb of the internal capsule"), ("Cingulate neuron", "entorhinal cortex via the cingulum"), ("Entorhinal neuron", "hippocampus via the perforant path")],
 None,
 [("hippocampus", "hippocampus-l", "ipsilateral", "output via the fimbria"), ("fornix", "fornix", "ipsilateral", "crus, body and columns"), ("mammillary-body", "mammillary-body-l", "ipsilateral", "postcommissural fornix ends here"), ("thalamus-anterior-nuclei", "thalamus-ventral-anterior-l", "ipsilateral", "mammillothalamic tract"), ("gyrus-cingulate", "gyrus-cingulate-anterior-l", "ipsilateral", "cingulate cortex"), ("gyrus-parahippocampal-uncus", "gyrus-parahippocampal-anterior-l", "ipsilateral", "cingulum bundle to the entorhinal cortex"), ("hippocampus", "hippocampus-l", "ipsilateral", "perforant path closes the loop")],
 "Hippocampus (closing the loop), with outputs to the prefrontal cortex and the septal nuclei, and from the amygdala to the hypothalamus and brainstem for autonomic and behavioural responses.",
 [("Hippocampus (bilateral)", "Anterograde amnesia with preserved remote memory and intelligence", "bilateral"), ("Fornix (bilateral, surgery)", "Anterograde amnesia", "bilateral"), ("Mammillary bodies (thiamine deficiency)", "Korsakoff amnesia with confabulation", "bilateral"), ("Anterior or mediodorsal thalamus (infarct)", "Amnesia, apathy, confabulation", "bilateral"), ("Cingulate gyrus (bilateral)", "Akinetic mutism, apathy", "bilateral"), ("Amygdala (bilateral)", "Klüver–Bucy syndrome: placidity, hyperorality, hypersexuality", "bilateral")],
 ["Memory loss for new events with intact reasoning is the Papez circuit; the lesion can be anywhere along it", "Thiamine deficiency and third ventricular surgery injure the same circuit at different stations", "Unilateral lesions cause material-specific loss: verbal on the left, visuospatial on the right"],
 [R("sp-limbic-system"), R("sp-hippocampus"), R("sp-corpus-callosum")], meshes=["hippocampus-l", "hippocampus-r", "fornix", "mammillary-body-l", "mammillary-body-r", "mammillothalamic-tract-l", "mammillothalamic-tract-r", "gyrus-cingulate-anterior-l", "gyrus-cingulate-anterior-r", "amygdala-l", "amygdala-r"], syndromes=["syn-wernicke-korsakoff", "syn-kluver-bucy"]))

E.append(pw("pathway-olfactory", "Olfactory pathway", "olfactory", "smell",
 "Olfactory receptor neurons in the nasal epithelium send unmyelinated axons through the cribriform plate to synapse in the glomeruli of the olfactory bulb on mitral and tufted cells, whose axons form the olfactory tract. At the anterior perforated substance the tract divides: the lateral stria ends in the primary olfactory cortex of the uncus (piriform cortex), the amygdala and the entorhinal cortex, and the medial stria in the septal area and, through the anterior commissure, the opposite bulb. Smell is the only sense that reaches the cortex without a thalamic relay and one of the few that is largely ipsilateral, and its cortical stations in the medial temporal lobe explain olfactory auras in temporal lobe epilepsy.",
 (["cn-01-olfactory"], "Bipolar olfactory receptor neurons in the olfactory epithelium (regenerate throughout life)."),
 [("Olfactory receptor neuron", "mitral and tufted cells in the glomeruli of the olfactory bulb"), ("Mitral/tufted cell", "piriform cortex, amygdala, entorhinal cortex, olfactory tubercle (via the lateral olfactory stria); anterior olfactory nucleus and contralateral bulb (via the medial stria and anterior commissure)"), ("Piriform cortex neuron", "orbitofrontal cortex via the mediodorsal thalamus (secondary olfactory cortex); hypothalamus")],
 ("Anterior commissure (partial)", "anterior-commissure", "Mostly ipsilateral; some fibers cross to the opposite bulb."),
 [("cn-01-olfactory", None, "ipsilateral", "olfactory filaments through the cribriform plate"), ("lobe-frontal", "cortex-orbitofrontal-l", "ipsilateral", "olfactory bulb and tract in the olfactory sulcus of the orbital surface"), ("gyrus-parahippocampal-uncus", "uncus-l", "ipsilateral", "primary olfactory (piriform) cortex of the uncus via the lateral stria"), ("amygdala", "amygdala-l", "ipsilateral", "corticomedial amygdala"), ("thalamus-mediodorsal", "thalamus-mediodorsal-l", "ipsilateral", "relay to the orbitofrontal cortex for conscious odour identification")],
 "Piriform cortex (uncus), amygdala, entorhinal cortex and, via the mediodorsal thalamus, the orbitofrontal cortex; hypothalamus for feeding and reproductive responses.",
 [("Olfactory epithelium (rhinitis, viral infection, toxins)", "Anosmia or hyposmia, often bilateral; the commonest cause", "bilateral"), ("Olfactory filaments (cribriform plate fracture)", "Post-traumatic anosmia, often permanent", "bilateral"), ("Olfactory bulb or tract (meningioma, frontal tumor)", "Unilateral anosmia, often unnoticed, with frontal signs", "ipsilateral"), ("Uncus / medial temporal lobe (seizures)", "Olfactory hallucinations (uncinate fits), usually unpleasant", "n/a"), ("Neurodegeneration (Parkinson, Alzheimer)", "Early hyposmia preceding motor or cognitive symptoms", "bilateral")],
 ["Test smell in every patient with personality change: a subfrontal meningioma announces itself here", "Olfactory hallucinations are almost always temporal lobe seizures, not psychiatric"],
 [R("sp-olfactory"), R("sp-olfactory-testing"), R("sp-olfactory-training")], meshes=["uncus-l", "uncus-r", "amygdala-l", "amygdala-r"], syndromes=["syn-anosmia"]))

E.append(pw("pathway-gustatory", "Gustatory pathway", "gustatory", "taste",
 "Taste buds on the anterior two-thirds of the tongue signal through the chorda tympani of the facial nerve, those on the posterior third through the glossopharyngeal nerve, and those on the epiglottis and pharynx through the vagus; all these fibers, with cell bodies in the geniculate, petrosal and nodose ganglia, end in the rostral part of the nucleus of the solitary tract. Second-order axons ascend mainly uncrossed in the central tegmental tract to the ventral posteromedial thalamus and then to the gustatory cortex in the frontal operculum and anterior insula, with connections to the orbitofrontal cortex where taste and smell combine into flavour. Loss of taste therefore localizes to the peripheral nerves far more often than to the brain.",
 (["ganglion-geniculate", "nucleus-solitarius"], "Taste receptor cells; first-order neurons in the geniculate (VII), petrosal (IX) and nodose (X) ganglia."),
 [("Ganglion cell of VII, IX or X", "rostral (gustatory) nucleus of the solitary tract"), ("Solitary nucleus neuron", "VPM thalamus (parvocellular) via the central tegmental tract, mostly ipsilateral"), ("VPM neuron", "gustatory cortex in the frontal operculum and anterior insula")],
 None,
 [("ganglion-geniculate", None, "ipsilateral", "chorda tympani for the anterior tongue"), ("cn-09-glossopharyngeal", None, "ipsilateral", "posterior tongue"), ("nucleus-solitarius", "brainstem", "ipsilateral", "rostral gustatory nucleus in the medulla"), ("level-pons-rostral", "brainstem", "ipsilateral", "central tegmental tract"), ("thalamus-vpm", "thalamus-ventral-posterior-ventrolateral-l", "ipsilateral", "parvocellular VPM"), ("insula", "insula-l", "ipsilateral", "anterior insula and frontal operculum: primary gustatory cortex")],
 "Primary gustatory cortex in the anterior insula and frontal operculum; orbitofrontal cortex for flavour; hypothalamus and amygdala for appetite and aversion.",
 [("Chorda tympani / facial nerve proximal to the chorda", "Loss of taste on the anterior two-thirds of the ipsilateral tongue (with facial palsy in Bell palsy)", "ipsilateral"), ("Glossopharyngeal nerve", "Loss of taste on the posterior tongue, rarely noticed", "ipsilateral"), ("Solitary nucleus (lateral medulla)", "Ipsilateral ageusia with the other lateral medullary signs", "ipsilateral"), ("Thalamus or insular cortex", "Contralateral or bilateral taste disturbance, usually subtle", "n/a"), ("Middle ear surgery or lingual nerve injury", "Metallic taste or loss on the anterior tongue", "ipsilateral")],
 ["Most 'loss of taste' is loss of smell: test both", "Taste loss with a facial palsy puts the lesion above the chorda tympani, in the mastoid segment or higher"],
 [R("sp-neural-taste-pathway"), R("sp-nucleus-gustatory"), R("sp-taste")], meshes=["brainstem", "insula-l", "insula-r"], syndromes=["syn-facial-palsy-peripheral-vs-central", "syn-wallenberg-lateral-medullary"]))

write(E)
