import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).parent))
from synlib import *
E = []

E.append(syn("syn-brown-sequard", "Brown-Séquard syndrome (hemicord)", "traumatic", ["spinal-cord", "spinal-white-columns", "spinal-grey-anterior-horn", "spinal-nerve-root-dermatome"], "ipsilateral",
 "After a stab wound to the back, or with a lateral disc or tumor pressing on one side of the cord, a patient has weakness of the leg on one side with brisk reflexes and an upgoing toe, cannot feel a tuning fork or joint movement in that same leg, yet reports that pin-prick and cold are lost in the other leg, starting a couple of segments below the injury. At the level of the lesion itself there is a narrow band of complete sensory loss and flaccid weakness on the injured side.",
 [D("motor", "ipsilateral", "below the lesion", "Spastic weakness with hyperreflexia and extensor plantar (lateral corticospinal tract)", "pathway-lateral-corticospinal"), D("sensory-vibration-proprioception", "ipsilateral", "below the lesion", "Loss of vibration and position sense (posterior column)", "pathway-dcml"), D("sensory-pain-temp", "contralateral", "from 1–2 segments below the lesion downward", "Loss of pain and temperature (spinothalamic tract)", "pathway-lateral-spinothalamic"), D("motor", "ipsilateral", "at the level of the lesion", "Segmental lower motor neuron weakness and a band of anesthesia from anterior horn and root damage", "spinal-grey-anterior-horn")],
 "The three long tracts of the cord cross at different places, and a lesion of one half of the cord separates them. The lateral corticospinal tract has already crossed in the medulla, so it carries the motor command for the same side of the body, and cutting it produces ipsilateral upper motor neuron weakness below the lesion. The posterior columns carry uncrossed proprioceptive and vibration fibers, which cross only in the medulla after relaying in the gracile and cuneate nuclei, so their interruption gives ipsilateral loss of those modalities. The spinothalamic tract, by contrast, is formed by second-order fibers that crossed in the anterior white commissure within one or two segments of their entry, so it carries pain and temperature from the opposite side, and its section gives contralateral loss beginning a segment or two below the lesion, where the fibers entering at the lesion level have not yet crossed. Fibers crossing at the level of the lesion are caught on both sides, and the damaged dorsal root and anterior horn add an ipsilateral segmental band of complete sensory loss and flaccid weakness that marks the level exactly. Light touch survives on both sides because it travels by both routes. The dissociation, with weakness and proprioceptive loss on one side and pain loss on the other, is unique to the cord and cannot be produced by any brain lesion.",
 [pathol("Penetrating cord injury", "MRI", "Hemicord signal change and hemorrhage at the level of the wound on T2 and gradient echo; CT for bone and metal fragments.", sequence="T2"), pathol("Extramedullary compression", "MRI", "Lateral disc herniation, meningioma or schwannoma indenting one side of the cord with cord signal change.", sequence="T2"), pathol("Demyelination", "MRI", "Short, eccentric dorsolateral T2 lesion typical of multiple sclerosis, enhancing when acute.", sequence="T1+Gd")],
 ["Penetrating trauma", "Lateral cervical disc herniation or spondylosis", "Extramedullary tumor (meningioma, schwannoma)", "Multiple sclerosis (partial form)", "Radiation myelopathy, hemicord infarct"],
 [("Lateral medullary syndrome", "Facial sensory loss and cranial nerve signs; no limb weakness"), ("Peripheral nerve or plexus injury", "Lower motor neuron pattern, no contralateral sensory loss, no level"), ("Conversion disorder", "Sensory loss splits the midline exactly in all modalities and does not follow tract anatomy")],
 ["Spinal immobilization and urgent MRI when traumatic or compressive; surgical decompression as indicated", "Methylprednisolone is not routinely used for traumatic cord injury", "Prognosis for walking is the best of the incomplete cord syndromes"],
 [R("sp-brown-s-quard-syndrome"), R("sp-brown-syndrome"), R("sp-peripheral-nerve-injury")], marker=sphere(-4, -45, -80, 8), imagingHint=hint("axial", -4, -45, -80, "one half of the cervical cord"), preset="posterior", eponyms=["Brown-Séquard syndrome", "hemisection of the cord"], exam=["Find the motor level: last normal muscle group", "Pin-prick from the feet upward on each side separately: the level will differ by side", "Vibration and joint position in each foot", "Reflexes and plantars", "Look for the narrow band of complete loss at the lesion"]))

E.append(syn("syn-anterior-cord", "Anterior cord syndrome (anterior spinal artery)", "vascular", ["anterior-spinal-artery", "spinal-grey-anterior-horn", "spinal-white-columns", "artery-adamkiewicz", "intermediolateral-column"], "bilateral",
 "During or after aortic surgery, or with sudden back pain in a patient with a dissecting aorta, both legs become paralyzed within minutes to hours. Pain and temperature sensation are lost below the level on both sides and the bladder does not empty, but the patient can still feel the position of the toes and a tuning fork on the ankle. Initially the legs are flaccid and areflexic; spasticity emerges over weeks.",
 [D("motor", "bilateral", "below the lesion", "Paraplegia or quadriplegia: flaccid at first (spinal shock), then spastic; segmental lower motor neuron signs at the level", "pathway-lateral-corticospinal"), D("sensory-pain-temp", "bilateral", "below the lesion", "Loss of pain and temperature with a sensory level", "pathway-lateral-spinothalamic"), D("sensory-vibration-proprioception", "bilateral", "preserved", "Vibration and position sense intact (posterior columns spared)", "pathway-dcml"), D("sphincter", "bilateral", "bladder and bowel", "Retention then reflex incontinence; autonomic dysfunction", "intermediolateral-column"), D("pain", "bilateral", "back", "Sudden severe back pain at onset in ischemic cases", "anterior-spinal-artery")],
 "A single anterior spinal artery, fed by the vertebral arteries above and by a few radicular arteries below, of which the artery of Adamkiewicz in the lower thoracic region is the largest, supplies the anterior two-thirds of the cord: the anterior horns, the lateral and anterior white columns with the corticospinal and spinothalamic tracts, and the intermediolateral columns. The posterior columns are fed by the paired posterior spinal arteries with their rich pial anastomosis. Occlusion of the anterior artery or of its dominant feeder therefore infarcts everything except the posterior columns, bilaterally, because the vessel is midline. The corticospinal tracts, having crossed in the medulla, serve the same-side limbs, and the spinothalamic tracts, having crossed in the cord, serve the opposite side, but since both sides of the cord are infarcted the weakness and the pain-temperature loss are simply bilateral below the lesion, with a level. The preserved vibration and proprioception, carried in the intact posterior columns, are the diagnostic dissociation. Because the mid-thoracic cord lies at the watershed between the cervical and lumbar radicular supplies, that is where ischemia strikes first during aortic clamping or hypotension. Spinal shock with flaccidity and areflexia precedes the emergence of spasticity as the isolated cord segments recover excitability.",
 [pathol("Spinal cord infarct", "MRI", "T2 hyperintensity of the anterior two-thirds of the cord over several segments with 'owl's eyes' anterior horn hyperintensity on axial images and restricted diffusion; may be normal in the first hours.", sequence="DWI"), pathol("Aortic pathology", "CTA", "Aortic dissection or aneurysm, or recent aortic surgery, involving the segmental artery origins.", sequence="CT contrast"), pathol("Vertebral body infarct", "MRI", "Coexisting bone marrow signal change in the adjacent vertebral body supports a vascular cause.", sequence="STIR")],
 ["Aortic dissection, aneurysm repair or clamping", "Profound hypotension", "Atherosclerotic or embolic occlusion of a radicular artery", "Fibrocartilaginous embolism", "Vertebral artery dissection (cervical cases)", "Disc herniation or burst fracture compressing the anterior cord"],
 [("Transverse myelitis", "Posterior columns also involved; slower onset; CSF inflammatory"), ("Guillain–Barré syndrome", "No sensory level, distal sensory symptoms, no sphincter loss early"), ("Epidural hematoma or abscess", "Compressive picture with all modalities; MRI shows the collection")],
 ["Emergency MRI; if the cause is compressive, surgery; if ischemic, maintain blood pressure and treat the aortic cause", "Lumbar CSF drainage and blood pressure augmentation in perioperative aortic cases", "Bladder catheterization, thromboprophylaxis and rehabilitation"],
 [R("sp-anterior-spinal-artery-syndrome"), R("sp-anterior-spinal-artery"), R("sp-spinal-cord-arteries")], arteryId="anterior-spinal-artery", marker=sphere(0, -45, -90, 8), imagingHint=hint("axial", 0, -45, -90, "anterior two-thirds of the cord"), preset="anterior"))

E.append(syn("syn-central-cord-syringomyelia", "Central cord syndrome and syringomyelia", "congenital", ["spinal-cord", "spinal-white-columns", "spinal-grey-anterior-horn", "cervical-enlargement", "cerebellar-tonsil"], "bilateral",
 "A young adult notices painless burns and cuts on the fingers, then weakness and wasting of the hands. Examination shows loss of pain and temperature over the shoulders, arms and upper chest in a cape distribution while light touch, vibration and position sense are normal in the same area; the arm reflexes are absent, the hand muscles are wasted, and later the legs become spastic. In an elderly person a hyperextension neck injury produces the acute version, with weakness of the arms far worse than the legs.",
 [D("sensory-pain-temp", "bilateral", "cape distribution over shoulders and arms (cervical syrinx)", "Dissociated loss of pain and temperature with preserved touch and proprioception", "pathway-lateral-spinothalamic"), D("motor", "bilateral", "hands and arms", "Lower motor neuron weakness, wasting and areflexia at the level of the cavity (anterior horns)", "spinal-grey-anterior-horn"), D("motor", "bilateral", "legs (later or in acute cases)", "Spastic paraparesis from the lateral corticospinal tracts; arms weaker than legs in acute central cord injury", "pathway-lateral-corticospinal"), D("autonomic", "bilateral", "hands, eye", "Trophic changes, Charcot joints, Horner syndrome from the intermediolateral column", "pathway-oculosympathetic")],
 "The center of the cord, around the central canal, is where the second-order pain and temperature fibers from both sides cross in the anterior white commissure before ascending in the spinothalamic tracts. A cavity that expands from the central canal (a syrinx) or a hemorrhagic contusion of the central gray in hyperextension injury destroys these crossing fibers over the segments involved, so pain and temperature are lost bilaterally in exactly those dermatomes, while the posterior columns, which carry vibration and proprioception uncrossed at the periphery of the cord, and the spinothalamic fibers from the lower body, which crossed below the lesion and are already ascending in the lateral funiculus, are spared: a suspended, dissociated sensory loss. In the cervical cord this produces the cape or shawl distribution. As the cavity widens it reaches the anterior horns, producing wasting and areflexia of the hands and arms at the level, and then the medial part of the lateral funiculus, where the arm fibers of the corticospinal tract lie closest to the center, so spasticity appears in the legs and weakness in the arms exceeds that in the legs; the sacral fibers of the spinothalamic tract lie outermost and are spared until late (sacral sparing). Involvement of the intermediolateral column adds a Horner syndrome. Most syrinxes are driven by obstruction of CSF flow at the foramen magnum by a Chiari malformation.",
 [pathol("Syringomyelia", "MRI", "Central cavity within the cord isointense to CSF on all sequences, extending over several segments, with a Chiari I malformation or a tumor at either end.", sequence="T2"), pathol("Acute central cord injury", "MRI", "Central cord T2 hyperintensity and swelling at C4–C6 with spondylotic canal narrowing and ligamentum flavum buckling after hyperextension.", sequence="T2"), pathol("Intramedullary tumor", "MRI", "Enhancing nodule (ependymoma, hemangioblastoma) at one end of a syrinx.", sequence="T1+Gd")],
 ["Chiari I malformation with syringomyelia", "Post-traumatic or post-inflammatory syrinx", "Intramedullary tumor", "Acute hyperextension injury in a spondylotic cervical spine"],
 [("Cervical spondylotic myelopathy", "Posterior columns involved; no dissociated loss; gradual"), ("Brachial plexus or ulnar neuropathy", "Sensory loss follows nerve territory, all modalities"), ("Motor neuron disease", "No sensory loss at all"), ("Leprosy", "Nerve thickening, skin lesions, dissociated loss in a patchy distribution")],
 ["MRI of the whole neuraxis with contrast; posterior fossa decompression for a Chiari-related syrinx, shunting or tumor removal otherwise", "Protect insensate hands from burns", "Acute central cord injury: immobilization, blood pressure support; surgery for ongoing compression"],
 [R("sp-central-cord-syndrome"), R("sp-syringomyelia")], marker=sphere(0, -45, -85, 6), imagingHint=hint("sagittal", 0, -45, -85, "central cervical cord"), preset="posterior", eponyms=["Schneider syndrome (acute)"]))

E.append(syn("syn-posterior-cord-subacute-combined", "Posterior cord syndrome and subacute combined degeneration", "metabolic-toxic", ["spinal-white-columns", "spinal-cord", "posterior-spinal-arteries", "dorsal-root-ganglion"], "bilateral",
 "A patient who has had a gastrectomy, is a vegan, or takes metformin or uses nitrous oxide complains of tingling feet and unsteadiness in the dark. Examination shows loss of vibration and joint position sense in the feet with a positive Romberg test, brisk knee reflexes with absent ankle reflexes and extensor plantars, and a stamping gait; the electric shock down the spine on neck flexion (Lhermitte) may be present. Untreated, spastic paraparesis and dementia follow.",
 [D("sensory-vibration-proprioception", "bilateral", "legs then arms", "Loss of vibration and position sense with sensory ataxia and positive Romberg (posterior columns)", "pathway-dcml"), D("motor", "bilateral", "legs", "Spastic weakness with extensor plantars (lateral corticospinal tracts)", "pathway-lateral-corticospinal"), D("reflex", "bilateral", "legs", "Mixed picture: brisk knees with absent ankles when a peripheral neuropathy coexists", "dorsal-root-ganglion"), D("sensory-pain-temp", "bilateral", "preserved", "Pain and temperature relatively spared", "pathway-lateral-spinothalamic"), D("cognitive", "n/a", "cerebral white matter", "Memory loss, irritability, dementia in vitamin B12 deficiency", "corona-radiata")],
 "The posterior columns carry uncrossed proprioceptive and vibration fibers from the ipsilateral leg (fasciculus gracilis, medially) and arm (fasciculus cuneatus, laterally) to the medulla, where they cross; bilateral damage in the cord therefore produces bilateral loss of those modalities below the lesion without any crossed pattern, and the loss of position sense removes the feedback that keeps the patient upright when vision is removed, hence the Romberg sign and the worsening in the dark. Vitamin B12 is needed for the methylation reactions that maintain myelin, and its deficiency produces a vacuolar demyelination that begins in the large, heavily myelinated fibers of the posterior columns at the cervical and upper thoracic levels and then involves the lateral corticospinal tracts, hence 'combined': proprioceptive loss plus spastic weakness, with the spinothalamic tracts largely spared. Because the same deficiency causes a peripheral neuropathy, the ankle reflexes may be lost while the knees are brisk, and because the cerebral white matter and optic nerves are also affected, cognitive change and visual loss can accompany the myelopathy. Nitrous oxide inactivates B12 and produces the same syndrome acutely. Copper deficiency, HIV vacuolar myelopathy and tabes dorsalis attack the same columns, and posterior spinal artery infarction is a rare vascular cause.",
 [pathol("Subacute combined degeneration", "MRI", "Symmetric T2 hyperintensity of the posterior columns over the cervical and upper thoracic cord, an 'inverted V' on axial images, without enhancement; may resolve with treatment.", sequence="T2"), pathol("Tabes dorsalis", "MRI", "Posterior column atrophy and signal change in late syphilis; CSF VDRL positive.", sequence="T2"), pathol("Posterior spinal artery infarct", "MRI", "Acute restricted diffusion confined to the posterior columns after vertebral dissection or surgery.", sequence="DWI")],
 ["Vitamin B12 deficiency (pernicious anemia, gastrectomy, veganism, metformin, nitrous oxide abuse)", "Copper deficiency (zinc excess, bariatric surgery)", "Tabes dorsalis", "HIV vacuolar myelopathy", "Friedreich ataxia", "Posterior spinal artery infarct"],
 [("Sensory polyneuropathy", "Distal loss of all modalities with areflexia and no upper motor neuron signs"), ("Cervical spondylotic myelopathy", "Neck pain, radicular arm symptoms, compressive cord lesion on MRI"), ("Multiple sclerosis", "Relapsing course, asymmetric lesions, brain MRI")],
 ["Check B12, methylmalonic acid and homocysteine, plus copper and syphilis serology; treat empirically with parenteral B12 while awaiting results", "Stop nitrous oxide exposure", "Neurological recovery depends on the duration of deficiency; treat before the anemia appears"],
 [R("sp-spinal-cord-subacute-combined-degeneration"), R("sp-posterior-column")], marker=sphere(0, -50, -85, 6), imagingHint=hint("axial", 0, -50, -85, "posterior columns of the cervical cord"), preset="posterior", eponyms=["subacute combined degeneration of the cord"]))

E.append(syn("syn-complete-transection-spinal-shock", "Complete cord transection and spinal shock", "traumatic", ["spinal-cord", "spinal-white-columns", "spinal-grey-anterior-horn", "intermediolateral-column", "conus-medullaris"], "bilateral",
 "After a fall or a road accident the patient cannot move or feel anything below the level of the injury. For the first days to weeks the legs are flaccid, all reflexes below the level are absent, the bladder is distended and painless, the bowel is silent and, in cervical injuries, the blood pressure is low with a slow pulse and the skin warm. Then the reflexes return and become exaggerated, the legs stiffen and flex in spasms, and the bladder empties reflexly and unpredictably.",
 [D("motor", "bilateral", "all muscles below the level", "Complete paralysis: flaccid in spinal shock, then spastic with clonus and flexor spasms", "pathway-lateral-corticospinal"), D("sensory-light-touch", "bilateral", "all modalities below the level", "Complete sensory loss with a sharp level; a band of hyperesthesia just above", "pathway-dcml"), D("reflex", "bilateral", "below the level", "Areflexia in spinal shock; later hyperreflexia, extensor plantars, mass reflex", "spinal-grey-anterior-horn"), D("sphincter", "bilateral", "bladder, bowel, sexual function", "Retention with overflow, then reflex (spastic) bladder in lesions above the conus", "intermediolateral-column"), D("autonomic", "bilateral", "sympathetic outflow (lesions above T6)", "Neurogenic shock (hypotension, bradycardia) acutely; autonomic dysreflexia later", "sympathetic-trunk")],
 "Complete transection interrupts every ascending and descending tract at one level, so all sensation from below, whichever side it crossed on, and all motor commands to below, whichever side they came from, are lost bilaterally with a sharp sensory level that marks the segment. The level of the sensory loss on the trunk gives the segment, and the last working muscle group gives the motor level; a cervical lesion produces quadriplegia, a thoracic lesion paraplegia. Spinal shock is the temporary loss of all reflex activity in the isolated cord below the lesion, attributed to the sudden withdrawal of the tonic facilitation that descending reticulospinal and vestibulospinal pathways normally supply to spinal motor neurons and interneurons; without it the stretch reflex arcs, though anatomically intact, are silent, the bladder wall is atonic and, when the lesion lies above the sympathetic outflow at T1–T6, the loss of descending sympathetic drive causes vasodilatation and unopposed vagal bradycardia. Over days to weeks the isolated segments regain and then exceed their excitability through receptor upregulation and sprouting, producing spasticity, hyperreflexia, the mass reflex in which a small stimulus triggers flexor spasms, sweating and bladder emptying, and autonomic dysreflexia, in which a distended bladder or bowel below a high lesion provokes uncontrolled sympathetic discharge and severe hypertension because the cord's sympathetic neurons have no descending brake. Priapism and the bulbocavernosus reflex return early and their recovery marks the end of spinal shock.",
 [pathol("Cord transection or contusion", "MRI", "Cord discontinuity or extensive T2 hyperintensity with hemorrhage (T2* dark) at the fracture level; hematoma length predicts outcome.", sequence="T2"), pathol("Vertebral fracture-dislocation", "CT", "Burst fracture, facet dislocation or translation narrowing the canal; CT of the whole spine for other levels.", sequence="CT non-contrast"), pathol("Non-traumatic transverse lesion", "MRI", "Epidural abscess, metastasis or transverse myelitis producing the same complete syndrome over hours to days.", sequence="T1+Gd")],
 ["Vertebral fracture-dislocation", "Penetrating injury", "Metastatic epidural compression", "Epidural abscess or hematoma", "Transverse myelitis", "Cord infarct"],
 [("Incomplete cord syndromes", "Some function preserved below the level, sacral sparing"), ("Guillain–Barré syndrome", "No sensory level, ascending, cranial nerves involved, CSF protein raised"), ("Functional paralysis", "Inconsistent findings, normal reflexes and imaging")],
 ["Immobilize, maintain mean arterial pressure and oxygenation, and obtain CT and MRI urgently; early surgical decompression and stabilization", "Catheterize the bladder, prevent pressure sores and thromboembolism, protect the airway in cervical lesions", "Recognize and treat autonomic dysreflexia (sit the patient up, empty the bladder or bowel)"],
 [R("sp-spinal-cord-injuries"), R("sp-spinal-shock")], marker=sphere(0, -45, -100, 10), imagingHint=hint("sagittal", 0, -45, -100, "cervicothoracic cord"), preset="posterior", eponyms=["complete spinal cord injury"]))

E.append(syn("syn-conus-vs-cauda-equina", "Conus medullaris versus cauda equina syndrome", "compressive", ["conus-medullaris", "cauda-equina", "roots-l2-s1", "spinal-nerve-root-dermatome", "autonomic-sacral-parasympathetic"], "bilateral",
 "A patient with a large central lumbar disc prolapse has severe back and leg pain, numbness of the buttocks and perineum, weakness of both legs and cannot pass urine. In cauda equina syndrome the pain is severe and asymmetric, the weakness is flaccid and asymmetric with absent ankle reflexes, and the bladder is affected late; in a conus lesion the onset is sudden, saddle anesthesia and sphincter loss are early and symmetric, pain is mild, and the knee reflexes may be brisk. Both are emergencies.",
 [D("sensory-light-touch", "bilateral", "saddle area (S2–S5)", "Saddle anesthesia: symmetric and early in conus lesions, asymmetric and later in cauda equina", "roots-l2-s1"), D("sphincter", "bilateral", "bladder, bowel, sexual function", "Painless retention with overflow, fecal incontinence, impotence; early in conus, late in cauda equina", "autonomic-sacral-parasympathetic"), D("motor", "bilateral", "legs", "Conus: mild symmetric weakness, brisk knees possible; cauda: marked asymmetric flaccid weakness with areflexia", "cauda-equina"), D("pain", "bilateral", "back and legs", "Severe radicular pain in cauda equina; mild or absent in conus", "spinal-nerve-root-dermatome"), D("reflex", "bilateral", "sacral reflexes", "Absent anal and bulbocavernosus reflexes in both", "conus-medullaris")],
 "The spinal cord ends at the conus medullaris opposite L1–L2, and below that the lumbar and sacral roots hang as the cauda equina in the lumbar cistern. The conus contains the sacral segments S2–S5: the parasympathetic neurons for the bladder and rectum, the motor neurons for the sphincters and the sensory relay for the perineum, all packed into a centimeter or two of cord, so a lesion of the conus is symmetric and hits the sacral functions first and hardest, giving early saddle anesthesia and sphincter failure with little leg weakness, while the lumbar roots that have already left the cord above may be spared; if the lesion extends upward into the lumbar segments or spares the sacral roots that pass beside it, upper motor neuron signs such as brisk knee jerks can coexist. The cauda equina, by contrast, is a bundle of peripheral nerve roots, so its compression produces a lower motor neuron and radicular picture: severe pain in the distribution of the compressed roots, asymmetric flaccid weakness and areflexia, dermatomal sensory loss that becomes a saddle distribution as the lower sacral roots at the center of the bundle are engulfed, and sphincter loss that appears later because the sacral roots are the smallest and most central. Neither has a crossed component: both are bilateral because the structures involved lie in the midline of the canal. The distinction matters less than the recognition, since both require MRI within hours and decompression before the sphincters are permanently lost.",
 [pathol("Cauda equina compression", "MRI", "Large central disc extrusion, tumor or abscess filling the lumbar canal and compressing the roots; sagittal and axial T2 of the lumbar spine.", sequence="T2"), pathol("Conus lesion", "MRI", "Intramedullary tumor (ependymoma), infarct, demyelination or metastasis at T12–L1 with signal change in the conus; contrast needed.", sequence="T1+Gd"), pathol("Post-void residual", "US", "Bladder ultrasound showing retention above 200 mL supports the diagnosis and monitors recovery.", sequence="n/a")],
 ["Central lumbar disc herniation", "Spinal stenosis, trauma, epidural abscess or hematoma", "Metastasis or primary tumor (cauda: schwannoma, myxopapillary ependymoma; conus: ependymoma, metastasis)", "Ankylosing spondylitis, arachnoiditis", "Conus infarct"],
 [("Bilateral lumbosacral radiculopathy without sacral involvement", "No saddle anesthesia or sphincter change"), ("Lumbosacral plexopathy", "Unilateral, sphincters spared"), ("Cervical or thoracic myelopathy", "Sensory level higher, spasticity dominant")],
 ["Rectal examination, perineal sensation and a bladder scan in every patient with back pain and sphincter symptoms; emergency MRI of the whole spine", "Surgical decompression as soon as possible, ideally within 24–48 hours of sphincter involvement", "Catheterization and bowel management; MRI of the whole neuraxis for intramedullary lesions"],
 [R("sp-cauda-equina-and-conus-medullaris-syndromes"), R("sp-conus-medullaris"), R("sp-back-cauda-equina")], marker=sphere(0, -50, -160, 10), imagingHint=hint("sagittal", 0, -50, -160, "conus medullaris at T12–L1"), preset="posterior"))

E.append(syn("syn-cervical-spondylotic-myelopathy", "Cervical spondylotic myelopathy", "compressive", ["spinal-cord", "cervical-enlargement", "spinal-white-columns", "roots-c5-t1", "spinal-nerve-root-dermatome"], "bilateral",
 "An older patient reports that their hands have become clumsy, buttons are difficult and writing has deteriorated, while their family notices a stiff, unsteady gait. Examination shows wasting of the intrinsic hand muscles with absent or inverted reflexes at one cervical level, brisk reflexes below it with clonus, extensor plantars, a positive Hoffmann sign and reduced vibration sense in the feet; neck movement may be limited and painful.",
 [D("motor", "bilateral", "hands (at the level)", "Lower motor neuron weakness and wasting of the hands with reduced reflexes at the compressed segments", "spinal-grey-anterior-horn"), D("motor", "bilateral", "legs (below the level)", "Spastic paraparesis with hyperreflexia, clonus, Hoffmann sign and extensor plantars", "pathway-lateral-corticospinal"), D("sensory-vibration-proprioception", "bilateral", "legs and hands", "Reduced vibration and position sense, sensory ataxia, Lhermitte sign", "pathway-dcml"), D("gait", "bilateral", "gait", "Spastic, broad-based gait; frequent falls", "pathway-lateral-corticospinal"), D("sphincter", "bilateral", "bladder", "Urgency and frequency late", "intermediolateral-column")],
 "Degenerative disc bulging, osteophytes, facet hypertrophy and a thickened ligamentum flavum narrow the cervical canal, most often at C5–C6 and C6–C7, so that the cord is squeezed with every extension of the neck and its venous drainage and pial arteries are compromised. The compression damages the cord at the level of the stenosis and the long tracts passing through it. At the level, the anterior horn cells and the exiting roots are injured, producing lower motor neuron signs confined to those myotomes, typically wasting of the hand and forearm with loss of the corresponding reflex; the inverted supinator reflex, in which tapping the brachioradialis tendon produces finger flexion instead, shows a C5–C6 segmental lesion with hyperactive segments below. Below the level, the lateral corticospinal tracts, which crossed in the medulla and so serve the same side, are damaged bilaterally by the midline compression, giving spasticity and hyperreflexia in the legs, and the posterior columns, uncrossed until the medulla, give bilateral loss of vibration and proprioception. The spinothalamic tracts lie anterolaterally and are affected less. The combination of segmental lower motor neuron signs in the arms and upper motor neuron signs in the legs mimics motor neuron disease, but the sensory signs, the sphincter symptoms and the neck pain point to a compressive lesion.",
 [pathol("Cervical spondylotic myelopathy", "MRI", "Multilevel canal stenosis with cord flattening and intramedullary T2 hyperintensity at the most compressed level; T1 hypointensity implies irreversible change.", sequence="T2"), pathol("Ossification of the posterior longitudinal ligament", "CT", "Calcified ligament behind the vertebral bodies narrowing the canal, common in East Asian patients.", sequence="CT non-contrast"), pathol("Dynamic compression", "MRI", "Cord compression worsens in extension on flexion-extension imaging.", sequence="T2")],
 ["Degenerative cervical spondylosis", "Ossification of the posterior longitudinal ligament", "Congenitally narrow canal", "Rheumatoid atlantoaxial subluxation", "Disc herniation"],
 [("Amyotrophic lateral sclerosis", "No sensory signs, bulbar involvement, fasciculations widespread; EMG shows denervation in unaffected regions"), ("Multiple sclerosis", "Relapsing course, brain lesions, optic neuritis"), ("Subacute combined degeneration", "Low B12, no compression on MRI"), ("Carpal tunnel and ulnar neuropathy", "Hand symptoms in a nerve distribution without leg signs")],
 ["MRI of the cervical spine; surgical decompression for progressive myelopathy or cord signal change", "Avoid neck hyperextension and contact sports", "Nerve conduction studies to exclude a coexisting peripheral entrapment"],
 [R("sp-cervical-myelopathy"), R("sp-cervical-spondylosis")], marker=sphere(0, -45, -80, 8), imagingHint=hint("sagittal", 0, -45, -80, "cervical cord at C5–C7"), preset="posterior"))

E.append(syn("syn-als-pattern", "Amyotrophic lateral sclerosis: mixed upper and lower motor neuron pattern", "degenerative", ["spinal-grey-anterior-horn", "gyrus-precentral", "hypoglossal-nucleus", "nucleus-ambiguus", "spinal-white-columns"], "bilateral",
 "A patient in their sixties develops weakness and wasting of one hand with twitching visible under the skin of the arms, and over months the weakness spreads to the other limbs and to the tongue, so that speech becomes slurred and swallowing difficult. Reflexes are brisk in wasted limbs, the jaw jerk is exaggerated and the plantars are extensor, yet there is no sensory loss, no sphincter disturbance and eye movements remain normal to the end.",
 [D("motor", "bilateral", "limbs, asymmetric at onset", "Lower motor neuron signs: wasting, fasciculation, cramps, weakness", "spinal-grey-anterior-horn"), D("reflex", "bilateral", "same limbs", "Upper motor neuron signs: hyperreflexia in wasted limbs, spasticity, Hoffmann, Babinski, brisk jaw jerk", "pathway-lateral-corticospinal"), D("bulbar", "bilateral", "tongue, palate, larynx", "Mixed bulbar and pseudobulbar palsy: wasted fasciculating tongue with a brisk jaw jerk, dysarthria, dysphagia, emotional lability", "pathway-corticobulbar"), D("sensory-light-touch", "n/a", "spared", "No sensory loss; sphincters and eye movements spared", "pathway-dcml"), D("other", "bilateral", "diaphragm", "Respiratory failure from diaphragm weakness; orthopnea", "nerve-phrenic")],
 "Motor neuron disease destroys both the upper motor neurons, the pyramidal cells of the motor cortex whose axons form the corticospinal and corticobulbar tracts, and the lower motor neurons in the anterior horns of the cord and the motor nuclei of the brainstem, while sparing everything else. Loss of the lower motor neurons denervates muscle, producing wasting, weakness and the spontaneous discharges of dying motor units seen as fasciculations; loss of the upper motor neurons removes the descending inhibition of the surviving spinal reflex arcs, producing hyperreflexia and extensor plantars. The unique combination of a brisk reflex in a wasted, fasciculating muscle can only occur when both neurons of the motor pathway degenerate together. The corticospinal tracts cross in the medulla and the disease is bilateral, so the upper motor neuron signs are widespread without a lateralizing pattern, though the disease begins focally and spreads to contiguous regions. The sensory pathways, the oculomotor nuclei and the sacral Onuf nucleus that supplies the sphincters are spared for reasons that are not fully understood, and their preservation is part of the diagnostic criteria: any sensory level, sphincter loss or ophthalmoplegia should prompt a search for another diagnosis, above all compressive cervical myelopathy, which produces a similar arm-and-leg pattern. Diagnosis requires upper and lower motor neuron signs in several body regions with EMG evidence of denervation in clinically unaffected muscles.",
 [pathol("Amyotrophic lateral sclerosis", "MRI", "Often normal; bilateral corticospinal tract T2/FLAIR hyperintensity from the corona radiata to the pons and a hypointense precentral gyrus rim on SWI in some. Cervical MRI is done to exclude myelopathy.", sequence="FLAIR"), pathol("Denervation", "EMG/NCS", "Fibrillations, positive sharp waves and fasciculations with large, unstable motor units in at least three regions; normal sensory conduction.", sequence="n/a")],
 ["Sporadic amyotrophic lateral sclerosis", "Familial (C9orf72, SOD1) ALS", "Progressive muscular atrophy (lower motor neuron only) or primary lateral sclerosis (upper only) variants"],
 [("Cervical spondylotic myelopathy with radiculopathy", "Sensory signs, neck pain, compression on MRI; no bulbar signs"), ("Multifocal motor neuropathy with conduction block", "Pure lower motor neuron, asymmetric, distal, treatable; conduction block on NCS"), ("Kennedy disease (spinobulbar muscular atrophy)", "X-linked, slow, gynecomastia, perioral fasciculations, mild sensory neuropathy"), ("Inclusion body myositis", "Finger flexor and quadriceps weakness; CK raised; biopsy")],
 ["Confirm with EMG and exclude mimics with cervical MRI and blood tests; riluzole and edaravone modestly slow progression", "Multidisciplinary care: respiratory monitoring with early non-invasive ventilation, gastrostomy before weight loss, communication aids", "Discuss prognosis and advance care planning early"],
 [R("sp-motor-neuron-disease"), R("sp-electrodiagnostic-evaluation-of-motor-neuron-disease"), R("sp-motor-neuron")], marker=structs("tract-corticospinal-l", "tract-corticospinal-r"), imagingHint=hint("axial", 0, -45, -85, "anterior horns and lateral columns of the cervical cord"), preset="posterior", eponyms=["motor neuron disease", "Lou Gehrig disease"]))

E.append(syn("syn-radiculopathy-cervical", "Cervical radiculopathy (C5–C8)", "radiculopathy", ["roots-c5-t1", "spinal-nerve-root-dermatome", "dorsal-root-ganglion", "plexus-brachial"], "ipsilateral",
 "Neck pain shoots down the arm in a band, worse when the head is turned and tilted toward that side, with tingling in specific fingers: the thumb for C6, the middle finger for C7, the little finger for C8. The corresponding reflex is lost, biceps and brachioradialis for C6, triceps for C7, and one muscle group is weak, deltoid and biceps for C5, wrist extensors for C6, triceps and finger extensors for C7, finger flexors and intrinsics for C8. Relief on placing the hand on the head is characteristic.",
 [D("pain", "ipsilateral", "neck to arm in a dermatomal band", "Radicular pain and paresthesias worsened by neck extension and rotation (Spurling sign), relieved by shoulder abduction", "spinal-nerve-root-dermatome"), D("sensory-light-touch", "ipsilateral", "dermatome (C5 lateral shoulder, C6 thumb, C7 middle finger, C8 little finger)", "Dermatomal sensory loss, often incomplete because of overlap", "dorsal-root-ganglion"), D("motor", "ipsilateral", "myotome", "Weakness in the root's muscles across more than one nerve territory (C5 deltoid/biceps, C6 biceps/wrist extensors, C7 triceps/wrist flexors, C8 finger flexors/intrinsics)", "roots-c5-t1"), D("reflex", "ipsilateral", "one reflex", "Reduced biceps and brachioradialis (C5–C6) or triceps (C7); C8 has no reflex", "roots-c5-t1")],
 "Each cervical spinal nerve leaves the canal through the intervertebral foramen above the vertebra of the same number (C6 exits between C5 and C6), so a C5–C6 disc herniation or foraminal osteophyte compresses the C6 root, and a C6–C7 lesion the C7 root, the two commonest. The root contains the dorsal root ganglion's central processes for one dermatome and the motor axons for one myotome, and because the myotome of a root is distributed among several peripheral nerves, root weakness crosses nerve territories, whereas nerve weakness crosses root territories: C7 weakness involves the triceps (radial nerve) and the wrist flexors (median nerve), which no single nerve lesion could produce. The lesion is proximal to the plexus, so it is strictly unilateral and ipsilateral. Pain follows the dermatome because the dorsal root is compressed and inflamed, and it is provoked by narrowing the foramen with extension and ipsilateral tilt and relieved by abducting the arm, which reduces tension on the root. The reflex arc runs through the root, so the reflex of that segment is lost while others remain, which localizes the level more reliably than sensory testing, since adjacent dermatomes overlap. Sparing of the sensory nerve action potential on nerve conduction studies distinguishes a preganglionic root lesion, where the dorsal root ganglion is intact, from a postganglionic plexus or nerve lesion, where it is lost.",
 [pathol("Foraminal disc herniation or spondylosis", "MRI", "Posterolateral disc protrusion or uncovertebral osteophyte narrowing the foramen and contacting the exiting root on axial T2; sagittal images through the foramina.", sequence="T2"), pathol("Root avulsion or tumor", "MRI", "Pseudomeningocele after traction injury; enhancing nerve sheath tumor enlarging the foramen.", sequence="T1+Gd"), pathol("Denervation", "EMG/NCS", "Denervation in muscles of one myotome across several nerves, including the paraspinals, with normal sensory nerve action potentials.", sequence="n/a")],
 ["Cervical disc herniation (younger)", "Foraminal spondylosis (older)", "Herpes zoster", "Nerve sheath tumor", "Traction injury", "Diabetic or inflammatory radiculitis"],
 [("Carpal tunnel syndrome (vs C6–C7)", "Sensory loss confined to the median territory, thenar weakness only, night symptoms, no neck pain"), ("Ulnar neuropathy (vs C8)", "Sensory loss in the little finger but sparing the medial forearm; no finger flexor weakness of the index"), ("Brachial neuritis (Parsonage–Turner)", "Severe pain first, then multi-root weakness with no compressive lesion"), ("Rotator cuff or shoulder disease", "Pain with shoulder movement, no neurological deficit")],
 ["Most disc-related radiculopathies resolve in weeks with analgesia and physiotherapy", "MRI for progressive weakness, myelopathic signs or pain unresponsive after 6–8 weeks; EMG when the level is unclear", "Foraminotomy or anterior discectomy for persistent deficit or intractable pain"],
 [R("sp-cervical-radiculopathy"), R("sp-electrodiagnostic-evaluation-of-cervical-radiculopathy"), R("sp-spinal-nerves")], marker=nerve("brachial-plexus-l"), imagingHint=hint("axial", -15, -45, -85, "cervical roots leaving the foramina"), preset="posterior"))

E.append(syn("syn-radiculopathy-lumbosacral", "Lumbosacral radiculopathy (L4, L5, S1)", "radiculopathy", ["roots-l2-s1", "spinal-nerve-root-dermatome", "cauda-equina", "dorsal-root-ganglion"], "ipsilateral",
 "A patient bends to lift something and feels pain in the back that shoots down the back of the leg into the foot, worse on coughing, sitting and bending, with tingling in the big toe or the little toe. Raising the straight leg reproduces the pain at thirty degrees. The findings give the root: weak dorsiflexion of the ankle and toes with numbness of the dorsum of the foot for L5, absent ankle reflex with weak plantar flexion and numbness of the lateral foot for S1, weak quadriceps with a reduced knee jerk and numbness of the medial leg for L4.",
 [D("pain", "ipsilateral", "back to leg in a dermatomal band (sciatica)", "Radicular pain worse on sitting, bending and Valsalva; positive straight leg raise (L5, S1) or femoral stretch test (L4)", "spinal-nerve-root-dermatome"), D("sensory-light-touch", "ipsilateral", "dermatome (L4 medial leg, L5 dorsum of the foot and big toe, S1 lateral foot and sole)", "Dermatomal sensory loss", "dorsal-root-ganglion"), D("motor", "ipsilateral", "myotome", "L4 quadriceps; L5 extensor hallucis longus, tibialis anterior, hip abductors; S1 plantar flexors and gluteus maximus", "roots-l2-s1"), D("reflex", "ipsilateral", "knee (L4) or ankle (S1)", "Reduced knee jerk (L4) or ankle jerk (S1); L5 has no reliable reflex", "roots-l2-s1")],
 "In the lumbar spine the roots descend within the canal for several segments before exiting, so a posterolateral disc herniation at one level compresses the root that is passing by on its way to the foramen one level below: an L4–L5 disc pinches the L5 root and an L5–S1 disc the S1 root, which are the two commonest patterns, whereas a far lateral disc catches the root exiting at that level. The compressed root is inflamed and mechanically sensitive, so stretching it by raising the straight leg, which tenses the sciatic nerve and the L5 and S1 roots, reproduces the pain, and raising the opposite leg (crossed straight leg raise) is a specific though less sensitive sign; the L4 root is stretched instead by extending the hip with the knee flexed. The pattern is strictly ipsilateral because the lesion is proximal to the plexus, and it distinguishes itself from a peripheral neuropathy by crossing nerve territories: L5 weakness involves the tibialis anterior and extensor hallucis (deep peroneal nerve) together with the hip abductors (superior gluteal nerve) and the ankle invertor (tibial nerve), which no single nerve lesion produces, and this is how an L5 radiculopathy is separated from the common peroneal palsy that also causes foot drop. The reflex arcs run through the roots, so the ankle reflex is lost with S1 and the knee reflex with L4. A large central disc herniation can compress the whole cauda equina and must be excluded by asking about perineal numbness and bladder function.",
 [pathol("Lumbar disc herniation", "MRI", "Posterolateral extrusion at L4–L5 or L5–S1 displacing the traversing root in the lateral recess on axial T2; far lateral discs compress the exiting root in the foramen.", sequence="T2"), pathol("Foraminal stenosis and spondylolisthesis", "MRI", "Facet hypertrophy and slip narrowing the foramen and compressing the exiting root, seen on sagittal images.", sequence="T2"), pathol("Denervation", "EMG/NCS", "Denervation in a myotomal distribution including paraspinal muscles with normal sural and superficial peroneal sensory responses.", sequence="n/a")],
 ["Lumbar disc herniation", "Degenerative foraminal stenosis and spondylolisthesis", "Synovial cyst", "Herpes zoster", "Diabetic radiculoplexus neuropathy", "Metastasis or nerve sheath tumor"],
 [("Common peroneal neuropathy (vs L5)", "Foot drop with sparing of inversion and hip abduction; sensory loss over the dorsum only; conduction block at the fibular head"), ("Hip or sacroiliac disease", "Pain with joint movement, no neurological deficit"), ("Lumbosacral plexopathy", "Multiple roots' territories, often painful, with weight loss or diabetes"), ("Cauda equina syndrome", "Bilateral, saddle anesthesia, sphincter involvement: emergency")],
 ["Most cases settle within 6–12 weeks with activity as tolerated and analgesia; urgent imaging only for red flags (sphincter symptoms, progressive weakness, cancer, infection)", "MRI and surgical referral for persistent severe pain or progressive deficit; discectomy speeds recovery in selected patients", "Epidural steroid injection for short-term relief"],
 [R("sp-sciatica"), R("sp-spinal-nerves")], marker=structs("cauda-equina"), imagingHint=hint("sagittal", 0, -50, -165, "lumbosacral roots below the conus"), preset="posterior", eponyms=["sciatica"]))

write(E)
