import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).parent))
from synlib import *
E = []
S6 = lambda a, b=None: C("snell", 6, a, b)
S11 = lambda a, b=None: C("snell", 11, a, b)
B8 = lambda a, b=None: C("berkowitz", 8, a, b)
B10 = lambda a, b=None: C("berkowitz", 10, a, b)
B11 = lambda a, b=None: C("berkowitz", 11, a, b)
B13 = lambda a, b=None: C("berkowitz", 13, a, b)

E.append(syn("syn-cerebellar-hemispheric", "Cerebellar hemisphere syndrome", "functional-pattern", ["cerebellar-hemisphere", "dentate-nucleus", "superior-cerebellar-peduncle", "cerebellum"], "ipsilateral",
 "The patient's arm and leg on one side are clumsy: the finger overshoots the target and wobbles as it approaches, rapid alternating movements are irregular, the heel slides off the shin, and the outstretched arm rebounds when released. Speech is slurred and scanning, the eyes show nystagmus that is coarser on looking toward the affected side, and the gait veers toward that side. Strength and sensation are normal and reflexes are pendular.",
 [D("cerebellar", "ipsilateral", "arm and leg", "Dysmetria, intention tremor, dysdiadochokinesia, rebound, hypotonia", "pathway-cerebellar-circuits"), D("cerebellar", "n/a", "speech", "Scanning, slurred dysarthria", "cerebellar-hemisphere"), D("oculomotor", "ipsilateral", "gaze holding", "Gaze-evoked nystagmus, coarser toward the lesion; saccadic dysmetria", "flocculonodular-lobe"), D("gait", "ipsilateral", "gait", "Veering and falling toward the side of the lesion", "cerebellar-hemisphere")],
 "Each cerebellar hemisphere coordinates the limbs of its own side, a consequence of double crossing: its output through the dentate nucleus and superior cerebellar peduncle decussates in the midbrain to reach the contralateral thalamus and motor cortex, and the motor cortex then acts on the body through the corticospinal tract, which crosses back in the medulla. Signs of a hemispheric lesion are therefore ipsilateral, and any 'crossed' cerebellar sign means the lesion has moved above the decussation into the midbrain, thalamus or cortex. The lateral hemisphere and dentate plan and time skilled multi-joint movements, so their loss produces dysmetria, intention tremor and the decomposition of movement, while hypotonia and pendular reflexes reflect the loss of cerebellar facilitation of the motor cortex and gamma motor neurons. The cerebellum does not initiate movement or carry sensation, so power, reflex grading and sensation are normal and the deficit is one of accuracy. Nystagmus and the slow saccades reflect involvement of the flocculus and vermis or the outflow to the ocular motor nuclei. Acute unilateral causes are vascular; chronic unilateral causes are tumors, abscess and demyelination.",
 [pathol("Cerebellar infarct", "MRI", "Restricted diffusion in the PICA, AICA or SCA territory of the hemisphere; watch for swelling.", sequence="DWI"), pathol("Cerebellar tumor", "MRI", "Enhancing hemispheric mass (metastasis, hemangioblastoma with a cyst and mural nodule, pilocytic astrocytoma in children).", sequence="T1+Gd"), pathol("Cerebellar abscess", "MRI", "Ring-enhancing lesion with central restricted diffusion, often from otitis or mastoiditis.", sequence="DWI")],
 ["Cerebellar infarct or hemorrhage", "Metastasis or primary tumor", "Abscess", "Multiple sclerosis"],
 [("Sensory ataxia", "Worse with the eyes closed (Romberg), reduced vibration and position sense, absent reflexes"), ("Contralateral thalamic or frontal lesion", "Ataxia contralateral to the lesion, other cortical or thalamic signs"), ("Vestibular lesion", "Vertigo, no limb dysmetria")],
 ["Treat the cause; monitor acute lesions for posterior fossa swelling", "Physiotherapy with weighted tools and gait aids", "Avoid sedatives and alcohol, which unmask cerebellar dysfunction"],
 [S6(241, 244), B8(67, 73)], marker=structs("cerebellar-hemisphere-l"), imagingHint=hint("axial", -35, -60, -35, "cerebellar hemisphere"), preset="posterior", exam=["Finger-nose with the target moved; look for terminal tremor and overshoot", "Rapid alternating hand movements", "Heel-shin", "Rebound of the outstretched arms", "Tandem gait and direction of veering", "Gaze-evoked nystagmus in each direction"]))

E.append(syn("syn-cerebellar-vermian-midline", "Midline (vermian) cerebellar syndrome", "functional-pattern", ["cerebellar-vermis", "flocculonodular-lobe", "fastigial-nucleus", "cerebellum"], "midline",
 "The patient cannot stand or walk without a wide base and falls in any direction, yet when lying in bed the finger-nose and heel-shin tests are almost normal. A child with a midline tumor presents with morning headache, vomiting and a stumbling gait; an alcoholic with anterior vermian degeneration presents with a gait ataxia that has developed over years while the arms remain coordinated. Head titubation and truncal sway when sitting are common.",
 [D("gait", "bilateral", "trunk and gait", "Truncal and gait ataxia with a wide base, inability to tandem walk, falls in all directions", "cerebellar-vermis"), D("cerebellar", "bilateral", "trunk", "Titubation and truncal sway on sitting; limbs relatively spared", "fastigial-nucleus"), D("vestibular", "bilateral", "vestibulocerebellum", "Positional vertigo, downbeat or periodic alternating nystagmus, impaired VOR suppression", "flocculonodular-lobe"), D("other", "n/a", "fourth ventricle", "Headache and vomiting from hydrocephalus in mass lesions", "ventricle-fourth")],
 "The vermis and the flocculonodular lobe receive spinocerebellar and vestibular input that is uncrossed and bilateral, and send their output through the fastigial nuclei to the vestibular and reticular nuclei of both sides, which drive the vestibulospinal and reticulospinal tracts that keep the trunk upright. A midline lesion therefore produces a symmetric disorder of balance and gait without lateralization, and because the lateral hemispheres and dentate nuclei that coordinate the limbs are spared, the limbs test surprisingly well when the trunk is supported: this dissociation between severe truncal ataxia and mild limb ataxia is the signature of a vermian lesion. There is no ipsilateral or contralateral rule to apply, because the affected structures are midline and project bilaterally. The nodulus and flocculus calibrate the vestibulo-ocular reflex and hold gaze, so their involvement produces positional nystagmus and vertigo that mimic a peripheral vestibular disorder, and the vermis lies over the fourth ventricle, so midline tumors in children obstruct CSF flow early. The anterior vermis degenerates selectively in chronic alcohol exposure, producing a leg-and-gait syndrome with spared arms.",
 [pathol("Medulloblastoma", "MRI", "Enhancing midline mass arising from the vermis filling the fourth ventricle with hydrocephalus in a child; restricted diffusion because it is cellular.", sequence="T1+Gd"), pathol("Alcoholic cerebellar degeneration", "MRI", "Atrophy of the anterior superior vermis with widened folia on sagittal images.", sequence="T1"), pathol("Vermian infarct", "MRI", "Restricted diffusion in the vermis (SCA or PICA medial branches).", sequence="DWI")],
 ["Medulloblastoma or ependymoma in children", "Alcoholic cerebellar degeneration", "Paraneoplastic cerebellar degeneration", "Vermian infarct or hemorrhage", "Phenytoin toxicity"],
 [("Sensory ataxia", "Romberg markedly positive; vibration and position sense lost"), ("Bilateral vestibular loss", "Oscillopsia with head movement; no titubation"), ("Normal pressure hydrocephalus", "Magnetic gait with cognitive change and incontinence, ventriculomegaly without atrophy")],
 ["Urgent imaging in a child with gait ataxia and headache; neurosurgical management of posterior fossa tumors", "Thiamine and abstinence in alcohol-related degeneration", "Gait and balance rehabilitation"],
 [S6(241, 244), B8(67, 73)], marker=structs("cerebellar-vermis-vi"), imagingHint=hint("sagittal", 0, -60, -30, "cerebellar vermis over the fourth ventricle"), preset="lateral-l"))

E.append(syn("syn-chiari-tonsillar-ectopia", "Chiari I malformation and tonsillar ectopia", "congenital", ["cerebellar-tonsil", "level-medulla-olive", "spinal-cord", "subarachnoid-space-cisterns"], "midline",
 "A young adult has occipital headaches that are triggered by coughing, straining or laughing and last seconds to minutes. Over time they notice that their hands are numb to heat and they have burned themselves without pain, a cape-like loss from an associated syrinx. Examination may show downbeat nystagmus, a lower cranial nerve palsy, limb ataxia or spastic legs. Many cases are incidental findings on MRI.",
 [D("pain", "n/a", "occiput", "Cough-induced occipital headache (Valsalva-related)", "cerebellar-tonsil"), D("sensory-pain-temp", "bilateral", "cape distribution over arms and shoulders", "Dissociated loss from an associated cervical syrinx", "pathway-lateral-spinothalamic"), D("oculomotor", "bilateral", "downbeat", "Downbeat nystagmus from cervicomedullary compression", "flocculonodular-lobe"), D("cranial-nerve", "bilateral", "lower cranial nerves", "Dysphagia, hoarseness, sleep apnea from medullary compression", "nucleus-ambiguus")],
 "In Chiari I malformation the cerebellar tonsils lie more than about five millimeters below the foramen magnum, crowding the cervicomedullary junction and obstructing the normal to-and-fro movement of CSF between the cranial and spinal compartments with each heartbeat and each Valsalva maneuver. The transient pressure difference across the foramen during coughing displaces the tonsils further and stretches the dura and lower cranial nerve roots, producing the characteristic short occipital headaches. The obstruction also drives CSF into the central canal of the cervical cord, producing syringomyelia in a substantial fraction of patients; the expanding cavity first destroys the fibers of the spinothalamic tract crossing in the anterior white commissure, which gives the bilateral dissociated loss of pain and temperature in the arms and shoulders with preserved touch and proprioception, before spreading to the anterior horns and lateral columns. Compression of the medulla and the lower cerebellum accounts for downbeat nystagmus, lower cranial nerve palsies and ataxia; because the compressed structures are midline, most signs are bilateral and there is no lateralizing rule. The malformation is often silent, and an incidental ectopia without a syrinx or symptoms needs only observation.",
 [pathol("Tonsillar ectopia", "MRI", "Peg-shaped cerebellar tonsils extending more than 5 mm below the basion–opisthion line on a sagittal T1 image, with crowding of the foramen magnum and effacement of the cisterna magna.", sequence="T1"), pathol("Syringomyelia", "MRI", "Central CSF-intensity cavity within the cervical (or thoracic) cord on sagittal T2; check the entire cord.", sequence="T2"), pathol("CSF flow study", "MRI", "Reduced or absent pulsatile CSF flow at the foramen magnum on phase-contrast cine imaging.", sequence="n/a")],
 ["Congenital small posterior fossa", "Intracranial hypotension (acquired tonsillar descent, reversible)", "Raised intracranial pressure from a mass (acquired, an emergency)", "Lumboperitoneal shunting"],
 [("Cough headache of other cause", "Normal MRI"), ("Tonsillar herniation from a mass", "Acute, with drowsiness and a supratentorial or posterior fossa lesion"), ("Intracranial hypotension", "Orthostatic headache with dural enhancement and slumping of the brainstem")],
 ["Observation for asymptomatic ectopia without a syrinx", "Posterior fossa decompression for symptomatic patients or a progressive syrinx", "Do not perform a lumbar puncture when the tonsils are low without considering the risk of further descent"],
 [C("snell", 5, 215), C("snell", 18, 513), C("berkowitz", 5, 44), C("berkowitz", 12, 112), C("berkowitz", 30, 270)], marker=structs("cerebellar-tonsil-l", "cerebellar-tonsil-r"), imagingHint=hint("sagittal", 0, -45, -55, "cerebellar tonsils at the foramen magnum"), preset="lateral-l", eponyms=["Chiari I malformation", "Arnold–Chiari malformation (type II)"]))

E.append(syn("syn-cn3-palsy", "Oculomotor nerve palsy: pupil-involving versus pupil-sparing", "compressive", ["cn-03-oculomotor", "oculomotor-nucleus", "artery-pcom", "sinus-cavernous"], "ipsilateral",
 "A patient presents with a drooping eyelid; when it is lifted, the eye is turned down and out and cannot look up, down or in, and the patient sees double. In one version the pupil on that side is large and does not react to light and the patient has a severe headache: this is an aneurysm until proven otherwise. In the other version, in a diabetic or hypertensive patient with periorbital ache, the pupil is normal and the palsy resolves in weeks.",
 [D("oculomotor", "ipsilateral", "medial, superior, inferior rectus and inferior oblique", "Eye down and out with loss of adduction, elevation and depression; diplopia", "cn-03-oculomotor"), D("other", "ipsilateral", "levator palpebrae", "Complete ptosis", "cn-03-oculomotor"), D("pupil", "ipsilateral", "one pupil", "Fixed dilated pupil (compressive) or spared pupil (ischemic)", "pathway-pupillary-light-reflex")],
 "The oculomotor nerve is the final, uncrossed motor pathway to four extraocular muscles, the levator and the pupillary sphincter, so all signs are on the side of the nerve. The parasympathetic pupillary fibers travel on the surface of the nerve, superomedially, immediately beneath the posterior communicating artery as the nerve passes forward from the interpeduncular fossa toward the cavernous sinus; an enlarging aneurysm at the junction of the internal carotid and posterior communicating arteries, an expanding uncus during herniation, or a tumor presses on these outer fibers first, so the pupil dilates early and sometimes before the muscles are affected. The vasa nervorum that fail in diabetes and hypertension supply the core of the nerve, where the somatic motor fibers run, while the surface pupillary fibers are nourished by the surrounding CSF and pial vessels and survive, hence a complete external palsy with a normal pupil. The rule is not absolute: partial or early compression can spare the pupil for a time, and ischemia occasionally involves it slightly, so a pupil-sparing but incomplete palsy, or a spared pupil that later dilates, still requires imaging of the posterior communicating artery. A nuclear lesion produces a different pattern with bilateral ptosis and contralateral superior rectus weakness, because those subnuclei are shared or crossed.",
 [pathol("Posterior communicating artery aneurysm", "CTA", "Saccular aneurysm at the ICA–PComm junction abutting the third nerve; CTA is the first test, catheter angiography if negative with high suspicion.", sequence="CT contrast", timing="Emergency"), pathol("Ischemic (microvascular) palsy", "MRI", "Normal nerve; imaging is done to exclude other causes and shows small vessel disease at most. Recovery in 6–12 weeks.", sequence="T1+Gd"), pathol("Uncal herniation", "CT", "Supratentorial mass with medial temporal displacement into the tentorial notch, effaced suprasellar cistern.", sequence="CT non-contrast")],
 ["Posterior communicating artery aneurysm (pupil involved)", "Diabetic or hypertensive microvascular ischemia (pupil spared)", "Uncal herniation", "Cavernous sinus lesion", "Midbrain infarct or tumor", "Giant cell arteritis in the elderly"],
 [("Myasthenia gravis", "Ptosis and ophthalmoplegia that fluctuate; pupil never involved; ice test"), ("Horner syndrome", "Ptosis mild with a small, not large, pupil"), ("Thyroid eye disease", "Restrictive limitation with proptosis and lid retraction rather than ptosis")],
 ["Pupil-involving or incomplete third nerve palsy: emergency CTA or MRA for an aneurysm the same day", "Complete pupil-sparing palsy in a vasculopath over 50: observe with repeat pupil checks and imaging if not improving by 3 months", "Patch the eye for diplopia; check ESR/CRP in the elderly"],
 [S11(350, 351), B10(87, 90), B11(93, 95)], marker=nerve("cn-03-oculomotor-l"), imagingHint=hint("axial", -12, -5, -15, "third nerve beneath the posterior communicating artery"), preset="inferior"))

E.append(syn("syn-cn4-palsy", "Trochlear nerve palsy", "traumatic", ["cn-04-trochlear", "trochlear-nucleus", "level-midbrain-inferior-colliculus"], "contralateral",
 "After a minor head injury, or with no history at all, a patient complains of vertical double vision that is worst reading or going down stairs, and tilts the head away from the affected eye to fuse the images. The affected eye sits slightly higher, the hypertropia increases when they look toward the nose and when the head is tilted toward the affected shoulder. Old photographs may show that the head tilt has been present for years.",
 [D("oculomotor", "ipsilateral", "superior oblique", "Hypertropia worse on contralateral gaze and ipsilateral head tilt (three-step test); excyclotorsion", "cn-04-trochlear"), D("other", "n/a", "head posture", "Compensatory head tilt away from the affected eye, chin down", "cn-04-trochlear"), D("oculomotor", "ipsilateral", "vertical fusion", "Vertical diplopia worst in downgaze and reading", "cn-04-trochlear")],
 "The trochlear nucleus lies in the caudal midbrain at the level of the inferior colliculus, and its axons run dorsally, cross in the superior medullary velum and exit from the dorsal surface of the brainstem, the only cranial nerve to do either; the nerve then supplies the contralateral superior oblique after its long course around the midbrain and through the cavernous sinus. A nuclear or fascicular lesion in the midbrain therefore paralyzes the superior oblique of the opposite eye, whereas a lesion of the nerve after it has crossed, which is the usual situation, paralyzes the eye on the same side. The superior oblique depresses the adducted eye and intorts it, so its loss leaves the eye slightly elevated and extorted, with the diplopia greatest in downgaze and adduction, and the patient tilts the head toward the opposite shoulder to intort the eye by using the intact muscles; tilting toward the affected side calls on the paralyzed muscle and increases the deviation, the basis of the Bielschowsky head tilt test. The thin nerve is vulnerable to shearing at the tentorial edge in closed head injury, and bilateral palsies after trauma are common because both nerves cross in the same small velum. Decompensation of a congenital palsy, recognized by a large vertical fusional range and a lifelong head tilt, is the other common presentation.",
 [pathol("Traumatic or microvascular palsy", "MRI", "Imaging is usually normal; look at the dorsal midbrain and the tentorial edge for contusion or hemorrhage.", sequence="SWI"), pathol("Dorsal midbrain lesion", "MRI", "Lesion at the level of the inferior colliculus producing a contralateral palsy, sometimes with a Horner on the side of the lesion.", sequence="FLAIR")],
 ["Closed head trauma (often bilateral)", "Congenital palsy decompensating in adult life", "Microvascular ischemia in diabetes and hypertension", "Dorsal midbrain lesion", "Cavernous sinus disease"],
 [("Skew deviation", "Vertical misalignment with intorsion of the higher eye and central signs; head tilt test negative or reversed"), ("Ocular myasthenia", "Variable and fatigable"), ("Thyroid eye disease (inferior rectus restriction)", "Hypotropia of the affected eye, restricted elevation, proptosis")],
 ["Three-step test to confirm; check old photographs for a long-standing head tilt", "Observe microvascular and traumatic palsies for spontaneous recovery over months; prisms meanwhile", "Strabismus surgery for persistent decompensated palsies"],
 [S11(351), B11(95, 96)], marker=nerve("trochlear-nerve-l"), imagingHint=hint("axial", 0, -30, -8, "dorsal midbrain at the inferior colliculus where the nerves cross"), preset="posterior"))

E.append(syn("syn-cn6-palsy", "Abducens nerve palsy and its false-localizing value", "csf-pressure", ["cn-06-abducens", "abducens-nucleus", "level-pons-caudal", "sinus-cavernous"], "ipsilateral",
 "A patient develops horizontal double vision that is worse when looking to one side and at distance, and turns the head toward that side to avoid it. The affected eye cannot abduct past the midline, or does so incompletely, while all other movements are normal. In one patient the cause is a diabetic microvascular lesion that recovers; in another, headache and papilledema reveal raised intracranial pressure from a tumor nowhere near the pons.",
 [D("oculomotor", "ipsilateral", "lateral rectus", "Abduction deficit with esotropia greatest on gaze to the affected side and at distance", "cn-06-abducens"), D("other", "n/a", "head posture", "Head turned toward the affected side", "cn-06-abducens"), D("other", "bilateral", "raised ICP (when false-localizing)", "Headache, papilledema, sometimes bilateral palsies", "subarachnoid-space-cisterns")],
 "The abducens nerve leaves the pontomedullary junction and runs the longest intracranial course of any cranial nerve, ascending the clivus in the subarachnoid space, bending sharply over the petrous apex beneath the petroclinoid ligament to enter Dorello's canal, and running through the body of the cavernous sinus to the lateral rectus. It is uncrossed, so an abduction deficit is on the side of the nerve. That long vertical course and the sharp bend at the petrous ridge make it the nerve most vulnerable to any process that shifts the brainstem downward or raises intracranial pressure, so a sixth nerve palsy, especially if bilateral, is a classic false-localizing sign that must not be taken to mean pontine disease. A nuclear lesion is recognized because the nucleus also contains the interneurons for the contralateral medial rectus, so nuclear damage causes a conjugate gaze palsy rather than an isolated abduction deficit, usually with an ipsilateral facial palsy from the overlying facial genu. In the cavernous sinus the nerve lies medially beside the carotid artery with the oculosympathetic fibers briefly attached, so a sixth nerve palsy with an ipsilateral Horner syndrome points to the sinus; at the petrous apex it is accompanied by facial pain and deafness in Gradenigo syndrome.",
 [pathol("Raised intracranial pressure", "MRI", "Papilledema correlates: distended optic nerve sheaths, flattened posterior globes, partially empty sella; mass, venous thrombosis or IIH as the cause.", sequence="T2"), pathol("Clival or cavernous lesion", "MRI", "Enhancing chordoma, meningioma, nasopharyngeal carcinoma or cavernous sinus mass along the nerve's course.", sequence="T1+Gd"), pathol("Pontine lesion", "MRI", "Demyelination or infarct at the facial colliculus giving a gaze palsy rather than an isolated palsy.", sequence="FLAIR")],
 ["Microvascular ischemia (diabetes, hypertension)", "Raised intracranial pressure of any cause", "Trauma", "Clival tumor, nasopharyngeal carcinoma, cavernous sinus disease", "Petrous apicitis (Gradenigo)", "Multiple sclerosis (young)"],
 [("Thyroid eye disease (medial rectus restriction)", "Abduction limited by a tight medial rectus; forced duction positive; proptosis"), ("Ocular myasthenia", "Variable, fatigable, normal pupils"), ("Duane syndrome", "Congenital; globe retraction and narrowing of the fissure on adduction"), ("Convergence spasm", "Miosis on attempted lateral gaze; functional")],
 ["Examine the fundi for papilledema in every sixth nerve palsy; image if present, bilateral, young, or with any other sign", "Isolated palsy in a vasculopath over 50: observe for recovery at 3 months", "Prism or occlusion for diplopia; botulinum toxin to the medial rectus in persistent cases"],
 [S11(351), S11(358), B11(93, 96)], marker=nerve("cn-06-abducens-l"), imagingHint=hint("axial", -8, -35, -30, "abducens nerve rising from the pontomedullary junction along the clivus"), preset="anterior"))

E.append(syn("syn-trigeminal-neuralgia", "Trigeminal neuralgia", "compressive", ["cn-05-trigeminal", "ganglion-trigeminal", "artery-sca", "spinal-trigeminal-nucleus-tract"], "ipsilateral",
 "An older patient describes electric shocks in the cheek and jaw that last a second or two, come in volleys, and are set off by chewing, brushing the teeth, a breath of cold air or a light touch to a particular spot on the face. Between attacks there is no pain and the examination is normal. In a young woman with bilateral or persistent pain, sensory loss or other cranial nerve signs, multiple sclerosis or a tumor must be sought.",
 [D("pain", "ipsilateral", "V2 and/or V3 divisions, rarely V1", "Paroxysmal lancinating pain with trigger zones; no pain between attacks", "cn-05-trigeminal"), D("sensory-light-touch", "n/a", "face", "Normal sensation and corneal reflex in classic cases; any deficit suggests a structural cause", "trigeminal-nuclei"), D("other", "ipsilateral", "face", "Facial spasm with the pain (tic douloureux)", "cn-05-trigeminal")],
 "In most patients the trigeminal root is compressed and indented at its entry into the pons by a loop of the superior cerebellar artery, occasionally a vein, which demyelinates the large touch fibers at the root entry zone where central myelin gives way to peripheral myelin. The demyelinated fibers become hyperexcitable and generate ectopic bursts, and cross-talk between light-touch fibers and neighboring pain fibers means that a trivial touch stimulus is felt as an explosion of pain, which explains the trigger zones and the sparing of sensation between attacks. The nerve is the uncrossed sensory supply of the ipsilateral face, so the pain is strictly unilateral and confined to one or two divisions, most often the maxillary and mandibular. Because the second-order neurons for facial pain lie in the spinal trigeminal nucleus in the medulla, a demyelinating plaque along the root fibers as they enter the pons or descend in the spinal tract can produce the same pain, which is why multiple sclerosis is the commonest cause in the young and is the explanation for bilateral cases. A cerebellopontine angle tumor compresses the root from outside and adds sensory loss, a depressed corneal reflex or other cranial nerve signs.",
 [pathol("Neurovascular compression", "MRI", "Superior cerebellar artery loop contacting and distorting the trigeminal root at the pontine entry zone on thin-section heavily T2-weighted images (CISS/FIESTA) with MRA.", sequence="T2"), pathol("Multiple sclerosis", "MRI", "FLAIR-bright plaque in the pontine trigeminal root entry zone or along the spinal tract.", sequence="FLAIR"), pathol("Cerebellopontine angle tumor", "MRI", "Meningioma, epidermoid or schwannoma compressing the nerve; epidermoids restrict diffusion.", sequence="T1+Gd")],
 ["Neurovascular compression by the superior cerebellar artery", "Multiple sclerosis", "Cerebellopontine angle tumor", "Herpes zoster (postherpetic, continuous rather than paroxysmal)"],
 [("Dental pain", "Continuous, localized to a tooth, tender to percussion"), ("Cluster headache", "Orbital pain lasting 15–180 minutes with autonomic features"), ("Glossopharyngeal neuralgia", "Pain in the throat and ear triggered by swallowing"), ("Postherpetic neuralgia", "Constant burning with allodynia after a rash, usually V1")],
 ["Carbamazepine or oxcarbazepine is first-line and its response supports the diagnosis", "MRI with thin brainstem sequences in every patient to exclude MS and tumor and to show vascular contact", "Microvascular decompression or ablative procedures (radiofrequency, gamma knife) for drug-resistant cases"],
 [S11(351), S11(358), B13(120), C("berkowitz", 14, 126)], marker=nerve("cn-05-trigeminal-l"), imagingHint=hint("axial", -20, -30, -25, "trigeminal root entry zone at the lateral pons"), preset="inferior", eponyms=["tic douloureux"]))

E.append(syn("syn-facial-palsy-peripheral-vs-central", "Facial palsy: peripheral (Bell) versus central", "functional-pattern", ["cn-07-facial", "facial-motor-nucleus", "gyrus-precentral", "internal-capsule", "ganglion-geniculate"], "ipsilateral",
 "A patient wakes with one side of the face drooping. If the forehead is smooth and the eye will not close, taste is odd and sounds are loud in that ear, the whole nerve has failed from its nucleus onward: Bell palsy. If the forehead wrinkles symmetrically and the eye closes while the mouth droops, and the arm on the same side is weak, the lesion is in the opposite hemisphere: a stroke. The forehead decides.",
 [D("cranial-nerve", "ipsilateral", "whole face including the forehead (peripheral)", "Lower motor neuron facial palsy: cannot wrinkle the forehead, close the eye or smile; Bell phenomenon", "cn-07-facial"), D("cranial-nerve", "contralateral", "lower face, forehead spared (central)", "Upper motor neuron facial weakness with preserved forehead and emotional smile", "pathway-corticobulbar"), D("other", "ipsilateral", "taste, hearing, tears (peripheral, proximal lesions)", "Loss of taste on the anterior tongue, hyperacusis, reduced tearing depending on the level in the canal", "ganglion-geniculate"), D("motor", "contralateral", "arm (central)", "Associated hemiparesis or dysarthria when central", "pathway-lateral-corticospinal")],
 "The facial motor nucleus in the caudal pons has two functional halves. The part supplying the upper face receives corticobulbar input from both hemispheres, whereas the part supplying the lower face receives input mainly from the contralateral motor cortex, crossing at the level of the nucleus. A lesion of the corticobulbar fibers on one side, in the cortex, corona radiata, internal capsule or crus, therefore leaves the forehead moving, because the other hemisphere still drives it, and weakens the contralateral lower face; the accompanying arm weakness is on the same side as the facial weakness, since the corticospinal fibers cross further down in the medulla. A lesion of the nucleus or the nerve itself, in the pons, cerebellopontine angle, facial canal or parotid, removes the final common pathway to all the ipsilateral facial muscles, including the frontalis, and the paralysis is complete and on the side of the lesion. Emotional smiling uses a separate limbic route to the nucleus and often survives a central lesion, a further clue. The level of a peripheral lesion within the temporal bone is read from the branches: loss of tearing places it at or proximal to the geniculate ganglion, hyperacusis proximal to the stapedius branch, loss of taste proximal to the chorda tympani, and none of these means a lesion at or beyond the stylomastoid foramen. Bell palsy is a presumed viral inflammation of the nerve within the narrow labyrinthine segment of the canal.",
 [pathol("Bell palsy", "MRI", "Enhancement of the labyrinthine segment and geniculate ganglion of the facial nerve; imaging is reserved for atypical or non-recovering cases.", sequence="T1+Gd"), pathol("Central facial palsy", "MRI", "Restricted diffusion in the contralateral motor cortex, corona radiata, capsule or pons above the facial nucleus.", sequence="DWI"), pathol("Parotid or temporal bone lesion", "CT", "Parotid tumor, temporal bone fracture through the facial canal, or cholesteatoma eroding the canal.", sequence="CT non-contrast")],
 ["Bell palsy (idiopathic, presumed herpes simplex)", "Ramsay Hunt syndrome (zoster)", "Lyme disease (bilateral in endemic areas)", "Stroke (central)", "Parotid malignancy, temporal bone fracture", "Sarcoidosis, Guillain–Barré (bilateral)"],
 [("Pontine lesion involving the nucleus", "Peripheral-type palsy with an ipsilateral gaze palsy and contralateral hemiparesis"), ("Cerebellopontine angle tumor", "Slowly progressive, with deafness and facial numbness"), ("Myasthenia gravis", "Bilateral fatigable weakness")],
 ["Peripheral palsy: prednisolone within 72 hours; eye protection with lubricants and taping at night", "Forehead-sparing weakness or any limb sign: stroke pathway", "Check the ear for vesicles (Ramsay Hunt) and ask about tick exposure; bilateral palsies need systemic workup"],
 [C("snell", 11, 352), B13(120, 124)], marker=nerve("cn-07-facial-l"), imagingHint=hint("axial", -35, -30, -30, "facial nerve in the internal acoustic meatus and labyrinthine segment"), preset="inferior", eponyms=["Bell palsy"], exam=["Raise the eyebrows: symmetric forehead means central", "Close the eyes tightly: Bell phenomenon and incomplete closure in peripheral", "Show the teeth and puff the cheeks", "Ask about taste, hearing and tearing on that side", "Look in the ear and on the palate for vesicles", "Test the limbs on the same side"]))

E.append(syn("syn-cerebellopontine-angle", "Cerebellopontine angle syndrome", "neoplastic", ["cn-08-vestibulocochlear", "cn-07-facial", "cn-05-trigeminal", "cerebellar-hemisphere", "level-pons-caudal", "middle-cerebellar-peduncle"], "ipsilateral",
 "Hearing in one ear has been fading for two years with tinnitus, and the patient now notices imbalance rather than spinning vertigo. Later the cheek becomes numb and the corneal reflex on that side is lost; eventually there is facial weakness, ataxia of the arm and leg on the same side, and, with large tumors, headache and papilledema. The sequence eighth, fifth, seventh nerves and then cerebellum tells the story of a slowly growing mass at the angle.",
 [D("auditory", "ipsilateral", "one ear", "Progressive sensorineural hearing loss with poor speech discrimination and tinnitus", "cn-08-vestibulocochlear"), D("vestibular", "ipsilateral", "vestibular nerve", "Imbalance more than vertigo; canal paresis on caloric testing", "pathway-vestibular-vor"), D("sensory-light-touch", "ipsilateral", "face", "Facial numbness with a depressed corneal reflex", "cn-05-trigeminal"), D("cranial-nerve", "ipsilateral", "face", "Late lower motor neuron facial weakness (the nerve is surprisingly resistant)", "cn-07-facial"), D("cerebellar", "ipsilateral", "limbs and gait", "Ataxia from compression of the cerebellar hemisphere and middle peduncle", "pathway-cerebellar-circuits"), D("other", "n/a", "raised ICP", "Headache, papilledema, hydrocephalus with large tumors", "ventricle-fourth")],
 "The cerebellopontine angle is the wedge of cistern between the pons, the middle cerebellar peduncle and the petrous bone, containing the seventh and eighth nerves on their way to the internal acoustic meatus, with the trigeminal root above and the ninth, tenth and eleventh nerves below. All of these are uncrossed peripheral nerves, so every sign is on the side of the mass. A vestibular schwannoma starts in the meatus on the superior vestibular nerve and compresses the cochlear nerve first, so the earliest symptom is unilateral retrocochlear hearing loss in which speech discrimination is worse than the pure-tone threshold predicts, and because the vestibular loss is gradual the brain compensates and the patient feels unsteady rather than vertiginous. As the tumor grows into the angle it stretches the trigeminal root, dulling the corneal reflex and facial sensation, then flattens the facial nerve, which tolerates stretching remarkably well, and finally indents the cerebellar hemisphere and peduncle, producing ipsilateral ataxia (cerebellar signs are ipsilateral because of the double crossing of cerebellar output and corticospinal fibers). Very large tumors displace the brainstem and obstruct the fourth ventricle. Bilateral tumors define neurofibromatosis type 2.",
 [pathol("Vestibular schwannoma", "MRI", "Avidly enhancing mass centered on the internal acoustic meatus with an 'ice-cream cone' extension into the angle, widening the porus acusticus; small intracanalicular tumors need thin post-contrast or CISS images.", sequence="T1+Gd"), pathol("Meningioma", "MRI", "Broad-based dural mass eccentric to the meatus with a dural tail, hyperostosis on CT.", sequence="T1+Gd"), pathol("Epidermoid", "MRI", "Lobulated non-enhancing mass insinuating around nerves, bright on DWI (distinguishes it from an arachnoid cyst).", sequence="DWI")],
 ["Vestibular schwannoma (acoustic neuroma)", "Meningioma", "Epidermoid cyst", "Metastasis or lymphoma", "Neurofibromatosis type 2 (bilateral)"],
 [("Ménière disease", "Episodic vertigo with fluctuating low-frequency hearing loss; normal MRI"), ("Presbycusis", "Bilateral, symmetric high-frequency loss with proportional discrimination"), ("Bell palsy", "Sudden, complete facial palsy without deafness")],
 ["Any asymmetric sensorineural hearing loss: MRI of the internal acoustic meatus with contrast", "Options: observation with serial MRI, stereotactic radiosurgery, or microsurgical resection depending on size, hearing and age", "Test the corneal reflex and facial nerve in every patient with unilateral deafness"],
 [C("berkowitz", 12, 106), B13(119), B13(122), C("berkowitz", 29, 256), C("berkowitz", 29, 261)], marker=sphere(-38, -35, -32, 12), imagingHint=hint("axial", -38, -35, -32, "cerebellopontine angle at the internal acoustic meatus"), preset="inferior", eponyms=["acoustic neuroma syndrome"]))

E.append(syn("syn-cavernous-sinus", "Cavernous sinus syndrome", "compressive", ["sinus-cavernous", "cn-03-oculomotor", "cn-04-trochlear", "cn-06-abducens", "artery-internal-carotid", "pituitary-infundibulum"], "ipsilateral",
 "The patient has a painful, swollen, red eye with a drooping lid that is fixed in all directions, numbness of the forehead and cheek on the same side, and sometimes a small pupil. A diabetic with a fever and a black eschar in the nose is a surgical emergency; a patient with a pituitary tumor develops the same signs slowly; a young person after a head injury may have a pulsating, bruit-bearing eye from a fistula.",
 [D("oculomotor", "ipsilateral", "III, IV and VI", "Complete external ophthalmoplegia with ptosis; VI often first", "sinus-cavernous"), D("sensory-light-touch", "ipsilateral", "V1 (and V2)", "Numbness of the forehead, cornea and cheek; loss of corneal reflex", "cn-05-trigeminal"), D("pupil", "ipsilateral", "one pupil", "Variable: dilated (III), small (sympathetic plexus) or mid-position and fixed (both)", "pathway-oculosympathetic"), D("other", "ipsilateral", "orbit", "Proptosis, chemosis, orbital venous congestion, bruit in fistulas", "sinus-cavernous")],
 "The cavernous sinus is a venous channel beside the sella through which the internal carotid artery runs with the sympathetic plexus on its wall, the abducens nerve floating beside the artery, and the oculomotor, trochlear, ophthalmic and maxillary nerves stacked in the lateral wall. Every one of these is an uncrossed structure serving the ipsilateral eye and face, so a mass, thrombus or inflammation in the sinus produces a purely ipsilateral collection of signs: paralysis of all three ocular motor nerves, sensory loss in the first and sometimes second trigeminal divisions and, from the sympathetic plexus, a Horner syndrome that can combine with the third nerve palsy to leave a mid-sized fixed pupil. The abducens nerve, lying free in the sinus rather than in its wall, is usually affected first. Venous obstruction of the ophthalmic veins, which drain into the sinus, causes the proptosis and chemosis, and in a carotid-cavernous fistula arterial blood flows retrograde into the same veins, producing a pulsating eye with a bruit. The optic nerve lies outside the sinus, in the optic canal above it, so vision is preserved unless the orbital apex is involved, which is the distinction between a cavernous sinus and an orbital apex syndrome. Because the two sinuses connect through the intercavernous sinuses, septic thrombosis often spreads to the other side within days.",
 [pathol("Cavernous sinus thrombosis", "MRV", "Filling defect and expansion of the sinus with convex lateral walls, dilated superior ophthalmic vein and proptosis; enhancement of the sinus wall.", sequence="T1+Gd"), pathol("Tumor or invasive fungal infection", "MRI", "Enhancing soft tissue replacing the sinus, narrowing or encasing the carotid, extending from the sphenoid sinus in mucormycosis or from the sella in pituitary adenoma.", sequence="T1+Gd"), pathol("Carotid-cavernous fistula", "DSA", "Early opacification of the cavernous sinus and superior ophthalmic vein during the arterial phase; CTA shows the dilated vein.")],
 ["Septic thrombosis from facial, sinus or dental infection", "Invasive fungal sinusitis (mucormycosis) in diabetics and the immunosuppressed", "Pituitary adenoma or apoplexy, meningioma, nasopharyngeal carcinoma, metastasis", "Carotid-cavernous fistula after trauma or aneurysm rupture", "Tolosa–Hunt idiopathic granulomatous inflammation"],
 [("Orbital apex syndrome", "Adds optic neuropathy with visual loss and an afferent pupillary defect"), ("Orbital cellulitis", "Fever and proptosis with normal cranial nerves early; CT shows orbital fat stranding"), ("Ocular myasthenia", "Painless, variable, no sensory loss")],
 ["Urgent contrast MRI/MRV; blood cultures and intravenous antibiotics with anticoagulation for septic thrombosis", "Emergency ENT assessment and surgical debridement plus amphotericin for suspected mucormycosis", "Endovascular closure of fistulas; steroids for Tolosa–Hunt after excluding infection and tumor"],
 [C("snell", 15, 432, 433), S11(351), B10(84, 86), B11(93), B11(95, 96)], marker=sphere(-15, 5, -20, 10), imagingHint=hint("coronal", -15, 5, -20, "cavernous sinus lateral to the sella"), preset="anterior"))

write(E)
