import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).parent))
from lib import *
E = []
S = lambda ch, a, b=None: C("snell", ch, a, b)
B = lambda ch, a, b=None: C("berkowitz", ch, a, b)
def q(id, type_, vignette, stem, options, answer, explanation, structures=(), syndromes=(), pathways=(), highlight=(), difficulty="2", cites=()):
    E.append({"kind": "quiz", "id": id, "type": type_, "vignette": vignette, "stem": stem, "options": [{"key": k, "text": t} for k, t in zip("ABCDE", options)], "answer": answer, "explanation": explanation,
              "targets": {"structureIds": list(structures), "syndromeIds": list(syndromes), "pathwayIds": list(pathways)}, "highlightOnReveal": list(highlight), "difficulty": difficulty, "citations": list(cites), "original": True})

q("qz-01", "localize", "A 68-year-old man with atrial fibrillation is found slumped at breakfast. He does not speak or follow commands, his eyes are turned to the left, the right side of his face droops below the eye and his right arm and leg do not move. He does not blink to a threat from the right.", "Where is the lesion?",
  ["Left internal capsule (lacune)", "Left middle cerebral artery stem territory", "Left pons", "Left thalamus", "Right frontal lobe"], "B",
  "Global aphasia, gaze deviation toward the lesion, right hemianopia and a face-arm-leg hemiplegia together require the whole left MCA territory: the language cortex, the frontal eye field, the optic radiation and the capsule. A capsular lacune gives no aphasia or field defect; a pontine lesion would turn the eyes away from the lesion and add a peripheral facial palsy.",
  syndromes=["syn-mca-stem-infarct"], structures=["artery-mca"], highlight=["territory-mca-major-l", "artery-mca-l"], cites=[B(7, 55, 59)])
q("qz-02", "localize", "A 55-year-old woman with sudden vertigo and vomiting has hoarseness and cannot swallow her saliva. Her right eyelid droops slightly and the right pupil is smaller. Pin-prick is dull on the right side of her face and on the left arm and leg. Strength is normal everywhere.", "Which single lesion explains all the findings?",
  ["Right lateral medulla", "Left lateral medulla", "Right medial medulla", "Right lateral pons", "Left thalamus"], "A",
  "Ipsilateral facial pain loss (spinal trigeminal tract), contralateral body pain loss (crossed spinothalamic tract), ipsilateral Horner syndrome and ipsilateral bulbar palsy with preserved strength is the lateral medullary syndrome on the side of the facial signs. The lateral pons would add facial weakness and deafness.",
  syndromes=["syn-wallenberg-lateral-medullary"], pathways=["pathway-lateral-spinothalamic", "pathway-trigeminothalamic"], highlight=["brainstem", "artery-pica-r"], cites=[B(9, 77, 78)])
q("qz-03", "localize", "A 30-year-old man is stabbed in the back at the level of the lower thoracic spine. He has weakness of the right leg with a brisk knee jerk and an upgoing toe, cannot feel a tuning fork on the right ankle, and cannot feel a pin on the left leg below the groin.", "Which pathway accounts for the left-sided finding?",
  ["Right lateral corticospinal tract", "Right posterior column", "Right spinothalamic tract", "Left spinothalamic tract", "Left posterior column"], "C",
  "Pain and temperature fibers cross in the anterior white commissure within a segment or two of entry, so the right spinothalamic tract carries pain from the left leg; a right hemicord lesion therefore gives left pain loss with right weakness and right proprioceptive loss (Brown-Séquard).",
  syndromes=["syn-brown-sequard"], pathways=["pathway-lateral-spinothalamic", "pathway-dcml"], highlight=["spinal-cord"], cites=[S(4, 168, 170)])
q("qz-04", "identify", "A 72-year-old hypertensive woman wakes with weakness of the left face, arm and leg that are all equally affected. Sensation, visual fields, speech and awareness are normal. CT is normal.", "The most likely site of the lesion is:",
  ["Right precentral gyrus", "Right posterior limb of the internal capsule", "Right thalamus", "Right lateral medulla", "Left cerebellum"], "B",
  "A pure motor hemiparesis involving face, arm and leg equally without any cortical or sensory sign is a lacunar infarct in the posterior limb of the internal capsule (or basis pontis), where the corticospinal and corticobulbar fibers are packed together and the sensory fibers lie just behind.",
  syndromes=["syn-lacunar-pure-motor"], structures=["internal-capsule"], highlight=["internal-capsule-r"], cites=[B(7, 60, 63)])
q("qz-05", "localize", "A 45-year-old woman notices that when she looks to the right, her left eye stays in the middle while the right eye moves fully and jerks. When a pencil is brought toward her nose both eyes converge normally.", "Where is the lesion?",
  ["Left medial longitudinal fasciculus", "Right medial longitudinal fasciculus", "Left oculomotor nerve", "Right abducens nucleus", "Left frontal eye field"], "A",
  "Failure of adduction of the left eye on right gaze with abducting nystagmus of the right eye and preserved convergence is a left internuclear ophthalmoplegia: the left MLF carries the crossed interneuron axons from the right abducens nucleus to the left medial rectus subnucleus.",
  syndromes=["syn-ino"], pathways=["pathway-horizontal-gaze"], highlight=["brainstem"], cites=[B(11, 99, 100)])
q("qz-06", "mechanism", "A 60-year-old man has a complete ptosis of the right eye. When the lid is lifted the eye is turned down and out, and the pupil is 7 mm and unreactive. He has a severe headache.", "What is the most urgent diagnosis to exclude?",
  ["Diabetic microvascular third nerve palsy", "Posterior communicating artery aneurysm", "Myasthenia gravis", "Midbrain infarct", "Horner syndrome"], "B",
  "A painful third nerve palsy with a dilated fixed pupil means compression of the superficially placed pupillary fibers, classically by a posterior communicating aneurysm; a microvascular palsy usually spares the pupil. Emergency CTA is required.",
  syndromes=["syn-cn3-palsy", "syn-subarachnoid-hemorrhage"], structures=["artery-pcom"], highlight=["cn-03-oculomotor-r", "artery-pcom-r"], cites=[B(11, 93, 95)])
q("qz-07", "localize", "A 25-year-old woman has had blurred vision in the left eye for three days with pain on moving the eye. Acuity is 6/36 on the left, colors look washed out, and the left pupil dilates when the light is swung onto it from the right eye. The fundus is normal.", "Where is the lesion?",
  ["Left retina", "Left optic nerve", "Optic chiasm", "Right optic tract", "Left occipital cortex"], "B",
  "Monocular visual loss with color desaturation, pain on eye movement, a relative afferent pupillary defect and a normal disc is retrobulbar optic neuritis of that nerve. Chiasmal and retrochiasmal lesions produce bilateral or homonymous field defects.",
  syndromes=["syn-optic-neuritis", "syn-rapd"], structures=["cn-02-optic"], highlight=["optic-nerve-l"], cites=[B(6, 48, 49)])
q("qz-08", "localize", "A 40-year-old man walks into door frames on both sides and has stopped driving. Confrontation testing shows that he cannot see the examiner's fingers in the temporal half of the field of each eye. His acuity is normal and he has recently noticed enlarged hands and a change in his face.", "Where is the lesion?",
  ["Both optic nerves", "Optic chiasm", "Left optic tract", "Both occipital lobes", "Right parietal lobe"], "B",
  "Bitemporal hemianopia is the signature of a chiasmal lesion, where the crossing nasal retinal fibers from both eyes are interrupted; the acromegalic features point to a pituitary macroadenoma compressing the chiasm from below.",
  syndromes=["syn-chiasmal-bitemporal", "syn-pituitary-mass"], structures=["optic-chiasm"], highlight=["optic-chiasm", "pituitary-gland"], cites=[S(11, 349, 350)])
q("qz-09", "identify", "A 70-year-old man's daughter reports that he ignores food on the left side of his plate, shaves only the right side of his face and denies that his left arm is weak although he cannot lift it. He draws all the numbers of a clock on the right side.", "The lesion is most likely in the:",
  ["Left parietal lobe", "Right parietal lobe", "Right occipital lobe", "Left frontal lobe", "Right thalamus"], "B",
  "Left hemispatial neglect with anosognosia is the hallmark of a right inferior parietal lesion; the right hemisphere attends to both sides of space, so its loss leaves the left side unattended. A field defect would not produce denial or the clock drawing pattern.",
  syndromes=["syn-hemineglect"], structures=["gyrus-supramarginal"], highlight=["gyrus-supramarginal-anterior-r", "gyrus-angular-r"], cites=[B(7, 53)])
q("qz-10", "mechanism", "A 50-year-old woman with a large right frontal tumor becomes drowsy over an hour. Her right pupil is dilated and unreactive. Her right arm and leg are weak with an upgoing toe.", "Why is the weakness on the same side as the tumor?",
  ["The tumor has spread to the left hemisphere", "The right cerebral peduncle is compressed by the uncus", "The left cerebral peduncle is compressed against the tentorial edge", "The corticospinal tract has not crossed at this level", "Post-ictal Todd paresis"], "C",
  "Uncal herniation normally compresses the ipsilateral peduncle and weakens the contralateral limbs; when the midbrain is pushed across so that the opposite peduncle is notched against the tentorium (Kernohan notch), the weakness appears on the side of the mass. The dilated pupil, not the weakness, indicates the side of the lesion.",
  syndromes=["syn-uncal-herniation"], structures=["cerebral-peduncle-crus"], highlight=["uncus-r", "brainstem"], cites=[B(30, 270)])
q("qz-11", "localize", "A 35-year-old woman has a drooping right eyelid that is only 1–2 mm lower than the left, a right pupil that is smaller than the left, and the difference is greater when the lights are dimmed. She has had right-sided neck pain since a yoga class two days ago.", "What is the most important next step?",
  ["Reassure: physiologic anisocoria", "MRI of the brain for a pituitary tumor", "CT angiography of the neck for carotid dissection", "Chest X-ray for an apical tumor", "Edrophonium test"], "C",
  "A Horner syndrome (anisocoria greater in the dark, mild ptosis) with new neck pain is an internal carotid dissection until proven otherwise; the sympathetic plexus runs on the carotid wall. Vessel imaging of the neck is urgent because of the stroke risk.",
  syndromes=["syn-horner"], pathways=["pathway-oculosympathetic"], highlight=["artery-internal-carotid-r"], cites=[B(10, 85, 87)])
q("qz-12", "localize", "A 62-year-old man has weakness of the right arm and leg that spares the face and loss of vibration and position sense in the same limbs. On protrusion his tongue deviates to the left and the left half of the tongue is wasted.", "Where is the lesion?",
  ["Left medial medulla", "Right medial medulla", "Left lateral medulla", "Left internal capsule", "Left pons"], "A",
  "A lower motor neuron tongue palsy (deviation toward the lesion, wasting) with contralateral limb weakness and proprioceptive loss and a spared face is the medial medullary syndrome on the side of the tongue palsy: the pyramid and medial lemniscus serve the opposite side while the hypoglossal nucleus is ipsilateral.",
  syndromes=["syn-dejerine-medial-medullary"], pathways=["pathway-lateral-corticospinal", "pathway-dcml"], highlight=["brainstem"], cites=[B(9, 77, 78)])
q("qz-13", "identify", "A 20-year-old motorcyclist has an arm that hangs at his side, rotated inward with the elbow straight, after a crash in which his shoulder hit the road. He can move his fingers normally. Sensation is reduced over the outer shoulder and forearm.", "Which roots have been injured?",
  ["C5–C6", "C7", "C8–T1", "T1 only", "C4"], "A",
  "The waiter's tip posture with preserved hand function and lateral arm sensory loss is an upper brachial plexus (Erb) palsy from traction on C5–C6: shoulder abductors, external rotators, elbow flexors and supinator are lost.",
  syndromes=["syn-erb-duchenne"], structures=["plexus-brachial"], highlight=["brachial-plexus-l"], cites=[S(14, 412, 413)])
q("qz-14", "localize", "A 58-year-old woman trips over her right foot. She cannot dorsiflex or evert the right foot, but inversion and plantar flexion are strong and the ankle jerk is normal. Sensation is reduced over the dorsum of the foot. She recently lost 15 kg.", "Where is the lesion?",
  ["L5 root", "Sciatic nerve at the hip", "Common peroneal nerve at the fibular neck", "Tibial nerve", "Anterior horn cells"], "C",
  "Foot drop with weak eversion but preserved inversion (tibialis posterior, L5 via the tibial nerve) and a normal ankle reflex is a common peroneal neuropathy; an L5 radiculopathy would weaken inversion and hip abduction as well. Weight loss removes the fat protecting the nerve at the fibular neck.",
  syndromes=["syn-peroneal-palsy-foot-drop", "syn-radiculopathy-lumbosacral"], structures=["nerve-common-peroneal"], highlight=["common-peroneal-nerve-r"], cites=[B(17, 163, 166)])
q("qz-15", "mechanism", "A 45-year-old alcoholic is admitted confused and unsteady. He cannot abduct either eye and has coarse nystagmus. A junior doctor gives intravenous glucose and he becomes more drowsy.", "What should have been given first, and which structures are being damaged?",
  ["Naloxone; the pons", "Thiamine; the mammillary bodies and periaqueductal region", "Glucose is correct; the cerebellum", "Antibiotics; the meninges", "Lorazepam; the hippocampus"], "B",
  "Confusion, ophthalmoplegia and ataxia in a malnourished alcoholic is Wernicke encephalopathy, a thiamine-dependent injury of the periventricular structures around the third and fourth ventricles and aqueduct; glucose without thiamine precipitates or worsens it, and the mammillary body damage leaves Korsakoff amnesia.",
  syndromes=["syn-wernicke-korsakoff"], structures=["mammillary-body"], highlight=["mammillary-body-l", "mammillary-body-r"], cites=[B(22, 233)])
q("qz-16", "localize", "A 66-year-old man describes electric shocks in his right cheek and jaw lasting a second, set off by chewing and by touching a spot beside his nose. Between attacks he has no pain and the examination, including the corneal reflex, is normal.", "Which nerve divisions are involved and what is the usual cause?",
  ["V1; herpes zoster", "V2 and V3; vascular compression of the trigeminal root", "V3 only; dental abscess", "VII; Bell palsy", "IX; glossopharyngeal neuralgia"], "B",
  "Paroxysmal lancinating pain with trigger zones in the maxillary and mandibular territories and a normal examination is classic trigeminal neuralgia, usually from compression of the root entry zone by a loop of the superior cerebellar artery.",
  syndromes=["syn-trigeminal-neuralgia"], structures=["cn-05-trigeminal", "artery-sca"], highlight=["cn-05-trigeminal-r", "artery-sca-r"], cites=[B(13, 120)])
q("qz-17", "identify", "A 55-year-old woman has a spastic gait, a small stiff tongue that she cannot protrude, slow strangled speech and cries uncontrollably when asked about her family. Her jaw jerk is very brisk. There is no wasting or fasciculation of the tongue.", "The lesion pattern is:",
  ["Bilateral lower motor neuron lesions of IX–XII (bulbar palsy)", "Bilateral corticobulbar tract lesions (pseudobulbar palsy)", "Unilateral capsular infarct", "Myasthenia gravis", "Cerebellar degeneration"], "B",
  "Spastic dysarthria, a spastic tongue without wasting, a brisk jaw jerk and emotional lability are the features of pseudobulbar palsy from bilateral upper motor neuron (corticobulbar) lesions; bulbar palsy would show a wasted, fasciculating tongue and an absent jaw jerk.",
  syndromes=["syn-bulbar-vs-pseudobulbar"], pathways=["pathway-corticobulbar"], highlight=["tract-corticobulbar-l", "tract-corticobulbar-r"], cites=[B(13, 119, 121)])
q("qz-18", "imaging", "A 78-year-old woman on warfarin has become confused and unsteady over three weeks and now has a mild left hemiparesis. CT shows a crescent-shaped collection over the right hemisphere that is slightly darker than brain and crosses the coronal suture.", "What is the diagnosis?",
  ["Acute epidural hematoma", "Chronic subdural hematoma", "Subarachnoid hemorrhage", "Cortical infarct", "Meningioma"], "B",
  "A crescentic, hypodense extra-axial collection that crosses sutures in an elderly anticoagulated patient with a subacute course is a chronic subdural hematoma from torn bridging veins; an epidural hematoma is biconvex, hyperdense and does not cross sutures.",
  syndromes=["syn-subdural-hematoma", "syn-epidural-hematoma"], structures=["veins-superficial-cerebral"], highlight=["dura-mater-cranial"], cites=[B(20, 199, 200)])
q("qz-19", "localize", "A 30-year-old woman has an unsteady gait with a wide base and cannot tandem walk, but the finger-nose and heel-shin tests are almost normal when she is lying down. She has headaches in the morning and vomits. Her discs are swollen.", "Which part of the cerebellum is most likely involved?",
  ["Left cerebellar hemisphere", "Right cerebellar hemisphere", "Vermis", "Dentate nucleus", "Superior cerebellar peduncle"], "C",
  "Severe truncal and gait ataxia with relatively spared limb coordination is a midline (vermian) syndrome; a midline mass over the fourth ventricle also obstructs CSF flow, explaining the headache, vomiting and papilledema.",
  syndromes=["syn-cerebellar-vermian-midline", "syn-hydrocephalus"], structures=["cerebellar-vermis"], highlight=["cerebellar-vermis-vi"], cites=[B(8, 67, 73)])
q("qz-20", "localize", "A 64-year-old man develops a right hemianopia. He can write a sentence but cannot read it back a minute later, although he can spell words aloud and recognizes words spelled to him. He cannot name colors but matches them correctly.", "Which two structures are damaged?",
  ["Left angular gyrus and Wernicke's area", "Left calcarine cortex and splenium of the corpus callosum", "Right calcarine cortex and left angular gyrus", "Left optic tract and lateral geniculate body", "Bilateral occipital lobes"], "B",
  "Alexia without agraphia arises when a left occipital infarct blinds the right hemifield and the accompanying splenial lesion disconnects the seeing right occipital cortex from the left angular gyrus; writing, which needs no visual input, survives.",
  syndromes=["syn-alexia-without-agraphia", "syn-pca-infarct"], structures=["corpus-callosum", "cortex-calcarine"], highlight=["cortex-intracalcarine-l", "corpus-callosum"], cites=[B(6, 50)])
q("qz-21", "identify", "A 28-year-old woman notices double vision and drooping eyelids by evening that are better in the morning. Her pupils are normal. Chewing tires her halfway through a meal. Reflexes and sensation are normal.", "What is the site of the disorder?",
  ["Oculomotor nerve", "Neuromuscular junction (postsynaptic)", "Neuromuscular junction (presynaptic)", "Extraocular muscles", "Midbrain nuclei"], "B",
  "Fatigable ptosis, diplopia that fits no nerve and bulbar fatigue with spared pupils, reflexes and sensation is myasthenia gravis, a postsynaptic acetylcholine receptor disorder; Lambert–Eaton (presynaptic) causes proximal leg weakness with areflexia and autonomic symptoms.",
  syndromes=["syn-myasthenia-gravis", "syn-lambert-eaton"], structures=["neuromuscular-junction"], highlight=["cn-03-oculomotor-l", "cn-03-oculomotor-r"], cites=[B(30, 293, 297)])
q("qz-22", "localize", "A 40-year-old man has burned his fingers several times without feeling it. Pin-prick and temperature sensation are absent over both shoulders, arms and the upper chest, but he feels a tuning fork and joint movement normally there. The small muscles of his hands are wasted and the arm reflexes are absent.", "Where is the lesion?",
  ["Both median nerves", "Posterior columns of the cervical cord", "Central cervical cord (syrinx)", "Brachial plexus bilaterally", "Lateral medulla"], "C",
  "Bilateral cape-like dissociated loss of pain and temperature with preserved proprioception, plus lower motor neuron signs in the arms, is a central cervical cord lesion destroying the crossing spinothalamic fibers and the anterior horns: syringomyelia.",
  syndromes=["syn-central-cord-syringomyelia"], pathways=["pathway-lateral-spinothalamic"], highlight=["spinal-cord"], cites=[S(4, 169, 171)])
q("qz-23", "localize", "A 70-year-old woman with a spinning sensation and vomiting for six hours has nystagmus that beats to the right when she looks right and to the left when she looks left. Rapid head turning to either side produces no corrective eye movement. She cannot stand without support.", "What does the examination indicate?",
  ["Right vestibular neuritis", "Left vestibular neuritis", "Benign paroxysmal positional vertigo", "A central (brainstem or cerebellar) lesion", "Ménière disease"], "D",
  "Direction-changing (gaze-evoked) nystagmus, a normal head impulse test and inability to stand are central features of the HINTS examination; a peripheral lesion gives unidirectional nystagmus with an abnormal head impulse toward the affected ear.",
  syndromes=["syn-central-vs-peripheral-vertigo", "syn-pica-cerebellar-infarct"], pathways=["pathway-vestibular-vor"], highlight=["brainstem", "cerebellar-hemisphere-l"], cites=[B(12, 110, 112)])
q("qz-24", "identify", "A 45-year-old woman has developed a slowly worsening hearing loss in the left ear over two years with tinnitus. Speech discrimination in that ear is much worse than the pure-tone loss predicts. The left corneal reflex is absent and there is mild left facial weakness.", "The most likely lesion is a:",
  ["Left cochlear otosclerosis", "Left cerebellopontine angle tumor", "Left lateral pontine infarct", "Ménière disease", "Left temporal lobe glioma"], "B",
  "Progressive retrocochlear unilateral hearing loss followed by trigeminal and then facial involvement is the sequence of a cerebellopontine angle mass, usually a vestibular schwannoma, stretching the neighboring nerves as it grows.",
  syndromes=["syn-cerebellopontine-angle"], structures=["cn-08-vestibulocochlear"], highlight=["cn-08-vestibulocochlear-l", "cn-07-facial-l", "cn-05-trigeminal-l"], cites=[B(12, 106)])
q("qz-25", "mechanism", "A 22-year-old man is quadriplegic after a diving injury at C5. On the third day a nurse finds him flushed and sweating above the neck with a headache and a blood pressure of 220/120 and a pulse of 48. His bladder is distended.", "What is happening?",
  ["Pulmonary embolism", "Autonomic dysreflexia from bladder distension", "Neurogenic shock", "Hemorrhagic stroke", "Spinal shock"], "B",
  "A noxious stimulus below a lesion above T6 triggers massive sympathetic discharge from the disconnected splanchnic outflow, producing hypertension with reflex bradycardia and flushing above the lesion: autonomic dysreflexia. Emptying the bladder is the treatment.",
  syndromes=["syn-complete-transection-spinal-shock"], structures=["intermediolateral-column", "splanchnic-nerves"], highlight=["spinal-cord"], cites=[S(4, 167, 168)])
q("qz-26", "localize", "A 60-year-old man develops a resting tremor of the right hand that disappears when he reaches for a cup, with small handwriting and reduced arm swing on the right. His face is expressionless.", "Which structure has degenerated, and on which side?",
  ["Right substantia nigra", "Left substantia nigra", "Right cerebellum", "Left subthalamic nucleus", "Bilateral caudate nuclei"], "B",
  "Asymmetric parkinsonism reflects dopamine loss in the substantia nigra contralateral to the affected limbs, because each basal ganglia loop acts on the opposite body through the crossed corticospinal projection.",
  syndromes=["syn-parkinsonism"], pathways=["pathway-basal-ganglia-loops"], highlight=["substantia-nigra-l"], cites=[B(23, 243, 250)])
q("qz-27", "imaging", "A 50-year-old woman has the worst headache of her life, reaching its peak within seconds, with vomiting and neck stiffness. CT within two hours is reported as normal.", "What is the next step?",
  ["Discharge with analgesia", "Lumbar puncture at 12 hours looking for xanthochromia", "MRI brain routine", "Start migraine prophylaxis", "Repeat CT in one week"], "B",
  "A thunderclap headache requires exclusion of subarachnoid hemorrhage; CT is very sensitive within six hours, but a negative early CT in a typical history is followed by lumbar puncture at 12 hours to detect the bilirubin of xanthochromia, and then vessel imaging if positive.",
  syndromes=["syn-subarachnoid-hemorrhage"], structures=["subarachnoid-space-cisterns", "circle-of-willis"], highlight=["artery-acom"], cites=[B(20, 196, 198)])
q("qz-28", "localize", "A 35-year-old woman reports numb, tingling hands that wake her at night and that she shakes to relieve. The thumb, index and middle fingers are affected, the little finger is spared, and the thenar muscles are slightly wasted. Sensation over the base of the thumb on the palm is normal.", "Where is the lesion?",
  ["C6 root", "Median nerve in the carpal tunnel", "Median nerve at the elbow", "Ulnar nerve at the wrist", "Lower trunk of the brachial plexus"], "B",
  "Nocturnal paresthesias in the lateral three and a half digits with thenar weakness and sparing of the thenar palm (palmar cutaneous branch leaves above the tunnel) is carpal tunnel syndrome; a C6 root lesion would involve the forearm and reflexes.",
  syndromes=["syn-carpal-tunnel"], structures=["nerve-median"], highlight=["median-nerve-l"], cites=[B(16, 148, 150)])
q("qz-29", "localize", "A 58-year-old man cannot look up. His pupils are large and do not react to light but constrict when he looks at his nose, and when he tries to look up his eyes jerk inward and retract. He has had headaches for a month.", "Where is the lesion?",
  ["Bilateral oculomotor nerves", "Dorsal midbrain (pretectum and posterior commissure)", "Pons", "Cavernous sinus", "Frontal eye fields"], "B",
  "Up-gaze palsy, light-near dissociation, lid retraction and convergence-retraction nystagmus form the dorsal midbrain (Parinaud) syndrome, from compression of the pretectum and posterior commissure, typically by a pineal tumor or hydrocephalus.",
  syndromes=["syn-parinaud-dorsal-midbrain"], pathways=["pathway-vertical-gaze", "pathway-pupillary-light-reflex"], highlight=["brainstem", "pineal-gland"], cites=[B(11, 100)])
q("qz-30", "localize", "A 66-year-old woman is brought in with sudden weakness of the right leg, much worse than the arm, with the face spared. She is slow to respond, has a grasp reflex in the right hand and is incontinent of urine. Speech is preserved.", "Which artery is occluded?",
  ["Left middle cerebral artery, superior division", "Left anterior cerebral artery", "Left posterior cerebral artery", "Left lenticulostriate artery", "Basilar artery"], "B",
  "Leg-predominant contralateral weakness with abulia, a grasp reflex and incontinence follows infarction of the medial frontal lobe and paracentral lobule, the territory of the anterior cerebral artery, where the leg is represented on the homunculus.",
  syndromes=["syn-aca-infarct"], structures=["artery-aca", "territory-aca"], highlight=["territory-aca-major-l", "artery-aca-l"], cites=[B(7, 58, 59)])

write(E)
