import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).parent))
from lib import *
E = []
SN3 = lambda a, b=None: C("snell", 3, a, b)
SNA = lambda a, b=None: C("snell", 19, a, b)
BK15 = lambda a, b=None: C("berkowitz", 15, a, b)
BK16 = lambda a, b=None: C("berkowitz", 16, a, b)

def pn(id, name, summary, location, function, imaging, lesion, exam, pearls, citations, sub="upper-limb", syndromes=(), pitfalls=(), synonyms=(), latin=None, subdivisions=(), afferents=(), efferents=(), meshes=()):
    return structure(id, name, "peripheral", summary, location, function, ["vasa nervorum from regional arteries"], imaging, lesion, exam, pearls, citations, subsystem=sub, meshIds=list(meshes), level={"region": "peripheral"},
        syndromes=syndromes, pitfalls=pitfalls, synonyms=synonyms, latin=latin, subdivisions=subdivisions, afferents=afferents, efferents=efferents, tags=["pns", sub])

NOIMG = "Peripheral nerves of the limbs are outside the MNI brain volume; no atlas mesh is shown. Ultrasound and MR neurography image the nerve directly; electrodiagnosis localizes the lesion functionally."

E.append(pn("plexus-brachial", "Brachial plexus", latin="Plexus brachialis",
 summary="The ventral rami of C5–T1 reorganize in the neck and axilla into the brachial plexus so that fibers from each root are redistributed to several nerves: roots form trunks (upper C5–C6, middle C7, lower C8–T1) between the scalene muscles, trunks split into anterior and posterior divisions behind the clavicle, divisions regroup into cords named for their position around the axillary artery (lateral, posterior, medial), and cords give the terminal nerves. The sequence 'roots, trunks, divisions, cords, branches' is the key to localizing plexus injuries: upper trunk lesions (Erb) paralyse the shoulder and elbow flexors, lower trunk lesions (Klumpke) the hand, and cord lesions produce recognizable combinations that no single nerve or root explains.",
 location="From the intervertebral foramina of C5–T1 through the interscalene triangle (roots and trunks), over the first rib behind the clavicle (divisions), and around the axillary artery in the axilla (cords) to the terminal branches at the lower border of pectoralis minor.",
 subdivisions=[("Roots (C5–T1)", "dorsal scapular nerve (C5), long thoracic nerve (C5–C7), contributions to the phrenic nerve"), ("Trunks", "upper (C5–C6): suprascapular nerve and nerve to subclavius; middle (C7); lower (C8–T1)"), ("Divisions", "anterior divisions → flexors (lateral and medial cords); posterior divisions → extensors (posterior cord)"), ("Lateral cord", "musculocutaneous nerve, lateral root of the median nerve, lateral pectoral nerve"), ("Posterior cord", "axillary and radial nerves, subscapular and thoracodorsal nerves"), ("Medial cord", "ulnar nerve, medial root of the median nerve, medial pectoral, medial cutaneous nerves of arm and forearm")],
 function="Motor and sensory supply of the entire upper limb and shoulder girdle, plus sympathetic fibers distributed with the nerves.",
 imaging=img([view("axial", 0, -48, -65, "cervical cord: the plexus roots emerge at C5–T1 below the MNI volume")],
     NOIMG + " MR neurography of the plexus shows the trunks and cords as bright fascicular structures on STIR; thickening, enhancement or discontinuity indicate injury, inflammation or infiltration.",
     [pathol("Traumatic plexopathy / root avulsion", "MRI", "Pseudomeningocele at an avulsed root on cervical MRI or CT myelography; thickened T2-bright trunks in stretch injury.", sequence="STIR"), pathol("Neoplastic versus radiation plexopathy", "MRI", "Enhancing mass infiltrating the lower plexus (Pancoast tumor, breast cancer, painful, Horner) versus diffuse thickening without mass after radiation (painless, myokymia on EMG).", sequence="T1+Gd"), pathol("Neuralgic amyotrophy", "MRI", "Focal nerve constrictions or T2 hyperintensity in the upper trunk and its branches with denervation edema in shoulder muscles.", sequence="STIR")],
     "MR neurography (STIR, T1+Gd); EMG/NCS to separate root, plexus and nerve"),
 lesion=[("Erb–Duchenne palsy: arm hangs adducted, internally rotated, pronated (waiter's tip)", "ipsilateral", "Upper trunk C5–C6: deltoid, biceps, supraspinatus, infraspinatus, brachioradialis"), ("Klumpke palsy: claw hand with intrinsic wasting, often with Horner syndrome", "ipsilateral", "Lower trunk C8–T1, T1 sympathetic fibers"), ("Weak elbow flexion and forearm pronation with lateral forearm numbness", "ipsilateral", "Lateral cord: musculocutaneous and lateral median fibers"), ("Weak wrist and finger extension plus deltoid weakness", "ipsilateral", "Posterior cord: radial and axillary nerves"), ("Hand intrinsic and finger flexor weakness with medial arm numbness", "ipsilateral", "Medial cord: ulnar and medial median fibers")],
 exam=["Test muscles supplied by different nerves from the same root, and by the same nerve from different roots, to separate root, plexus and nerve", "Sensory map: dermatomal (root) versus peripheral nerve versus plexus (cord) territories", "Reflexes: biceps C5–C6, triceps C7", "Look for Horner syndrome, winging of the scapula and paraspinal wasting (root level)", "Tinel sign over the supraclavicular fossa"],
 pearls=["Preserved paraspinal and serratus anterior function with a plexus pattern places the lesion beyond the roots", "A painful, progressive lower plexopathy with Horner syndrome is a Pancoast tumor until proven otherwise; a painless slowly progressive one after breast cancer treatment is radiation"],
 citations=[SN3(81, 83), SN3(111, 113), C("snell", 14, 412, 413), BK15(134, 135), BK16(141, 147)], syndromes=["syn-erb-duchenne", "syn-klumpke", "syn-neurogenic-thoracic-outlet", "syn-parsonage-turner"], pitfalls=["Cervical radiculopathy and brachial plexopathy overlap in symptoms; EMG of paraspinal muscles and sensory nerve action potentials (preserved in root lesions, lost in plexus lesions) separate them"]))

E.append(pn("nerve-phrenic", "Phrenic nerve", latin="Nervus phrenicus", synonyms=["C3, C4, C5 keep the diaphragm alive"],
 summary="Formed mainly from C4 with contributions from C3 and C5 at the lateral border of the anterior scalene, the phrenic nerve descends on that muscle, enters the thorax between the subclavian artery and vein, and runs in front of the lung root over the pericardium to reach the diaphragm, which it supplies motor fibers and to which it also gives sensory fibers (plus the pericardium, mediastinal pleura and peritoneum under the diaphragm). Its interruption paralyses a hemidiaphragm, which is tolerated at rest but produces orthopnea; bilateral loss, as in high cervical cord injury, Guillain–Barré syndrome or neuralgic amyotrophy, causes respiratory failure.",
 location="From the C3–C5 roots across the anterior scalene, behind the sternocleidomastoid and subclavian vein, in front of the lung hilum along the pericardium to the diaphragm; the right nerve is shorter and more vertical.",
 function="Sole motor supply to the diaphragm; sensory supply to the central diaphragm, pericardium and mediastinal pleura (referred shoulder-tip pain via C4).",
 imaging=img([view("axial", 0, -48, -65, "upper cervical cord; the phrenic motor neurons lie at C3–C5")],
     NOIMG + " A raised hemidiaphragm on a chest radiograph with paradoxical movement on fluoroscopic or ultrasound sniff test is the imaging sign of phrenic palsy.",
     [pathol("Phrenic nerve palsy", "US", "Absent or paradoxical diaphragmatic excursion on sniff test ultrasound; elevated hemidiaphragm on radiograph.", sequence="n/a"), pathol("Mediastinal tumor or cardiac surgery injury", "CT", "Mass along the course of the nerve or post-surgical change with an elevated hemidiaphragm.", sequence="CT contrast")],
     "Chest radiograph and diaphragm ultrasound; phrenic nerve conduction and diaphragm EMG"),
 lesion=[("Orthopnea and exertional dyspnea with an elevated hemidiaphragm", "ipsilateral", "Hemidiaphragm paralysis"), ("Respiratory failure requiring ventilation", "bilateral", "Bilateral phrenic loss: high cervical injury above C3, Guillain–Barré, motor neuron disease"), ("Shoulder-tip pain", "ipsilateral", "Referred sensory fibers via C4 from diaphragmatic irritation")],
 exam=["Observe abdominal paradox (abdomen moves in on inspiration) when lying flat", "Vital capacity sitting versus supine (a fall over 20% suggests diaphragm weakness)", "Percuss the diaphragm level"],
 pearls=["A patient who cannot lie flat but has clear lungs may have diaphragm paralysis", "Cord injuries above C3 need ventilation; C4 and below usually breathe"],
 citations=[SN3(113), SNA(510, 511), BK15(129, 130), C("berkowitz", 27, 281, 284)], syndromes=["syn-guillain-barre", "syn-parsonage-turner", "syn-complete-transection-spinal-shock"]))

E.append(pn("nerve-long-thoracic", "Long thoracic nerve", latin="Nervus thoracicus longus",
 summary="Arising directly from the C5, C6 and C7 roots before they form the trunks, the long thoracic nerve descends behind the plexus and over the outer surface of serratus anterior, which it supplies segmentally. Its long superficial course makes it vulnerable to stretch (carrying heavy loads, sports), to surgery in the axilla and to neuralgic amyotrophy; the resulting serratus palsy produces winging of the scapula when the arm is pushed forward. Because it leaves the roots proximal to the trunks, its involvement points to a root or very proximal lesion rather than a trunk or cord lesion.",
 location="From the posterior aspect of the C5–C7 roots in the neck, through or behind the middle scalene, down the lateral chest wall on serratus anterior to its lower digitations.",
 function="Motor supply to serratus anterior: protraction and upward rotation of the scapula and stabilization of the scapula against the chest wall during arm elevation.",
 imaging=img([view("axial", 0, -48, -65, "cervical cord; the nerve arises from C5–C7 roots")],
     NOIMG + " MR neurography shows the nerve along the chest wall; denervation edema of serratus anterior on STIR is the indirect sign.",
     [pathol("Long thoracic neuropathy", "MRI", "T2 hyperintensity and later fatty atrophy of serratus anterior with a normal or thickened nerve.", sequence="STIR")],
     "EMG of serratus anterior; MR neurography"),
 lesion=[("Medial winging of the scapula on forward pushing against a wall", "ipsilateral", "Serratus anterior paralysis"), ("Difficulty elevating the arm above 90 degrees", "ipsilateral", "Loss of scapular upward rotation"), ("No sensory loss", "n/a", "Purely motor nerve")],
 exam=["Push-against-the-wall test for winging", "Compare with lateral winging of trapezius palsy (accessory nerve), which appears on abduction", "Check the rest of the plexus and the C5–C7 roots"],
 pearls=["Winging worse on pushing forward is serratus (long thoracic); worse on abduction is trapezius (accessory nerve)", "Serratus involvement with shoulder pain a few weeks earlier is neuralgic amyotrophy"],
 citations=[SN3(113), BK16(141, 147)], syndromes=["syn-parsonage-turner", "syn-erb-duchenne"]))

E.append(pn("nerve-suprascapular", "Suprascapular nerve", latin="Nervus suprascapularis",
 summary="A branch of the upper trunk (C5–C6) that runs back through the suprascapular notch under the transverse scapular ligament to supply supraspinatus, then around the spinoglenoid notch to supply infraspinatus, with sensory fibers to the shoulder joint but no cutaneous branch. It is compressed at either notch (ganglion cysts, repetitive overhead activity in athletes) and injured in upper trunk lesions and neuralgic amyotrophy, producing a painless or aching shoulder with weak abduction initiation and external rotation and visible wasting of the spinati.",
 location="From the upper trunk in the posterior triangle, laterally beneath the trapezius to the suprascapular notch, into the supraspinous fossa, then around the lateral border of the scapular spine (spinoglenoid notch) into the infraspinous fossa.",
 function="Motor supply to supraspinatus (initiation of abduction) and infraspinatus (external rotation); proprioceptive supply to the glenohumeral and acromioclavicular joints.",
 imaging=img([view("axial", 0, -48, -65, "cervical cord; fibers from C5–C6")],
     NOIMG + " Shoulder MRI shows a paralabral cyst at the spinoglenoid notch compressing the nerve and denervation edema or fatty atrophy of the spinati.",
     [pathol("Suprascapular nerve entrapment", "MRI", "Ganglion cyst at the suprascapular or spinoglenoid notch with STIR-bright, later atrophic, supraspinatus and/or infraspinatus.", sequence="STIR")],
     "Shoulder MRI; EMG of supraspinatus and infraspinatus"),
 lesion=[("Weak initiation of abduction and weak external rotation with wasting of the spinati", "ipsilateral", "Suprascapular notch lesion (both muscles)"), ("Isolated infraspinatus wasting and weak external rotation", "ipsilateral", "Spinoglenoid notch lesion (infraspinatus only)"), ("Deep posterior shoulder pain without cutaneous loss", "ipsilateral", "Articular sensory fibers")],
 exam=["Inspect the supra- and infraspinous fossae from behind for wasting", "External rotation against resistance with the elbow at the side", "Empty can test for supraspinatus"],
 pearls=["Infraspinatus wasting alone points to the spinoglenoid notch; both spinati point to the suprascapular notch", "Rotator cuff tear and suprascapular neuropathy both weaken external rotation; wasting with a normal cuff on MRI points to the nerve"],
 citations=[SN3(113), BK16(141, 147)], syndromes=["syn-erb-duchenne", "syn-parsonage-turner"]))

E.append(pn("nerve-axillary", "Axillary nerve", latin="Nervus axillaris", synonyms=["circumflex nerve"],
 summary="A terminal branch of the posterior cord (C5–C6) that leaves the axilla backward through the quadrangular space with the posterior circumflex humeral artery, winds around the surgical neck of the humerus and supplies deltoid and teres minor and a patch of skin over the deltoid (the regimental badge area). Its fixed course at the surgical neck makes it the nerve most often injured by anterior shoulder dislocation and proximal humeral fracture; the result is a flat shoulder that cannot abduct and numbness over the lateral shoulder.",
 location="From the posterior cord behind the axillary artery, through the quadrangular space (bounded by teres minor, teres major, long head of triceps and the humerus), around the surgical neck of the humerus deep to deltoid.",
 function="Motor supply to deltoid (abduction from 15 to 90 degrees) and teres minor (external rotation); sensory supply to the skin over the lower deltoid (superior lateral cutaneous nerve of the arm).",
 imaging=img([view("axial", 0, -48, -65, "cervical cord; fibers from C5–C6")],
     NOIMG + " Shoulder MRI shows deltoid and teres minor denervation edema and the nerve in the quadrangular space; radiographs show the dislocation or fracture responsible.",
     [pathol("Axillary neuropathy after shoulder dislocation", "MRI", "STIR-bright deltoid and teres minor with a thickened nerve at the surgical neck.", sequence="STIR"), pathol("Quadrilateral space syndrome", "MRI", "Isolated teres minor atrophy from compression in the quadrangular space, often in throwing athletes.", sequence="T1")],
     "Radiograph, shoulder MRI; EMG of deltoid and teres minor"),
 lesion=[("Weak shoulder abduction with a flattened deltoid contour", "ipsilateral", "Deltoid paralysis"), ("Numbness over the lateral upper arm (regimental badge)", "ipsilateral", "Superior lateral cutaneous nerve of the arm"), ("Weak external rotation", "ipsilateral", "Teres minor")],
 exam=["Test abduction against resistance and palpate deltoid contraction before reducing a dislocation", "Sensation over the deltoid", "Compare with a C5 radiculopathy (biceps and rhomboids also involved) and upper trunk lesion (supraspinatus, biceps)"],
 pearls=["Document deltoid function and lateral shoulder sensation before and after reducing every shoulder dislocation", "Deltoid weakness with intact biceps and supraspinatus is the axillary nerve, not C5"],
 citations=[SN3(113), BK16(141, 147), BK16(150)], syndromes=["syn-axillary-neuropathy", "syn-erb-duchenne"]))

E.append(pn("nerve-musculocutaneous", "Musculocutaneous nerve", latin="Nervus musculocutaneus",
 summary="The terminal branch of the lateral cord (C5–C7) that pierces coracobrachialis, runs between biceps and brachialis supplying all three, and emerges lateral to the biceps tendon as the lateral cutaneous nerve of the forearm. It is rarely injured alone (heavy lifting, shoulder surgery, strenuous exercise), and its lesion produces weak elbow flexion and supination with an absent biceps reflex and numbness over the lateral forearm; brachioradialis (radial nerve) still allows some flexion.",
 location="From the lateral cord in the axilla, through coracobrachialis, down the arm between biceps brachii and brachialis, continuing as the lateral antebrachial cutaneous nerve along the radial border of the forearm.",
 function="Motor supply to coracobrachialis, biceps brachii and brachialis (elbow flexion, forearm supination, shoulder flexion); sensory supply to the lateral forearm.",
 imaging=img([view("axial", 0, -48, -65, "cervical cord; fibers from C5–C7")],
     NOIMG + " Arm MRI shows biceps and brachialis denervation; ultrasound follows the nerve through coracobrachialis.",
     [pathol("Musculocutaneous neuropathy", "MRI", "STIR hyperintensity of biceps, brachialis and coracobrachialis after strenuous exertion or surgery.", sequence="STIR")],
     "EMG; ultrasound"),
 lesion=[("Weak elbow flexion and supination with absent biceps jerk", "ipsilateral", "Biceps and brachialis paralysis; brachioradialis preserved"), ("Numbness of the lateral forearm", "ipsilateral", "Lateral antebrachial cutaneous nerve"), ("Preserved deltoid and supraspinatus", "n/a", "Distinguishes it from an upper trunk (Erb) lesion")],
 exam=["Elbow flexion with the forearm supinated (biceps) versus in mid-position (brachioradialis)", "Biceps reflex", "Sensation over the lateral forearm versus the lateral arm (axillary) and thumb (C6)"],
 pearls=["Weak biceps with normal deltoid and normal brachioradialis is the musculocutaneous nerve; add deltoid and it is the upper trunk or C5–C6", "Lateral forearm numbness with intact thumb sensation separates the nerve from a C6 root"],
 citations=[SN3(113), BK16(141, 147)], syndromes=["syn-erb-duchenne"]))

E.append(pn("nerve-median", "Median nerve", latin="Nervus medianus",
 summary="Formed by lateral and medial roots from the lateral and medial cords (C6–T1), the median nerve runs down the arm with the brachial artery, passes through the cubital fossa medial to the biceps tendon, between the heads of pronator teres and under the flexor digitorum superficialis arch (giving the pure motor anterior interosseous nerve), and enters the hand through the carpal tunnel beneath the flexor retinaculum. It supplies most forearm flexors and pronators, the LOAF muscles of the hand (lateral two lumbricals, opponens, abductor pollicis brevis, flexor pollicis brevis) and sensation to the lateral three and a half digits. Carpal tunnel syndrome is the commonest entrapment neuropathy of all.",
 location="Axilla and arm on the brachial artery, cubital fossa medial to the artery, forearm between flexor digitorum superficialis and profundus, wrist under the flexor retinaculum with the nine flexor tendons, hand as the recurrent motor branch and digital nerves.",
 subdivisions=[("Forearm branches", "pronator teres, flexor carpi radialis, palmaris longus, flexor digitorum superficialis"), ("Anterior interosseous nerve", "flexor pollicis longus, flexor digitorum profundus to index and middle fingers, pronator quadratus; no sensory fibers"), ("Palmar cutaneous branch", "thenar skin; arises above the wrist, spared in carpal tunnel syndrome"), ("Recurrent motor branch", "abductor pollicis brevis, opponens pollicis, flexor pollicis brevis"), ("Digital nerves", "sensation of thumb, index, middle and lateral half of the ring finger and their dorsal tips")],
 function="Pronation, wrist and finger flexion, thumb opposition and abduction, precision grip; sensation of the radial palm and lateral three and a half digits.",
 imaging=img([view("axial", 0, -48, -65, "cervical cord; fibers from C6–T1")],
     NOIMG + " Wrist ultrasound measures the cross-sectional area of the nerve at the carpal tunnel inlet (enlarged in carpal tunnel syndrome); MRI shows flattening under the retinaculum and denervation of the thenar muscles.",
     [pathol("Carpal tunnel syndrome", "US", "Enlarged median nerve cross-sectional area (over ~10–12 mm²) at the tunnel inlet with distal flattening; nerve conduction shows slowed sensory and prolonged distal motor latency across the wrist.", sequence="n/a"), pathol("Anterior interosseous neuropathy", "MRI", "Denervation edema of flexor pollicis longus, pronator quadratus and the radial half of flexor digitorum profundus without sensory change.", sequence="STIR"), pathol("Pronator syndrome", "MRI", "Proximal median compression at pronator teres with forearm flexor and thenar involvement and forearm pain.", sequence="STIR")],
     "Nerve conduction studies and EMG; wrist ultrasound; MRI for proximal lesions"),
 lesion=[("Nocturnal tingling of the thumb, index and middle fingers relieved by shaking, later thenar wasting (carpal tunnel syndrome)", "ipsilateral", "Compression under the flexor retinaculum; palmar cutaneous branch spared"), ("Inability to make an O with thumb and index (pinch sign)", "ipsilateral", "Anterior interosseous nerve: flexor pollicis longus and index profundus"), ("Hand of benediction on attempted fist", "ipsilateral", "High median lesion: index and middle fingers cannot flex"), ("Ape hand with loss of opposition", "ipsilateral", "Recurrent motor branch or carpal tunnel: thenar paralysis")],
 exam=["Thumb abduction against resistance (abductor pollicis brevis) and opposition", "Two-point discrimination on the index finger versus the little finger", "Phalen and Tinel signs at the wrist", "Pinch sign for the anterior interosseous nerve", "Thenar skin sensation (spared in carpal tunnel, lost in proximal lesions)"],
 pearls=["Numbness that spares the thenar eminence and involves the fingertips of the first three digits is the carpal tunnel; thenar numbness means the lesion is above the wrist", "Weak thumb abduction with normal pronation and forearm flexion places the lesion at the wrist"],
 citations=[SN3(113), SN3(120), BK16(141, 147), BK16(148, 150)], syndromes=["syn-carpal-tunnel", "syn-klumpke"], pitfalls=["C6 or C7 radiculopathy mimics carpal tunnel syndrome: neck pain, a reduced reflex and proximal weakness point to the root"]))

E.append(pn("nerve-ulnar", "Ulnar nerve", latin="Nervus ulnaris",
 summary="The terminal branch of the medial cord (C8–T1) descends on the medial side of the arm, passes behind the medial epicondyle in the cubital tunnel (where it is palpable and vulnerable), enters the forearm between the heads of flexor carpi ulnaris, supplies that muscle and the ulnar half of flexor digitorum profundus, and crosses the wrist superficial to the flexor retinaculum through Guyon's canal to supply most of the small muscles of the hand (interossei, medial lumbricals, hypothenar muscles, adductor pollicis) and sensation to the little finger and half the ring finger. Its dorsal cutaneous branch arises above the wrist, so dorsal ulnar hand sensation separates elbow from wrist lesions.",
 location="Medial arm on coracobrachialis, then behind the medial intermuscular septum, through the cubital tunnel behind the medial epicondyle, down the medial forearm under flexor carpi ulnaris with the ulnar artery, through Guyon's canal at the wrist lateral to the pisiform, into the hand as superficial (sensory) and deep (motor) branches.",
 subdivisions=[("Forearm branches", "flexor carpi ulnaris, flexor digitorum profundus to ring and little fingers"), ("Dorsal cutaneous branch", "dorsal ulnar hand; arises 5–8 cm above the wrist"), ("Superficial terminal branch", "palmaris brevis, sensation of little finger and medial half of ring finger"), ("Deep terminal branch", "hypothenar muscles, interossei, medial two lumbricals, adductor pollicis, flexor pollicis brevis (deep head)")],
 function="Finger abduction and adduction, thumb adduction, flexion of the ring and little fingers, power grip and fine finger control; sensation of the medial one and a half digits and the ulnar hand.",
 imaging=img([view("axial", 0, -48, -65, "cervical cord; fibers from C8–T1")],
     NOIMG + " Elbow ultrasound and MRI show nerve enlargement at the cubital tunnel, subluxation over the epicondyle, and denervation of the interossei and flexor digitorum profundus.",
     [pathol("Ulnar neuropathy at the elbow", "US", "Enlarged nerve at or just proximal to the medial epicondyle; nerve conduction shows focal slowing across the elbow segment.", sequence="n/a"), pathol("Guyon's canal (wrist) lesion", "MRI", "Ganglion or hamate fracture compressing the deep branch with intrinsic denervation and spared dorsal sensation.", sequence="STIR")],
     "Nerve conduction studies across the elbow; ultrasound; MRI of the wrist for Guyon's canal"),
 lesion=[("Numbness of the little finger and half the ring finger, weak finger abduction, wasting of the first dorsal interosseous", "ipsilateral", "Ulnar nerve at the elbow (cubital tunnel), the commonest site"), ("Claw hand (ulnar paradox: worse with distal lesions)", "ipsilateral", "Loss of lumbricals to ring and little fingers; profundus preserved in wrist lesions makes the claw worse"), ("Froment sign: thumb flexes when pinching paper", "ipsilateral", "Adductor pollicis weakness compensated by flexor pollicis longus (median)"), ("Intrinsic wasting with normal sensation", "ipsilateral", "Deep branch lesion in Guyon's canal (cyclist's palsy)")],
 exam=["Finger abduction against resistance and first dorsal interosseous bulk", "Froment sign and Wartenberg sign (abducted little finger)", "Sensation on the little finger, and on the dorsal ulnar hand to separate elbow from wrist", "Tinel at the elbow; elbow flexion test", "Flexor digitorum profundus to the little finger (spared in wrist lesions)"],
 pearls=["Dorsal ulnar hand numbness means the lesion is above the wrist; normal dorsal sensation with intrinsic weakness means Guyon's canal", "Hand intrinsic wasting with normal sensation everywhere should raise motor neuron disease or a C8–T1 lesion, not just an ulnar palsy"],
 citations=[SN3(113), SN3(120), BK16(141, 147), BK16(150, 153)], syndromes=["syn-cubital-tunnel", "syn-klumpke", "syn-neurogenic-thoracic-outlet"], pitfalls=["Lower trunk plexopathy and C8–T1 radiculopathy also waste the hand, but they involve median-innervated thenar muscles and medial forearm sensation too"]))

E.append(pn("nerve-radial", "Radial nerve", latin="Nervus radialis",
 summary="The largest branch of the posterior cord (C5–T1), the radial nerve supplies every extensor of the elbow, wrist and fingers. It spirals around the back of the humerus in the radial groove with the profunda brachii artery, where it is compressed against the bone during deep sleep (Saturday night palsy) or torn by humeral shaft fractures, pierces the lateral intermuscular septum, and divides in front of the lateral epicondyle into a superficial sensory branch (dorsal radial hand) and the posterior interosseous nerve, which passes through supinator to the finger extensors. Wrist drop with sparing of triceps is its signature.",
 location="Axilla behind the axillary artery, radial (spiral) groove of the humerus between the heads of triceps, lateral arm between brachialis and brachioradialis, division at the lateral epicondyle; the posterior interosseous nerve winds around the radial neck through the arcade of Frohse and supinator.",
 subdivisions=[("Branches in the axilla and arm", "triceps, anconeus, posterior cutaneous nerves of the arm and forearm"), ("Branches at the elbow", "brachioradialis, extensor carpi radialis longus"), ("Posterior interosseous nerve", "supinator, extensor carpi radialis brevis, extensor digitorum, extensor carpi ulnaris, extensor pollicis longus and brevis, abductor pollicis longus, extensor indicis"), ("Superficial radial nerve", "sensation over the dorsum of the hand and first web space (anatomical snuffbox)")],
 function="Extension of the elbow, wrist, fingers and thumb, supination, and stabilization of the wrist for grip; sensation of the posterior arm and forearm and the dorsolateral hand.",
 imaging=img([view("axial", 0, -48, -65, "cervical cord; fibers from C5–T1")],
     NOIMG + " Humerus radiographs show the fracture; ultrasound follows the nerve in the spiral groove and at the arcade of Frohse; MRI shows denervation of the extensor compartment.",
     [pathol("Radial neuropathy at the spiral groove", "US", "Swollen nerve in the spiral groove with denervation of brachioradialis and the extensors but spared triceps.", sequence="n/a"), pathol("Posterior interosseous neuropathy", "MRI", "Denervation of the finger extensors and extensor carpi ulnaris with spared wrist extension (radial deviation) and normal sensation; lipoma or ganglion at the arcade of Frohse.", sequence="STIR")],
     "Nerve conduction and EMG (triceps, brachioradialis, extensors); ultrasound"),
 lesion=[("Wrist drop and finger drop with weak brachioradialis, sparing triceps", "ipsilateral", "Lesion at the spiral groove"), ("Wrist drop with triceps weakness and posterior arm numbness", "ipsilateral", "Lesion in the axilla (crutch palsy)"), ("Finger drop with radially deviated wrist extension and normal sensation", "ipsilateral", "Posterior interosseous nerve"), ("Numbness of the dorsal first web space only", "ipsilateral", "Superficial radial nerve (handcuff neuropathy)")],
 exam=["Wrist and finger extension with the wrist supported to unmask true extensor weakness", "Triceps power and reflex (localizes above or below the spiral groove)", "Brachioradialis contraction with the forearm in mid-position", "Sensation in the first dorsal web space", "Beware apparent weakness of ulnar-innervated finger abduction when the wrist is flexed"],
 pearls=["Wrist drop with a preserved triceps reflex is the spiral groove; with an absent triceps reflex look higher (axilla, posterior cord, C7)", "Finger drop without wrist drop and with normal sensation is the posterior interosseous nerve"],
 citations=[SN3(113), SN3(120), BK16(141, 147), BK16(150, 151)], syndromes=["syn-radial-neuropathy", "syn-radiculopathy-cervical"], pitfalls=["A C7 radiculopathy also weakens triceps and wrist extension, but adds neck pain and involves pronator teres and flexor carpi radialis (median-innervated C7 muscles)"]))

E.append(pn("roots-c5-t1", "Cervical roots C5–T1", latin="Radices C5–T1", synonyms=["brachial plexus roots"],
 summary="The five roots of the brachial plexus each carry a recognizable package of muscle, reflex and dermatome that lets a cervical radiculopathy be assigned to a level at the bedside: C5 shoulder abduction and the lateral upper arm; C6 elbow flexion, wrist extension and the thumb; C7 elbow extension, wrist flexion and the middle finger; C8 finger flexion and the little finger; T1 finger abduction and the medial arm. Because cervical roots exit above their vertebra, the C6 root is compressed by the C5–C6 disc and the C7 root by the C6–C7 disc, the two commonest levels; C8 exits below C7.",
 location="Ventral rami leaving the intervertebral foramina between C4–C5 (C5 root) and T1–T2 (T1 root), passing between the scalene muscles into the posterior triangle to form the trunks of the plexus.",
 subdivisions=[("C5", "deltoid, supraspinatus, infraspinatus, biceps (with C6), rhomboids; biceps reflex; lateral upper arm"), ("C6", "biceps, brachioradialis, extensor carpi radialis, pronator teres; biceps and brachioradialis reflexes; thumb and lateral forearm"), ("C7", "triceps, wrist flexors, finger extensors, pronator teres, latissimus; triceps reflex; middle finger"), ("C8", "finger flexors, thumb flexors and extensors, hand intrinsics (with T1); finger flexor reflex; little finger and medial forearm"), ("T1", "hand intrinsics (interossei, abductor pollicis brevis); medial arm; sympathetic fibers to the eye")],
 function="Segmental motor, sensory and (T1) sympathetic supply to the upper limb, redistributed by the brachial plexus.",
 imaging=img([view("axial", 0, -48, -65, "upper cervical cord above the C5–T1 segments")],
     NOIMG + " Cervical MRI shows foraminal narrowing by disc or osteophyte at the appropriate level; the root affected is the one exiting at that foramen (C5–C6 disc → C6).",
     [pathol("Cervical disc herniation with radiculopathy", "MRI", "Posterolateral disc protrusion at C5–C6 or C6–C7 narrowing the foramen and contacting the exiting root.", sequence="T2"), pathol("Cervical spondylosis with foraminal stenosis", "CT", "Uncovertebral and facet osteophytes narrowing the foramina, often multilevel.", sequence="CT non-contrast")],
     "Cervical MRI; EMG including paraspinal muscles to confirm a root level"),
 lesion=[("Neck pain radiating to the thumb with weak biceps and brachioradialis and a reduced biceps reflex", "ipsilateral", "C6 radiculopathy (C5–C6 disc)"), ("Pain to the middle finger with weak triceps and wrist flexion and a reduced triceps reflex", "ipsilateral", "C7 radiculopathy (C6–C7 disc)"), ("Shoulder pain with weak deltaoid and external rotation", "ipsilateral", "C5 radiculopathy"), ("Little finger numbness with weak finger flexion and intrinsics, Horner syndrome possible", "ipsilateral", "C8–T1 lesion (disc, Pancoast tumor)")],
 exam=["Spurling test (neck extension and rotation to the painful side)", "Key muscle for each root and the reflexes", "Dermatomal sensation: thumb (C6), middle finger (C7), little finger (C8)", "Check for myelopathy signs in the legs (cord compression at the same level)"],
 pearls=["A reflex loss plus a dermatome plus a myotome equals a root; a single nerve pattern equals a nerve; a mixture equals the plexus", "Paraspinal muscle denervation on EMG proves the lesion is at the root, proximal to the plexus"],
 citations=[SN3(98, 100), SNA(510, 511), BK16(141, 147), BK15(130, 133)], syndromes=["syn-radiculopathy-cervical", "syn-cervical-spondylotic-myelopathy", "syn-erb-duchenne", "syn-klumpke"]))

write(E)
