import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).parent))
from lib import *
E = []
S = lambda ch, a, b=None: C("snell", ch, a, b)
B = lambda ch, a, b=None: C("berkowitz", ch, a, b)
def q(id, type_, vignette, stem, options, answer, explanation, structures=(), syndromes=(), pathways=(), highlight=(), difficulty="2", cites=()):
    E.append({"kind": "quiz", "id": id, "type": type_, "vignette": vignette, "stem": stem, "options": [{"key": k, "text": t} for k, t in zip("ABCDE", options)], "answer": answer, "explanation": explanation,
              "targets": {"structureIds": list(structures), "syndromeIds": list(syndromes), "pathwayIds": list(pathways)}, "highlightOnReveal": list(highlight), "difficulty": difficulty, "citations": list(cites), "original": True})

q("qz-31", "localize", "A 62-year-old right-handed woman speaks fluently but her sentences are full of wrong words she does not notice, she cannot follow a two-step command, and when asked to repeat 'no ifs, ands or buts' she produces nonsense. Her strength is normal. Finger counting is missed in the right upper quadrant.", "Which cortical region is damaged?",
  ["Left pars opercularis", "Left posterior superior temporal gyrus", "Left supramarginal gyrus alone", "Left angular gyrus", "Right posterior superior temporal gyrus"], "B",
  "Fluent paraphasic speech with impaired comprehension and repetition is Wernicke aphasia, from the posterior superior temporal gyrus of the dominant hemisphere; the superior quadrantanopia comes from Meyer's loop in the temporal white matter beneath it, and normal strength shows the precentral gyrus of the superior division is spared.",
  structures=["gyrus-superior-temporal-posterior", "tract-optic-radiation"], syndromes=["syn-aphasia-wernicke", "syn-mca-inferior-division"], highlight=["gyrus-superior-temporal-posterior-l", "tract-optic-radiation-l"], cites=[B(7, 53, 58)])
q("qz-32", "localize", "A 70-year-old man is brought by his wife because he no longer recognizes her or their children by their faces, though he knows them at once by voice. He reads normally, names objects and has a left upper quadrant field defect.", "Where is the lesion?",
  ["Right posterior fusiform gyrus", "Left posterior fusiform gyrus", "Right amygdala", "Left angular gyrus", "Bilateral occipital poles"], "A",
  "Prosopagnosia with preserved reading and object naming points to the right fusiform face area; the left upper quadrant defect places the lesion in the right occipito-temporal region where the lower calcarine bank and the optic radiation lie nearby. A left fusiform lesion would impair reading (pure alexia) rather than faces.",
  structures=["cortex-temporal-fusiform-posterior", "gyrus-lingual"], syndromes=["syn-pca-infarct"], highlight=["cortex-temporal-fusiform-posterior-r", "gyrus-lingual-r"], cites=[B(6, 47, 52), B(7, 58, 60)])
q("qz-33", "localize", "A 58-year-old right-handed woman has a small stroke. Her strength and sensation are normal, but when asked to show how she would use a key or brush her teeth she cannot do it with either hand, and she cannot copy meaningless hand postures. She understands the instructions and can describe the actions in words.", "Which structure is damaged?",
  ["Right supramarginal gyrus", "Left supramarginal gyrus", "Right precentral gyrus", "Body of the corpus callosum", "Left frontal operculum"], "B",
  "Ideomotor apraxia of both hands with intact comprehension and strength is a lesion of the dominant left inferior parietal lobule, which stores the movement formulas that the right hemisphere receives through the corpus callosum; a callosal lesion would spare the right hand, and a right parietal lesion would produce neglect rather than apraxia.",
  structures=["gyrus-supramarginal-anterior"], syndromes=["syn-gerstmann"], highlight=["gyrus-supramarginal-anterior-l"], difficulty="3", cites=[B(7, 58, 60)])
q("qz-34", "localize", "A 66-year-old man wakes unable to read the newspaper, although he can write a note to his wife, which he then cannot read back. He names objects and speaks normally. He has a right homonymous hemianopia.", "Which two structures are damaged together?",
  ["Left angular gyrus and left arcuate fasciculus", "Left calcarine cortex and the splenium of the corpus callosum", "Left pars triangularis and left insula", "Right calcarine cortex and the genu of the corpus callosum", "Left planum temporale and left Heschl's gyrus"], "B",
  "Alexia without agraphia is a disconnection: the left visual cortex is destroyed (right hemianopia) and the splenial fibers that would bring the surviving right visual cortex's information to the left language cortex are cut, so words are seen but cannot be read; writing, driven from the intact language areas, is preserved.",
  structures=["cortex-intracalcarine", "corpus-callosum", "tract-inferior-longitudinal-fasciculus"], syndromes=["syn-alexia-without-agraphia"], highlight=["cortex-intracalcarine-l", "corpus-callosum"], cites=[B(7, 58, 60)])
q("qz-35", "localize", "A 74-year-old woman after cardiac arrest can read single letters but not words, reaches past objects she looks at, and describes a picture of a kitchen one item at a time without grasping the scene. Acuity is normal.", "Where are the lesions?",
  ["Bilateral medial occipital cortex", "Bilateral parieto-occipital border zones", "Bilateral hippocampi", "Left angular gyrus", "Bilateral fusiform gyri"], "B",
  "Simultanagnosia, optic ataxia and ocular apraxia form Balint syndrome, from bilateral dorsal parieto-occipital damage; after cardiac arrest the lesions lie in the border zones between the middle and posterior cerebral arteries, the superior lateral occipital and superior parietal cortex.",
  structures=["cortex-lateral-occipital-superior", "territory-mca-occipital"], syndromes=["syn-balint", "syn-watershed-infarct"], highlight=["cortex-lateral-occipital-superior-l", "cortex-lateral-occipital-superior-r"], cites=[B(7, 58, 60), B(19, 190, 194)])
q("qz-36", "localize", "A 55-year-old man has sudden weakness of the left leg with a normal arm and face. He is apathetic and answers slowly, and his wife says he has been incontinent since the event. A grasp reflex is present on the left.", "Which artery is occluded?",
  ["Right middle cerebral artery, superior division", "Right anterior cerebral artery", "Right posterior cerebral artery", "Right lenticulostriate artery", "Basilar artery"], "B",
  "Leg-predominant weakness with abulia, incontinence and a grasp reflex is the anterior cerebral artery territory: the paracentral lobule (leg), the medial frontal micturition and motivation areas and the cingulate cortex. An MCA lesion would weaken the face and arm.",
  structures=["territory-aca-major", "gyrus-superior-frontal", "cortex-supplementary-motor"], syndromes=["syn-aca-infarct"], highlight=["territory-aca-major-r", "gyrus-superior-frontal-r"], cites=[B(7, 55, 57)])
q("qz-37", "localize", "A 48-year-old woman has had brief nocturnal attacks for years: she sits up suddenly, her right arm rises abducted and her head turns toward it, she makes a loud noise, and it is over in twenty seconds. She remembers the attacks. Two EEGs have been normal and she was told the attacks are psychological.", "Where do these seizures arise?",
  ["Left medial temporal lobe", "Left supplementary motor area", "Right supplementary motor area", "Left occipital lobe", "Left insula"], "B",
  "A brief nocturnal tonic seizure with a fencing posture (contralateral arm abducted, head turned toward it), vocalization and preserved awareness is the signature of the supplementary motor area; the focus is interhemispheric, so the scalp EEG is often normal, and the posture points to the left SMA. Medial temporal seizures begin with an epigastric aura and impair awareness.",
  structures=["cortex-supplementary-motor"], highlight=["cortex-supplementary-motor-l"], cites=[B(18, 167, 172)])
q("qz-38", "identify", "A 30-year-old woman with epilepsy describes each seizure beginning with a rising feeling in her stomach and a sense that everything has happened before, followed by lip smacking and fumbling with her right hand while her left hand assumes a fixed clawed posture. She is confused for ten minutes afterward and has difficulty speaking.", "Which side and structure?",
  ["Left hippocampus and amygdala", "Right hippocampus and amygdala", "Left frontal operculum", "Right superior temporal gyrus", "Left cingulate gyrus"], "A",
  "The epigastric aura and deja vu come from the medial temporal lobe; the dystonic posture of the left hand points to the contralateral (left) hemisphere, the automatisms are ipsilateral to the focus, and postictal aphasia marks the language-dominant side. Left mesial temporal epilepsy is the answer.",
  structures=["hippocampus", "amygdala", "uncus"], highlight=["hippocampus-l", "amygdala-l"], cites=[B(18, 167, 172)])
q("qz-39", "imaging", "A 45-year-old man has drug-resistant seizures of the type described above. Coronal FLAIR MRI shows a small bright left hippocampus with loss of its internal architecture and a dilated left temporal horn.", "What is the lesion?",
  ["Low-grade glioma", "Mesial temporal sclerosis", "Herpes encephalitis", "Cavernoma", "Focal cortical dysplasia"], "B",
  "A small hippocampus with increased FLAIR signal, loss of the internal digitations and an enlarged temporal horn is mesial temporal sclerosis, the commonest surgically curable epilepsy; a tumor would expand rather than shrink the hippocampus and herpes would be acute with fever.",
  structures=["hippocampus", "ventricle-lateral-inferior-horn"], highlight=["hippocampus-l", "ventricle-lateral-inferior-horn-l"], cites=[B(18, 167, 172)])
q("qz-40", "localize", "A 68-year-old woman is admitted with sudden deep sleepiness. When roused she cannot look up, has no memory of the morning and drifts off again. Her pupils are sluggish. Strength and sensation are normal.", "Which vascular structure is responsible?",
  ["Right middle cerebral artery", "Artery of Percheron (paramedian thalamic)", "Left posterior inferior cerebellar artery", "Anterior communicating artery", "Superior sagittal sinus"], "B",
  "Hypersomnolence with vertical gaze palsy and amnesia and no long-tract signs is bilateral paramedian thalamic and rostral midbrain infarction, the territory of a single artery of Percheron arising from one P1 segment.",
  structures=["thalamus-pulvinar-medial-centrolateral", "territory-posterior-choroidal-thalamoperforating"], syndromes=["syn-top-of-basilar"], highlight=["thalamus-pulvinar-medial-centrolateral-l", "thalamus-pulvinar-medial-centrolateral-r"], cites=[B(7, 62, 63)])
q("qz-41", "localize", "A 60-year-old man develops weakness of the right face, arm and leg, loss of all sensation on the right side and a right homonymous hemianopia within an hour. He speaks normally, follows commands and is aware of his deficits. CT shows no cortical change.", "Which artery is most likely occluded?",
  ["Left middle cerebral artery stem", "Left anterior choroidal artery", "Left posterior cerebral artery", "Left lenticulostriate artery", "Left superior cerebellar artery"], "B",
  "Hemiparesis, hemisensory loss and hemianopia without aphasia or neglect is the triad of the anterior choroidal artery, which supplies the posterior limb of the internal capsule (motor and sensory fibers) and the optic tract and geniculate; an MCA stem occlusion would add cortical signs, and a lenticulostriate lacune would spare the fields.",
  structures=["territory-anterior-choroidal-thalamoperforating", "artery-anterior-choroidal"], syndromes=["syn-anterior-choroidal-infarct"], highlight=["territory-anterior-choroidal-thalamoperforating-l", "artery-anterior-choroidal-l"], cites=[B(7, 62, 63)])
q("qz-42", "localize", "A 72-year-old hypertensive man has sudden weakness of the left arm and leg with ataxia of the same limbs out of proportion to the weakness; sensation, speech and vision are normal.", "Which structure best explains the combination?",
  ["Left cerebellar hemisphere", "Right posterior limb of the internal capsule with corticopontine fibers", "Right thalamus", "Left pons", "Right cerebellar hemisphere"], "B",
  "Ataxic hemiparesis is a lacune of the posterior limb (or basis pontis) interrupting the corticospinal tract and the corticopontine fibers together; the corticopontine input crosses in the pons and the cerebellar output crosses back, so ataxia lands on the weak side. A cerebellar lesion would give ipsilateral ataxia without weakness.",
  structures=["tract-corticopontine-frontal", "tract-corticospinal", "internal-capsule"], syndromes=["syn-lacunar-ataxic-hemiparesis"], highlight=["tract-corticopontine-frontal-r", "internal-capsule-r"], cites=[B(7, 60, 63)])
q("qz-43", "mechanism", "A 35-year-old man is found to have a small infarct of the right supramarginal gyrus after a cardiac embolus. Which of the following is the most likely persistent deficit?", "Choose the best answer.",
  ["Right hemianopia", "Left-sided extinction and neglect", "Expressive aphasia", "Right hand apraxia", "Left leg weakness"], "B",
  "The right inferior parietal lobule is the ventral attention hub; its lesion produces left neglect and extinction, often lasting because the superior longitudinal fasciculus II beneath it is interrupted. Aphasia and bilateral apraxia are left-hemisphere signs.",
  structures=["gyrus-supramarginal-anterior", "tract-superior-longitudinal-fasciculus-ii"], syndromes=["syn-hemineglect"], highlight=["gyrus-supramarginal-anterior-r", "tract-superior-longitudinal-fasciculus-ii-r"], cites=[B(7, 58, 60)])
q("qz-44", "localize", "A 54-year-old woman has a fall and afterward cannot smell coffee. Over months her family notes that she has become tactless, makes crude jokes and spends impulsively. She scores normally on a memory test.", "Which region should be imaged first?",
  ["Bilateral hippocampi", "Orbitofrontal cortex and olfactory tracts", "Left temporal pole", "Dorsolateral prefrontal cortex", "Anterior cingulate gyri"], "B",
  "Anosmia with disinhibition and preserved memory is the orbitofrontal syndrome: the gyri recti and orbital cortex sit on the anterior fossa floor beside the olfactory tracts and are bruised in falls (or compressed by an olfactory groove meningioma). The dorsolateral cortex would give a dysexecutive picture without anosmia.",
  structures=["cortex-orbitofrontal", "frontal-pole"], syndromes=["syn-anosmia"], highlight=["cortex-orbitofrontal-l", "cortex-orbitofrontal-r"], cites=[B(7, 61, 62), S(11, 327, 328)])
q("qz-45", "localize", "A 63-year-old man is brought by his daughter because he has become apathetic, sits all day and answers in monosyllables since a stroke two weeks ago. He is fully oriented and has no weakness. MRI shows a small infarct in the head of the caudate nucleus and the anterior limb of the internal capsule.", "Which connection is interrupted?",
  ["Corticospinal tract", "Anterior thalamic radiation and prefrontal-striatal loop", "Optic radiation", "Arcuate fasciculus", "Dentatorubrothalamic tract"], "B",
  "The anterior limb carries the anterior thalamic radiation between the mediodorsal and anterior thalamus and the prefrontal cortex, and the caudate head is the striatal station of the prefrontal loop; their interruption produces abulia without weakness, the frontal picture of a medial lenticulostriate (Heubner) infarct.",
  structures=["tract-thalamic-radiation-anterior", "tract-corticostriatal-anterior", "territory-medial-lenticulostriate"], highlight=["tract-thalamic-radiation-anterior-l", "territory-medial-lenticulostriate-l"], cites=[B(7, 62, 63)])
q("qz-46", "identify", "A 58-year-old man with atrial fibrillation has a stroke and afterward cannot repeat sentences, although he speaks fluently and understands everything; his speech contains sound substitutions that he corrects. MRI shows a small infarct in the left supramarginal white matter.", "Which fiber bundle is interrupted?",
  ["Uncinate fasciculus", "Arcuate fasciculus", "Inferior longitudinal fasciculus", "Frontal aslant tract", "Cingulum"], "B",
  "Conduction aphasia (fluent, comprehending, unable to repeat, self-corrected phonemic errors) is a disconnection of the posterior temporal from the frontal language cortex through the arcuate fasciculus, which runs beneath the supramarginal gyrus.",
  structures=["tract-arcuate-fasciculus"], syndromes=["syn-aphasia-conduction-global"], highlight=["tract-arcuate-fasciculus-l"], cites=[B(7, 53, 58)])
q("qz-47", "identify", "After removal of a medial frontal tumor a 40-year-old woman is mute and does not move her right arm for a week, then recovers fully over the following month. Repetition, when she began to speak, was normal from the start.", "What is the explanation?",
  ["Broca aphasia from the pars opercularis", "Supplementary motor area syndrome with frontal aslant tract disconnection", "Corticospinal tract infarct", "Conduction aphasia", "Anterior cerebral artery infarct of the paracentral lobule"], "B",
  "Transient mutism and contralateral akinesia after medial frontal surgery, with preserved repetition and full recovery in weeks, is the supplementary motor area syndrome: the SMA and its frontal aslant connection to the inferior frontal gyrus initiate speech and movement, and the lateral cortex takes over as they recover.",
  structures=["cortex-supplementary-motor", "tract-frontal-aslant"], highlight=["cortex-supplementary-motor-l", "tract-frontal-aslant-l"], cites=[B(4, 33, 34), B(7, 53, 58)])
q("qz-48", "localize", "A 70-year-old man has a stroke leaving him unable to see anything in his right visual field, but he can still recognize faces and read slowly. His pupils react normally. On fields, a small island of central vision survives on the right.", "Where is the lesion and why is the center spared?",
  ["Right optic tract; the macula has bilateral representation", "Left calcarine cortex; the occipital pole receives middle cerebral artery collateral supply", "Left optic radiation; macular fibers run separately", "Left lateral geniculate; the macula projects to the pulvinar", "Right calcarine cortex; the field defect is functional"], "B",
  "A congruous right hemianopia with normal pupils is a left calcarine (PCA) infarct, and the spared central island is macular sparing, because the macular cortex at the occipital pole is also supplied by terminal middle cerebral artery branches.",
  structures=["cortex-intracalcarine", "occipital-pole", "territory-pca-occipital"], syndromes=["syn-homonymous-hemianopia", "syn-pca-infarct"], highlight=["cortex-intracalcarine-l", "occipital-pole-l"], cites=[B(6, 47, 52)])
q("qz-49", "localize", "A 52-year-old woman notices that the left half of the room looks washed out, as if in black and white, while the right half is colored. Acuity is normal and she has a subtle left upper quadrant defect.", "Which cortical region is affected?",
  ["Right ventral occipito-temporal cortex (lingual and fusiform gyri)", "Right cuneus", "Left cuneus", "Right lateral geniculate nucleus", "Left fusiform gyrus"], "A",
  "Hemiachromatopsia in the left hemifield with an upper quadrant defect places the lesion in the right ventral occipito-temporal cortex below the calcarine sulcus, where the color-processing V4 region on the lingual and fusiform gyri lies next to the lower calcarine bank that represents the upper field.",
  structures=["cortex-temporo-occipital-fusiform", "gyrus-lingual"], syndromes=["syn-pca-infarct"], highlight=["cortex-temporo-occipital-fusiform-r", "gyrus-lingual-r"], cites=[B(6, 47, 52)])
q("qz-50", "localize", "A 45-year-old man has progressive right-sided hearing loss and tinnitus, then numbness of the right face and, later, unsteadiness with a right-sided intention tremor. MRI shows a mass in the right cerebellopontine angle extending into the internal auditory canal.", "Which cerebellar structure accounts for the last symptoms?",
  ["Right flocculus and cerebellar hemisphere (lobule VI, Crus I)", "Left dentate nucleus", "Vermis lobule VII", "Right lobule X only", "Left flocculus"], "A",
  "A vestibular schwannoma compresses the eighth nerve first, then the trigeminal nerve, then the flocculus and the anterior cerebellar hemisphere beside the middle cerebellar peduncle, producing ipsilateral limb ataxia and gaze-evoked nystagmus; cerebellar signs are ipsilateral because the outflow crosses twice.",
  structures=["cerebellar-lobule-x", "cerebellar-lobule-crus-i", "middle-cerebellar-peduncle"], syndromes=["syn-cerebellopontine-angle"], highlight=["cerebellar-lobule-x-r", "cerebellar-lobule-crus-i-r", "cn-08-vestibulocochlear-r"], cites=[B(12, 108, 114)])
q("qz-51", "localize", "A 66-year-old man with hypertension has sudden vertigo and vomiting and cannot stand. Head impulse testing is normal, there is direction-changing nystagmus, and there is no weakness, hearing loss or facial numbness.", "Which arterial territory is most likely involved?",
  ["Anterior inferior cerebellar artery", "Medial branch of the posterior inferior cerebellar artery (nodulus and uvula)", "Superior cerebellar artery", "Basilar paramedian pontine territory", "Labyrinthine artery"], "B",
  "Acute vertigo with a normal head impulse test, direction-changing nystagmus and inability to stand is a central vestibular lesion, most often a medial PICA infarct of the nodulus and uvula (lobules IX-X); AICA infarcts add deafness and facial weakness, and lateral medullary involvement adds crossed sensory loss.",
  structures=["cerebellar-lobule-ix", "cerebellar-lobule-x", "territory-inferior-cerebellar"], syndromes=["syn-central-vs-peripheral-vertigo", "syn-pica-cerebellar-infarct"], highlight=["cerebellar-lobule-ix-l", "cerebellar-lobule-ix-r", "territory-inferior-cerebellar-l"], cites=[B(12, 108, 114), B(8, 70, 73)])
q("qz-52", "localize", "A 60-year-old woman has a stroke in the right cerebellum. Her examination is remarkable only for mild gait unsteadiness, but her husband reports that she has become disorganized, cannot plan the day and answers questions in a flat, disinhibited way.", "Which lobules are most likely infarcted?",
  ["Anterior lobe (lobules I-V)", "Crus I and Crus II of the posterior lobe", "Nodulus and flocculus", "Vermis lobules VI-VII", "Lobules VIIIA and VIIIB"], "B",
  "A cerebellar lesion with executive and affective change and little motor deficit involves the posterior lobe hemispheres (Crus I and II), the cognitive cerebellum connected to the prefrontal cortex; the anterior lobe and lobule VIII carry the body maps and would produce ataxia.",
  structures=["cerebellar-lobule-crus-i", "cerebellar-lobule-crus-ii"], syndromes=["syn-cerebellar-hemispheric"], highlight=["cerebellar-lobule-crus-i-r", "cerebellar-lobule-crus-ii-r"], cites=[B(8, 67, 73)])
q("qz-53", "localize", "A 25-year-old woman has a slow, coarse tremor of the right arm that is present at rest, worsens when she holds the arm out and becomes wild when she reaches for a cup. It began three months after a midbrain hemorrhage.", "Which pathway is responsible?",
  ["Right corticospinal tract", "Left dentatorubrothalamic tract with the nigrostriatal fibers in the midbrain", "Right medial lemniscus", "Right dentate nucleus", "Left corticospinal tract"], "B",
  "A delayed rest-postural-intention tremor after a midbrain lesion is Holmes (rubral) tremor, from combined damage to the cerebellothalamic fibers passing through the red nucleus and to the nigrostriatal fibers; the lesion is contralateral (left midbrain) because the dentatorubrothalamic tract has already crossed.",
  structures=["tract-dentatorubrothalamic", "red-nucleus", "substantia-nigra-pars-compacta"], syndromes=["syn-benedikt", "syn-claude"], pathways=["pathway-cerebellar-circuits"], highlight=["tract-dentatorubrothalamic-l", "red-nucleus-l"], difficulty="3", cites=[B(23, 246, 250)])
q("qz-54", "mechanism", "A 78-year-old woman with a recent large left putaminal hemorrhage has a transient right hemiparesis. Which anatomical fact explains why hypertensive hemorrhages favor this site?", "Choose the best answer.",
  ["The putamen has the richest cortical blood supply", "The lateral lenticulostriate arteries are end-arteries arising directly from the high-pressure M1 segment", "The putamen lies in a watershed between two territories", "The internal capsule has no blood-brain barrier", "The putamen is drained by the great cerebral vein"], "B",
  "The lateral lenticulostriate perforators leave the M1 segment at right angles and take its full pressure without collateral support, so chronic hypertension produces lipohyalinosis and Charcot-Bouchard microaneurysms there; their rupture is the putaminal hemorrhage and their occlusion the capsular lacune.",
  structures=["territory-lateral-lenticulostriate", "arteries-lenticulostriate", "putamen"], syndromes=["syn-lacunar-pure-motor"], highlight=["territory-lateral-lenticulostriate-l", "putamen-l"], cites=[B(19, 194, 200)])
q("qz-55", "localize", "A 33-year-old woman develops weakness of hip abduction and foot dorsiflexion on the right with numbness of the dorsum of the foot after a prolonged labor. The ankle jerk is preserved. Nerve conduction studies show a normal superficial peroneal sensory response.", "Where is the lesion?",
  ["Common peroneal nerve at the fibular neck", "L5 root or lumbosacral plexus", "Sciatic nerve in the thigh", "Superficial peroneal nerve", "Tibial nerve"], "B",
  "Foot drop with weak hip abduction (superior gluteal nerve) cannot be a peroneal palsy, and a normal superficial peroneal sensory potential despite a numb dorsum means the lesion is proximal to the dorsal root ganglion or in the plexus close to it: the L5 root or lumbosacral trunk compressed by the fetal head. The sciatic nerve would reduce the sensory potential and spare hip abduction.",
  structures=["nerve-superior-gluteal", "plexus-lumbosacral", "nerves-dorsal-cutaneous-foot"], syndromes=["syn-lumbosacral-plexopathy", "syn-peroneal-palsy-foot-drop", "syn-radiculopathy-lumbosacral"], highlight=["superior-gluteal-nerve-r", "lumbosacral-plexus-r"], cites=[B(17, 157, 166)])
q("qz-56", "localize", "A 40-year-old man who fell asleep with his arm over a chair wakes with wrist and finger drop. The triceps is strong, the brachioradialis is weak, and sensation is lost over the dorsum of the hand and the back of the forearm.", "At which level is the radial nerve injured?",
  ["Axilla", "Spiral groove of the humerus", "Elbow (posterior interosseous branch)", "Wrist (superficial branch)", "Posterior cord of the plexus"], "B",
  "A spared triceps with weak brachioradialis and wrist extensors places the lesion at the spiral groove, below the triceps branches; numbness of the posterior forearm shows the posterior antebrachial cutaneous branch, which leaves in the groove, is involved, excluding a lesion below the elbow, where only the dorsal hand would be numb or, in a posterior interosseous lesion, nothing at all.",
  structures=["nerve-posterior-antebrachial-cutaneous", "nerve-superficial-radial", "nerve-radial"], syndromes=["syn-radial-neuropathy"], highlight=["posterior-antebrachial-cutaneous-nerve-l", "radial-nerve-l"], cites=[B(16, 141, 156)])
q("qz-57", "localize", "A 50-year-old woman has numbness of the little finger, wasting of the hand muscles and numbness of the medial forearm up to the elbow. The nerve conduction study shows an absent medial antebrachial cutaneous sensory response.", "Where is the lesion?",
  ["Ulnar nerve at the elbow", "Ulnar nerve at the wrist", "Lower trunk or medial cord of the brachial plexus", "C6 root", "Median nerve at the carpal tunnel"], "C",
  "The ulnar nerve supplies no forearm skin; numbness of the medial forearm with an absent medial antebrachial cutaneous potential proves the lesion is in the medial cord or lower trunk (thoracic outlet syndrome, Pancoast tumor, Klumpke injury), not at the elbow.",
  structures=["nerve-medial-antebrachial-cutaneous", "plexus-brachial"], syndromes=["syn-neurogenic-thoracic-outlet", "syn-klumpke", "syn-cubital-tunnel"], highlight=["medial-antebrachial-cutaneous-nerve-l", "brachial-plexus-l"], cites=[B(16, 141, 156)])
q("qz-58", "localize", "A 19-year-old man has a shoulder injury in rugby. Afterward he cannot abduct the shoulder or flex the elbow, sensation is reduced over the lateral arm and forearm, and the scapula wings laterally when he braces his shoulders back. EMG shows denervation of the rhomboids.", "Which is the most likely site of injury?",
  ["Upper trunk of the brachial plexus", "C5 and C6 roots (preganglionic)", "Musculocutaneous nerve", "Axillary nerve", "Lateral cord"], "B",
  "The pattern is an Erb-type upper plexus picture, but rhomboid denervation means the dorsal scapular nerve, which leaves the C5 root before the trunk forms, is involved, placing the lesion at the roots; a preganglionic root avulsion carries a poor prognosis and changes the surgical plan.",
  structures=["nerve-dorsal-scapular", "plexus-brachial", "nerve-lateral-antebrachial-cutaneous"], syndromes=["syn-erb-duchenne", "syn-radiculopathy-cervical"], highlight=["dorsal-scapular-nerve-l", "brachial-plexus-l"], difficulty="3", cites=[B(16, 141, 156)])
q("qz-59", "mechanism", "A 4-month-old ex-premature infant has stiff legs that scissor when held upright, with relatively normal arms. Cranial ultrasound in the neonatal period showed periventricular cysts.", "Why are the legs affected more than the arms?",
  ["The leg area of the motor cortex is supplied by the anterior cerebral artery", "The corticospinal fibers for the legs run closest to the lateral ventricles and are injured by periventricular leukomalacia", "The spinal cord is more vulnerable in prematurity", "The arm fibers cross earlier in the medulla", "The cerebellum controls the arms"], "B",
  "Spastic diplegia of prematurity is periventricular leukomalacia: the corticospinal fibers for the legs descend through the periventricular white matter nearest the ventricles, in the border zone of the immature brain's perfusion, while the arm and face fibers run more laterally and are spared.",
  structures=["tract-corticospinal", "cerebral-white-matter", "ventricle-lateral"], highlight=["tract-corticospinal-l", "tract-corticospinal-r"], cites=[S(18, 486, 506), B(4, 33, 38)])
q("qz-60", "imaging", "A 24-year-old woman with a two-week history of headache worse on lying down and transient visual obscurations has papilledema and a sixth nerve palsy. CT of the brain is normal. MR venography shows an absent flow signal in the right transverse sinus.", "What is the diagnosis and the mechanism of the sixth nerve palsy?",
  ["Idiopathic intracranial hypertension; the nerve is compressed in the cavernous sinus", "Cerebral venous sinus thrombosis with raised pressure; the sixth nerve is stretched over the petrous ridge as a false localizing sign", "Pontine glioma; the abducens nucleus is infiltrated", "Migraine; the palsy is ophthalmoplegic migraine", "Meningitis; the nerve is inflamed in the subarachnoid space"], "B",
  "Headache, papilledema and a sixth nerve palsy with a normal CT mean raised intracranial pressure, and the absent transverse sinus flow makes the cause venous sinus thrombosis; the long intracranial course of the abducens nerve over the petrous apex makes it the nerve stretched by pressure, a false localizing sign that does not indicate a pontine lesion.",
  structures=["sinus-transverse-sigmoid", "cn-06-abducens"], syndromes=["syn-cerebral-venous-sinus-thrombosis", "syn-cn6-palsy", "syn-idiopathic-intracranial-hypertension"], highlight=["sinus-transverse-r", "cn-06-abducens-r"], cites=[B(19, 200, 206), B(11, 91, 96)])

write(E)
