import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).parent))
from synlib import *
E = []
S17 = lambda a, b=None: C("snell", 17, a, b)
B7 = lambda a, b=None: C("berkowitz", 7, a, b)
B6 = lambda a, b=None: C("berkowitz", 6, a, b)

E.append(syn("syn-aca-infarct", "Anterior cerebral artery infarction", "vascular", ["territory-aca", "artery-aca", "lobe-frontal", "gyrus-precentral", "gyrus-cingulate"], "contralateral",
 "A patient develops sudden weakness that is much worse in the leg than the arm, with the face almost spared, together with sensory loss over the same leg. They may be abulic and slow to respond, incontinent of urine, and show a grasp reflex in the affected hand. With a large or bilateral infarct there is akinetic mutism. Speech is preserved apart from a transient transcortical motor aphasia when the dominant hemisphere is involved.",
 [D("motor", "contralateral", "leg more than arm, face spared", "Upper motor neuron weakness of the leg with extensor plantar", "pathway-lateral-corticospinal"), D("sensory-light-touch", "contralateral", "leg and foot", "Cortical sensory loss of the leg", "gyrus-postcentral"), D("cognitive", "n/a", "frontal", "Abulia, apathy, perseveration, grasp reflex", "cortex-prefrontal"), D("sphincter", "n/a", "bladder", "Urinary incontinence from loss of the paracentral micturition area", "gyrus-cingulate")],
 "The anterior cerebral artery runs in the interhemispheric fissure and supplies the medial surface of the frontal and parietal lobes, which is where the leg and foot are represented in the motor and sensory homunculus of the paracentral lobule. The corticospinal fibers from this area cross in the medullary pyramidal decussation, so the weakness is contralateral to the infarct, and it follows the homunculus rather than the whole hemibody: the leg is weakest, the shoulder may be weak, and the face and hand, which sit on the lateral convexity in middle cerebral territory, are spared. The medial frontal lobe includes the supplementary motor area and the anterior cingulate gyrus, whose loss gives abulia and, bilaterally, akinetic mutism; the paracentral lobule holds the cortical bladder control area, explaining the incontinence. Recurrent artery of Heubner involvement adds face and arm weakness from the anterior limb of the internal capsule and caudate head, a pattern that can mislead toward the middle cerebral artery.",
 [pathol("Acute ACA infarct", "MRI", "Restricted diffusion in the medial frontal and parietal cortex and the paracentral lobule along the interhemispheric fissure, sometimes extending to the caudate head.", sequence="DWI", timing="Minutes to hours"), pathol("ACA occlusion", "CTA", "Cut-off of the A2 segment; a vasospasm after anterior communicating aneurysm rupture is a common cause of bilateral infarcts.")],
 ["Vasospasm after anterior communicating artery aneurysm rupture", "Cardioembolism", "Anterior cerebral artery dissection or atherosclerosis", "Subfalcine herniation compressing the artery against the falx"],
 [("Parasagittal meningioma", "Gradual bilateral leg weakness and seizures; enhancing mass on MRI"), ("Spinal cord lesion", "Bilateral leg weakness with a sensory level and no cortical signs"), ("MCA infarct", "Face and arm weakness with aphasia or neglect")],
 ["Stroke pathway: thrombolysis and thrombectomy according to time and vessel status", "Screen for an anterior communicating aneurysm when the infarct is bilateral or accompanied by headache", "Early bladder management and antithrombotic prevention"],
 [S17(482, 483), B7(58, 59), C("berkowitz", 4, 39, 40)], arteryId="artery-aca", territoryId="territory-aca", marker=terr("territory-aca-major-l"), imagingHint=hint("sagittal", -8, -10, 55, "paracentral lobule in the ACA territory"), preset="medial-l", eponyms=[]))

E.append(syn("syn-mca-stem-infarct", "Middle cerebral artery stem (M1) infarction", "vascular", ["territory-mca", "artery-mca", "internal-capsule", "putamen", "insula", "lobe-frontal", "lobe-parietal", "lobe-temporal"], "contralateral",
 "The patient collapses with dense weakness of the face, arm and leg on one side, loss of sensation on the same side, a homonymous hemianopia and the eyes deviated toward the side of the lesion. If the dominant hemisphere is affected they are globally aphasic; if the non-dominant hemisphere, they neglect the left side and deny the deficit. Over the next two or three days the swelling brain may cause drowsiness and herniation, the malignant middle cerebral artery syndrome.",
 [D("motor", "contralateral", "face, arm and leg", "Complete hemiplegia, leg included because the lenticulostriate branches supply the internal capsule", "pathway-lateral-corticospinal"), D("sensory-light-touch", "contralateral", "hemibody", "Hemianesthesia to all modalities", "gyrus-postcentral"), D("visual-field", "contralateral", "homonymous", "Homonymous hemianopia from the optic radiation", "pathway-visual"), D("oculomotor", "ipsilateral", "conjugate", "Gaze deviation toward the lesion (frontal eye field)", "pathway-horizontal-gaze"), D("language", "n/a", "dominant hemisphere", "Global aphasia", "area-broca"), D("neglect", "contralateral", "non-dominant hemisphere", "Hemineglect and anosognosia", "gyrus-supramarginal")],
 "Occlusion of the M1 segment before the lenticulostriate branches removes blood from both the deep structures (internal capsule, putamen, caudate body) and the whole lateral convexity. The corticospinal and corticobulbar fibers pass through the posterior limb and genu of the internal capsule and cross in the pyramidal decussation, so the hemiplegia is contralateral and involves the leg even though the leg cortex lies in anterior cerebral territory. The thalamocortical sensory radiation and the optic radiation traverse the same capsule and the temporal and parietal white matter, giving the contralateral hemianesthesia and hemianopia. The frontal eye field drives the contralateral paramedian pontine reticular formation, so its loss lets the intact hemisphere push the eyes toward the lesion. Language areas of the dominant hemisphere (Broca, Wernicke and the arcuate fasciculus) all lie in the territory, so the aphasia is global; in the non-dominant hemisphere the equivalent parietal cortex handles spatial attention, hence neglect.",
 [pathol("Hyperdense MCA sign", "CT", "Dense thrombus in the M1 segment on non-contrast CT within the first hours, before parenchymal change.", sequence="CT non-contrast", timing="0–6 h"), pathol("Early ischemic change", "CT", "Loss of the insular ribbon and lentiform nucleus outline, sulcal effacement; quantified by ASPECTS.", sequence="CT non-contrast", timing="2–12 h"), pathol("Acute infarct", "MRI", "Restricted diffusion across the deep and superficial MCA territory; FLAIR change lags by several hours (DWI–FLAIR mismatch).", sequence="DWI"), pathol("Malignant edema", "CT", "Midline shift, effaced ventricles and uncal herniation at 48–72 h in large infarcts.", timing="2–5 days")],
 ["Cardioembolism (atrial fibrillation)", "Internal carotid atherosclerosis with artery-to-artery embolism", "Carotid dissection in younger patients", "Intracranial atherosclerosis"],
 [("Internal carotid occlusion", "Same picture plus possible monocular blindness; CTA shows the carotid"), ("Seizure with Todd paresis", "Short-lived, preceded by convulsion; DWI negative or cortical only"), ("Hemispheric hemorrhage", "Hyperdense blood on CT; headache and vomiting more prominent")],
 ["Emergency thrombectomy for M1 occlusion within the window, with thrombolysis when eligible", "Monitor for malignant edema; decompressive hemicraniectomy improves survival in selected patients under about 60", "Swallow assessment and aspiration precautions from the start", "Search for the embolic source with cardiac monitoring and carotid imaging"],
 [S17(473, 475), S17(482), B7(55, 59)], arteryId="artery-mca", territoryId="territory-mca", marker=terr("territory-mca-major-l", "territory-lateral-lenticulostriate-l"), imagingHint=hint("axial", -30, -10, 10, "insula, capsule and convexity in the MCA territory"), preset="lateral-l"))

E.append(syn("syn-mca-superior-division", "Middle cerebral artery superior division infarction", "vascular", ["territory-mca", "artery-mca-superior-division", "gyrus-precentral", "gyrus-postcentral", "area-broca", "frontal-eye-field"], "contralateral",
 "Weakness and numbness of the face and arm develop suddenly, with the leg relatively spared, and the eyes are turned toward the side of the infarct for the first day or two. In the dominant hemisphere the patient understands but cannot produce fluent speech: output is effortful and telegraphic, repetition is poor and there is often apraxia of the non-paralyzed hand. There is no hemianopia. The picture is a brachiofacial hemiparesis with Broca aphasia.",
 [D("motor", "contralateral", "face and arm more than leg", "Brachiofacial hemiparesis with forehead-sparing facial weakness", "pathway-corticobulbar"), D("sensory-light-touch", "contralateral", "face and arm", "Cortical sensory loss with astereognosis", "gyrus-postcentral"), D("language", "n/a", "dominant hemisphere", "Non-fluent (Broca) aphasia with preserved comprehension", "area-broca"), D("oculomotor", "ipsilateral", "conjugate", "Transient gaze preference toward the lesion", "frontal-eye-field")],
 "The superior division leaves the middle cerebral trunk in the Sylvian fissure and supplies the frontal and anterior parietal convexity: the lateral part of the precentral and postcentral gyri, the frontal operculum and the frontal eye field. The motor and sensory homunculi place the face and hand on this lateral surface and the leg on the medial surface served by the anterior cerebral artery, so the deficit is brachiofacial. Corticospinal and corticobulbar fibers cross in the brainstem, and the face area projects mainly to the contralateral lower facial subnucleus, so the weakness is contralateral and spares the forehead. Broca's area in the dominant inferior frontal gyrus lies in the territory, but Wernicke's area in the posterior temporal lobe belongs to the inferior division, which is why comprehension is preserved. The optic radiation runs through the temporal and parietal lobes below the territory, so vision is spared, a useful distinction from a stem occlusion.",
 [pathol("Acute superior-division infarct", "MRI", "Restricted diffusion in the frontal operculum, precentral and postcentral gyri on the lateral convexity, sparing the temporal lobe and deep nuclei.", sequence="DWI"), pathol("Branch occlusion", "CTA", "Cut-off of the superior M2 trunk with preserved inferior trunk flow.")],
 ["Cardioembolism", "Artery-to-artery embolism from carotid plaque", "Small emboli after cardiac procedures"],
 [("Lacunar pure motor stroke", "Face, arm and leg equally weak, no aphasia or sensory loss"), ("Inferior division infarct", "Fluent aphasia and visual field loss without much weakness"), ("Cortical vein thrombosis", "Seizures, headache and a hemorrhagic cortical lesion on imaging")],
 ["Acute stroke treatment; M2 thrombectomy is considered case by case", "Speech and language therapy begun early", "Secondary prevention directed at the embolic source"],
 [S17(473, 475), B7(55, 59)], arteryId="artery-mca-superior-division", territoryId="territory-mca", marker=terr("territory-mca-frontal-l", "territory-mca-parietal-l"), imagingHint=hint("axial", -45, 5, 30, "frontal operculum and precentral gyrus"), preset="lateral-l"))

E.append(syn("syn-mca-inferior-division", "Middle cerebral artery inferior division infarction", "vascular", ["territory-mca", "artery-mca-inferior-division", "area-wernicke", "gyrus-angular", "gyrus-supramarginal", "lobe-temporal"], "contralateral",
 "The patient is brought in speaking fluently but nonsensically, unaware that anything is wrong, and is sometimes mistaken for being confused or psychotic. Examination shows a superior quadrantanopia or hemianopia and, in the dominant hemisphere, poor comprehension and repetition with paraphasic speech; in the non-dominant hemisphere there is neglect, constructional apraxia and flat prosody. Weakness is absent or minimal, which makes the stroke easy to miss.",
 [D("language", "n/a", "dominant hemisphere", "Fluent (Wernicke) aphasia with impaired comprehension and repetition", "area-wernicke"), D("visual-field", "contralateral", "superior quadrant or hemianopia", "Field defect from the temporal optic radiation (Meyer's loop)", "pathway-visual"), D("neglect", "contralateral", "non-dominant hemisphere", "Hemispatial neglect, anosognosia, aprosodia", "gyrus-angular"), D("cognitive", "n/a", "dominant parietal", "Gerstmann features (acalculia, agraphia, finger agnosia, right-left confusion)", "gyrus-angular")],
 "The inferior division supplies the temporal lobe and the inferior parietal lobule: the superior temporal gyrus with Wernicke's area, the angular and supramarginal gyri, and the deep temporal white matter through which Meyer's loop of the optic radiation runs. The motor and somatosensory cortices belong to the superior division, so strength and primary sensation are preserved. The optic radiation carries the contralateral visual field: fibers for the upper field pass through the temporal lobe, so the defect is a contralateral superior quadrantanopia, becoming a full hemianopia when the parietal fibers are also involved. Language comprehension depends on the dominant posterior superior temporal gyrus, hence fluent aphasia with poor comprehension. The corresponding non-dominant parietal cortex builds the map of contralateral space, so its loss gives neglect of the left side and lack of awareness of the deficit. Because the corticospinal tract is untouched there is no crossed weakness to draw attention to the stroke, and the agitation of a Wernicke aphasic is often misread as a psychiatric emergency.",
 [pathol("Acute inferior-division infarct", "MRI", "Restricted diffusion in the posterior superior temporal gyrus and inferior parietal lobule with preserved frontal cortex and deep nuclei.", sequence="DWI"), pathol("Chronic infarct", "MRI", "Encephalomalacia of the posterior Sylvian region with ex-vacuo dilatation of the temporal horn.", sequence="FLAIR")],
 ["Cardioembolism", "Carotid atheroembolism"],
 [("Acute psychosis or delirium", "Field defect, paraphasias and neglect point to a focal lesion; DWI positive"), ("Herpes encephalitis", "Fever, seizures, temporal T2 change crossing vascular boundaries"), ("Transcortical sensory aphasia", "Repetition preserved; watershed location")],
 ["Acute stroke treatment as for any MCA occlusion", "Formal language and neglect assessment; neglect predicts poor rehabilitation outcome", "Driving restriction because of the field defect"],
 [S17(473, 475), B7(55, 59)], arteryId="artery-mca-inferior-division", territoryId="territory-mca", marker=terr("territory-mca-temporal-l", "territory-mca-parietal-l"), imagingHint=hint("axial", -55, -40, 15, "posterior superior temporal gyrus"), preset="lateral-l"))

E.append(syn("syn-anterior-choroidal-infarct", "Anterior choroidal artery infarction", "vascular", ["artery-anterior-choroidal", "territory-anterior-choroidal", "internal-capsule", "lateral-geniculate-nucleus"], "contralateral",
 "A patient presents with a hemiparesis affecting face, arm and leg, hemisensory loss and a homonymous hemianopia, yet is alert with intact language and no neglect. The triad of motor, sensory and visual loss without cortical signs is the classic anterior choroidal syndrome. Some patients show only a pure motor or sensorimotor lacunar picture; others have a peculiar sectoral field defect sparing a horizontal wedge.",
 [D("motor", "contralateral", "face, arm and leg", "Hemiparesis from the posterior limb of the internal capsule", "pathway-lateral-corticospinal"), D("sensory-light-touch", "contralateral", "hemibody", "Hemihypesthesia from the thalamocortical fibers in the posterior capsule", "pathway-dcml"), D("visual-field", "contralateral", "homonymous", "Homonymous hemianopia, sometimes with sparing of a horizontal sector", "lateral-geniculate-nucleus")],
 "The anterior choroidal artery arises from the internal carotid just beyond the posterior communicating origin and runs backward beneath the optic tract to enter the temporal horn, supplying on the way the posterior limb of the internal capsule, the retrolenticular fibers, the optic tract, part of the lateral geniculate body and the medial temporal lobe. All three long pathways pass through this small territory: the corticospinal tract, whose fibers cross in the pyramidal decussation, the thalamocortical sensory radiation carrying the crossed spinothalamic and lemniscal input, and the optic tract and lateral geniculate body carrying the contralateral hemifield. A single small infarct therefore reproduces the deficit of a whole hemisphere lesion but without aphasia, neglect or field loss from cortical damage, because the cortex is intact. The lateral geniculate has a dual supply, anterior choroidal and lateral posterior choroidal, which explains the unusual sectoranopias: loss of the anterior choroidal portion spares the horizontal wedge fed by the other vessel.",
 [pathol("Acute anterior choroidal infarct", "MRI", "Restricted diffusion in the posterior limb of the internal capsule extending down to the medial temporal lobe and lateral geniculate body, elongated in the anteroposterior direction.", sequence="DWI"), pathol("Vessel imaging", "CTA", "The artery is usually too small to show an occlusion; the parent carotid may show atheroma or dissection.")],
 ["Small vessel disease", "Carotid atheroembolism", "Surgical clipping or coiling of nearby aneurysms", "Cardioembolism"],
 [("Lacunar sensorimotor stroke", "No visual field defect"), ("MCA stem infarct", "Cortical signs (aphasia, neglect) and gaze deviation present"), ("PCA infarct", "Hemianopia with little or no weakness")],
 ["Standard acute ischemic stroke care", "Vascular risk factor control", "Field defect assessment before driving"],
 [S17(476), B7(60)], arteryId="artery-anterior-choroidal", territoryId="territory-anterior-choroidal", marker=terr("territory-anterior-choroidal-thalamoperforating-l"), imagingHint=hint("axial", -22, -15, 5, "posterior limb of the internal capsule"), preset="superior"))

E.append(syn("syn-pca-infarct", "Posterior cerebral artery infarction", "vascular", ["artery-pca", "territory-pca", "cortex-calcarine", "lobe-occipital", "thalamus", "hippocampus"], "contralateral",
 "The patient notices that half the world has disappeared, often bumping into things on one side, sometimes with a headache. Examination shows a congruous homonymous hemianopia with macular sparing and intact pupils; strength is normal. Dominant-side infarcts may add alexia without agraphia and color anomia, and medial temporal involvement produces a transient amnesia. If the proximal artery is occluded, thalamic infarction adds hemisensory loss and, later, thalamic pain.",
 [D("visual-field", "contralateral", "homonymous, congruous", "Hemianopia with macular sparing", "pathway-visual"), D("cognitive", "n/a", "dominant occipitotemporal", "Alexia without agraphia, color anomia, visual agnosia", "cortex-calcarine"), D("cognitive", "n/a", "medial temporal", "Transient anterograde amnesia", "hippocampus"), D("sensory-light-touch", "contralateral", "hemibody (proximal occlusion)", "Thalamic hemisensory loss", "thalamus-vpl")],
 "The posterior cerebral artery arises from the top of the basilar artery, curves around the midbrain and supplies the occipital lobe, the inferomedial temporal lobe, and through its proximal perforators the thalamus and midbrain. The calcarine cortex receives the contralateral visual hemifield: nasal retinal fibers cross in the chiasm, so each occipital lobe sees the opposite half of space from both eyes. The macular representation at the occipital pole often survives because it receives collateral flow from the middle cerebral artery, giving macular sparing, and the pupillary light fibers leave the optic tract before the geniculate, so the pupils react normally. Corticospinal fibers lie in middle cerebral territory, hence no weakness. In the dominant hemisphere, a lesion of the left occipital lobe plus the splenium of the corpus callosum disconnects the intact right visual cortex from the left angular gyrus, so the patient can write but cannot read what has been written. The hippocampus lies in the temporal branch territory and explains the amnesia, while proximal P1 occlusion involves the thalamoperforating branches and produces the sensory and midbrain signs.",
 [pathol("Acute PCA infarct", "MRI", "Restricted diffusion in the calcarine cortex, lingual gyrus and cuneus, often extending to the medial temporal lobe and splenium; thalamus involved in proximal occlusions.", sequence="DWI"), pathol("PCA occlusion", "CTA", "Absent flow in the P2 segment; check the basilar tip for a proximal embolus.")],
 ["Cardioembolism", "Vertebrobasilar atheroembolism", "Vertebral artery dissection", "Compression during transtentorial herniation"],
 [("Occipital hemorrhage", "Hyperdense blood on CT, headache prominent"), ("Migraine with aura", "Positive scintillations that march and resolve within an hour"), ("Posterior reversible encephalopathy", "Bilateral, vasogenic edema, hypertension or immunosuppression")],
 ["Acute stroke pathway", "Field testing and reading assessment; driving restriction", "Anticoagulation when cardioembolic"],
 [S17(482, 483), B6(49, 51), B7(58, 59)], arteryId="artery-pca", territoryId="territory-pca", marker=terr("territory-pca-major-l"), imagingHint=hint("axial", -10, -85, 5, "calcarine cortex"), preset="medial-l"))

E.append(syn("syn-top-of-basilar", "Top of the basilar syndrome", "vascular", ["artery-basilar", "artery-pca", "thalamus", "level-midbrain-superior-colliculus", "rimlf", "lobe-occipital"], "bilateral",
 "A patient suddenly becomes drowsy or briefly unresponsive and, on waking, has vertical gaze palsy, pupils that are small or unequal and react poorly, sometimes skew deviation, and visual field loss that can amount to cortical blindness. Some report vivid formed hallucinations or confabulate cheerfully. Limb weakness is often surprisingly mild for such a dramatic picture, because the embolus lodged at the basilar bifurcation and spared the pons.",
 [D("consciousness", "bilateral", "rostral brainstem", "Somnolence or coma from the paramedian midbrain and thalamic reticular projections", "reticular-formation"), D("oculomotor", "bilateral", "vertical", "Vertical gaze palsy, convergence-retraction nystagmus, skew deviation", "pathway-vertical-gaze"), D("pupil", "bilateral", "both pupils", "Small, unequal or poorly reactive pupils from pretectal and third nerve nuclear involvement", "pathway-pupillary-light-reflex"), D("visual-field", "bilateral", "both hemifields", "Hemianopia or cortical blindness from bilateral PCA infarcts", "pathway-visual"), D("cognitive", "bilateral", "thalamus and medial temporal", "Amnesia, confusion, peduncular hallucinosis", "thalamus-mediodorsal")],
 "An embolus arriving up the basilar artery stops at its bifurcation, where it obstructs the thalamoperforating and mesencephalic perforators and one or both posterior cerebral arteries. The paramedian midbrain contains the rostral interstitial nucleus of the MLF and the posterior commissure, which generate and cross the vertical gaze commands, the oculomotor nuclei with their Edinger–Westphal components, and the ascending reticular activating system, so vertical gaze, pupils and arousal are all affected bilaterally. The thalamoperforators supply the medial thalamus, adding amnesia and confusion, and the posterior cerebral arteries carry the crossed visual pathways to both occipital lobes, so bilateral occlusion causes cortical blindness with preserved pupils when the pretectum is spared. The corticospinal tracts pass through the crus and pons below the level of the embolus and cross far below in the medulla, so the classic case has little weakness. When the clot extends back into the basilar trunk the syndrome merges with a basilar occlusion and the outcome becomes far worse.",
 [pathol("Basilar tip occlusion", "CTA", "Filling defect at the basilar bifurcation with absent flow in one or both P1 segments and the thalamoperforators."), pathol("Acute infarcts", "MRI", "Restricted diffusion in the paramedian midbrain, medial thalami and occipital lobes, frequently bilateral.", sequence="DWI"), pathol("Hyperdense basilar", "CT", "Dense basilar artery on non-contrast CT; check when a patient presents with unexplained coma.", sequence="CT non-contrast")],
 ["Cardioembolism", "Vertebrobasilar atherosclerosis", "Vertebral artery dissection"],
 [("Metabolic coma", "No vertical gaze palsy or pupillary asymmetry; symmetric brainstem reflexes"), ("Non-convulsive status epilepticus", "EEG; fluctuating awareness without the ocular signs"), ("Artery of Percheron infarct", "Bilateral medial thalamic infarcts without occipital involvement")],
 ["Emergency thrombectomy for basilar occlusion", "Airway protection when drowsy", "Look for a cardiac source of embolism"],
 [B7(58), B7(63), C("berkowitz", 11, 100)], arteryId="artery-basilar", marker=sphere(0, -20, -5, 12), imagingHint=hint("axial", 0, -22, -5, "paramedian midbrain and medial thalami"), preset="anterior"))

E.append(syn("syn-watershed-infarct", "Watershed (borderzone) infarction", "vascular", ["territory-watershed", "artery-internal-carotid", "artery-mca", "corona-radiata"], "contralateral",
 "After an episode of hypotension, cardiac arrest or a tight carotid stenosis, a patient develops weakness that involves the proximal arm and thigh more than the hand and foot, a 'man in a barrel' pattern when bilateral. Dominant-hemisphere involvement produces transcortical aphasia in which repetition is strikingly preserved while spontaneous speech or comprehension fails; posterior lesions cause cortical visual problems such as Balint syndrome.",
 [D("motor", "contralateral", "proximal arm and leg (shoulder and hip)", "Proximal weakness sparing the hand and foot", "pathway-lateral-corticospinal"), D("language", "n/a", "dominant hemisphere", "Transcortical motor or sensory aphasia with preserved repetition", "area-broca"), D("visual-field", "contralateral", "posterior borderzone", "Cortical visual dysfunction, Balint features when bilateral", "lobule-superior-parietal"), D("cognitive", "bilateral", "internal borderzone", "Apathy and slowed cognition with bilateral deep white matter infarcts", "corona-radiata")],
 "The borderzones are the strips of cortex and white matter at the far ends of two adjacent arterial territories, where perfusion pressure is lowest: the anterior borderzone between the anterior and middle cerebral arteries along the superior frontal convexity, the posterior borderzone between the middle and posterior cerebral arteries in the parieto-occipital region, and the internal borderzone in the corona radiata between the deep perforators and the cortical branches. When systemic pressure falls or a carotid stenosis limits inflow, these strips infarct first. The anterior borderzone sits on the motor homunculus between the leg area (medial) and the face and hand area (lateral), which is the shoulder and hip representation, so the weakness is proximal; corticospinal fibers cross in the medulla, so it is contralateral. The perisylvian language cortex has the richest supply and survives, while the surrounding cortex that feeds it dies, producing the transcortical aphasias with intact repetition. Bilateral posterior borderzone infarcts disconnect the dorsal visual stream and produce simultanagnosia, optic ataxia and ocular apraxia.",
 [pathol("Cortical borderzone infarcts", "MRI", "Wedge-shaped restricted diffusion along the ACA–MCA and MCA–PCA boundaries, often bilateral after global hypotension.", sequence="DWI"), pathol("Internal borderzone infarcts", "MRI", "A chain of small deep white matter infarcts in the corona radiata ('rosary' or 'string of pearls') on the side of a carotid stenosis.", sequence="DWI"), pathol("Carotid stenosis", "CTA", "High-grade stenosis or occlusion of the ipsilateral internal carotid artery.")],
 ["Cardiac arrest and global hypoperfusion", "High-grade carotid stenosis with a hypotensive episode", "Cardiac surgery and prolonged hypotension"],
 [("Embolic multi-territory infarcts", "Random cortical distribution, not confined to boundaries"), ("Hypoxic-ischemic encephalopathy", "Diffuse cortical and deep gray involvement after arrest, rather than strips"), ("Spinal cord lesion", "Bilateral proximal weakness can mimic, but a sensory level and reflex changes distinguish")],
 ["Restore perfusion pressure; avoid aggressive blood pressure lowering", "Evaluate and treat carotid stenosis (endarterectomy or stenting)", "Cardiac and hemodynamic assessment"],
 [B6(50, 53), B7(58, 63)], territoryId="territory-watershed", marker=terr("territory-mca-frontal-l", "territory-aca-l"), imagingHint=hint("coronal", -25, -10, 45, "anterior borderzone on the superior frontal convexity"), preset="superior"))

E.append(syn("syn-thalamic-dejerine-roussy", "Thalamic syndrome (Dejerine–Roussy)", "vascular", ["thalamus", "thalamus-vpl", "thalamus-vpm", "arteries-thalamoperforating", "artery-pca"], "contralateral",
 "A patient recovers from a small posterior stroke that took away sensation on one side of the body, only to develop, weeks or months later, a spontaneous burning pain over the same side that is made worse by light touch, cold or emotion. Examination shows reduced sensation to all modalities on that side, sometimes with a mild hemiparesis, choreoathetosis or a 'thalamic hand' with the fingers flexed at the knuckles and extended at the joints.",
 [D("sensory-light-touch", "contralateral", "face, arm, trunk and leg", "Loss or reduction of all modalities including vibration and position sense", "thalamus-vpl"), D("pain", "contralateral", "hemibody", "Delayed central pain with allodynia and hyperpathia", "thalamus-vpl"), D("motor", "contralateral", "mild", "Transient hemiparesis when the adjacent internal capsule is involved", "internal-capsule"), D("cerebellar", "contralateral", "limb", "Ataxia and choreoathetosis from the ventral lateral nucleus and dentatothalamic fibers", "thalamus-va-vl")],
 "The ventral posterolateral and ventral posteromedial nuclei of the thalamus are the final relay for both the medial lemniscus and the spinothalamic tract, both of which have already crossed in the brainstem or spinal cord, and for the crossed trigeminal lemniscus from the face. An infarct here therefore removes every somatic sensory modality from the contralateral face and body at once, which no single cord or brainstem lesion can do, because in those places the pain and proprioceptive pathways travel separately. The supply comes from the thalamogeniculate branches of the posterior cerebral artery, and lesions large enough to catch the adjacent posterior limb of the internal capsule add weakness. The delayed pain is attributed to loss of inhibitory thalamic and cortical processing of surviving spinothalamic input, so that residual input is perceived as intolerable. Involvement of the ventral lateral nucleus interrupts the cerebellar outflow after its decussation in the midbrain, which is why the ataxia and involuntary movements appear on the same side as the sensory loss.",
 [pathol("Thalamic infarct", "MRI", "Restricted diffusion in the lateral thalamus (VPL/VPM) in the thalamogeniculate territory, often small.", sequence="DWI"), pathol("Thalamic hemorrhage", "CT", "Hyperdense lateral thalamic hemorrhage, may extend into the third ventricle or capsule.", sequence="CT non-contrast")],
 ["Lacunar infarct of the thalamogeniculate artery", "Hypertensive thalamic hemorrhage", "Posterior cerebral artery embolism"],
 [("Lacunar pure sensory stroke", "Same site; the term Dejerine–Roussy applies once pain has developed"), ("Parietal cortical lesion", "Discriminative loss with preserved primary modalities; no burning pain"), ("Lateral medullary syndrome", "Crossed facial and body sensory loss, dissociated modalities")],
 ["Neuropathic pain treatment (amitriptyline, gabapentinoids, lamotrigine) without expectation of complete relief", "Explain the delayed onset so the patient does not fear a new stroke", "Vascular risk factor control"],
 [C("snell", 12, 369), S17(482), C("berkowitz", 4, 38)], arteryId="artery-pca", marker=sphere(-16, -20, 6, 7), imagingHint=hint("axial", -16, -20, 6, "ventral posterolateral thalamus"), preset="superior", eponyms=["Dejerine–Roussy syndrome", "central post-stroke pain"]))

E.append(syn("syn-basilar-occlusion", "Basilar artery occlusion", "vascular", ["artery-basilar", "level-pons-caudal", "level-pons-rostral", "territory-basilar-paramedian", "pontine-nuclei"], "bilateral",
 "The story begins hours or days earlier with vertigo, double vision, slurred speech or transient weakness switching sides, then the patient becomes quadriparetic and drowsy or comatose. Examination reveals bilateral extensor plantars, pinpoint reactive pupils, absent horizontal eye movements, facial weakness and often ocular bobbing. Some patients remain fully aware but can move nothing except their eyes vertically: the locked-in state.",
 [D("motor", "bilateral", "all four limbs and face", "Quadriparesis with bilateral upper motor neuron signs and bulbar weakness", "pathway-lateral-corticospinal"), D("oculomotor", "bilateral", "horizontal", "Bilateral horizontal gaze palsy, internuclear ophthalmoplegia, ocular bobbing", "pathway-horizontal-gaze"), D("pupil", "bilateral", "both", "Pinpoint but reactive pupils from bilateral sympathetic interruption", "pathway-oculosympathetic"), D("consciousness", "bilateral", "reticular formation", "Coma when the pontine and midbrain tegmentum are infarcted", "reticular-formation"), D("bulbar", "bilateral", "face, tongue, pharynx", "Dysarthria, dysphagia, bilateral facial weakness", "pathway-corticobulbar")],
 "The basilar artery is a single midline vessel formed by the two vertebral arteries, so its occlusion removes the supply of both sides of the pons at once through the paramedian and short circumferential branches. The corticospinal tracts descend through the basis pontis as scattered bundles before they cross in the medulla, so bilateral pontine infarction paralyzes all four limbs, and the corticobulbar fibers to the facial, ambiguus and hypoglossal nuclei are lost with them, paralyzing the face and bulbar muscles. The abducens nuclei, paramedian pontine reticular formation and both MLFs occupy the dorsal pontine tegmentum, so horizontal gaze fails bilaterally, while the vertical gaze center in the midbrain is spared, which is why a locked-in patient can still look up and down. The descending sympathetic fibers run through the pontine tegmentum bilaterally, giving small pupils that still react because the parasympathetic pathway in the midbrain is intact. Whether the patient is comatose or locked in depends on whether the tegmental reticular formation infarcts along with the base.",
 [pathol("Basilar occlusion", "CTA", "Absent contrast in the basilar trunk; the hyperdense basilar sign on plain CT is an early clue.", sequence="CT contrast"), pathol("Pontine infarction", "MRI", "Restricted diffusion in the paramedian pons bilaterally, with variable cerebellar and occipital involvement.", sequence="DWI", timing="May be negative in the first hours; repeat if suspicion is high")],
 ["Vertebrobasilar atherosclerosis with in-situ thrombosis", "Cardioembolism", "Vertebral artery dissection"],
 [("Central pontine myelinolysis", "History of rapid sodium correction; symmetric central pontine T2 change without diffusion restriction pattern of infarct"), ("Pontine hemorrhage", "Hyperdense blood on CT; hyperthermia, pinpoint pupils, rapid coma"), ("Guillain–Barré syndrome", "Areflexic flaccid paralysis, preserved consciousness, ascending course")],
 ["Emergency CTA in any patient with fluctuating brainstem symptoms; thrombectomy for basilar occlusion", "Airway protection", "Establish communication with locked-in patients through vertical eye movements"],
 [B7(58), C("berkowitz", 9, 78, 79)], arteryId="artery-basilar", territoryId="territory-basilar-paramedian", marker=sphere(0, -30, -30, 12), imagingHint=hint("axial", 0, -30, -30, "basis pontis and tegmentum"), preset="anterior"))

E.append(syn("syn-locked-in", "Locked-in syndrome", "vascular", ["level-pons-caudal", "pyramid", "pontine-nuclei", "abducens-nucleus", "artery-basilar"], "bilateral",
 "A patient lies motionless and mute after a brainstem stroke and is assumed to be comatose, until a nurse notices that they blink on request and can look up and down. They cannot move any limb, cannot speak or swallow, and cannot look to either side, but they hear, see, feel and understand everything. Ask for eye movements before concluding that a patient with bilateral pontine signs is unconscious.",
 [D("motor", "bilateral", "all four limbs", "Quadriplegia with bilateral extensor plantars", "pathway-lateral-corticospinal"), D("bulbar", "bilateral", "face, jaw, tongue, pharynx, larynx", "Anarthria and aphagia; the face is paralyzed bilaterally", "pathway-corticobulbar"), D("oculomotor", "bilateral", "horizontal", "Loss of horizontal gaze with preserved vertical movement and blinking", "pathway-horizontal-gaze"), D("consciousness", "n/a", "preserved", "Full awareness; EEG normal; sleep-wake cycles intact", "reticular-formation")],
 "A lesion of the ventral pons destroys the corticospinal and corticobulbar fibers of both sides as they pass through the basis pontis on their way to the pyramidal decussation in the medulla, so every voluntary movement below the midbrain is lost bilaterally: limbs, face, tongue, palate and larynx. The horizontal gaze machinery, the abducens nuclei and the paramedian pontine reticular formation, sits in the caudal pontine tegmentum and is usually caught as well, whereas the vertical gaze center in the rostral midbrain, the oculomotor nuclei and the levator palpebrae are supplied from above the occlusion and survive, leaving vertical gaze and blinking as the only channels of output. The reticular activating system in the pontine and midbrain tegmentum is spared in the classic ventral lesion, so consciousness, sensation via the intact lemniscal and spinothalamic pathways in the tegmentum, and hearing are all preserved. The dissociation between an intact mind and a paralyzed body is the syndrome; when the tegmentum is also infarcted the patient is comatose instead.",
 [pathol("Ventral pontine infarct", "MRI", "Bilateral restricted diffusion in the basis pontis with relative sparing of the tegmentum; basilar occlusion on angiography.", sequence="DWI"), pathol("Pontine hemorrhage or myelinolysis", "MRI", "Central pontine T2 hyperintensity (osmotic demyelination) or hematoma producing the same syndrome.", sequence="T2")],
 ["Basilar artery thrombosis or embolism", "Pontine hemorrhage", "Central pontine myelinolysis", "Trauma or tumor of the ventral pons"],
 [("Coma", "Locked-in patients blink and look vertically on command; EEG shows a normal awake rhythm"), ("Severe Guillain–Barré syndrome", "Peripheral, areflexic, ophthalmoplegia complete including vertical movements, normal brain MRI"), ("Akinetic mutism", "Patient can move but does not; lesion is frontal or thalamic")],
 ["Establish yes/no communication with eye movements or blinks immediately and inform the team", "Airway, nutrition and pressure care as for quadriplegia", "Consider thrombectomy when presenting within the window with a basilar occlusion"],
 [C("berkowitz", 9, 75), C("berkowitz", 9, 78, 79)], arteryId="artery-basilar", marker=sphere(0, -28, -35, 12), imagingHint=hint("sagittal", 0, -28, -35, "ventral pons"), preset="lateral-l", eponyms=["de-efferented state"]))

write(E)
