import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).parent))
from synlib import *
E = []

E.append(syn("syn-wallenberg-lateral-medullary", "Lateral medullary syndrome (Wallenberg)", "vascular", ["level-medulla-olive", "spinal-trigeminal-nucleus-tract", "nucleus-ambiguus", "vestibular-nuclei", "inferior-cerebellar-peduncle", "artery-pica", "artery-vertebral", "territory-pica-lateral-medulla"], "ipsilateral",
 "Sudden vertigo, vomiting and violent hiccups are followed by hoarseness and difficulty swallowing. The patient falls toward one side and has a drooping eyelid and small pupil on that side, with loss of pain and temperature sensation on that side of the face and on the opposite side of the body. Strength is normal, which surprises everyone. Neck pain in a young patient means vertebral dissection.",
 [D("sensory-pain-temp", "ipsilateral", "face", "Loss of facial pain and temperature (spinal trigeminal tract and nucleus)", "spinal-trigeminal-nucleus-tract"), D("sensory-pain-temp", "contralateral", "arm, trunk and leg", "Loss of body pain and temperature (spinothalamic tract)", "pathway-lateral-spinothalamic"), D("bulbar", "ipsilateral", "palate, pharynx, larynx", "Dysphagia, hoarseness, absent gag, palate droops to the intact side (nucleus ambiguus)", "nucleus-ambiguus"), D("vestibular", "ipsilateral", "vestibular nuclei", "Vertigo, nystagmus, nausea, lateropulsion toward the lesion", "vestibular-nuclei"), D("cerebellar", "ipsilateral", "limbs", "Limb ataxia from the inferior cerebellar peduncle", "inferior-cerebellar-peduncle"), D("autonomic", "ipsilateral", "eye and face", "Horner syndrome from the descending sympathetic fibers", "pathway-oculosympathetic"), D("other", "n/a", "medulla", "Hiccups from the respiratory centers; sometimes central hypoventilation", "reticular-formation")],
 "The lateral medulla is supplied by the vertebral artery and its posterior inferior cerebellar branch, and a wedge-shaped infarct here cuts a characteristic set of structures. The spinothalamic tract has already crossed in the spinal cord, so body pain and temperature loss is contralateral, while the descending spinal trigeminal tract carries uncrossed facial pain fibers from the same side to the spinal nucleus, so facial loss is ipsilateral: this crossed sensory pattern is the fingerprint of a lateral brainstem lesion. The nucleus ambiguus, vestibular nuclei and inferior cerebellar peduncle are all ipsilateral structures, giving same-side bulbar palsy, vertigo and ataxia, and the descending sympathetic fibers from the hypothalamus run uncrossed through the lateral tegmentum, giving an ipsilateral Horner syndrome. The pyramid and the medial lemniscus lie medially, in the anterior spinal artery territory, and escape, so there is no weakness and vibration and position sense are preserved. This dissociation, with dramatic bulbar, cerebellar and pain-temperature signs but normal strength, is what distinguishes the syndrome from the medial medullary syndrome and from a pontine stroke, where the facial and abducens nuclei would be involved.",
 [pathol("Lateral medullary infarct", "MRI", "Restricted diffusion in the dorsolateral medulla, often small and missed on early CT; thin-section DWI needed.", sequence="DWI", pitfalls="Early DWI can be negative in the brainstem; repeat at 24–48 h if the clinical picture is clear"), pathol("Vertebral artery dissection", "MRA", "Tapered stenosis or intramural hematoma of the V3–V4 vertebral segment on fat-saturated T1 and MRA.", sequence="T1"), pathol("PICA occlusion", "CTA", "Absent PICA or vertebral artery filling; cerebellar hemisphere infarct may coexist and swell.")],
 ["Vertebral artery atherothrombosis", "Vertebral artery dissection (younger patients, neck pain)", "Posterior inferior cerebellar artery embolism"],
 [("Vestibular neuritis", "No dysphagia, Horner or crossed sensory loss; head impulse test positive"), ("Medial medullary syndrome", "Contralateral weakness and proprioceptive loss with tongue palsy; no facial sensory loss"), ("Lateral pontine (AICA) infarct", "Adds facial palsy and deafness; vertigo similar")],
 ["Swallow assessment before any oral intake; aspiration is the main early danger", "Antithrombotic therapy; anticoagulation or antiplatelet for dissection", "Monitor breathing overnight in the first days (central hypoventilation)", "Vestibular rehabilitation"],
 [R("sp-lateral-medullary-syndrome"), R("sp-pica"), R("sp-medial-medullary-syndrome")], level="medulla-olive", arteryId="artery-pica", territoryId="territory-pica-lateral-medulla", marker=sphere(-10, -42, -46, 8), imagingHint=hint("axial", -10, -42, -46, "dorsolateral medulla at the level of the olive"), preset="posterior", eponyms=["Wallenberg syndrome", "PICA syndrome"], exam=["Swinging pin from one side of the face to the other and down the body: find the crossed pattern", "Look at the pupils in dim light for Horner", "Say 'ah' and watch the palate; test the gag", "Finger-nose and heel-shin on the side of the lesion", "Head impulse test and observe nystagmus direction"]))

E.append(syn("syn-dejerine-medial-medullary", "Medial medullary syndrome (Dejerine)", "vascular", ["pyramid", "medial-lemniscus", "hypoglossal-nucleus", "level-medulla-olive", "anterior-spinal-artery", "artery-vertebral"], "ipsilateral",
 "A patient develops weakness of one arm and leg with the face spared, loses vibration and position sense on the same weak side, and on protruding the tongue it deviates to the other side, the side opposite the weakness. Pain and temperature sensation are normal. This contralateral limb weakness with ipsilateral tongue palsy is one of the classic crossed brainstem syndromes.",
 [D("motor", "contralateral", "arm and leg, face spared", "Hemiparesis with upper motor neuron signs (pyramid)", "pathway-lateral-corticospinal"), D("sensory-vibration-proprioception", "contralateral", "arm and leg", "Loss of vibration and position sense (medial lemniscus)", "pathway-dcml"), D("cranial-nerve", "ipsilateral", "tongue", "Lower motor neuron tongue weakness: deviation toward the lesion, later atrophy and fasciculation", "hypoglossal-nucleus"), D("sensory-pain-temp", "n/a", "spared", "Pain and temperature intact (spinothalamic tract lies laterally)", "pathway-lateral-spinothalamic")],
 "The paramedian medulla is fed by the anterior spinal artery and paramedian vertebral branches and contains three structures in a vertical row: the pyramid ventrally, the medial lemniscus behind it, and the hypoglossal nucleus and nerve dorsally. The pyramid carries corticospinal fibers that have not yet crossed, because the pyramidal decussation lies just below, so the weakness is contralateral and spares the face, whose corticobulbar fibers have already left the tract above this level. The medial lemniscus, formed by the internal arcuate fibers that crossed at the sensory decussation, carries contralateral vibration and proprioception, so those modalities are lost on the same side as the weakness. The hypoglossal nucleus and its emerging root are ipsilateral structures, so the tongue is paralyzed on the side of the lesion and pushes toward it when protruded, because the intact genioglossus pushes across. The spinothalamic tract lies far laterally, out of the anterior spinal territory, which is why pain and temperature are preserved and why the picture is the mirror image of the lateral medullary syndrome.",
 [pathol("Medial medullary infarct", "MRI", "Restricted diffusion in the paramedian ventral medulla, sometimes bilateral, adjacent to the anterior median fissure.", sequence="DWI"), pathol("Vertebral artery disease", "MRA", "Vertebral artery stenosis, occlusion or dissection on the side of the tongue palsy.")],
 ["Vertebral artery atherosclerosis involving the paramedian branches", "Anterior spinal artery occlusion", "Vertebral dissection"],
 [("Capsular lacune", "Face involved, no tongue lower motor neuron signs, no proprioceptive loss"), ("Lateral medullary syndrome", "No weakness; crossed pain-temperature loss; bulbar palsy"), ("Cervical cord lesion", "Ipsilateral weakness and proprioceptive loss, no tongue signs")],
 ["Acute stroke treatment", "Antithrombotic therapy and vertebral artery evaluation", "Speech therapy for the dysarthria"],
 [R("sp-medial-medullary-syndrome"), R("sp-dejerine-roussy-syndrome"), R("sp-lateral-medullary-syndrome")], level="medulla-olive", arteryId="anterior-spinal-artery", marker=sphere(-3, -40, -50, 6), imagingHint=hint("axial", -3, -40, -50, "paramedian medulla: pyramid, medial lemniscus, hypoglossal nucleus"), preset="anterior", eponyms=["Dejerine syndrome", "alternating hypoglossal hemiplegia"]))

E.append(syn("syn-millard-gubler", "Millard–Gubler syndrome (ventral pontine)", "vascular", ["level-pons-caudal", "facial-motor-nucleus", "pontine-nuclei", "artery-basilar", "arteries-pontine"], "ipsilateral",
 "A patient has a complete facial palsy on one side, including the forehead, and a hemiparesis of the arm and leg on the opposite side. Often the eye on the side of the facial palsy cannot abduct, adding horizontal diplopia. Sensation may be preserved or reduced on the weak side. The crossed facial and limb weakness locates the lesion to the ventral pons.",
 [D("cranial-nerve", "ipsilateral", "whole face", "Lower motor neuron facial palsy from the facial nerve fascicle", "facial-motor-nucleus"), D("motor", "contralateral", "arm and leg", "Hemiparesis from the corticospinal fibers in the basis pontis", "pathway-lateral-corticospinal"), D("cranial-nerve", "ipsilateral", "lateral rectus", "Abducens palsy when the sixth nerve fascicle is included", "abducens-nucleus"), D("sensory-light-touch", "contralateral", "hemibody (variable)", "Hemisensory loss if the lesion extends to the medial lemniscus", "pathway-dcml")],
 "The facial nerve fascicle leaves the facial motor nucleus in the caudal pontine tegmentum, loops around the abducens nucleus and then runs ventrolaterally through the basis pontis to emerge at the pontomedullary junction; on its way it passes right through the field of corticospinal bundles descending in the basis pontis. A lesion of the ventrocaudal pons therefore hits the uncrossed corticospinal fibers, which will cross in the medulla and so paralyze the contralateral limbs, together with the facial nerve fibers, which are already the final lower motor neuron for the ipsilateral face and so paralyze the whole ipsilateral face including the forehead. The abducens fascicle runs a similar ventral course from its nucleus and is frequently caught, adding ipsilateral abduction failure. This 'alternating' pattern, cranial nerve on one side and limbs on the other, is the signature of a brainstem lesion, and the specific nerve names the level: facial and abducens for the caudal pons, oculomotor for the midbrain, hypoglossal for the medulla. The forehead involvement separates the pontine facial palsy from the forehead-sparing central weakness of a capsular lesion, where the face and limbs are weak on the same side.",
 [pathol("Ventral pontine infarct", "MRI", "Restricted diffusion in the ventrolateral caudal pons on the side of the facial palsy.", sequence="DWI"), pathol("Pontine hemorrhage or cavernoma", "MRI", "Hematoma or a 'popcorn' cavernoma with a hemosiderin rim in the ventral pons.", sequence="SWI"), pathol("Pontine tumor", "MRI", "Expansile glioma of the pons in a child.", sequence="T1+Gd")],
 ["Paramedian pontine branch infarct (basilar)", "Pontine hemorrhage", "Cavernous malformation", "Pontine glioma", "Multiple sclerosis plaque"],
 [("Bell palsy with an unrelated capsular stroke", "Two lesions; the hemiparesis is on the same side as the facial palsy in a capsular lesion"), ("Foville syndrome", "Adds a conjugate gaze palsy from the abducens nucleus or PPRF (dorsal pons)"), ("Cerebellopontine angle mass", "Facial and eighth nerve signs without contralateral limb weakness")],
 ["Acute stroke treatment when vascular", "Eye protection for the paralyzed lid", "Investigate for cavernoma or demyelination in young patients"],
 [R("sp-millard-gubler-syndrome"), R("sp-ventral-cord-syndrome"), R("sp-cerebral-blood-supply")], level="pons-caudal", arteryId="artery-basilar", marker=sphere(-8, -32, -32, 7), imagingHint=hint("axial", -8, -32, -32, "ventrolateral caudal pons"), preset="anterior", eponyms=["Millard–Gubler syndrome", "ventral pontine syndrome"]))

E.append(syn("syn-foville", "Foville syndrome (dorsal caudal pontine)", "vascular", ["level-pons-caudal", "abducens-nucleus", "pprf", "facial-motor-nucleus", "medial-longitudinal-fasciculus"], "ipsilateral",
 "The patient cannot look toward one side with either eye, has a complete facial palsy on that same side, and a hemiparesis on the opposite side. Unlike a sixth nerve palsy, both eyes fail to move toward the lesion, and the gaze palsy cannot be overcome by turning the head. There may be a contralateral hemisensory loss.",
 [D("oculomotor", "ipsilateral", "conjugate horizontal gaze", "Gaze palsy toward the lesion (abducens nucleus or PPRF), not overcome by the oculocephalic reflex when nuclear", "pathway-horizontal-gaze"), D("cranial-nerve", "ipsilateral", "whole face", "Peripheral-type facial palsy", "facial-motor-nucleus"), D("motor", "contralateral", "arm and leg", "Hemiparesis from the corticospinal tract", "pathway-lateral-corticospinal"), D("sensory-light-touch", "contralateral", "hemibody (variable)", "Hemisensory loss from the medial lemniscus", "pathway-dcml")],
 "The dorsal caudal pons contains the abducens nucleus and the paramedian pontine reticular formation, which together generate conjugate horizontal gaze toward the same side: the abducens nucleus contains the motor neurons for the ipsilateral lateral rectus and the interneurons that cross into the contralateral MLF to drive the opposite medial rectus. Destroying it therefore paralyzes gaze toward the lesion in both eyes, and because the nucleus is the final common pathway, vestibular input cannot overcome the palsy, unlike a lesion of the PPRF or the frontal eye field. The facial nerve fibers loop around the abducens nucleus (the facial colliculus) and are caught with it, so the ipsilateral face is completely paralyzed. The corticospinal fibers in the basis pontis, still uncrossed above the pyramidal decussation, are involved when the lesion extends ventrally, producing contralateral hemiparesis. The syndrome is thus Millard–Gubler with a gaze palsy in place of, or in addition to, the sixth nerve palsy, and the gaze palsy is what proves that the lesion is dorsal and involves the nucleus rather than the fascicle.",
 [pathol("Dorsal pontine infarct", "MRI", "Restricted diffusion in the paramedian dorsal tegmentum of the caudal pons at the level of the facial colliculus.", sequence="DWI"), pathol("Pontine demyelination or tumor", "MRI", "FLAIR-bright plaque or enhancing mass at the floor of the fourth ventricle.", sequence="FLAIR")],
 ["Paramedian pontine infarct", "Pontine hemorrhage", "Multiple sclerosis", "Pontine glioma"],
 [("Millard–Gubler syndrome", "Sixth nerve palsy (one eye) rather than a conjugate gaze palsy"), ("Frontal eye field lesion", "Gaze deviates toward the lesion and the palsy is overcome by the oculocephalic maneuver; hemiparesis is on the same side as the gaze palsy... i.e., the eyes look away from the weak limbs"), ("One-and-a-half syndrome", "Adds an internuclear ophthalmoplegia on the same side")],
 ["Acute stroke treatment", "Corneal protection", "MRI with contrast to exclude demyelination or tumor in the young"],
 [R("sp-foville-syndrome"), R("sp-cerebral-blood-supply"), R("sp-ischemic-stroke")], level="pons-caudal", arteryId="artery-basilar", marker=sphere(-5, -38, -28, 6), imagingHint=hint("axial", -5, -38, -28, "facial colliculus and abducens nucleus"), preset="posterior", eponyms=["Foville syndrome", "inferior medial pontine syndrome"]))

E.append(syn("syn-weber", "Weber syndrome (ventral midbrain)", "vascular", ["cerebral-peduncle-crus", "oculomotor-nucleus", "level-midbrain-superior-colliculus", "artery-pca", "arteries-thalamoperforating"], "ipsilateral",
 "A patient develops a drooping eyelid and a fixed dilated pupil with the eye turned down and out on one side, together with weakness of the face, arm and leg on the opposite side. The pattern of a third nerve palsy with crossed hemiplegia is the classic ventral midbrain syndrome and is most often caused by a small infarct in the territory of the posterior cerebral artery perforators.",
 [D("cranial-nerve", "ipsilateral", "oculomotor", "Complete third nerve palsy with ptosis, mydriasis and the eye down and out", "cn-03-oculomotor"), D("motor", "contralateral", "face, arm and leg", "Hemiplegia including the lower face (corticobulbar fibers in the crus)", "pathway-lateral-corticospinal"), D("bulbar", "contralateral", "tongue and lower face", "Corticobulbar weakness", "pathway-corticobulbar")],
 "The oculomotor nerve fascicles leave their nucleus in the periaqueductal gray and pass ventrally through the red nucleus and the medial part of the crus cerebri to emerge in the interpeduncular fossa. The middle three-fifths of the crus carry the corticospinal and corticobulbar fibers, which have not yet crossed; the corticobulbar fibers will cross at the level of the facial and hypoglossal nuclei and the corticospinal fibers at the pyramidal decussation. A ventral midbrain lesion therefore paralyzes the contralateral face, arm and leg together, in contrast to the medullary syndromes where the face is spared, while the oculomotor fibers, already the final lower motor neurons for the ipsilateral eye muscles and the parasympathetic supply to the pupil, are lost on the side of the lesion. The result is the alternating pattern of a cranial nerve palsy on one side and long tract signs on the other, and the identity of the nerve fixes the level at the midbrain. The pupil is involved because the parasympathetic fibers travel within the fascicle, unlike the ischemic peripheral third nerve palsy of diabetes, where they are usually spared.",
 [pathol("Ventral midbrain infarct", "MRI", "Restricted diffusion in the medial crus cerebri and adjacent tegmentum on the side of the third nerve palsy.", sequence="DWI"), pathol("Uncal herniation compressing the peduncle", "CT", "Supratentorial mass with medial temporal lobe displacement and a compressed midbrain; false localizing when the opposite peduncle is pressed against the tentorium (Kernohan).", sequence="CT non-contrast")],
 ["Posterior cerebral artery or basilar perforator infarct", "Midbrain hemorrhage", "Uncal herniation", "Midbrain tumor or aneurysm of the posterior cerebral artery"],
 [("Peripheral third nerve palsy with a separate capsular stroke", "Two lesions; the hemiparesis would be on the same side as the ptosis only by coincidence"), ("Benedikt syndrome", "Contralateral tremor and ataxia (red nucleus) rather than hemiplegia"), ("Claude syndrome", "Contralateral ataxia without weakness")],
 ["Acute stroke management", "Exclude an aneurysm or herniation urgently when the pupil is involved", "Eye patching for diplopia while the palsy recovers"],
 [R("sp-weber-syndrome"), R("sp-sturge-weber-syndrome"), R("sp-weber-test")], level="midbrain-superior-colliculus", arteryId="artery-pca", marker=sphere(-8, -20, -12, 7), imagingHint=hint("axial", -8, -20, -12, "medial crus cerebri and oculomotor fascicle"), preset="anterior", eponyms=["Weber syndrome", "superior alternating hemiplegia"]))

E.append(syn("syn-claude", "Claude syndrome (dorsal midbrain tegmentum)", "vascular", ["red-nucleus", "oculomotor-nucleus", "superior-cerebellar-peduncle", "level-midbrain-superior-colliculus"], "ipsilateral",
 "A patient develops a third nerve palsy on one side and, on the opposite side, an ataxic arm and leg with dysmetria and an intention tremor, without weakness. The combination of an ipsilateral oculomotor palsy and contralateral cerebellar signs places the lesion in the midbrain tegmentum, where the third nerve fascicles cross the superior cerebellar peduncle decussation and the red nucleus.",
 [D("cranial-nerve", "ipsilateral", "oculomotor", "Third nerve palsy, often with pupil involvement", "cn-03-oculomotor"), D("cerebellar", "contralateral", "arm and leg", "Limb ataxia, dysmetria and intention tremor", "pathway-cerebellar-circuits"), D("motor", "n/a", "spared", "No significant weakness (crus cerebri spared)", "pathway-lateral-corticospinal")],
 "The dentate nucleus sends its output through the superior cerebellar peduncle, which decussates in the caudal midbrain and then ends in or passes through the red nucleus of the opposite side on its way to the thalamus. A lesion of the paramedian midbrain tegmentum at the level of the red nucleus therefore interrupts cerebellar outflow that has already crossed, and since that outflow, after relaying in the thalamus and motor cortex, would have crossed again through the corticospinal tract to reach the limbs on the side of the original cerebellar hemisphere, the ataxia appears on the side opposite the midbrain lesion. The oculomotor fascicles run through the same region on their way from the nucleus to the interpeduncular fossa and are lost on the side of the lesion, since the nerve is the final ipsilateral motor pathway. The crus cerebri lies ventral to the lesion and is spared, so there is no hemiplegia, which separates Claude from Weber; involvement of the red nucleus itself with rubral tremor and some weakness makes it Benedikt. The supplying vessels are the paramedian perforators from the top of the basilar and the proximal posterior cerebral artery.",
 [pathol("Paramedian midbrain infarct", "MRI", "Small area of restricted diffusion in the paramedian midbrain tegmentum at the level of the red nucleus.", sequence="DWI"), pathol("Midbrain hemorrhage", "CT", "Small hyperdense tegmental hemorrhage; check for cavernoma on MRI.", sequence="CT non-contrast")],
 ["Perforator infarct from the posterior cerebral or basilar artery", "Midbrain hemorrhage or cavernoma", "Demyelination"],
 [("Weber syndrome", "Contralateral hemiplegia instead of ataxia"), ("Benedikt syndrome", "Adds contralateral tremor and involuntary movements from the red nucleus"), ("Cerebellar infarct with a separate third nerve palsy", "Ataxia would be ipsilateral to the cerebellar lesion")],
 ["Acute stroke treatment", "Diplopia management", "Physiotherapy for ataxia"],
 [R("sp-red-nucleus"), R("sp-brainstem-stroke"), R("sp-cranial-nerve-iii-palsy")], level="midbrain-superior-colliculus", marker=sphere(-4, -22, -10, 6), imagingHint=hint("axial", -4, -22, -10, "paramedian midbrain tegmentum, red nucleus"), preset="anterior", eponyms=["Claude syndrome"]))

E.append(syn("syn-benedikt", "Benedikt syndrome (midbrain tegmentum with red nucleus)", "vascular", ["red-nucleus", "oculomotor-nucleus", "substantia-nigra", "cerebral-peduncle-crus", "level-midbrain-superior-colliculus"], "ipsilateral",
 "The patient has a third nerve palsy on one side and, on the other, a coarse tremor that is present at rest, worsens with posture and becomes wild on reaching, together with ataxia, choreoathetoid movements and sometimes mild weakness. This combination of an oculomotor palsy with contralateral involuntary movements marks a lesion of the midbrain tegmentum that includes the red nucleus.",
 [D("cranial-nerve", "ipsilateral", "oculomotor", "Third nerve palsy", "cn-03-oculomotor"), D("cerebellar", "contralateral", "arm more than leg", "Holmes (rubral) tremor: rest, postural and intention components; ataxia", "red-nucleus"), D("other", "contralateral", "limbs", "Choreoathetosis or hemiballismus-like movements from the nigra and subthalamic connections", "substantia-nigra"), D("motor", "contralateral", "mild", "Mild hemiparesis if the lesion reaches the crus", "pathway-lateral-corticospinal")],
 "The red nucleus sits in the midbrain tegmentum at the level of the superior colliculus, receiving the crossed dentatothalamic fibers from the opposite cerebellum and sending the rubrospinal tract, which crosses immediately, to the contralateral cord. A lesion here interrupts cerebellar outflow after its decussation and damages the red nucleus and the neighboring substantia nigra, so the resulting tremor and ataxia are contralateral, following the same double-crossing logic as the Claude syndrome: cerebellar information that crossed once in the superior cerebellar peduncle would have been re-crossed by the corticospinal tract to serve the opposite limbs. The oculomotor fascicles pass directly through the red nucleus on their way to the interpeduncular fossa, and their interruption gives the ipsilateral third nerve palsy. The characteristic Holmes tremor, slow and present at rest as well as on action, is attributed to the combined loss of cerebellothalamic and nigrostriatal input, and it typically appears weeks after the acute lesion. Ventral extension into the crus adds contralateral weakness, blending the syndrome with Weber.",
 [pathol("Midbrain tegmental infarct", "MRI", "Restricted diffusion involving the red nucleus and adjacent tegmentum on the side of the third nerve palsy.", sequence="DWI"), pathol("Midbrain tumor or vascular malformation", "MRI", "Enhancing lesion or cavernoma in the tegmentum; tremor may be delayed.", sequence="T1+Gd")],
 ["Perforator infarct from the posterior cerebral artery", "Midbrain hemorrhage", "Cavernous malformation", "Tumor"],
 [("Claude syndrome", "Ataxia only, no rest tremor or involuntary movements"), ("Weber syndrome", "Hemiplegia without tremor"), ("Parkinsonian rest tremor", "No third nerve palsy; bilateral over time")],
 ["Treat the underlying lesion", "Holmes tremor may respond partly to levodopa or to thalamic deep brain stimulation", "Diplopia management"],
 [R("sp-benedikt-syndrome"), R("sp-cerebral-blood-supply"), R("sp-ischemic-stroke")], level="midbrain-superior-colliculus", marker=sphere(-6, -20, -8, 7), imagingHint=hint("axial", -6, -20, -8, "red nucleus and oculomotor fascicle"), preset="anterior", eponyms=["Benedikt syndrome"]))

E.append(syn("syn-parinaud-dorsal-midbrain", "Parinaud (dorsal midbrain) syndrome", "compressive", ["pretectal-area", "superior-colliculus", "rimlf", "level-midbrain-superior-colliculus", "cerebral-aqueduct", "pineal-gland"], "bilateral",
 "A young patient complains of double vision and blurred vision on looking up, and headache. Examination shows that neither eye can look up, the lids are retracted so the eyes look startled, the pupils are large and react to a near target but not to light, and when the patient tries to look up the eyes jerk inward and retract into the orbit. Downward gaze may follow. Papilledema is common because the aqueduct is compressed.",
 [D("oculomotor", "bilateral", "vertical", "Supranuclear up-gaze palsy, often overcome by the oculocephalic reflex early on", "pathway-vertical-gaze"), D("pupil", "bilateral", "both", "Light-near dissociation: mid-dilated pupils reacting to near but not to light", "pathway-pupillary-light-reflex"), D("oculomotor", "bilateral", "lids and convergence", "Lid retraction (Collier sign) and convergence-retraction nystagmus on attempted up-gaze", "pretectal-area"), D("other", "bilateral", "aqueduct", "Headache and papilledema from obstructive hydrocephalus", "cerebral-aqueduct")],
 "The pretectal area and posterior commissure lie just in front of the superior colliculi, beneath the pineal gland and above the aqueduct. Up-gaze commands from the rostral interstitial nucleus of the MLF cross through the posterior commissure to reach the oculomotor subnuclei of both sides, so compression of this small region abolishes up-gaze bilaterally while leaving the oculomotor nuclei, and therefore individual eye movements and the near response, intact. The pretectal nuclei that receive the light reflex afferents from both optic tracts are damaged, so the light reflex fails in both eyes, whereas the near reflex, which reaches the Edinger–Westphal nuclei from the cortex by a more ventral route, survives: light-near dissociation. Lid retraction and convergence-retraction nystagmus result from disinhibition of the levator and from co-contraction of all the extraocular muscles when the pretectum misfires. The aqueduct runs directly beneath, so a pineal tumor or a dilated third ventricle produces both the eye signs and hydrocephalus. Because the whole structure is midline and receives bilateral input, there is no ipsilateral or contralateral pattern; the syndrome is symmetric.",
 [pathol("Pineal region tumor", "MRI", "Enhancing mass in the pineal region compressing the tectum with dilatation of the lateral and third ventricles.", sequence="T1+Gd"), pathol("Hydrocephalus", "CT", "Dilated third and lateral ventricles with a normal fourth ventricle (aqueduct stenosis) and a distended suprapineal recess pressing on the tectum.", sequence="CT non-contrast"), pathol("Dorsal midbrain infarct", "MRI", "Restricted diffusion in the pretectum after a top-of-the-basilar embolus.", sequence="DWI")],
 ["Pineal tumor (germinoma, pineoblastoma) in the young", "Obstructive hydrocephalus", "Top of the basilar infarct or midbrain hemorrhage in the elderly", "Multiple sclerosis"],
 [("Progressive supranuclear palsy", "Down-gaze affected first, slow progression, no hydrocephalus, older patient"), ("Thyroid eye disease", "Up-gaze restriction from a tight inferior rectus, forced duction abnormal, normal pupils"), ("Bilateral third nerve nuclear lesion", "Ptosis and other muscles involved")],
 ["Urgent MRI and neurosurgical assessment; CSF diversion for hydrocephalus", "Tumor markers (AFP, beta-hCG) in serum and CSF for germ cell tumors", "Prisms or occlusion for diplopia"],
 [R("sp-parinaud-syndrome"), R("sp-peripheral-nerve-injury")], level="midbrain-superior-colliculus", marker=sphere(0, -28, -2, 8), imagingHint=hint("sagittal", 0, -28, -2, "pretectum beneath the pineal, above the aqueduct"), preset="lateral-l", eponyms=["Parinaud syndrome", "pretectal syndrome", "Sylvian aqueduct syndrome"]))

E.append(syn("syn-ino", "Internuclear ophthalmoplegia", "demyelinating", ["medial-longitudinal-fasciculus", "level-pons-caudal", "level-pons-rostral", "abducens-nucleus", "oculomotor-nucleus"], "ipsilateral",
 "A young woman notices double vision on looking to one side. When she looks to the right, the left eye stays in the midline or adducts slowly while the right eye abducts fully and shows jerky nystagmus; when she looks left, both eyes move normally. Asked to look at a pencil brought toward her nose, both eyes converge, proving that the medial rectus itself works. In an older patient with the same finding, a small pontine stroke is the likely cause.",
 [D("oculomotor", "ipsilateral", "adduction of the eye on the side of the lesion", "Adduction failure or slowing on contralateral gaze with preserved convergence", "medial-longitudinal-fasciculus"), D("oculomotor", "contralateral", "abducting eye", "Dissociated nystagmus of the abducting eye", "pathway-horizontal-gaze"), D("oculomotor", "bilateral", "vertical", "Skew deviation and vertical gaze-evoked nystagmus when bilateral", "pathway-vestibular-vor")],
 "Conjugate horizontal gaze depends on the abducens nucleus of one side driving the lateral rectus of its own eye and, through interneurons whose axons cross immediately and ascend in the contralateral MLF, the medial rectus subnucleus of the opposite oculomotor nucleus. A lesion of the MLF on one side cuts the ascending interneuron axons after they have crossed, so the medial rectus on the side of the lesion no longer receives the gaze command: on gaze away from the lesion the ipsilateral eye fails to adduct, and the syndrome is named for the side of the eye that does not adduct, which is the side of the MLF lesion. The abducting eye shows nystagmus, attributed to adaptive increased innervation sent to both yoked muscles. The medial rectus and its motor neurons are intact, so convergence, which uses a separate midbrain pathway, is preserved; this separates INO from a partial third nerve palsy. Bilateral INO in a young adult is almost diagnostic of multiple sclerosis because the MLFs lie side by side in the periventricular tegmentum; unilateral INO in the elderly is usually a paramedian pontine perforator infarct.",
 [pathol("Multiple sclerosis plaque", "MRI", "Small T2/FLAIR-bright lesion in the dorsal paramedian pons or midbrain along the MLF, often with other periventricular lesions; thin sagittal sections help.", sequence="FLAIR"), pathol("Pontine lacunar infarct", "MRI", "Punctate restricted diffusion in the paramedian tegmentum in an older patient.", sequence="DWI")],
 ["Multiple sclerosis (young, often bilateral)", "Paramedian pontine infarct (older)", "Brainstem tumor or hemorrhage", "Wernicke encephalopathy"],
 [("Medial rectus (partial third nerve) palsy", "Convergence also fails; ptosis or pupil signs may coexist"), ("Myasthenia gravis", "Pseudo-INO that fatigues and reverses with ice or edrophonium; ptosis common"), ("One-and-a-half syndrome", "Adds an ipsilateral conjugate gaze palsy")],
 ["MRI of the brain with attention to the brainstem; evaluate for multiple sclerosis in the young", "Stroke workup and secondary prevention in the elderly", "Diplopia is usually mild and improves; prisms if persistent"],
 [R("sp-internuclear-ophthalmoplegia"), R("sp-nodes-of-ranvier")], level="pons-rostral", marker=sphere(-2, -35, -25, 5), imagingHint=hint("axial", -2, -35, -25, "medial longitudinal fasciculus in the dorsal paramedian pons"), preset="posterior", eponyms=["INO", "MLF syndrome"]))

E.append(syn("syn-one-and-a-half", "One-and-a-half syndrome", "vascular", ["abducens-nucleus", "pprf", "medial-longitudinal-fasciculus", "level-pons-caudal"], "ipsilateral",
 "The patient's eyes are fixed in the horizontal plane except for one movement: the eye opposite the lesion can still abduct, and it does so with nystagmus. Looking toward the side of the lesion is impossible with either eye, and looking away, the eye on the side of the lesion cannot adduct. Vertical movements and convergence are preserved. Often there is also a facial palsy on the side of the lesion.",
 [D("oculomotor", "ipsilateral", "conjugate gaze toward the lesion", "Horizontal gaze palsy toward the lesion (the 'one')", "pathway-horizontal-gaze"), D("oculomotor", "ipsilateral", "adduction on contralateral gaze", "Internuclear ophthalmoplegia (the 'half')", "medial-longitudinal-fasciculus"), D("oculomotor", "contralateral", "abduction", "Only surviving horizontal movement: abduction of the contralateral eye with nystagmus", "abducens-nucleus"), D("cranial-nerve", "ipsilateral", "face", "Facial palsy when the facial colliculus is involved (eight-and-a-half syndrome)", "facial-motor-nucleus")],
 "A single lesion of the dorsal paramedian pons can destroy both the abducens nucleus or paramedian pontine reticular formation on one side and the adjacent MLF on the same side. Loss of the abducens nucleus paralyzes gaze toward the lesion in both eyes, because the nucleus contains the lateral rectus motor neurons for its own eye and the interneurons that cross to the opposite medial rectus; this is the 'one', a complete conjugate gaze palsy to the side of the lesion. The MLF on the side of the lesion carries the already-crossed interneuron axons from the opposite abducens nucleus up to the ipsilateral medial rectus subnucleus, so gaze away from the lesion fails in the ipsilateral eye; this is the 'half', an internuclear ophthalmoplegia. What survives is abduction of the contralateral eye, driven by the intact contralateral abducens nucleus, and it shows the dissociated nystagmus of any INO. Vertical gaze and convergence use midbrain pathways and are spared. The facial nerve loops over the abducens nucleus, so its involvement adds an ipsilateral peripheral facial palsy. The two lesion sites are within a few millimeters, which is why one small infarct or plaque produces the combination.",
 [pathol("Dorsal pontine infarct", "MRI", "Small restricted diffusion focus in the paramedian dorsal pontine tegmentum at the level of the abducens nucleus.", sequence="DWI"), pathol("Multiple sclerosis", "MRI", "FLAIR lesion at the floor of the fourth ventricle in the caudal pons with other demyelinating lesions.", sequence="FLAIR")],
 ["Paramedian pontine infarct", "Multiple sclerosis", "Pontine hemorrhage or tumor"],
 [("Bilateral INO", "Both eyes fail to adduct, both abduct: gaze to each side is partially possible"), ("Bilateral sixth nerve palsies", "Adduction is normal; abduction fails on both sides"), ("Ocular myasthenia", "Variable, fatigable, no nystagmus, ptosis")],
 ["Stroke or demyelination workup depending on age", "Occlusion or prism for diplopia; recovery is common", "Corneal care if facial palsy coexists"],
 [R("sp-internuclear-ophthalmoplegia"), R("sp-cranial-nerve-6"), R("sp-brainstem-stroke")], level="pons-caudal", marker=sphere(-4, -38, -28, 6), imagingHint=hint("axial", -4, -38, -28, "abducens nucleus and adjacent MLF"), preset="posterior"))

E.append(syn("syn-horizontal-gaze-palsy-pontine", "Pontine horizontal gaze palsy", "vascular", ["pprf", "abducens-nucleus", "level-pons-caudal", "frontal-eye-field"], "ipsilateral",
 "After a pontine stroke the patient cannot look toward the side of the lesion with either eye, and at rest the eyes drift toward the opposite side, away from the lesion and toward any hemiparesis. This is the reverse of the hemispheric pattern, where the eyes look toward the lesion and away from the weak limbs. Distinguishing the two is a bedside way to tell a pontine from a hemispheric stroke.",
 [D("oculomotor", "ipsilateral", "conjugate horizontal gaze", "Gaze palsy toward the lesion; eyes deviated away from the lesion", "pprf"), D("motor", "contralateral", "arm and leg", "Hemiparesis when the basis pontis is involved; the eyes look toward the weak side", "pathway-lateral-corticospinal"), D("oculomotor", "ipsilateral", "vestibulo-ocular", "Oculocephalic reflex overcomes a PPRF lesion but not an abducens nuclear lesion", "pathway-vestibular-vor")],
 "The frontal eye field of each hemisphere sends its saccade command across the midline to the paramedian pontine reticular formation of the opposite side, which fires the adjacent abducens nucleus to move both eyes toward that side. A right hemispheric lesion therefore removes the drive to the left PPRF: the patient cannot look left, and the unopposed left hemisphere pushes the eyes to the right, toward the lesion; with the crossed corticospinal fibers also damaged, the weak limbs are on the left, so the eyes look away from the hemiparesis. A left pontine lesion of the PPRF or abducens nucleus removes leftward gaze at its final stage: the eyes cannot look left, toward the lesion, and drift right, away from it; the uncrossed corticospinal fibers in the left basis pontis produce a right hemiparesis, so now the eyes look toward the weak limbs. The vestibulo-ocular reflex reaches the abducens nucleus directly from the vestibular nuclei, bypassing the PPRF, so a PPRF lesion (supranuclear) can be overcome by head turning and caloric stimulation whereas an abducens nuclear lesion cannot, and a nuclear lesion adds an ipsilateral facial palsy from the facial colliculus.",
 [pathol("Paramedian pontine infarct", "MRI", "Restricted diffusion in the dorsal paramedian caudal pons; may extend ventrally into the corticospinal fibers.", sequence="DWI"), pathol("Pontine hemorrhage", "CT", "Hyperdense tegmental hematoma; often hypertensive.", sequence="CT non-contrast")],
 ["Paramedian pontine infarct", "Pontine hemorrhage", "Multiple sclerosis", "Pontine glioma"],
 [("Frontal eye field lesion", "Eyes deviate toward the lesion, palsy overcome by the oculocephalic reflex, resolves within days"), ("Sixth nerve palsy", "Only one eye fails to abduct; the other adducts normally"), ("Seizure with gaze deviation", "Eyes deviate away from an irritative focus and jerk; transient")],
 ["Acute stroke treatment", "Bedside: use the direction of gaze deviation relative to the weak side to localize before imaging", "Recovery of gaze is usual over weeks"],
 [R("sp-cranial-nerve-6"), R("sp-brainstem-stroke"), R("sp-internuclear-ophthalmoplegia")], level="pons-caudal", marker=sphere(-5, -38, -28, 6), imagingHint=hint("axial", -5, -38, -28, "PPRF and abducens nucleus"), preset="posterior"))

E.append(syn("syn-aica-lateral-pontine", "Lateral pontine syndrome (AICA infarct)", "vascular", ["level-pons-caudal", "facial-motor-nucleus", "cochlear-nuclei", "vestibular-nuclei", "spinal-trigeminal-nucleus-tract", "middle-cerebellar-peduncle", "artery-aica"], "ipsilateral",
 "A patient develops sudden vertigo and vomiting with deafness in one ear, a complete facial palsy on the same side, and clumsiness of the arm and leg on that side. Pain sensation is lost on that side of the face and on the opposite side of the body, and there may be a Horner syndrome. Weakness is absent. It looks like a Wallenberg syndrome that has moved up one level and acquired the seventh and eighth nerves.",
 [D("auditory", "ipsilateral", "one ear", "Sudden sensorineural deafness (cochlear nucleus, labyrinthine artery)", "cochlear-nuclei"), D("cranial-nerve", "ipsilateral", "whole face", "Peripheral-type facial palsy (facial nucleus)", "facial-motor-nucleus"), D("vestibular", "ipsilateral", "vestibular nuclei and labyrinth", "Vertigo, nystagmus, vomiting", "vestibular-nuclei"), D("cerebellar", "ipsilateral", "limbs", "Ataxia from the middle cerebellar peduncle and cerebellar infarct", "middle-cerebellar-peduncle"), D("sensory-pain-temp", "ipsilateral", "face", "Facial pain and temperature loss (spinal trigeminal tract)", "spinal-trigeminal-nucleus-tract"), D("sensory-pain-temp", "contralateral", "body", "Body pain and temperature loss (spinothalamic tract)", "pathway-lateral-spinothalamic"), D("autonomic", "ipsilateral", "eye", "Horner syndrome", "pathway-oculosympathetic")],
 "The anterior inferior cerebellar artery supplies the lateral caudal pons, the middle cerebellar peduncle, the anterior inferior cerebellum and, through the labyrinthine artery, the inner ear. The lateral pontine tegmentum contains the same long tracts that make the lateral medullary syndrome, the spinothalamic tract (already crossed, so body pain loss is contralateral), the spinal trigeminal tract (uncrossed, so facial pain loss is ipsilateral) and the descending sympathetic fibers (uncrossed, giving an ipsilateral Horner), plus the structures specific to this level: the facial motor nucleus, the cochlear and vestibular nuclei at the pontomedullary junction and the middle cerebellar peduncle. These are all ipsilateral, so the facial palsy, deafness, vertigo and ataxia are on the side of the lesion. The corticospinal fibers in the basis pontis and the medial lemniscus lie in the paramedian territory of the basilar perforators and are spared, hence no weakness or proprioceptive loss. Deafness is the distinguishing feature: an isolated acute unilateral hearing loss with vertigo should always raise AICA infarction, since the labyrinthine artery is usually a branch of AICA.",
 [pathol("AICA infarct", "MRI", "Restricted diffusion in the lateral caudal pons, middle cerebellar peduncle and anterior inferior cerebellum (flocculus region).", sequence="DWI"), pathol("AICA or basilar disease", "CTA", "Basilar atherosclerosis at the AICA origin or AICA occlusion; vertebrobasilar dissection in the young.")],
 ["Basilar artery atherosclerosis occluding the AICA origin", "Cardioembolism", "Vertebrobasilar dissection"],
 [("Vestibular neuritis with a coincidental Bell palsy", "No deafness, no crossed sensory loss, no ataxia beyond imbalance"), ("Lateral medullary syndrome", "No deafness or facial palsy; dysphagia and hoarseness present"), ("Labyrinthitis", "Hearing loss and vertigo with normal neurological examination and negative DWI")],
 ["Stroke treatment; anticoagulate for dissection or cardioembolism as appropriate", "Audiology; hearing rarely recovers fully", "Eye protection for the facial palsy; vestibular rehabilitation"],
 [R("sp-anterior-inferior-cerebellar-arteries"), R("sp-brainstem-stroke"), R("sp-cranial-nerve-8")], level="pons-caudal", arteryId="artery-aica", territoryId="territory-aica", marker=sphere(-22, -40, -35, 9), imagingHint=hint("axial", -22, -40, -35, "lateral caudal pons and middle cerebellar peduncle"), preset="posterior", eponyms=["AICA syndrome", "lateral inferior pontine syndrome"]))

E.append(syn("syn-sca-infarct", "Superior cerebellar artery infarction", "vascular", ["artery-sca", "cerebellar-hemisphere", "superior-cerebellar-peduncle", "dentate-nucleus", "territory-sca", "level-pons-rostral"], "ipsilateral",
 "The patient presents with a sudden inability to walk, vomiting, dysarthria and a clumsy arm on one side. There may be a Horner syndrome on the same side and loss of pain sensation on the opposite side of the body, without facial involvement. Over the next two days drowsiness can develop as the swollen superior cerebellum compresses the brainstem and fourth ventricle.",
 [D("cerebellar", "ipsilateral", "arm and leg, gait", "Limb and gait ataxia with dysarthria (superior cerebellar hemisphere and dentate)", "pathway-cerebellar-circuits"), D("sensory-pain-temp", "contralateral", "body, face spared", "Loss of body pain and temperature from the spinothalamic tract in the rostral lateral pons", "pathway-lateral-spinothalamic"), D("autonomic", "ipsilateral", "eye", "Horner syndrome", "pathway-oculosympathetic"), D("consciousness", "n/a", "mass effect", "Drowsiness and later coma from brainstem compression and hydrocephalus", "ventricle-fourth")],
 "The superior cerebellar artery arises from the basilar just below its bifurcation, curves around the rostral pons beneath the tentorium and supplies the superior surface of the cerebellum, the dentate nucleus, the superior cerebellar peduncle and the lateral rostral pontine tegmentum. Cerebellar signs are ipsilateral because cerebellar hemisphere output crosses in the superior cerebellar peduncle decussation and is crossed back by the corticospinal tract, so each hemisphere governs its own side of the body. The lateral rostral pons carries the spinothalamic tract, which crossed in the cord and now carries body pain and temperature from the opposite side, and the uncrossed descending sympathetic fibers; the spinal trigeminal tract has already ended below this level, which is why the face is spared, unlike in the lateral medullary and AICA syndromes. The facial and abducens nuclei lie caudal to the territory, so there is no facial palsy or deafness. The superior cerebellum abuts the tentorium and the midbrain, so swelling produces upward herniation and aqueduct obstruction, the main threat to life.",
 [pathol("SCA infarct", "MRI", "Restricted diffusion in the superior cerebellar hemisphere and vermis, often in a wedge extending to the dentate.", sequence="DWI"), pathol("Mass effect", "CT", "Effaced fourth ventricle and quadrigeminal cistern with early hydrocephalus at 24–72 h.", timing="Peak swelling day 2–3"), pathol("Embolic source", "CTA", "SCA branch occlusion; the artery is often embolized from the heart because of its proximal origin.")],
 ["Cardioembolism (the SCA is the cerebellar artery most often embolized)", "Basilar atherosclerosis", "Vertebrobasilar dissection"],
 [("Lateral medullary syndrome", "Facial sensory loss and bulbar palsy present; no dysarthria of cerebellar type"), ("AICA infarct", "Deafness and facial palsy"), ("Cerebellar hemorrhage", "Hyperdense on CT, headache and rapid deterioration")],
 ["Stroke treatment and neurosurgical monitoring for swelling; suboccipital decompression or ventriculostomy if deteriorating", "Anticoagulation for a cardiac source after the swelling phase", "Physiotherapy for ataxia"],
 [R("sp-cerebellar-infarction"), R("sp-cerebral-blood-supply"), R("sp-ischemic-stroke")], arteryId="artery-sca", territoryId="territory-sca", marker=terr("territory-superior-cerebellar-l"), imagingHint=hint("axial", -25, -60, -25, "superior cerebellar hemisphere"), preset="posterior"))

E.append(syn("syn-pica-cerebellar-infarct", "PICA cerebellar infarction with mass effect", "vascular", ["artery-pica", "cerebellar-hemisphere", "cerebellar-tonsil", "cerebellar-vermis", "ventricle-fourth", "territory-pica-lateral-medulla"], "ipsilateral",
 "A patient develops vertigo, vomiting, headache and an unsteady gait, veering to one side, with nystagmus and dysmetria of the limbs on that side, and is initially labeled as having labyrinthitis. Within one to three days they become drowsy, with a sixth nerve palsy and then a rising blood pressure and irregular breathing, as the swollen inferior cerebellum compresses the medulla and obstructs the fourth ventricle.",
 [D("cerebellar", "ipsilateral", "limbs and gait", "Limb ataxia, gait ataxia with lateropulsion, gaze-evoked nystagmus", "pathway-cerebellar-circuits"), D("vestibular", "ipsilateral", "vestibulocerebellum", "Vertigo and vomiting from the nodulus and flocculus", "flocculonodular-lobe"), D("consciousness", "n/a", "brainstem compression", "Drowsiness progressing to coma with obstructive hydrocephalus", "ventricle-fourth"), D("cranial-nerve", "ipsilateral", "abducens, facial", "False-localizing sixth nerve palsy and facial weakness from brainstem compression", "abducens-nucleus")],
 "The posterior inferior cerebellar artery supplies the inferior surface of the cerebellar hemisphere, the tonsil and the inferior vermis in addition to the lateral medulla, and an embolus or thrombus lodging beyond the medullary branches produces a purely cerebellar infarct. Cerebellar signs are ipsilateral to the lesion because the hemisphere's output crosses in the midbrain and is crossed back by the corticospinal tract to reach its own side of the body, and the inferior vermis and flocculonodular lobe give the vertigo, nystagmus and truncal imbalance. The danger of the syndrome lies not in the deficit but in the anatomy of the posterior fossa: the inferior cerebellum lies against the medulla and fourth ventricle, and as the infarct swells over the following days it pushes the tonsils into the foramen magnum and the brainstem forward, obstructing CSF outflow. The resulting hydrocephalus and medullary compression cause a stepwise decline in consciousness, cranial nerve palsies and finally cardiorespiratory arrest, which decompression can prevent. The initial similarity to vestibular neuritis, which never causes limb ataxia or a positive HINTS pattern of central type, is the diagnostic trap.",
 [pathol("PICA territory infarct", "MRI", "Restricted diffusion in the inferior cerebellar hemisphere and tonsil, sometimes with the lateral medulla.", sequence="DWI"), pathol("Malignant cerebellar edema", "CT", "Compressed or obliterated fourth ventricle, effaced basal cisterns, dilated temporal horns, tonsillar descent.", sequence="CT non-contrast", timing="Days 1–4")],
 ["Vertebral artery atherothrombosis or dissection", "Cardioembolism"],
 [("Vestibular neuritis", "Normal limb coordination, positive head impulse test, unidirectional nystagmus"), ("Cerebellar hemorrhage", "Hyperdense on CT from the outset"), ("Lateral medullary syndrome", "Bulbar signs and crossed sensory loss without significant hemispheric swelling")],
 ["Admit to a monitored bed; repeat CT at any decline in consciousness", "Suboccipital decompressive craniectomy and external ventricular drainage for deterioration from mass effect", "Antithrombotic therapy and vertebral artery imaging"],
 [R("sp-cerebellar-infarction"), R("sp-lateral-medullary-syndrome"), R("sp-vertebrobasilar-system")], arteryId="artery-pica", territoryId="territory-pica-lateral-medulla", marker=terr("territory-inferior-cerebellar-l"), imagingHint=hint("axial", -30, -60, -45, "inferior cerebellar hemisphere and tonsil"), preset="posterior"))

E.append(syn("syn-horner", "Horner syndrome", "functional-pattern", ["hypothalamus", "intermediolateral-column", "sympathetic-trunk", "ganglion-superior-cervical", "artery-internal-carotid", "cervical-sympathetic-chain"], "ipsilateral",
 "One pupil is smaller than the other and the difference is greater in a dim room, the eyelid on that side droops a millimeter or two and the lower lid sits slightly higher, giving the eye a sunken look. The affected side of the face may not sweat. Depending on the cause there may be neck pain, hoarseness, weakness of the hand, or a brainstem syndrome; in a child a lighter iris on the affected side implies a congenital lesion.",
 [D("pupil", "ipsilateral", "one pupil", "Miosis with dilation lag; anisocoria greatest in darkness", "pathway-oculosympathetic"), D("other", "ipsilateral", "upper and lower lids", "Mild ptosis (Müller's muscle) and 'upside-down ptosis' of the lower lid; apparent enophthalmos", "pathway-oculosympathetic"), D("autonomic", "ipsilateral", "face", "Anhidrosis of the face with central and preganglionic lesions; spared with postganglionic lesions", "ganglion-superior-cervical")],
 "The sympathetic pathway to the eye is entirely uncrossed, a three-neuron chain from the hypothalamus through the lateral brainstem and cervical cord to the ciliospinal center at C8–T2, then out through the T1 root over the lung apex and up the cervical chain to the superior cervical ganglion, and finally along the internal carotid artery through the cavernous sinus to the dilator pupillae and the smooth muscle of the lids. A lesion anywhere along this route produces the same ipsilateral triad, so the syndrome itself localizes only to the pathway, and the company it keeps localizes the lesion: first-order lesions (lateral medullary infarct, cervical cord) come with brainstem or cord signs and anhidrosis of the whole half of the body; second-order lesions (apical lung tumor, neck trauma, thyroid or carotid surgery) come with hand weakness, arm pain or a neck scar and facial anhidrosis; third-order lesions (carotid dissection, cavernous sinus disease, cluster headache) spare sweating, because the sudomotor fibers to the face leave the chain with the external carotid artery. The pupil is small because the dilator is paralyzed while the parasympathetic sphincter, reaching the eye by the third nerve, is intact, which is why the anisocoria widens in the dark and both pupils react normally to light.",
 [pathol("Carotid dissection", "MRA", "Crescentic intramural hematoma around a narrowed lumen on fat-saturated T1; string sign or tapered occlusion on angiography.", sequence="T1"), pathol("Pancoast tumor", "CT", "Apical lung mass invading the T1 root and stellate ganglion; look at the lung apex on any Horner workup.", sequence="CT contrast"), pathol("Lateral medullary infarct", "MRI", "Dorsolateral medullary restricted diffusion with the other Wallenberg signs.", sequence="DWI")],
 ["Internal carotid artery dissection", "Lateral medullary infarct", "Apical lung tumor", "Neck trauma or surgery", "Cavernous sinus lesion", "Cluster headache (transient)", "Congenital or birth trauma"],
 [("Physiologic anisocoria", "Difference equal in light and dark, no ptosis, no dilation lag"), ("Third nerve palsy with ptosis", "The pupil is large, not small, and ptosis is marked"), ("Adie tonic pupil", "The larger pupil is abnormal; poor light reaction, tonic near response")],
 ["A painful Horner is carotid dissection until proven otherwise: urgent CTA or MRA of the neck", "Apraclonidine (reversal of anisocoria) confirms the diagnosis; hydroxyamphetamine separates pre- from postganglionic lesions", "Image the whole pathway from hypothalamus to cavernous sinus when no cause is apparent, including the lung apex"],
 [R("sp-horner-syndrome"), R("sp-cerebral-cortex")], marker=structs("artery-internal-carotid-l"), imagingHint=hint("axial", -25, 0, -40, "internal carotid artery in the neck"), preset="anterior", eponyms=["oculosympathetic paresis", "Bernard–Horner syndrome"]))

write(E)
