import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).parent))
from synlib import *
E = []

E.append(syn("syn-uncal-herniation", "Uncal (lateral transtentorial) herniation", "herniation", ["gyrus-parahippocampal-uncus", "cn-03-oculomotor", "cerebral-peduncle-crus", "tentorium-cerebelli", "artery-pca", "reticular-formation"], "ipsilateral",
 "A patient with a growing temporal hematoma becomes drowsy, and the pupil on the side of the lesion enlarges and stops reacting to light while the eye drifts down and out. Then the opposite arm and leg weaken and the plantar becomes extensor. If nothing is done the patient becomes unresponsive, the other pupil dilates, the posture becomes extensor and breathing becomes irregular. Occasionally the weakness appears on the same side as the mass, because the opposite peduncle has been crushed against the tentorial edge.",
 [D("pupil", "ipsilateral", "one pupil, then both", "Early dilated, sluggish pupil from third nerve compression; later fixed and dilated, then bilateral", "cn-03-oculomotor"), D("consciousness", "n/a", "midbrain reticular formation", "Progressive drowsiness to coma as the midbrain is displaced and compressed", "reticular-formation"), D("motor", "contralateral", "arm and leg", "Hemiparesis with extensor plantar from compression of the ipsilateral cerebral peduncle", "pathway-lateral-corticospinal"), D("motor", "ipsilateral", "arm and leg (false localizing)", "Kernohan notch: hemiparesis on the side of the mass from compression of the contralateral peduncle against the tentorium", "cerebral-peduncle-crus"), D("visual-field", "contralateral", "homonymous", "Occipital infarct from compression of the posterior cerebral artery against the tentorial edge", "artery-pca")],
 "The tentorium cerebelli separates the temporal lobes from the posterior fossa, leaving the tentorial notch through which the midbrain passes with the oculomotor nerves and the posterior cerebral arteries running beside it. An expanding lateral supratentorial mass pushes the medial temporal lobe, the uncus and parahippocampal gyrus, over the free edge of the tentorium into the notch. The first structure crushed is the oculomotor nerve, which runs forward from the midbrain beneath the uncus; its superficial pupilloconstrictor fibers fail before the motor fibers, so an enlarging, sluggish pupil on the side of the mass is the earliest sign, followed by ptosis and a down-and-out eye. The herniating uncus then presses on the cerebral peduncle, which carries the corticospinal fibers before their crossing in the medulla, so weakness appears on the opposite side; when the midbrain is instead displaced against the opposite tentorial edge, the contralateral peduncle is notched and the weakness appears on the same side as the mass, the false-localizing Kernohan sign, which is why the pupil, not the weakness, is trusted to indicate the side of the lesion. Compression and distortion of the midbrain reticular formation cause the decline in consciousness, and downward displacement stretches the paramedian perforating arteries, producing the Duret hemorrhages of the brainstem that make the late stages irreversible. The posterior cerebral artery is compressed against the tentorium, adding an occipital infarct in survivors.",
 [pathol("Uncal herniation", "CT", "Medial temporal lobe displaced into the suprasellar cistern, effacement of the ipsilateral ambient and suprasellar cisterns, midline shift, dilated contralateral temporal horn, midbrain rotation and widened contralateral ambient cistern.", sequence="CT non-contrast"), pathol("Duret hemorrhages", "MRI", "Linear or flame-shaped hemorrhages in the midline of the midbrain and pons on SWI or CT after downward displacement.", sequence="SWI"), pathol("PCA territory infarct", "MRI", "Occipital restricted diffusion on the side of the herniation.", sequence="DWI")],
 ["Epidural or subdural hematoma", "Temporal lobe contusion or hemorrhage", "Large MCA infarct with edema", "Tumor or abscess of the temporal lobe"],
 [("Primary third nerve palsy from an aneurysm", "Alert patient, no hemiparesis or altered consciousness"), ("Metabolic coma", "Pupils small and reactive, no lateralizing signs"), ("Pontine hemorrhage", "Pinpoint reactive pupils, quadriplegia, abrupt coma")],
 ["A dilating pupil in a patient with a mass is a surgical emergency: hyperventilate briefly, give mannitol or hypertonic saline, and evacuate the mass", "Head elevation, sedation, avoid hypotension and hypoxia", "Intracranial pressure monitoring and decompressive craniectomy when the mass cannot be removed"],
 [R("sp-uncal-herniation"), R("sp-transtentorial-herniation"), R("sp-cranial-meninges")], marker=structs("uncus-l"), imagingHint=hint("coronal", -25, -10, -20, "uncus at the tentorial notch beside the midbrain"), preset="inferior", eponyms=["lateral transtentorial herniation", "Kernohan notch phenomenon"]))

E.append(syn("syn-subfalcine-herniation", "Subfalcine (cingulate) herniation", "herniation", ["gyrus-cingulate", "falx-cerebri", "artery-aca", "ventricle-lateral"], "contralateral",
 "A patient with a large frontal or parietal mass has a headache and is drowsy, and the CT shows the septum pellucidum and the anterior ventricles pushed far across the midline beneath the falx. If the displaced hemisphere pinches its anterior cerebral artery against the rigid falx, weakness of the opposite leg develops on top of whatever deficit the mass has already produced. The far lateral ventricle dilates because its foramen of Monro is kinked.",
 [D("consciousness", "n/a", "diffuse", "Headache and depressed consciousness from the mass and raised pressure", "reticular-formation"), D("motor", "contralateral", "leg", "Leg weakness from compression of the anterior cerebral artery against the falx (ACA infarct)", "pathway-lateral-corticospinal"), D("other", "n/a", "ventricles", "Trapped contralateral lateral ventricle from obstruction of the foramen of Monro", "ventricle-lateral"), D("cognitive", "n/a", "medial frontal", "Abulia, incontinence, gait apraxia with bilateral medial frontal ischemia", "gyrus-cingulate")],
 "The falx cerebri hangs in the interhemispheric fissure from the vault to the corpus callosum, and its free lower edge lies just above the cingulate gyrus and the pericallosal branches of the anterior cerebral arteries. A mass in one hemisphere displaces the hemisphere toward the other side, and the cingulate gyrus, the most medial structure, is pushed under the free edge of the falx, taking the anterior cerebral artery with it. The herniation itself is usually silent, being the commonest and least dangerous of the herniations, and it is recognized on imaging by the midline shift of the septum pellucidum and the asymmetric ventricles; the third ventricle and the foramen of Monro are distorted so that the ventricle on the opposite side cannot drain and dilates, adding to the pressure. When the shift is large the anterior cerebral artery is compressed against the falx, infarcting the medial frontal and parietal cortex where the leg is represented; the corticospinal fibers from that cortex cross in the medulla, so the leg weakness is contralateral to the herniating hemisphere and the artery, in addition to whatever deficit the mass itself has produced. Both anterior cerebral arteries can be involved because they lie side by side, giving bilateral leg weakness, abulia and incontinence. Progressive shift precedes transtentorial herniation, so the degree of midline shift on CT is a marker of danger.",
 [pathol("Subfalcine herniation", "CT", "Displacement of the septum pellucidum, third ventricle and anterior falx-adjacent structures across the midline, measured as midline shift in millimeters; dilated contralateral ventricle.", sequence="CT non-contrast"), pathol("ACA infarct", "MRI", "Restricted diffusion in the medial frontal and parietal cortex on the side of the compressed artery, sometimes bilateral.", sequence="DWI")],
 ["Large hemispheric infarct with edema", "Subdural or intracerebral hematoma", "Tumor with edema", "Abscess"],
 [("Primary ACA infarct", "Leg weakness without a mass or midline shift"), ("Hydrocephalus", "Ventricles dilated symmetrically without shift")],
 ["Treat the mass and the raised pressure; midline shift above about 5 mm with clinical decline prompts surgical decompression", "Serial CT to monitor shift and the trapped ventricle", "Prevent secondary ACA infarction by early relief of the shift"],
 [R("sp-subfalcine-herniation"), R("sp-cranial-meninges")], marker=structs("gyrus-cingulate-anterior-l"), imagingHint=hint("coronal", 0, 10, 30, "cingulate gyrus beneath the free edge of the falx"), preset="anterior", eponyms=["cingulate herniation"]))

E.append(syn("syn-central-transtentorial-herniation", "Central (downward) transtentorial herniation", "herniation", ["thalamus", "level-midbrain-superior-colliculus", "reticular-formation", "red-nucleus", "level-pons-caudal"], "bilateral",
 "A patient with diffuse brain swelling or a midline mass becomes progressively less responsive without a dilating pupil. First they are drowsy with small reactive pupils, sighs and yawns, and their arms flex when a painful stimulus is applied; then they breathe in a crescendo-decrescendo rhythm, the pupils become mid-sized and fixed, the eyes stop moving with the head, and the limbs extend; finally breathing becomes rapid then irregular, the pupils dilate, and the limbs are flaccid.",
 [D("consciousness", "bilateral", "diencephalon then brainstem", "Progressive decline from drowsiness to coma as the reticular activating system is compressed level by level", "reticular-formation"), D("pupil", "bilateral", "both", "Small reactive (diencephalic stage), then mid-position fixed (midbrain), then dilated (terminal)", "pathway-pupillary-light-reflex"), D("motor", "bilateral", "all limbs", "Decorticate (flexor) posturing at the diencephalic stage, decerebrate (extensor) posturing at the midbrain-pontine stage, flaccidity at the medullary stage", "pathway-rubrospinal"), D("oculomotor", "bilateral", "vestibulo-ocular reflex", "Loss of oculocephalic and caloric responses as the pons is involved", "pathway-vestibular-vor"), D("other", "bilateral", "respiration", "Cheyne–Stokes then central hyperventilation, ataxic breathing and apnea", "reticular-formation")],
 "A diffuse increase in the volume of both hemispheres, or a midline mass, pushes the diencephalon and the upper brainstem downward through the tentorial notch, and the signs appear in rostrocaudal order as each level is compressed and its perforating arteries are stretched. At the diencephalic stage the thalamus and hypothalamus are compressed, consciousness fades, the pupils are small because the descending sympathetic pathway from the hypothalamus is interrupted while the midbrain parasympathetic outflow is intact, and the limbs adopt the decorticate posture, with the arms flexed by the rubrospinal and other brainstem flexor pathways that are still connected below the red nucleus while cortical control is lost. At the midbrain stage the third nerve nuclei and the pretectal light reflex pathways fail, so the pupils become mid-sized and fixed, the vertical gaze pathways are lost, and because the red nucleus and its rubrospinal tract are now disconnected, only the pontine vestibulospinal and reticulospinal extensor drives reach the cord, producing decerebrate extension. At the pontine stage the horizontal gaze centers and the vestibulo-ocular arcs are destroyed, so the eyes no longer move with head turning or caloric stimulation, breathing becomes rapid and regular, and at the medullary stage the respiratory centers fail and the limbs are flaccid. The Duret hemorrhages produced by shearing of the basilar perforators during descent make the pontine stage irreversible. Because the herniation is midline and symmetric, there is no lateralizing pupil and no ipsilateral or contralateral pattern to read, which is the clinical difference from uncal herniation.",
 [pathol("Central herniation", "CT", "Effacement of the suprasellar, perimesencephalic and quadrigeminal cisterns, downward displacement of the pineal calcification, obliteration of the basal cisterns, compressed ventricles.", sequence="CT non-contrast"), pathol("Duret hemorrhages", "MRI", "Central midbrain and pontine hemorrhages on SWI in a patient with a history of herniation.", sequence="SWI"), pathol("Diffuse cerebral edema", "CT", "Loss of gray-white differentiation, effaced sulci and cisterns, 'pseudo-subarachnoid hemorrhage' appearance.", sequence="CT non-contrast")],
 ["Diffuse cerebral edema (trauma, anoxia, hepatic failure, hyponatremia)", "Bilateral or midline masses", "Hydrocephalus", "Large hemispheric mass in late stages"],
 [("Metabolic encephalopathy", "Pupils reactive throughout, no rostrocaudal progression, asterixis or myoclonus"), ("Pontine hemorrhage", "Abrupt coma with pinpoint pupils and quadriplegia without preceding diencephalic stage"), ("Brain death", "End stage of the same process: absent brainstem reflexes and apnea")],
 ["Treat intracranial hypertension urgently: osmotherapy, head elevation, sedation, ventilation to normocapnia, CSF drainage, decompressive surgery", "Intracranial pressure monitoring in comatose patients with swelling", "Recognize the stage from pupils, posture and breathing; the midbrain stage is the last from which good recovery is likely"],
 [R("sp-transtentorial-herniation"), R("sp-brain-herniation")], marker=sphere(0, -22, -8, 12), imagingHint=hint("sagittal", 0, -22, -8, "midbrain at the tentorial notch"), preset="lateral-l", eponyms=["rostrocaudal deterioration"]))

E.append(syn("syn-tonsillar-herniation", "Tonsillar herniation (coning)", "herniation", ["cerebellar-tonsil", "level-medulla-olive", "reticular-formation", "ventricle-fourth"], "bilateral",
 "A patient with a posterior fossa mass, or a patient with raised intracranial pressure who has just had a lumbar puncture, develops a stiff neck, holds the head tilted, vomits, and then abruptly becomes apneic with a slow pulse and a rising blood pressure. The pupils may be small and then dilate; the arms extend. Unless the pressure is relieved within minutes, breathing stops permanently while the heart continues.",
 [D("other", "bilateral", "respiratory centers", "Apnea and ataxic breathing from medullary compression", "reticular-formation"), D("autonomic", "bilateral", "cardiovascular centers", "Cushing response: hypertension, bradycardia and irregular respiration", "reticular-formation"), D("consciousness", "bilateral", "medulla and lower pons", "Abrupt loss of consciousness", "reticular-formation"), D("pain", "bilateral", "neck", "Neck stiffness, head tilt and occipital pain from dural stretching and tonsillar impaction", "cerebellar-tonsil"), D("cranial-nerve", "bilateral", "lower cranial nerves", "Dysphagia, bilateral sixth nerve palsies and downbeat nystagmus before the crisis", "abducens-nucleus")],
 "The foramen magnum is the only exit from the rigid skull, and the cerebellar tonsils lie directly above it beside the medulla. When the pressure in the posterior fossa rises, from a cerebellar hematoma, infarct or tumor, or when the pressure difference across the foramen is suddenly increased by withdrawing CSF from the lumbar sac in a patient with a supratentorial mass, the tonsils are forced down through the foramen, plugging it and compressing the medulla against the bony rim. The medulla contains the respiratory rhythm generators and the cardiovascular centers, so the first consequences are irregular breathing, the Cushing response of hypertension with reflex bradycardia as the medulla tries to maintain its own perfusion, and then apnea; the heart, which has its own rhythm, keeps beating after breathing stops, which is why the classical death from coning is respiratory. The obstruction of the foramen also blocks CSF outflow from the fourth ventricle and worsens the hydrocephalus that produced it. The structures crushed are midline and the compression is symmetric, so there is no lateralizing sign and no ipsilateral or contralateral rule to apply, and the warning signs are those of medullary and lower pontine irritation: neck stiffness and head tilt, vomiting, hiccups, downbeat nystagmus and bilateral abducens palsies. Chronic tonsillar descent in Chiari malformation is a different, slow process, but it explains why a lumbar puncture can precipitate acute coning even when the supratentorial pressure is modest.",
 [pathol("Tonsillar herniation", "CT", "Tonsils below the foramen magnum with obliteration of the cisterna magna and crowding of the foramen; posterior fossa mass with a compressed fourth ventricle and hydrocephalus.", sequence="CT non-contrast"), pathol("Tonsillar descent", "MRI", "Peg-shaped tonsils below the basion–opisthion line on sagittal T1 with an effaced cisterna magna and medullary compression.", sequence="T1"), pathol("Cerebellar hemorrhage or infarct", "CT", "Hyperdense cerebellar hematoma or hypodense swollen infarct with fourth ventricular effacement, the commonest acute causes.", sequence="CT non-contrast")],
 ["Cerebellar hemorrhage or infarct with swelling", "Posterior fossa tumor", "Lumbar puncture in the presence of raised intracranial pressure", "Diffuse cerebral edema as the end stage of central herniation"],
 [("Chiari I malformation", "Chronic, cough headache, no acute deterioration"), ("Vasovagal syncope during lumbar puncture", "Brief, with recovery and no neurological signs"), ("Brainstem stroke", "Focal signs, cranial nerve pattern, no mass")],
 ["Never perform a lumbar puncture in a patient with signs of raised intracranial pressure or a posterior fossa mass without imaging first", "Emergency ventriculostomy and suboccipital decompression for posterior fossa masses with tonsillar descent", "Intubate and ventilate, osmotherapy, head up"],
 [R("sp-tonsillar-herniation"), R("sp-foramen-magnum"), R("sp-cranial-meninges")], marker=structs("cerebellar-lobule-ix-l", "cerebellar-lobule-ix-r"), imagingHint=hint("sagittal", 0, -45, -55, "cerebellar tonsils at the foramen magnum"), preset="posterior", eponyms=["coning", "foramen magnum herniation"]))

E.append(syn("syn-hydrocephalus", "Hydrocephalus: obstructive versus communicating", "csf-pressure", ["ventricle-lateral", "ventricle-third", "cerebral-aqueduct", "ventricle-fourth", "arachnoid-granulations", "choroid-plexus"], "bilateral",
 "A child with a large head and a bulging fontanelle whose eyes are forced downward, or an adult with a morning headache that wakes them, vomiting, blurred vision from swollen optic discs and double vision from a sixth nerve palsy, has hydrocephalus. If the CT shows dilated lateral and third ventricles with a normal fourth, the block is in the aqueduct; if all four ventricles are dilated, the block is outside them, at the basal cisterns or the arachnoid granulations, after meningitis or subarachnoid hemorrhage.",
 [D("consciousness", "bilateral", "diffuse", "Headache worse in the morning and on lying, vomiting, drowsiness; coma with acute obstruction", "reticular-formation"), D("visual-acuity", "bilateral", "optic discs", "Papilledema with enlarged blind spots and transient visual obscurations; late optic atrophy", "cn-02-optic"), D("oculomotor", "bilateral", "abducens (false localizing), up-gaze", "Sixth nerve palsies from raised pressure; sunset eyes and Parinaud signs from third ventricular dilatation pressing on the tectum", "pathway-vertical-gaze"), D("gait", "bilateral", "legs", "Spastic, magnetic gait from stretching of the leg fibers around the dilated frontal horns", "pathway-lateral-corticospinal"), D("sphincter", "bilateral", "bladder", "Urgency and incontinence from stretched periventricular frontal fibers", "gyrus-cingulate")],
 "Cerebrospinal fluid is secreted by the choroid plexus of the lateral, third and fourth ventricles, flows through the foramina of Monro, the third ventricle, the aqueduct and the fourth ventricle, leaves through the foramina of Luschka and Magendie into the subarachnoid space and is absorbed into the venous sinuses through the arachnoid granulations. Obstruction anywhere along the route dilates the ventricles upstream of the block, and the pattern of dilatation locates it: a block at one foramen of Monro traps one lateral ventricle; a block in the aqueduct, the narrowest part, dilates both lateral ventricles and the third but leaves the fourth normal; a block at the fourth ventricular outlets dilates all four; and failure of absorption at the granulations or obstruction of the basal cisterns by blood, pus or carcinomatosis, called communicating hydrocephalus because the ventricles still communicate with the subarachnoid space, dilates all four together with the cisterns. The distinction matters because a lumbar puncture is dangerous in obstructive hydrocephalus, where the lumbar sac is not in communication with the ventricles and drainage can precipitate herniation, but is diagnostic and sometimes therapeutic in communicating hydrocephalus. The signs are those of raised intracranial pressure, bilateral and without an ipsilateral or contralateral pattern: papilledema from transmission of pressure along the optic nerve sheaths, sixth nerve palsies from stretching of the long abducens nerves, and, when the third ventricle balloons back over the tectum, the up-gaze palsy of the dorsal midbrain syndrome. The leg fibers of the corticospinal tract sweep around the frontal horns on their way to the internal capsule and are stretched first, giving the characteristic gait and bladder disturbance.",
 [pathol("Obstructive hydrocephalus", "CT", "Dilated lateral and third ventricles with a normal fourth ventricle (aqueduct stenosis or tectal tumor) or all four dilated with an outlet block; rounded frontal horns, periventricular low density from transependymal CSF flow, effaced sulci.", sequence="CT non-contrast"), pathol("Communicating hydrocephalus", "MRI", "All four ventricles dilated with prominent basal cisterns; look for the cause: leptomeningeal enhancement, subarachnoid blood, previous meningitis.", sequence="T1+Gd"), pathol("Level of obstruction", "MRI", "Sagittal T2 and CISS show aqueduct stenosis, a tectal glioma, a colloid cyst at the foramen of Monro or a fourth ventricular tumor; absent aqueductal flow void.", sequence="T2")],
 ["Aqueduct stenosis (congenital or tectal tumor)", "Posterior fossa tumor or Chiari malformation", "Colloid cyst of the third ventricle", "Subarachnoid hemorrhage, meningitis, carcinomatosis (communicating)", "Intraventricular hemorrhage of prematurity"],
 [("Idiopathic intracranial hypertension", "Small or normal ventricles with papilledema"), ("Cerebral atrophy (hydrocephalus ex vacuo)", "Ventricles and sulci enlarged in proportion, no pressure signs"), ("Normal pressure hydrocephalus", "Chronic triad in the elderly with normal opening pressure")],
 ["Urgent CT in any patient with headache, vomiting and papilledema; do not perform a lumbar puncture in obstructive hydrocephalus", "External ventricular drainage for acute obstruction; endoscopic third ventriculostomy for aqueduct stenosis; ventriculoperitoneal shunt for communicating forms", "Treat the underlying tumor or cyst"],
 [R("sp-hydrocephalus"), R("sp-idiopathic-normal-pressure-hydrocephalus"), R("sp-cerebrospinal-fluid")], marker=structs("ventricle-lateral-l", "ventricle-lateral-r", "ventricle-third"), imagingHint=hint("coronal", 0, -10, 15, "lateral and third ventricles"), preset="anterior"))

E.append(syn("syn-normal-pressure-hydrocephalus", "Normal pressure hydrocephalus", "csf-pressure", ["ventricle-lateral", "ventricle-third", "arachnoid-granulations", "corona-radiata", "lobe-frontal"], "bilateral",
 "An elderly patient shuffles into clinic with feet that seem glued to the floor, turning in several small steps, and the family report months of forgetfulness, slowness and, more recently, urinary urgency and wetting. There is no tremor and the arms swing normally. CT shows ventricles that are far larger than the sulci would predict, and after fifty milliliters of CSF is removed the gait improves for a few days.",
 [D("gait", "bilateral", "legs", "Magnetic, wide-based, shuffling gait with difficulty initiating steps and turning; upper body relatively spared", "pathway-lateral-corticospinal"), D("cognitive", "bilateral", "frontal-subcortical", "Slowing, apathy, poor attention and executive function; memory impaired secondarily", "cortex-prefrontal"), D("sphincter", "bilateral", "bladder", "Urgency progressing to incontinence, often with indifference", "gyrus-cingulate")],
 "In normal pressure hydrocephalus CSF absorption through the arachnoid granulations is chronically impaired, often after old hemorrhage, infection or for no discoverable reason in the elderly, and the ventricles slowly enlarge while the intracranial pressure measured at a single lumbar puncture remains within the normal range, though prolonged monitoring shows intermittent pressure waves. The enlarged frontal horns stretch the periventricular white matter, and the fibers that run closest to the ventricular wall on their way from the medial frontal cortex to the internal capsule are those for the legs and for bladder control, together with the frontal-subcortical circuits that connect the prefrontal cortex to the basal ganglia and thalamus. Stretching and ischemia of these fibers explain the triad: a gait disorder that resembles parkinsonism in the legs but spares the arms, urinary urgency from loss of the frontal inhibition of the bladder reflex, and a subcortical dementia of slowing and apathy rather than the amnesia of Alzheimer disease. The process is bilateral and symmetric with no lateralizing or crossed signs. The distinction from atrophy rests on the disproportion between ventricular size and sulcal width, with crowding of the sulci at the vertex and widening of the Sylvian fissures, and from Alzheimer disease and vascular parkinsonism on the temporary improvement in gait after a large-volume lumbar puncture or a period of lumbar drainage, which also predicts the response to shunting. The gait responds best and earliest; established dementia responds least.",
 [pathol("Normal pressure hydrocephalus", "MRI", "Ventriculomegaly out of proportion to sulcal atrophy (Evans index above 0.3), tight high-convexity sulci with widened Sylvian fissures (DESH), callosal angle under 90°, periventricular T2 change and an accentuated aqueductal flow void.", sequence="T2"), pathol("Tap test", "LP/CSF", "Normal opening pressure; objective gait improvement after removal of 30–50 mL of CSF or after 3 days of lumbar drainage predicts shunt response.", sequence="n/a"), pathol("Secondary causes", "MRI", "Hemosiderin from old subarachnoid hemorrhage, meningeal thickening from previous infection.", sequence="SWI")],
 ["Idiopathic (elderly)", "Previous subarachnoid hemorrhage", "Previous meningitis", "Head injury"],
 [("Alzheimer disease", "Memory loss precedes gait change; hippocampal atrophy; no tap response"), ("Vascular parkinsonism", "Stepwise course with extensive white matter disease and lacunes"), ("Parkinson disease", "Rest tremor, asymmetric rigidity, reduced arm swing, levodopa response"), ("Cervical myelopathy", "Spasticity, sensory signs, compression on MRI")],
 ["MRI and a large-volume tap test or lumbar drain trial in patients with the triad and ventriculomegaly", "Ventriculoperitoneal shunt with an adjustable valve for responders; the gait improves most", "Manage comorbid Alzheimer pathology and vascular risk"],
 [R("sp-idiopathic-normal-pressure-hydrocephalus"), R("sp-cerebrospinal-fluid")], marker=structs("ventricle-lateral-l", "ventricle-lateral-r"), imagingHint=hint("coronal", 0, -10, 15, "frontal horns and periventricular white matter"), preset="anterior", eponyms=["Hakim–Adams syndrome"]))

E.append(syn("syn-idiopathic-intracranial-hypertension", "Idiopathic intracranial hypertension", "csf-pressure", ["arachnoid-granulations", "cn-02-optic", "cn-06-abducens", "sinus-transverse-sigmoid", "subarachnoid-space-cisterns"], "bilateral",
 "An overweight young woman has daily headaches that are worse on waking and on bending, a whooshing pulsatile noise in the ears, brief episodes of visual dimming on standing and horizontal double vision. Both optic discs are swollen, the blind spots are enlarged and one eye cannot fully abduct, but the rest of the examination is normal, the MRI shows no mass and small ventricles, and the lumbar puncture opening pressure is thirty-five centimeters of CSF with normal fluid.",
 [D("pain", "bilateral", "head", "Daily headache worse on waking, lying and straining; pulsatile tinnitus", "subarachnoid-space-cisterns"), D("visual-acuity", "bilateral", "optic discs", "Papilledema with transient visual obscurations, enlarged blind spots, progressive constriction of the fields and, untreated, permanent visual loss", "cn-02-optic"), D("oculomotor", "bilateral", "abducens", "Unilateral or bilateral sixth nerve palsies (false localizing)", "cn-06-abducens"), D("consciousness", "n/a", "preserved", "Alert, normal cognition; no focal deficit", "reticular-formation")],
 "The intracranial pressure rises without a mass, hydrocephalus or infection, most often in obese women of childbearing age, through mechanisms that are still debated but include impaired CSF absorption, raised venous pressure in the dural sinuses and, in many, stenosis of the transverse sinuses that may be cause or consequence. The raised pressure is transmitted throughout the subarachnoid space and along the optic nerve sheaths, where it obstructs axoplasmic flow in the optic nerve heads and produces papilledema; the swollen nerve fibers enlarge the blind spot and, if the pressure persists, die, constricting the field from the periphery and eventually destroying central vision, which makes the condition a threat to sight rather than to life. The abducens nerves, with their long course up the clivus and over the petrous apex, are stretched by the pressure and fail on one or both sides, giving diplopia that has nothing to do with the pons; a false-localizing sixth nerve palsy is the rule. Pulsatile tinnitus arises from turbulent venous flow through the compressed transverse sinuses, and the headache from stretching of the pain-sensitive dura. There is no focal lesion and no crossed or lateralized deficit apart from the sixth nerve palsy; the ventricles are small because the pressure is uniform, which separates the condition from hydrocephalus. The diagnosis requires papilledema, a normal neurological examination apart from sixth nerve palsy, normal imaging including venography to exclude sinus thrombosis, and a raised opening pressure with normal CSF composition.",
 [pathol("Signs of intracranial hypertension", "MRI", "Partially empty sella, flattening of the posterior globes, distension and tortuosity of the optic nerve sheaths, protrusion of the optic nerve heads, slit-like ventricles.", sequence="T2"), pathol("Transverse sinus stenosis", "MRV", "Bilateral narrowing of the distal transverse sinuses; also excludes venous sinus thrombosis, the essential mimic.", sequence="n/a"), pathol("Raised opening pressure", "LP/CSF", "Opening pressure above 25 cm CSF in the lateral decubitus position with normal protein, glucose and cells.", sequence="n/a")],
 ["Idiopathic, associated with obesity and recent weight gain", "Drugs: tetracyclines, retinoids, growth hormone, steroid withdrawal", "Secondary: venous sinus thrombosis, sleep apnea, anemia, endocrine disease (these are excluded by definition)"],
 [("Cerebral venous sinus thrombosis", "Identical presentation; MRV shows the thrombus; seizures and focal signs may occur"), ("Hydrocephalus", "Dilated ventricles"), ("Malignant hypertension", "Very high blood pressure with retinal hemorrhages and exudates"), ("Pseudopapilledema (drusen)", "Normal pressure; drusen on ultrasound or autofluorescence")],
 ["Formal perimetry at diagnosis and follow-up; visual fields, not headache, guide treatment", "Weight loss and acetazolamide; stop causative drugs", "Optic nerve sheath fenestration, venous sinus stenting or CSF shunting for progressive visual loss"],
 [R("sp-pseudotumor-cerebri"), R("sp-intracranial-hypertension"), R("sp-cerebrospinal-fluid")], marker=structs("optic-nerve-l", "optic-nerve-r"), imagingHint=hint("axial", 0, 20, -12, "optic nerve sheaths and posterior globes"), preset="anterior", eponyms=["pseudotumor cerebri", "benign intracranial hypertension"]))

E.append(syn("syn-epidural-hematoma", "Epidural (extradural) hematoma", "traumatic", ["dura-mater", "meningeal-spaces", "lobe-temporal", "cn-03-oculomotor"], "ipsilateral",
 "A young man is knocked out briefly in a fall, wakes and talks normally, then over the next few hours develops a worsening headache, vomits, becomes drowsy and is found with a dilated pupil on the side of the injury and weakness of the opposite limbs. The skull X-ray or CT shows a fracture of the temporal bone crossing the groove of the middle meningeal artery, and beneath it a lens-shaped clot pressing the brain inward.",
 [D("consciousness", "n/a", "diffuse, then brainstem", "Initial concussion, lucid interval, then progressive deterioration to coma as the clot expands", "reticular-formation"), D("pupil", "ipsilateral", "one pupil", "Dilated fixed pupil from uncal herniation", "cn-03-oculomotor"), D("motor", "contralateral", "arm and leg", "Hemiparesis from compression of the hemisphere and the cerebral peduncle", "pathway-lateral-corticospinal"), D("pain", "ipsilateral", "head", "Severe headache and vomiting", "dura-mater")],
 "The dura mater is the periosteum of the inner table of the skull, and the middle meningeal artery runs in a groove on the inner surface of the thin squamous temporal bone between the bone and the dura. A blow to the temple fractures the bone across the groove and tears the artery, and arterial blood at systemic pressure strips the dura from the skull, accumulating in the potential space between them. Because the dura is firmly attached at the sutures, the clot cannot spread across them and instead grows inward as a biconvex lens, in contrast to the crescentic subdural hematoma that spreads freely over the hemisphere beneath the dura. The initial blow causes a brief concussion, and the patient recovers as the arterial bleeding takes time to reach a critical volume, producing the lucid interval that is the classical and dangerous feature, because the deterioration that follows is due to a rapidly expanding arterial mass and not to brain injury. The expanding clot compresses the temporal lobe and pushes the uncus over the tentorium, so the sequence of signs is that of uncal herniation: an ipsilateral dilated pupil from third nerve compression, then contralateral hemiparesis from compression of the ipsilateral cerebral peduncle, whose corticospinal fibers cross in the medulla, then coma. Venous epidural hematomas from torn dural sinuses, in the posterior fossa or vertex, evolve more slowly. Because the underlying brain is often uninjured, prompt evacuation produces full recovery, which makes recognition of the lucid interval critical.",
 [pathol("Acute epidural hematoma", "CT", "Hyperdense biconvex (lentiform) extra-axial collection that does not cross sutures but may cross the falx or tentorium, usually beneath a temporal fracture; a swirl sign of low density indicates active bleeding.", sequence="CT non-contrast"), pathol("Skull fracture", "CT", "Linear fracture of the squamous temporal bone crossing the middle meningeal groove on bone windows.", sequence="CT non-contrast"), pathol("Mass effect", "CT", "Midline shift, effaced ventricle and uncal herniation with a large clot.", sequence="CT non-contrast")],
 ["Temporal skull fracture tearing the middle meningeal artery", "Dural venous sinus tear (posterior fossa, vertex)", "Anticoagulation with minor trauma"],
 [("Acute subdural hematoma", "Crescentic, crosses sutures, usually with underlying brain injury and no lucid interval"), ("Cerebral contusion", "Intraparenchymal hemorrhage in the temporal or frontal poles"), ("Concussion", "Recovery without deterioration; normal CT")],
 ["Immediate CT for any head injury with loss of consciousness, vomiting, drowsiness or a fracture; observe those with a lucid interval closely", "Emergency craniotomy and evacuation for symptomatic or large (over 30 mL) hematomas; small asymptomatic clots may be observed with repeat CT", "Reverse anticoagulation; manage intracranial pressure"],
 [R("sp-epidural-hematoma"), R("sp-peripheral-nerve-injury")], marker=sphere(-55, -10, 10, 20), imagingHint=hint("axial", -55, -10, 10, "temporal convexity beneath the squamous temporal bone"), preset="lateral-l", eponyms=["extradural hematoma"]))

E.append(syn("syn-subdural-hematoma", "Subdural hematoma", "traumatic", ["dura-mater", "arachnoid-mater", "meningeal-spaces", "veins-superficial-cerebral", "sinus-superior-sagittal"], "ipsilateral",
 "An elderly man on warfarin, or an alcoholic with atrophy, becomes confused, unsteady and drowsy over days to weeks, sometimes without remembering any injury; the family notice a fluctuating level of alertness, a headache and a slight weakness of one side. CT shows a crescent of blood over one hemisphere, dark if old and layered if it has rebled. In a young patient after a violent injury, the same crescent appears within hours, is bright white, and comes with a contused, swollen brain and a poor outlook.",
 [D("consciousness", "n/a", "diffuse", "Fluctuating confusion and drowsiness (chronic); coma from the outset (acute with brain injury)", "reticular-formation"), D("motor", "contralateral", "arm and leg", "Hemiparesis from hemispheric compression; may be ipsilateral through Kernohan notch", "pathway-lateral-corticospinal"), D("pain", "ipsilateral", "head", "Headache, worse over weeks in chronic hematomas", "dura-mater"), D("gait", "bilateral", "gait", "Unsteadiness and falls in the elderly, mimicking dementia or normal pressure hydrocephalus", "lobe-frontal"), D("pupil", "ipsilateral", "one pupil", "Dilated pupil with uncal herniation in large collections", "cn-03-oculomotor")],
 "The bridging veins run from the surface of the hemisphere through the subdural space and the dura to empty into the superior sagittal sinus, and they are torn when the brain moves relative to the skull: violently in acceleration-deceleration injury, or with trivial force in the elderly and in alcoholics, in whom cerebral atrophy has lengthened and stretched the veins across a widened subdural space. Venous blood at low pressure spreads freely between the dura and the arachnoid, which are not attached to each other, and so the hematoma forms a thin crescent over the whole convexity, crossing sutures but stopping at the falx and tentorium, the opposite of the epidural clot. In the acute form the same force that tears the veins contuses and swells the brain, and the mass effect and the brain injury combine to produce early coma and a high mortality. In the chronic form the small initial bleed is walled off by a vascular membrane that repeatedly rebleeds and secretes fluid, so the collection grows over weeks in a brain that has room to accommodate it, and the signs are those of a slowly increasing unilateral mass: fluctuating drowsiness, headache and a mild contralateral hemiparesis, since the compressed motor cortex and its corticospinal fibers serve the opposite side after crossing in the medulla, with the same risk of a false-localizing ipsilateral weakness from the Kernohan notch when the shift is large. Bilateral chronic hematomas cancel each other's shift and present as dementia or gait disorder, and anticoagulants and antiplatelet drugs are the commonest precipitants.",
 [pathol("Acute subdural hematoma", "CT", "Hyperdense crescentic collection over the convexity crossing sutures, often with underlying contusions and marked midline shift.", sequence="CT non-contrast"), pathol("Chronic subdural hematoma", "CT", "Hypodense or isodense crescent with mass effect; isodense collections are missed unless the sulcal effacement and shift are noticed; mixed density and fluid levels with rebleeding.", sequence="CT non-contrast"), pathol("Membranes and age", "MRI", "T1-bright subacute blood, enhancing membranes, and hemosiderin on SWI; MRI detects small bilateral isodense collections.", sequence="FLAIR")],
 ["Head injury, often trivial in the elderly", "Anticoagulation and antiplatelet therapy", "Cerebral atrophy (age, alcohol)", "Intracranial hypotension (spontaneous or after lumbar puncture)", "Shaken infant"],
 [("Epidural hematoma", "Biconvex, does not cross sutures, arterial, lucid interval"), ("Dementia or normal pressure hydrocephalus", "No crescent on CT; slower course"), ("Stroke", "Abrupt onset; DWI or hemorrhage within the brain")],
 ["CT for any elderly or anticoagulated patient with confusion, headache or falls; reverse anticoagulation", "Burr-hole drainage for symptomatic chronic hematomas; craniotomy for acute hematomas over 10 mm or with shift", "Observe small asymptomatic collections with repeat imaging; consider tranexamic acid or embolization of the middle meningeal artery for recurrence"],
 [R("sp-subdural-hematoma"), R("sp-peripheral-nerve-injury")], marker=sphere(-60, -10, 20, 25), imagingHint=hint("coronal", -60, -10, 20, "subdural space over the convexity beneath the bridging veins"), preset="lateral-l"))

E.append(syn("syn-subarachnoid-hemorrhage", "Aneurysmal subarachnoid hemorrhage and vasospasm", "vascular", ["subarachnoid-space-cisterns", "circle-of-willis", "artery-acom", "artery-pcom", "artery-mca", "cn-03-oculomotor"], "bilateral",
 "A patient describes the worst headache of their life, reaching maximum intensity within seconds, with vomiting, neck stiffness and photophobia; some collapse and lose consciousness briefly. A third nerve palsy with a dilated pupil points to a posterior communicating aneurysm. If the patient survives the first days, a new focal deficit or confusion between days four and fourteen means vasospasm, and drowsiness with dilated ventricles means hydrocephalus.",
 [D("pain", "bilateral", "head and neck", "Thunderclap headache with meningism, photophobia and vomiting", "subarachnoid-space-cisterns"), D("consciousness", "n/a", "diffuse", "Transient loss of consciousness at ictus; drowsiness from raised pressure or hydrocephalus", "reticular-formation"), D("cranial-nerve", "ipsilateral", "oculomotor", "Pupil-involving third nerve palsy with posterior communicating aneurysms", "cn-03-oculomotor"), D("motor", "contralateral", "focal deficits (delayed)", "Delayed ischemic deficits from vasospasm in the territory of the spasmed artery, days 4–14", "pathway-lateral-corticospinal"), D("visual-acuity", "bilateral", "retina", "Subhyaloid (Terson) hemorrhages on fundoscopy", "cn-02-optic")],
 "Saccular aneurysms form at the branch points of the circle of Willis, where the muscular layer of the arterial wall is deficient: the anterior communicating, posterior communicating and middle cerebral bifurcation are the commonest sites. The arteries lie in the subarachnoid space bathed in CSF, so rupture floods the basal cisterns with arterial blood in seconds; the sudden rise in intracranial pressure explains the abrupt headache and the transient loss of consciousness, and blood irritating the meninges produces the neck stiffness that appears over the following hours. Because the hemorrhage lies outside the brain, there is often no focal deficit at first, unless the jet of blood or the expanding aneurysm has injured a neighbor: a posterior communicating aneurysm sits directly on the oculomotor nerve, and its enlargement or rupture compresses the superficial pupillary fibers first, giving a painful pupil-involving third nerve palsy that is a warning sign before rupture. Blood in the cisterns has two delayed consequences. It blocks the arachnoid granulations and the basal cisterns, producing communicating hydrocephalus, and its breakdown products cause the cerebral arteries to constrict from about the fourth day, most severely where the clot is thickest, so that delayed infarcts appear in the territory of the spasmed vessel and produce the focal deficits, contralateral weakness or aphasia, of that territory. Rebleeding, most likely in the first day, is the other early killer and the reason aneurysms are secured urgently.",
 [pathol("Subarachnoid hemorrhage", "CT", "Hyperdense blood in the basal cisterns, Sylvian fissures and sulci within 6 hours in nearly all cases; the distribution suggests the aneurysm site (anterior interhemispheric for AComm, Sylvian for MCA).", sequence="CT non-contrast", timing="Sensitivity falls after 6–12 hours"), pathol("Xanthochromia", "LP/CSF", "Yellow supernatant from bilirubin 12 hours or more after the ictus when CT is negative and suspicion persists.", sequence="n/a"), pathol("Aneurysm", "CTA", "Saccular aneurysm at a circle of Willis branch point; catheter angiography if CTA is negative."), pathol("Vasospasm", "CTA", "Segmental narrowing of the proximal arteries with raised transcranial Doppler velocities; delayed infarcts on DWI.", timing="Days 4–14")],
 ["Ruptured saccular aneurysm (85%)", "Perimesencephalic non-aneurysmal hemorrhage", "Arteriovenous malformation", "Trauma", "Reversible cerebral vasoconstriction syndrome, dissection"],
 [("Migraine or thunderclap headache of other cause", "CT within 6 hours and, if negative, lumbar puncture excludes SAH"), ("Meningitis", "Fever, slower onset, CSF pleocytosis"), ("Reversible cerebral vasoconstriction syndrome", "Recurrent thunderclap headaches, normal CSF, multifocal constriction that resolves")],
 ["Immediate CT; lumbar puncture at 12 hours if CT negative; CTA once confirmed", "Secure the aneurysm within 24–72 hours by endovascular coiling or clipping; nimodipine for 21 days; maintain normovolemia", "Monitor for hydrocephalus (ventricular drain), vasospasm (Doppler, clinical) and hyponatremia"],
 [R("sp-subarachnoid-hemorrhage"), R("sp-cerebral-blood-supply"), R("sp-ischemic-stroke")], marker=structs("artery-acom", "artery-pcom-l", "artery-pcom-r"), imagingHint=hint("axial", 0, 5, -15, "basal cisterns around the circle of Willis"), preset="inferior"))

E.append(syn("syn-cerebral-venous-sinus-thrombosis", "Cerebral venous sinus thrombosis", "vascular", ["sinus-superior-sagittal", "sinus-transverse-sigmoid", "veins-superficial-cerebral", "vein-great-cerebral", "sinus-cavernous"], "bilateral",
 "A woman in the postpartum period, or on the combined contraceptive pill, develops a headache that builds over days and is worse lying flat, then has a focal seizure and weakness of one leg, and the fundi show swollen discs. CT shows a hemorrhagic lesion that does not fit an arterial territory, near the vertex; CT venography shows a filling defect in the superior sagittal sinus. Deep venous thrombosis produces bilateral thalamic swelling and coma; cavernous sinus thrombosis a painful ophthalmoplegia with proptosis.",
 [D("pain", "bilateral", "head", "Subacute progressive headache, worse lying down, with papilledema (raised pressure)", "sinus-superior-sagittal"), D("motor", "contralateral", "leg, or bilateral legs", "Focal deficits from venous infarcts, often parasagittal leg weakness, sometimes bilateral", "pathway-lateral-corticospinal"), D("other", "n/a", "cortex", "Focal or generalized seizures, far commoner than in arterial stroke", "veins-superficial-cerebral"), D("consciousness", "bilateral", "thalami (deep venous thrombosis)", "Drowsiness to coma with bilateral thalamic and basal ganglia edema", "vein-great-cerebral"), D("oculomotor", "ipsilateral", "cavernous sinus", "Painful ophthalmoplegia, proptosis and chemosis with cavernous sinus thrombosis", "sinus-cavernous")],
 "The dural venous sinuses drain the cerebral veins to the internal jugular veins: the superior sagittal sinus collects the superficial veins from the convexities, the great cerebral vein and straight sinus drain the deep structures, and the transverse and sigmoid sinuses carry both to the jugular bulb. Thrombosis of a sinus obstructs venous outflow from the region it drains without interrupting arterial inflow, so blood continues to arrive but cannot leave; capillary pressure rises, fluid leaks into the tissue, and the swollen, congested cortex is prone to seizures and to hemorrhage into the edematous tissue. These venous infarcts do not respect arterial territories, are often bilateral or parasagittal when the superior sagittal sinus is involved, since the veins of both leg areas drain into it, and can be hemorrhagic from the start. Occlusion of the sinus also blocks CSF absorption through the arachnoid granulations that project into it, so intracranial pressure rises with headache, papilledema and sixth nerve palsies even without infarction, a picture identical to idiopathic intracranial hypertension. Thrombosis of the deep system swells both thalami and produces coma, and thrombosis of the cavernous sinus, usually septic, involves the ocular motor nerves in its wall. Because the superior sagittal sinus drains both hemispheres, deficits are often bilateral, and when unilateral they are contralateral to the congested cortex, since the corticospinal fibers cross in the medulla. The clinical clue is a headache that has progressed over days in a patient with a prothrombotic state, and the diagnosis is made by imaging the veins, not the arteries.",
 [pathol("Venous sinus thrombosis", "MRV", "Absent flow in the superior sagittal, transverse or sigmoid sinus on MR or CT venography; the 'empty delta' sign on contrast CT; a hyperdense sinus or cortical vein (cord sign) on plain CT.", sequence="n/a"), pathol("Venous infarct", "MRI", "Parasagittal or temporal edema with petechial or frank hemorrhage not confined to an arterial territory; mixed restricted and facilitated diffusion.", sequence="FLAIR"), pathol("Thrombus signal", "MRI", "T1-bright subacute clot within the sinus and a blooming cortical vein on SWI.", sequence="SWI")],
 ["Pregnancy and puerperium, oral contraceptives", "Thrombophilia (factor V Leiden, antiphospholipid syndrome)", "Dehydration, malignancy, inflammatory bowel disease", "Local infection (otitis, mastoiditis, sinusitis) for lateral and cavernous sinuses", "Head injury, lumbar puncture, dural puncture"],
 [("Idiopathic intracranial hypertension", "Normal venography; no seizures or focal deficits"), ("Arterial stroke", "Abrupt onset, territorial infarct on DWI, no venous filling defect"), ("Meningitis or encephalitis", "Fever, CSF pleocytosis; may coexist")],
 ["CT or MR venography in any subacute headache with papilledema, seizures or atypical infarcts", "Anticoagulate with heparin even when the infarct is hemorrhagic; treat the underlying cause and any infection", "Endovascular thrombectomy or decompressive craniectomy for deterioration despite anticoagulation; antiepileptic drugs for seizures"],
 [R("sp-cerebral-venous-sinus-thrombosis"), R("sp-coronary-sinus-thrombosis"), R("sp-renal-vein-thrombosis")], marker=structs("sinus-superior-sagittal"), imagingHint=hint("sagittal", 0, -30, 60, "superior sagittal sinus at the vertex"), preset="superior"))

E.append(syn("syn-hemiballismus", "Hemiballismus", "vascular", ["subthalamic-nucleus", "globus-pallidus", "putamen", "thalamus"], "contralateral",
 "An elderly hypertensive or poorly controlled diabetic patient suddenly begins to fling one arm and leg in wide, violent, uncontrollable movements that continue while awake, exhaust the patient and may injure the limb. The movements involve the proximal joints, look like throwing, and stop in sleep. Strength, sensation and cognition are normal. Over weeks the flinging usually subsides into a milder chorea and then resolves.",
 [D("other", "contralateral", "arm and leg, proximal", "Large-amplitude flinging (ballistic) movements of one side of the body", "subthalamic-nucleus"), D("motor", "n/a", "preserved", "No weakness, spasticity or reflex change", "pathway-lateral-corticospinal"), D("other", "contralateral", "face (sometimes)", "Facial and lingual involvement with grimacing in some", "subthalamic-nucleus")],
 "The subthalamic nucleus is the only excitatory nucleus in the basal ganglia loop: it receives inhibition from the external pallidum and drives the internal pallidum and substantia nigra reticulata, which in turn inhibit the motor thalamus. Its output is the brake in the indirect pathway that suppresses unwanted movement. A small infarct or hemorrhage that destroys the nucleus on one side removes that excitatory drive, so the internal pallidum falls silent, the ventral lateral thalamus is released from inhibition and fires excessively on the motor and premotor cortex, which discharges the flinging, involuntary movements. The basal ganglia loops of each hemisphere serve the contralateral body through the corticospinal tract, which crosses in the medulla, so a right subthalamic lesion produces left hemiballismus. The movements are not weakness, because the corticospinal system is intact, and they cease in sleep because cortical drive falls. The subthalamic nucleus is supplied by perforators from the posterior communicating and posterior cerebral arteries and is a typical site for hypertensive lacunes and small hemorrhages; nonketotic hyperglycemia produces the same syndrome from striatal dysfunction, with a characteristic T1-bright putamen on MRI. Lesions of the striatum, the pallidum or the thalamus can also cause hemichorea-hemiballismus, and dopamine-blocking drugs help by reducing the thalamocortical overactivity. Spontaneous recovery is the rule as the remaining circuit adapts.",
 [pathol("Subthalamic lacunar infarct or hemorrhage", "MRI", "Small area of restricted diffusion or hemorrhage in the contralateral subthalamic nucleus, below the thalamus and above the substantia nigra on coronal images.", sequence="DWI"), pathol("Nonketotic hyperglycemic hemichorea", "MRI", "T1 hyperintensity of the contralateral putamen and caudate without diffusion restriction, resolving with glucose control.", sequence="T1"), pathol("Other basal ganglia lesion", "MRI", "Striatal or pallidal infarct, tumor or demyelination on the side opposite the movements.", sequence="FLAIR")],
 ["Lacunar infarct of the subthalamic nucleus", "Small hypertensive hemorrhage", "Nonketotic hyperglycemia", "Striatal or thalamic infarct", "Tumor, demyelination, HIV toxoplasmosis (bilateral or unilateral)"],
 [("Focal motor seizure", "Rhythmic, brief, with impaired awareness or spread; EEG"), ("Hemichorea from Huntington or Sydenham chorea", "Bilateral over time, family history or streptococcal illness, smaller amplitude"), ("Tardive dyskinesia", "Orofacial, bilateral, history of dopamine blockers")],
 ["MRI and glucose; correct hyperglycemia", "Dopamine-depleting or blocking drugs (tetrabenazine, haloperidol, risperidone) taper as the movements subside", "Protect the limb; deep brain stimulation or pallidotomy for rare persistent cases"],
 [R("sp-hemiballismus"), R("sp-cerebral-blood-supply"), R("sp-ischemic-stroke")], marker=structs("subthalamic-nucleus-r"), imagingHint=hint("coronal", 12, -12, -6, "subthalamic nucleus beneath the thalamus"), preset="anterior", eponyms=["hemichorea-hemiballismus"]))

E.append(syn("syn-parkinsonism", "Parkinsonism", "degenerative", ["substantia-nigra", "putamen", "globus-pallidus", "subthalamic-nucleus", "thalamus-va-vl"], "bilateral",
 "A patient in their sixties has noticed that one hand shakes at rest, stops shaking when they reach for a cup, and that handwriting has become small and cramped; a spouse says the face has lost its expression and the voice its volume. Examination finds a resting tremor at four to six cycles per second, cogwheel rigidity that appears when the other arm is moved, slow and decrementing finger tapping, a stooped posture with a shuffling gait and reduced arm swing on the affected side, and a tendency to fall backward when pulled.",
 [D("other", "bilateral", "limbs, asymmetric onset", "Bradykinesia: slow, small, decrementing repetitive movements; hypomimia, micrographia, hypophonia", "pathway-basal-ganglia-loops"), D("other", "bilateral", "limbs and neck", "Rigidity (lead-pipe, with cogwheeling when tremor coexists)", "substantia-nigra"), D("other", "bilateral", "hands, asymmetric", "Rest tremor at 4–6 Hz, pill-rolling, suppressed by movement", "thalamus-va-vl"), D("gait", "bilateral", "gait and posture", "Shuffling festinating gait, stooped posture, freezing, postural instability with retropulsion", "pathway-basal-ganglia-loops"), D("autonomic", "bilateral", "diffuse", "Constipation, orthostatic hypotension, urinary urgency, anosmia and REM sleep behavior disorder, often preceding motor signs", "pathway-olfactory")],
 "The dopaminergic neurons of the substantia nigra pars compacta project to the striatum, where dopamine facilitates the direct pathway through D1 receptors and inhibits the indirect pathway through D2 receptors, tilting the balance of the basal ganglia loops toward the release of movement. When more than half of these neurons have died, the direct pathway weakens and the indirect pathway is disinhibited, the subthalamic nucleus and internal pallidum become overactive, and the ventral lateral and ventral anterior thalamus are held under excessive inhibition, so the motor cortex receives too little thalamic drive: movements become small, slow and infrequent (bradykinesia), and the postural and locomotor programs of the brainstem are under-recruited, giving the stooped posture, shuffling gait and loss of postural reflexes. The abnormal synchronous oscillations of the pallidothalamic circuit that appear when dopamine is lost are relayed to the cortex as the rest tremor, which is suppressed when voluntary movement resets the circuit, and the rigidity reflects enhanced long-latency stretch reflexes. Each hemisphere's loop controls the contralateral body through the crossed corticospinal projection, so the asymmetric neuronal loss of Parkinson disease produces signs that begin on one side, opposite the more affected nigra, and remain asymmetric. The corticospinal tract itself is intact, so strength and reflexes are normal and the plantars are flexor. Lewy body pathology starts in the olfactory bulb, dorsal vagal nucleus and locus coeruleus years before it reaches the nigra, which explains the premotor anosmia, constipation and REM sleep behavior disorder. Symmetric onset, early falls, early dementia, ophthalmoplegia, marked autonomic failure or a poor levodopa response point to the atypical parkinsonian syndromes, and drugs that block dopamine receptors produce a symmetric reversible form.",
 [pathol("Parkinson disease", "MRI", "Usually normal; loss of the dorsolateral nigral hyperintensity ('swallow tail') on high-resolution SWI, and neuromelanin loss on specialized sequences. MRI is done to exclude structural mimics.", sequence="SWI"), pathol("Dopamine transporter imaging", "SPECT", "Reduced striatal uptake, asymmetric and worse in the putamen, in Parkinson disease and the atypical degenerations; normal in essential tremor and drug-induced parkinsonism.", sequence="n/a"), pathol("Atypical parkinsonism", "MRI", "Midbrain atrophy ('hummingbird' sign) in progressive supranuclear palsy; putaminal rim and pontine 'hot cross bun' in multiple system atrophy; asymmetric cortical atrophy in corticobasal degeneration.", sequence="T2"), pathol("Vascular parkinsonism", "MRI", "Extensive white matter disease and basal ganglia lacunes with lower-body predominant signs.", sequence="FLAIR")],
 ["Parkinson disease (Lewy body)", "Drug-induced (antipsychotics, metoclopramide, valproate)", "Multiple system atrophy, progressive supranuclear palsy, corticobasal degeneration, dementia with Lewy bodies", "Vascular parkinsonism", "Normal pressure hydrocephalus, Wilson disease (young), carbon monoxide or manganese toxicity"],
 [("Essential tremor", "Action and postural tremor, no bradykinesia or rigidity, often familial and alcohol-responsive"), ("Normal pressure hydrocephalus", "Gait and bladder first, ventriculomegaly, tap response"), ("Depression or hypothyroidism", "Slowing without rigidity or tremor"), ("Dystonic tremor", "Irregular, position-dependent, with dystonic posturing")],
 ["Clinical diagnosis: bradykinesia plus tremor or rigidity, asymmetric, with a clear levodopa response; review drugs", "Levodopa is the most effective therapy; dopamine agonists and MAO-B inhibitors in younger patients; physiotherapy and exercise throughout", "Deep brain stimulation of the subthalamic nucleus or internal pallidum for motor fluctuations and dyskinesias"],
 [R("sp-parkinsonism"), R("sp-parkinson-disease"), R("sp-parkinson-plus-syndrome")], marker=structs("substantia-nigra-l", "substantia-nigra-r"), imagingHint=hint("axial", 0, -20, -15, "substantia nigra in the midbrain"), preset="inferior", eponyms=["Parkinson disease", "paralysis agitans"]))

E.append(syn("syn-wernicke-korsakoff", "Wernicke encephalopathy and Korsakoff syndrome", "metabolic-toxic", ["mammillary-body", "thalamus-mediodorsal", "thalamus-anterior-nuclei", "periaqueductal-grey", "hypothalamus", "cerebellar-vermis"], "bilateral",
 "A malnourished alcoholic, or a patient after bariatric surgery or with hyperemesis, is brought in confused and unsteady, and is found to have nystagmus and an inability to abduct either eye. Given glucose without thiamine, the confusion deepens. After treatment the ophthalmoplegia clears within hours and the gait improves over weeks, but the patient is left unable to form new memories, reciting invented explanations for the gaps and unconcerned by them: Korsakoff psychosis.",
 [D("cognitive", "bilateral", "global then memory", "Acute confusion, inattention and apathy (Wernicke); dense anterograde amnesia with confabulation and preserved intelligence (Korsakoff)", "thalamus-mediodorsal"), D("oculomotor", "bilateral", "abducens, gaze", "Nystagmus, bilateral sixth nerve palsies, conjugate gaze palsies, rarely complete ophthalmoplegia", "abducens-nucleus"), D("gait", "bilateral", "trunk and legs", "Wide-based ataxic gait from the anterior vermis and vestibular nuclei; limbs relatively spared", "cerebellar-vermis"), D("autonomic", "bilateral", "hypothalamus", "Hypothermia, hypotension, tachycardia", "hypothalamus"), D("consciousness", "bilateral", "diffuse", "Stupor and coma if untreated", "reticular-formation")],
 "Thiamine is a cofactor for the enzymes of glucose metabolism, and the periventricular structures around the third and fourth ventricles and the aqueduct have the highest thiamine turnover; when the vitamin runs out, especially when a glucose load suddenly increases demand, these regions suffer a symmetric, bilateral, non-inflammatory injury with petechial hemorrhage. The affected structures explain each sign: the abducens and vestibular nuclei and the periaqueductal gray beneath the fourth ventricle and aqueduct account for the nystagmus and the bilateral sixth nerve and gaze palsies; the anterior vermis and the vestibular nuclei for the gait ataxia; the hypothalamus around the third ventricle for the hypothermia and autonomic instability; and the medial thalamus and reticular formation for the confusion and stupor. Because the process is symmetric and midline, there are no crossed or lateralized signs, and the triad is often incomplete, so the diagnosis must be considered in any confused malnourished patient. The mammillary bodies and the mediodorsal and anterior thalamic nuclei are stations of the Papez circuit through which the hippocampus consolidates new memories via the fornix and mammillothalamic tract, and their destruction, which is not reversed by treatment, leaves the isolated anterograde amnesia of Korsakoff syndrome: the patient cannot lay down new memories although remote memory, attention and reasoning survive, and fills the gaps with confabulation. Early thiamine reverses the eye signs within hours and prevents the amnesia; delay makes it permanent.",
 [pathol("Wernicke encephalopathy", "MRI", "Symmetric FLAIR and T2 hyperintensity of the medial thalami, mammillary bodies, periaqueductal gray, tectum and around the third ventricle, sometimes enhancing; restricted diffusion acutely.", sequence="FLAIR", pitfalls="Normal MRI does not exclude the diagnosis; treat on suspicion"), pathol("Korsakoff syndrome", "MRI", "Atrophy of the mammillary bodies and medial thalami on coronal T1 in the chronic stage.", sequence="T1"), pathol("Alcoholic cerebellar degeneration", "MRI", "Atrophy of the anterior superior vermis.", sequence="T1")],
 ["Chronic alcoholism with malnutrition", "Bariatric surgery, prolonged vomiting (hyperemesis gravidarum), starvation", "Parenteral nutrition or glucose without thiamine", "Malabsorption, dialysis, malignancy"],
 [("Alcohol withdrawal delirium", "Tremor, agitation, hallucinations, autonomic overactivity without ophthalmoplegia; may coexist"), ("Hepatic encephalopathy", "Asterixis, raised ammonia, no eye signs"), ("Top of the basilar stroke", "Abrupt onset, vertical gaze palsy, pupillary signs, DWI positive"), ("Miller Fisher syndrome", "Ophthalmoplegia with ataxia and areflexia after infection, no confusion")],
 ["Give high-dose parenteral thiamine immediately, before any glucose, to any patient at risk with confusion, ataxia or eye signs; do not wait for imaging or levels", "Correct magnesium, which is required for thiamine to work; treat withdrawal", "Continue thiamine and nutritional rehabilitation; Korsakoff amnesia recovers only partly"],
 [R("sp-wernicke-encephalopathy")], marker=structs("mammillary-body-l", "mammillary-body-r", "thalamus-mediodorsal-l", "thalamus-mediodorsal-r"), imagingHint=hint("coronal", 0, -8, -10, "mammillary bodies and medial thalami around the third ventricle"), preset="anterior", eponyms=["Wernicke–Korsakoff syndrome"]))

E.append(syn("syn-pituitary-mass", "Pituitary mass lesion", "neoplastic", ["pituitary-infundibulum", "optic-chiasm", "sinus-cavernous", "hypothalamus", "artery-internal-carotid"], "bilateral",
 "A patient presents with a hormone syndrome, with visual loss, or with an incidental finding on a scan. A young woman has amenorrhea and galactorrhea from prolactin; a middle-aged man notices his rings and shoes no longer fit; another patient is tired, cold and has lost body hair as the normal gland is crushed. When the tumor reaches the chiasm the temporal fields go, and when it invades the cavernous sinus the eye movements fail. A sudden headache with visual collapse and ophthalmoplegia means the tumor has bled.",
 [D("other", "n/a", "endocrine", "Hypersecretion (prolactin, growth hormone, ACTH) or hypopituitarism from compression of the normal gland", "pituitary-infundibulum"), D("visual-field", "bilateral", "temporal fields", "Bitemporal hemianopia from chiasmal compression, superior quadrants first", "pathway-visual"), D("oculomotor", "ipsilateral", "III, IV, VI", "Ocular motor palsies from lateral extension into the cavernous sinus", "sinus-cavernous"), D("pain", "bilateral", "head", "Headache from dural stretching; thunderclap headache with apoplexy", "dura-mater"), D("autonomic", "bilateral", "hypothalamus", "Diabetes insipidus and hypothalamic dysfunction with suprasellar extension (mostly craniopharyngioma)", "hypothalamus")],
 "The pituitary gland sits in the sella turcica, roofed by the diaphragma sellae, with the optic chiasm about a centimeter above the diaphragm, the cavernous sinuses and their carotid arteries and ocular motor nerves on either side, the sphenoid sinus below and the hypothalamus above through the stalk. A tumor of the anterior gland grows within this box, and its clinical expression is determined by what it secretes and by which neighbor it reaches. Hormonal effects come first: prolactin-secreting adenomas cause amenorrhea, galactorrhea and, in men, hypogonadism; growth hormone causes acromegaly; ACTH causes Cushing disease; and a large non-functioning tumor compresses the normal gland, so that the trophic hormones fail in a characteristic order, gonadotropins and growth hormone first, then thyroid and finally adrenal. Growth upward pushes the diaphragma and reaches the chiasm from below, compressing the crossing fibers from the inferior nasal retinae that carry the superior temporal fields, so the bitemporal hemianopia starts in the upper quadrants; because the chiasm is midline and both sets of crossing fibers are involved, the field loss is bilateral. Lateral growth invades the cavernous sinus and involves the uncrossed nerves in its wall, producing ipsilateral ophthalmoplegia. Hemorrhage or infarction of a tumor, pituitary apoplexy, expands the mass within hours, causing sudden headache, visual loss, ophthalmoplegia and acute adrenal insufficiency, which is life-threatening. Stalk compression by any mass raises prolactin modestly by removing dopaminergic inhibition, so a mildly raised prolactin does not prove a prolactinoma.",
 [pathol("Pituitary adenoma", "MRI", "Sellar mass enhancing less than the normal gland on dynamic post-contrast T1, expanding the sella, elevating the chiasm and displacing the stalk; microadenomas under 10 mm, macroadenomas above.", sequence="T1+Gd"), pathol("Cavernous sinus invasion", "MRI", "Tumor encasing more than two-thirds of the cavernous carotid (Knosp grade) on coronal images.", sequence="T1+Gd"), pathol("Pituitary apoplexy", "MRI", "Hemorrhage or infarction within an adenoma with fluid levels, T1 shortening and sudden enlargement; hyperdense on CT.", sequence="T1"), pathol("Craniopharyngioma", "CT", "Cystic, calcified suprasellar mass in a child or older adult, often with hydrocephalus.", sequence="CT non-contrast")],
 ["Pituitary adenoma (prolactinoma, non-functioning, somatotroph, corticotroph)", "Craniopharyngioma", "Rathke cleft cyst", "Meningioma, metastasis, lymphocytic hypophysitis", "Pituitary apoplexy (Sheehan syndrome postpartum)"],
 [("Chiasmal glioma or meningioma", "Arises above the sella; normal gland seen separately"), ("Internal carotid aneurysm", "Flow void on MRI, pulsatile; never biopsy"), ("Physiological enlargement", "Pregnancy, adolescence, primary hypothyroidism; homogeneous gland without a discrete lesion")],
 ["Full pituitary hormone profile, formal perimetry and MRI of the sella", "Dopamine agonists for prolactinomas; transsphenoidal surgery for other tumors compressing the chiasm or secreting hormones; radiotherapy for residual disease", "Apoplexy: immediate hydrocortisone, then urgent decompression if vision or eye movements are affected; lifelong replacement for hypopituitarism"],
 [R("sp-pituitary-adenoma"), R("sp-pituitary-apoplexy"), R("sp-pituitary-gland")], marker=structs("pituitary-gland"), imagingHint=hint("coronal", 0, 2, -28, "pituitary gland in the sella beneath the chiasm"), preset="anterior"))

write(E)
