import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).parent))
from synlib import *
E = []

def mono(id, name, cat, structures, presentation, deficits, reasoning, imaging, causes, mimics, mgmt, cites, marker, hint_, eponyms=(), preset="anterior", exam=None):
    return syn(id, name, cat, structures, "ipsilateral", presentation, deficits, reasoning, imaging, causes, mimics, mgmt, cites, marker=marker, imagingHint=hint_, eponyms=eponyms, preset=preset, exam=exam)

EMG = lambda txt: pathol("Nerve conduction and EMG", "EMG/NCS", txt, sequence="n/a")

E.append(mono("syn-erb-duchenne", "Upper brachial plexus palsy (Erb–Duchenne)", "plexopathy", ["plexus-brachial", "roots-c5-t1", "nerve-axillary", "nerve-musculocutaneous", "nerve-suprascapular"],
 "After a difficult delivery with shoulder dystocia, or a motorcycle crash in which the shoulder was forced down while the head went the other way, the arm hangs limp at the side, rotated inward with the elbow straight and the forearm pronated, the wrist and fingers flexed: the 'waiter's tip'. The hand grips normally. Sensation is reduced over the outer shoulder and the lateral forearm, and the biceps and brachioradialis reflexes are absent.",
 [D("motor", "ipsilateral", "shoulder abductors and external rotators, elbow flexors, supinator", "Weak deltoid, supraspinatus, infraspinatus, biceps, brachialis, brachioradialis; arm adducted, internally rotated, extended and pronated", "plexus-brachial"), D("sensory-light-touch", "ipsilateral", "lateral arm and forearm (C5–C6)", "Sensory loss over the deltoid and radial forearm", "roots-c5-t1"), D("reflex", "ipsilateral", "biceps and brachioradialis", "Absent C5–C6 reflexes; triceps preserved", "roots-c5-t1"), D("motor", "n/a", "hand", "Hand and finger function preserved (C8–T1 intact)", "nerve-median")],
 "Forcing the head and shoulder apart stretches the upper part of the brachial plexus, the C5 and C6 roots and the upper trunk they form, while the lower roots are protected by their more horizontal course. The upper trunk gives the suprascapular nerve to the supraspinatus and infraspinatus, and its fibers continue into the lateral cord to the musculocutaneous nerve for the elbow flexors and into the posterior cord to the axillary nerve for the deltoid and teres minor; C5–C6 fibers also reach the brachioradialis and supinator through the radial nerve. Their loss paralyzes shoulder abduction and external rotation, elbow flexion and supination, and the intact antagonists supplied by C7–T1 pull the limb into the characteristic adducted, internally rotated, extended and pronated posture. The C5 and C6 dermatomes cover the lateral shoulder, arm and forearm, so the sensory loss follows them, and the biceps and brachioradialis reflex arcs, which run through C5–C6, are lost while the C7 triceps jerk survives. The lesion is peripheral and uncrossed, so everything is ipsilateral. Whether the roots are avulsed from the cord (preganglionic, no recovery possible, with a Horner if T1 is also torn) or the trunk is stretched (postganglionic, recovery possible) is the crucial prognostic question: preserved sensory nerve action potentials in an anesthetic area show that the dorsal root ganglion is still connected to the periphery and the lesion is preganglionic.",
 [pathol("Plexus stretch injury", "MRI", "Edema and T2 hyperintensity of the C5–C6 roots and upper trunk on MR neurography; pseudomeningoceles at the foramina indicate root avulsion.", sequence="STIR"), pathol("Root avulsion", "CT", "CT myelography showing contrast-filled pseudomeningoceles and absent rootlets at C5–C6.", sequence="CT contrast"), EMG("Denervation in C5–C6 muscles with preserved lateral antebrachial cutaneous sensory responses in avulsion (preganglionic) or absent responses in trunk lesions (postganglionic).")],
 ["Obstetric shoulder dystocia", "Motorcycle and traction injuries", "Rucksack (pack) palsy", "Radiation plexopathy (upper trunk)", "Brachial neuritis"],
 [("C5–C6 radiculopathy", "Neck pain, usually one root, paraspinal denervation"), ("Axillary nerve injury alone", "Deltoid only, elbow flexion normal"), ("Rotator cuff tear", "Pain and weakness of abduction without sensory loss or reflex change")],
 ["Physiotherapy to prevent contractures; most obstetric palsies recover within months", "EMG at 3–4 weeks and MRI to define avulsion; nerve grafting or transfers if no biceps recovery by 3–6 months", "Late tendon transfers for fixed deficits"],
 [R("sp-erb-palsy"), R("sp-spinal-nerves"), R("sp-peripheral-nerve-injury")], nerve("brachial-plexus-l"), hint("coronal", -60, -20, -40, "upper trunk of the brachial plexus"), eponyms=["Erb palsy", "waiter's tip deformity"]))

E.append(mono("syn-klumpke", "Lower brachial plexus palsy (Klumpke)", "plexopathy", ["plexus-brachial", "roots-c5-t1", "nerve-ulnar", "nerve-median", "cervical-sympathetic-chain"],
 "A patient who grabbed a branch while falling, or a baby delivered with the arm pulled upward, has a claw hand: the fingers cannot be spread or brought together, the small hand muscles are wasted, and grip is weak, while the shoulder and elbow work. Sensation is absent along the inner forearm and the little finger. A drooping lid and small pupil on the same side mean the T1 root has been torn from the cord.",
 [D("motor", "ipsilateral", "intrinsic hand muscles, long finger flexors", "Claw hand with weak grip; wasting of the thenar, hypothenar and interossei; wrist flexion weak", "plexus-brachial"), D("sensory-light-touch", "ipsilateral", "medial forearm, medial hand and little finger (C8–T1)", "Sensory loss along the ulnar border of the forearm and hand", "roots-c5-t1"), D("autonomic", "ipsilateral", "eye", "Horner syndrome when the T1 root is avulsed", "pathway-oculosympathetic"), D("motor", "n/a", "shoulder and elbow", "Proximal muscles preserved", "nerve-axillary")],
 "Traction on the abducted arm stretches the lower roots of the plexus, C8 and T1, and the lower trunk they form. These fibers pass through the medial cord into the ulnar nerve for the interossei, the hypothenar muscles and the medial long finger flexors, and into the median nerve for the thenar muscles and the lateral finger flexors, so all the intrinsic muscles and the finger flexors fail together: the unopposed extensors and the loss of lumbrical action produce the claw posture, and grip is lost. The shoulder and elbow muscles, supplied from C5–C7 through the upper and middle trunks, are unaffected. The C8 and T1 dermatomes cover the medial forearm and the ulnar side of the hand, so sensory loss lies there; involvement of the medial forearm distinguishes a lower plexus lesion from an ulnar neuropathy, whose sensory territory stops at the wrist. The preganglionic sympathetic fibers for the eye leave the cord in the T1 root and pass through the stellate ganglion, so avulsion of the root also produces a Horner syndrome on the same side, a sign that the injury is at the cord and cannot be repaired. All signs are ipsilateral since the plexus is a peripheral structure. Chronic compression of the lower trunk by a cervical rib or fibrous band produces the same pattern slowly as neurogenic thoracic outlet syndrome, and infiltration by an apical lung tumor produces it with pain and a Horner.",
 [pathol("Lower trunk injury or avulsion", "MRI", "T2 hyperintensity of the C8–T1 roots and lower trunk on MR neurography; pseudomeningocele at T1 with avulsion.", sequence="STIR"), pathol("Apical lung (Pancoast) tumor", "CT", "Apical mass invading the lower trunk and stellate ganglion in adults with painful progressive lower plexopathy.", sequence="CT contrast"), EMG("Denervation in C8–T1 muscles of both ulnar and median territories; medial antebrachial cutaneous sensory response absent in postganglionic lesions, preserved in avulsion.")],
 ["Traction injury with the arm abducted", "Obstetric injury (rare, usually with the whole plexus)", "Pancoast tumor", "Cervical rib and neurogenic thoracic outlet syndrome", "Metastatic infiltration"],
 [("Ulnar neuropathy at the elbow", "Sensory loss spares the medial forearm; median-innervated thenar muscles are normal"), ("C8 radiculopathy", "Neck pain, paraspinal denervation, no Horner"), ("Combined median and ulnar neuropathy", "Sensory loss follows nerve territories, sparing the forearm")],
 ["Look for a Horner and image the lung apex in adult lower plexopathy", "EMG to define the level; surgical exploration if no recovery", "Hand therapy and splinting for the claw deformity"],
 [R("sp-klumpke-palsy"), R("sp-spinal-nerves"), R("sp-peripheral-nerve-injury")], nerve("brachial-plexus-l"), hint("coronal", -55, -25, -60, "lower trunk of the brachial plexus over the first rib"), eponyms=["Klumpke palsy", "Dejerine–Klumpke palsy"]))

E.append(mono("syn-neurogenic-thoracic-outlet", "Neurogenic thoracic outlet syndrome", "entrapment", ["plexus-brachial", "roots-c5-t1", "nerve-ulnar", "nerve-median"],
 "A young adult with a long neck notices slowly progressive wasting of the thumb side of the hand, aching in the inner forearm and tingling of the little and ring fingers, worse with the arm raised. Examination shows the Gilliatt–Sumner hand: marked wasting of the abductor pollicis brevis with milder involvement of the hypothenar and interosseous muscles, and sensory loss along the medial forearm. A neck X-ray shows a cervical rib or an elongated C7 transverse process.",
 [D("motor", "ipsilateral", "thenar (abductor pollicis brevis) more than hypothenar and interossei", "Wasting and weakness of the intrinsic hand muscles, thenar worst", "plexus-brachial"), D("sensory-light-touch", "ipsilateral", "medial forearm and ulnar hand (T1 > C8)", "Sensory loss and paresthesias along the medial forearm and little finger", "roots-c5-t1"), D("pain", "ipsilateral", "medial arm and forearm", "Aching pain worse with arm elevation and carrying", "plexus-brachial")],
 "The lower trunk of the brachial plexus crosses the first rib behind the scalenus anterior, and in a minority of people a cervical rib or a fibrous band from an elongated C7 transverse process to the first rib lifts and angulates the trunk, stretching the T1 fibers most because they lie lowest and are draped most tightly over the band. The T1 root contributes most of the fibers for the abductor pollicis brevis, so the thenar wasting exceeds that of the hypothenar and interossei, which have a larger C8 contribution, a distribution that no single nerve lesion produces: it is more thenar than an ulnar neuropathy and involves the interossei and the medial forearm unlike a carpal tunnel syndrome. Sensory loss follows the T1 dermatome along the medial forearm and the C8 dermatome on the ulnar hand, and the medial antebrachial cutaneous nerve conduction is reduced, which is the most sensitive electrodiagnostic finding. All signs are ipsilateral to the band. True neurogenic thoracic outlet syndrome is rare; the far commoner 'disputed' form consists of arm pain and paresthesias without objective deficit, and vascular forms compress the subclavian vessels rather than the plexus, so an objective neurological deficit with the characteristic hand is the requirement for the diagnosis and for surgery.",
 [pathol("Cervical rib or band", "CT", "Cervical rib or elongated C7 transverse process; a fibrous band is not seen but inferred. MR neurography may show the angulated lower trunk.", sequence="CT non-contrast"), EMG("Reduced medial antebrachial cutaneous sensory response and reduced median motor amplitude with preserved median sensory response; denervation in the abductor pollicis brevis and first dorsal interosseous."), pathol("Subclavian compression (vascular forms)", "CTA", "Subclavian artery stenosis or aneurysm with arm elevation, or venous thrombosis (Paget–Schroetter).")],
 ["Cervical rib with a fibrous band", "Elongated C7 transverse process with a band", "Scalene muscle anomalies", "Callus from a clavicle fracture"],
 [("Ulnar neuropathy at the elbow", "Thenar spared, forearm sensation spared, slowing across the elbow"), ("Carpal tunnel syndrome", "Sensory loss on the palmar thumb and index, no interosseous or forearm involvement"), ("C8–T1 radiculopathy", "Neck pain, paraspinal denervation"), ("Motor neuron disease", "No sensory loss, fasciculations, spreads beyond one limb")],
 ["Confirm electrodiagnostically before surgery; X-ray and CT of the thoracic outlet", "Resection of the cervical rib and band, or first rib, for objective neurogenic deficit", "Physiotherapy and posture correction for disputed forms"],
 [R("sp-thoracic-outlet-syndrome"), R("sp-brachial-plexus-2")], nerve("brachial-plexus-l"), hint("coronal", -55, -25, -60, "lower trunk over the first rib"), eponyms=["Gilliatt–Sumner hand"]))

E.append(mono("syn-carpal-tunnel", "Carpal tunnel syndrome", "entrapment", ["nerve-median", "plexus-brachial"],
 "A middle-aged woman wakes at night with numb, painful hands that she shakes to relieve, and drops small objects during the day. Tingling involves the thumb, index and middle fingers and the radial half of the ring finger but spares the little finger and the palm; the thenar eminence is wasted in advanced cases and thumb abduction is weak. Tapping the wrist (Tinel) or holding it flexed (Phalen) reproduces the tingling.",
 [D("sensory-light-touch", "ipsilateral", "palmar thumb, index, middle and radial ring finger", "Nocturnal paresthesias and later sensory loss in the median digital distribution, sparing the thenar palm", "nerve-median"), D("motor", "ipsilateral", "abductor pollicis brevis, opponens pollicis", "Thenar wasting and weak thumb abduction and opposition; long flexors spared", "nerve-median"), D("pain", "ipsilateral", "wrist, sometimes forearm and shoulder", "Aching pain radiating proximally", "nerve-median")],
 "The median nerve enters the hand beneath the flexor retinaculum in the carpal tunnel together with the nine flexor tendons, and any increase in the contents or decrease in the space of the tunnel compresses it: tenosynovitis, fluid retention in pregnancy, hypothyroidism, acromegaly, amyloid, diabetes and repetitive wrist flexion. Compression damages the large myelinated fibers first, producing paresthesias that are worst at night when the wrist flexes during sleep and venous congestion rises. The palmar cutaneous branch leaves the nerve above the tunnel and passes over the retinaculum, so sensation over the thenar eminence is spared, a point that separates carpal tunnel syndrome from a proximal median lesion or a C6–C7 radiculopathy. The motor branch to the thenar muscles arises within or just beyond the tunnel, so the abductor pollicis brevis and opponens waste while the flexor pollicis longus and the pronator, supplied in the forearm, are normal; the first two lumbricals are also affected but are hard to test. The lesion is peripheral and ipsilateral, and though it is often bilateral, one hand usually dominates. Nerve conduction shows slowing across the wrist with normal forearm conduction, which confirms the site. Sensory symptoms that include the little finger, the forearm, or weakness of the finger flexors point elsewhere.",
 [EMG("Prolonged median distal sensory and motor latencies across the wrist with normal ulnar values; denervation of the abductor pollicis brevis in severe cases."), pathol("Median nerve compression", "US", "Enlarged cross-sectional area of the median nerve proximal to the tunnel (above about 10 mm²) with flattening beneath the retinaculum.", sequence="n/a"), pathol("Space-occupying lesion in the tunnel", "MRI", "Ganglion, tenosynovitis, amyloid or anomalous muscle within the carpal tunnel in atypical cases.", sequence="T2")],
 ["Idiopathic (often bilateral, middle-aged women)", "Pregnancy, hypothyroidism, diabetes, acromegaly, rheumatoid arthritis", "Repetitive wrist use", "Amyloidosis and dialysis", "Wrist fracture"],
 [("C6–C7 radiculopathy", "Neck pain, sensory loss including the forearm and thenar palm, reflex change, normal distal latencies"), ("Pronator syndrome (proximal median)", "Thenar palm numb, forearm pain, flexor pollicis longus weak"), ("Polyneuropathy", "Bilateral, symmetric, feet involved, sural response abnormal"), ("Thoracic outlet syndrome", "Medial forearm sensory loss and interosseous weakness")],
 ["Night splints and activity modification; treat the underlying condition", "Corticosteroid injection into the tunnel for temporary relief", "Surgical release for persistent symptoms, sensory loss or thenar wasting"],
 [R("sp-carpal-tunnel-syndrome"), R("sp-electrodiagnostic-evaluation-of-carpal-tunnel-syndrome"), R("sp-peripheral-nerve-injury")], nerve("median-nerve-l"), hint("axial", -60, -30, -200, "median nerve at the wrist (virtual)"), eponyms=[]))

E.append(mono("syn-cubital-tunnel", "Ulnar neuropathy at the elbow", "entrapment", ["nerve-ulnar", "plexus-brachial"],
 "A patient who leans on the elbow at a desk, or who had an elbow fracture years ago, has numbness of the little finger and the ulnar half of the ring finger on both the palmar and dorsal surfaces, weakness of finger spreading, and a hand that is wasted between the thumb and index finger. The ring and little fingers curl into a claw; when pinching a sheet of paper the thumb flexes at its tip (Froment sign). Tapping behind the medial epicondyle sends tingling into the little finger.",
 [D("sensory-light-touch", "ipsilateral", "little finger, ulnar half of the ring finger, dorsal and palmar ulnar hand", "Sensory loss in the ulnar territory including the dorsum of the hand; forearm spared", "nerve-ulnar"), D("motor", "ipsilateral", "interossei, hypothenar, adductor pollicis, medial lumbricals, flexor digitorum profundus to the ring and little fingers", "Weak finger abduction and adduction, wasting of the first dorsal interosseous, Froment sign, ulnar claw of the ring and little fingers, Wartenberg sign", "nerve-ulnar"), D("pain", "ipsilateral", "medial elbow", "Aching at the elbow with Tinel sign in the ulnar groove", "nerve-ulnar")],
 "The ulnar nerve passes behind the medial epicondyle in the ulnar groove and then beneath the aponeurosis between the two heads of the flexor carpi ulnaris (the cubital tunnel), where it is superficial, tethered and stretched by elbow flexion and compressed by leaning; a previous fracture, arthritis or a shallow groove that lets the nerve dislocate adds to the injury. All the ulnar-innervated muscles lie distal to the elbow, so an elbow lesion weakens the flexor carpi ulnaris and the ulnar half of the flexor digitorum profundus as well as the hand intrinsics, whereas a lesion at the wrist (Guyon's canal) spares the forearm muscles and, depending on the site, the sensory branches. The dorsal cutaneous branch leaves the nerve several centimeters above the wrist, so dorsal ulnar hand sensation is lost with an elbow lesion but spared with a wrist lesion, and the medial forearm, supplied by the medial antebrachial cutaneous nerve from the plexus, is spared with any ulnar lesion, which distinguishes it from a C8 root or lower trunk lesion. The claw posture is produced by paralysis of the medial two lumbricals and interossei, which normally flex the knuckles and extend the fingers, and it is paradoxically less severe in high lesions because the paralyzed profundus no longer flexes the fingertips (the ulnar paradox). Froment sign reflects substitution of the median flexor pollicis longus for the paralyzed adductor pollicis. The lesion is peripheral and ipsilateral; conduction slowing or block across the elbow confirms the site.",
 [EMG("Slowing of ulnar motor conduction or conduction block across the elbow segment with normal forearm and wrist conduction; denervation in the first dorsal interosseous and flexor carpi ulnaris; dorsal ulnar cutaneous response reduced."), pathol("Nerve enlargement at the elbow", "US", "Swollen hypoechoic ulnar nerve in the groove or beneath the cubital tunnel aponeurosis, with subluxation on flexion in some.", sequence="n/a"), pathol("Elbow deformity or mass", "MRI", "Old fracture, arthritis, ganglion or accessory anconeus compressing the nerve.", sequence="T2")],
 ["Leaning on the elbow, prolonged flexion (habitual, occupational, perioperative)", "Old elbow fracture (tardy ulnar palsy)", "Arthritis, ganglion", "Subluxing ulnar nerve"],
 [("C8 radiculopathy or lower trunk plexopathy", "Sensory loss extends to the medial forearm, thenar muscles involved, neck or shoulder pain"), ("Ulnar neuropathy at the wrist", "Dorsal hand sensation and forearm muscles spared; cyclist's palsy or ganglion"), ("Motor neuron disease", "No sensory loss, wasting spreads to median muscles")],
 ["Avoid leaning and prolonged flexion; elbow pad or night extension splint", "Electrodiagnosis to confirm the elbow site and grade severity", "Surgical decompression or transposition for progressive weakness or failure of conservative measures"],
 [R("sp-ulnar-nerve-entrapment"), R("sp-ulnar-neuropathy"), R("sp-ulnar-nerve")], nerve("ulnar-nerve-l"), hint("axial", -55, -20, -140, "ulnar nerve behind the medial epicondyle (virtual)"), eponyms=["cubital tunnel syndrome", "tardy ulnar palsy"]))

E.append(mono("syn-radial-neuropathy", "Radial neuropathy (Saturday night palsy)", "entrapment", ["nerve-radial", "plexus-brachial"],
 "A patient wakes after falling asleep drunk with an arm draped over a chair and finds the wrist and fingers hanging limp: the wrist cannot be extended, the fingers cannot be straightened at the knuckles, and the thumb cannot be extended or abducted in the plane of the hand. Grip feels weak because the wrist cannot be stabilized, but with the wrist held up by the examiner the grip is strong. The triceps is spared and there is a small patch of numbness on the back of the hand between the thumb and index finger.",
 [D("motor", "ipsilateral", "wrist and finger extensors, brachioradialis, supinator, thumb extensors and abductor", "Wrist drop and finger drop; weak brachioradialis; triceps spared in spiral groove lesions", "nerve-radial"), D("sensory-light-touch", "ipsilateral", "dorsum of the first web space", "Small area of sensory loss on the dorsolateral hand; often minimal", "nerve-radial"), D("reflex", "ipsilateral", "brachioradialis", "Reduced brachioradialis reflex; triceps reflex normal", "nerve-radial"), D("motor", "n/a", "grip and finger abduction", "Apparent grip and interosseous weakness that corrects when the wrist is passively extended (false ulnar weakness)", "nerve-ulnar")],
 "The radial nerve winds around the back of the humerus in the spiral groove, where it lies directly on bone and is compressed by the edge of a chair or by a fracture. The branches to the triceps leave above the groove, so a groove lesion spares elbow extension and the triceps reflex, whereas an axillary lesion (crutch palsy) paralyzes the triceps too and involves the posterior cutaneous nerve of the arm. Below the groove the nerve supplies the brachioradialis, the wrist extensors and, through the posterior interosseous branch, the finger and thumb extensors, so all of these fail together: the wrist drops, the fingers cannot extend at the metacarpophalangeal joints (the interphalangeal joints still extend through the lumbricals and interossei) and the thumb cannot extend. Because the finger flexors and the intrinsic muscles work best with the wrist extended, the patient's grip and finger spreading appear weak until the examiner supports the wrist, a trap that mimics a combined median and ulnar lesion. The superficial radial sensory branch supplies only the dorsum of the radial hand, so sensory loss is small, and the deep branch (posterior interosseous nerve) is purely motor, so an entrapment at the supinator produces finger drop with preserved wrist extension (radial deviation from the intact extensor carpi radialis) and no sensory loss at all. The nerve is peripheral and the deficit ipsilateral.",
 [EMG("Conduction block or slowing of the radial nerve across the spiral groove with denervation in the extensor muscles but not the triceps; superficial radial sensory response reduced."), pathol("Humeral fracture", "CT", "Midshaft humeral fracture with the nerve in the fracture line; ultrasound can show nerve continuity.", sequence="CT non-contrast"), pathol("Posterior interosseous compression", "MRI", "Mass, ganglion or fibrous arcade of Frohse at the supinator with denervation edema of the extensor muscles.", sequence="STIR")],
 ["Compression in the spiral groove during deep sleep or intoxication", "Humeral shaft fracture", "Crutch compression in the axilla", "Posterior interosseous entrapment at the supinator (finger drop without wrist drop)", "Lead poisoning, vasculitis (bilateral)"],
 [("C7 radiculopathy", "Triceps weak with the extensors, wrist flexors also weak, neck pain, C7 sensory loss"), ("Cortical hand (small motor cortex infarct)", "Weakness mainly of finger extension with brisk reflexes and cortical sensory signs"), ("Lead neuropathy", "Bilateral wrist drop, abdominal pain, anemia")],
 ["Wrist splint in extension to preserve function while awaiting recovery; most compressive palsies recover within 2–4 months", "EMG at 3 weeks if no early improvement to distinguish conduction block from axonal loss", "Surgical exploration for fracture-associated palsies without recovery"],
 [R("sp-compressive-radial-neuropathy"), R("sp-radial-nerve")], nerve("radial-nerve-l"), hint("axial", -55, -25, -120, "radial nerve in the spiral groove (virtual)"), eponyms=["Saturday night palsy", "honeymoon palsy"]))

E.append(mono("syn-femoral-neuropathy", "Femoral neuropathy", "entrapment", ["nerve-femoral", "plexus-lumbosacral", "roots-l2-s1"],
 "After a long operation in the lithotomy position, or with a retroperitoneal hematoma in an anticoagulated patient, a patient cannot straighten the knee and the leg buckles on stairs. The quadriceps is weak and later wasted, the knee jerk is absent, and sensation is reduced over the front of the thigh and the inner side of the leg down to the ankle. Hip adduction is normal, which separates the lesion from the L3–L4 roots or the lumbar plexus.",
 [D("motor", "ipsilateral", "quadriceps, iliopsoas (proximal lesions)", "Weak knee extension with buckling; weak hip flexion if the lesion is above the inguinal ligament", "nerve-femoral"), D("reflex", "ipsilateral", "knee", "Absent patellar reflex", "nerve-femoral"), D("sensory-light-touch", "ipsilateral", "anterior and medial thigh, medial leg to the ankle (saphenous)", "Sensory loss in the femoral and saphenous distribution", "nerve-femoral"), D("motor", "n/a", "hip adductors", "Adduction spared (obturator nerve), distinguishing it from an L3–L4 root or plexus lesion", "nerve-obturator")],
 "The femoral nerve forms in the psoas from the L2–L4 roots, emerges at its lateral border, runs in the groove between the psoas and iliacus beneath the iliac fascia, and passes under the inguinal ligament to divide into branches for the quadriceps and sartorius and the saphenous nerve for the medial leg. Within the pelvis it is vulnerable to compression by a hematoma in the iliacus muscle in anticoagulated or hemophiliac patients, to stretching by prolonged hip flexion and abduction in the lithotomy position, to retractors in pelvic surgery and to diabetic ischemia. A lesion here paralyzes the quadriceps and, if proximal, the iliopsoas, abolishes the knee reflex whose arc runs through the nerve, and produces sensory loss over the anterior thigh and along the saphenous territory on the medial leg. The obturator nerve arises from the same roots but leaves the plexus separately through the obturator foramen, so hip adduction is preserved in a femoral neuropathy and lost in a lumbar plexus or L3–L4 root lesion, and the L4 root is further distinguished by its contribution to the tibialis anterior. Sensory loss in a femoral lesion extends to the ankle, well beyond the L2–L3 dermatomes that a root lesion would involve. The deficit is ipsilateral, being a peripheral nerve. Diabetic lumbosacral radiculoplexus neuropathy (diabetic amyotrophy) produces a painful, asymmetric picture that begins in femoral territory but spreads beyond it, with weight loss.",
 [pathol("Iliacus or psoas hematoma", "CT", "Hyperdense collection within the iliacus or psoas muscle displacing the nerve; urgent in anticoagulated patients.", sequence="CT non-contrast"), EMG("Reduced femoral motor amplitude with denervation of the quadriceps and iliopsoas but not the adductors or paraspinals; saphenous sensory response reduced in postganglionic lesions."), pathol("Pelvic mass", "MRI", "Tumor or abscess along the psoas compressing the nerve; diabetic amyotrophy shows plexus and root enhancement.", sequence="T1+Gd")],
 ["Retroperitoneal or iliacus hematoma", "Lithotomy position, hip surgery, pelvic surgery", "Diabetic radiculoplexus neuropathy", "Pelvic tumor or abscess", "Femoral catheterization"],
 [("L3–L4 radiculopathy", "Back pain, adductor weakness, paraspinal denervation, sensory loss confined to the L3–L4 dermatomes"), ("Lumbar plexopathy", "Adductors and other nerves involved, often painful, with diabetes or malignancy"), ("Quadriceps myopathy or inclusion body myositis", "Bilateral, no sensory loss, reflexes preserved until late")],
 ["Reverse anticoagulation and consider surgical decompression for a hematoma with progressive deficit", "Knee brace and physiotherapy; most compressive lesions recover over months", "Screen for diabetes and malignancy when no mechanical cause is evident"],
 [R("sp-thigh-femoral-nerve"), R("sp-neuropathy")], nerve("femoral-nerve-l"), hint("coronal", -60, -10, -200, "femoral nerve beneath the inguinal ligament (virtual)")))

E.append(mono("syn-meralgia-paresthetica", "Meralgia paresthetica", "entrapment", ["nerve-lateral-femoral-cutaneous", "plexus-lumbosacral"],
 "An overweight patient, or one who has recently lost weight or wears a heavy belt, complains of burning, tingling and numbness over an oval patch on the outer thigh, worse on standing and walking and relieved by sitting. There is no weakness, the knee reflex is normal and the sensory loss is sharply confined to the anterolateral thigh above the knee. Pressure just inside the anterior superior iliac spine reproduces the discomfort.",
 [D("sensory-light-touch", "ipsilateral", "anterolateral thigh", "Burning paresthesias, allodynia and later numbness in an oval area on the lateral thigh", "nerve-lateral-femoral-cutaneous"), D("motor", "n/a", "none", "No weakness; knee reflex normal", "nerve-femoral"), D("pain", "ipsilateral", "lateral thigh", "Pain worse with standing, hip extension and tight clothing", "nerve-lateral-femoral-cutaneous")],
 "The lateral femoral cutaneous nerve is a purely sensory branch of the lumbar plexus from the L2 and L3 roots that crosses the iliacus and leaves the pelvis by passing under, through or over the lateral end of the inguinal ligament just medial to the anterior superior iliac spine, where it turns sharply from a horizontal to a vertical course. At that angle it is compressed by a tight belt, a protuberant abdomen, pregnancy, prolonged hip extension or scar, and it can be injured during pelvic surgery or iliac crest bone harvest. Because the nerve carries no motor fibers and no reflex arc, the syndrome is purely sensory, which is its most useful feature: any weakness of the quadriceps or loss of the knee jerk means the femoral nerve or the L2–L4 roots are involved instead. The territory is the anterolateral thigh from the greater trochanter to the knee, which overlaps the L2–L3 dermatomes, but a root lesion would produce back pain, would extend medially and would involve the iliopsoas or quadriceps. The lesion is peripheral and ipsilateral, though it is bilateral in about a fifth of patients with obesity or diabetes. Sensory conduction of the nerve is technically difficult, so the diagnosis is clinical, confirmed if necessary by relief after a local anesthetic block at the inguinal ligament.",
 [pathol("Meralgia paresthetica", "US", "Enlarged, hypoechoic lateral femoral cutaneous nerve at the inguinal ligament; ultrasound also guides the diagnostic block.", sequence="n/a"), pathol("Pelvic or retroperitoneal lesion (atypical cases)", "MRI", "Mass along the nerve's course over the iliacus when the onset is progressive or bilateral without a mechanical cause.", sequence="T2")],
 ["Obesity, pregnancy, tight belts and clothing", "Diabetes", "Prolonged hip extension or lying prone", "Pelvic surgery, iliac crest harvest, hernia repair", "Retroperitoneal mass (rare)"],
 [("L2–L3 radiculopathy", "Back pain, weakness of hip flexion, sensory loss extending to the anterior and medial thigh"), ("Femoral neuropathy", "Quadriceps weakness and absent knee jerk"), ("Trochanteric bursitis", "Tenderness over the trochanter with normal sensation")],
 ["Remove the compression: weight loss, loose clothing; reassure, as most cases resolve", "Local anesthetic and steroid injection at the inguinal ligament", "Neuropathic pain agents; rarely surgical decompression or neurectomy"],
 [R("sp-meralgia-paresthetica"), R("sp-peripheral-nerve-injury")], nerve("lateral-femoral-cutaneous-nerve-l"), hint("coronal", -100, 10, -210, "lateral femoral cutaneous nerve at the anterior superior iliac spine (virtual)")))

E.append(mono("syn-sciatic-neuropathy", "Sciatic neuropathy", "traumatic", ["nerve-sciatic", "nerve-common-peroneal", "nerve-tibial", "plexus-lumbosacral"],
 "After a hip replacement, a posterior hip dislocation or an injection into the buttock, a patient has a flail foot that neither dorsiflexes nor plantar flexes, weak knee flexion, and numbness of the whole foot and the lateral leg, sparing the inner side of the leg. The ankle reflex is absent and the knee reflex is normal. The peroneal division is usually worse than the tibial, so the picture can mimic a foot drop from the fibular head until the plantar flexors are examined.",
 [D("motor", "ipsilateral", "hamstrings, all muscles below the knee", "Weak knee flexion; foot drop with weak eversion, inversion and plantar flexion (peroneal division usually more affected than tibial)", "nerve-sciatic"), D("sensory-light-touch", "ipsilateral", "lateral leg, dorsum and sole of the foot", "Sensory loss in the peroneal and tibial territories; medial leg (saphenous) spared", "nerve-sciatic"), D("reflex", "ipsilateral", "ankle", "Absent ankle jerk with preserved knee jerk", "nerve-tibial"), D("pain", "ipsilateral", "buttock and posterior thigh", "Deep pain in the buttock radiating down the leg", "nerve-sciatic")],
 "The sciatic nerve carries the L4–S3 fibers of the sacral plexus out of the pelvis through the greater sciatic foramen beneath the piriformis, runs down the posterior thigh supplying the hamstrings, and divides above the knee into the tibial and common peroneal nerves. Its two divisions are separate bundles from the outset, and the peroneal division, with fewer and larger fascicles and less connective tissue, tethered at the fibular head, is the more vulnerable to stretch, so a sciatic lesion at the hip frequently presents as a predominant foot drop that can be mistaken for a common peroneal palsy; the distinction rests on finding weakness of the tibial-innervated plantar flexors and invertors and the hamstrings, an absent ankle reflex and sensory loss on the sole. The knee reflex and hip adduction are normal because the femoral and obturator nerves are separate, and the medial leg is spared because the saphenous nerve is femoral. The lesion is peripheral and ipsilateral. A lesion of the L5 and S1 roots produces a similar distribution but adds back pain, gluteal weakness from the superior and inferior gluteal nerves, which leave the plexus before the sciatic nerve is formed, and paraspinal denervation on EMG; a lumbosacral plexopathy involves the gluteal nerves as well. Common causes at the hip are surgery, dislocation, hematoma and prolonged compression in coma, and in the thigh, injections and tumors.",
 [EMG("Denervation in both peroneal and tibial-innervated muscles and the hamstrings, sparing the glutei and paraspinals; sural and superficial peroneal sensory responses reduced."), pathol("Hip or gluteal lesion", "MRI", "Hematoma, tumor, or postoperative change around the nerve at the sciatic notch; T2 hyperintensity and enlargement of the nerve on MR neurography.", sequence="STIR"), pathol("Hip dislocation or arthroplasty", "CT", "Posterior dislocation, acetabular fracture fragments or a prosthetic component in contact with the nerve.", sequence="CT non-contrast")],
 ["Hip arthroplasty or posterior dislocation", "Gluteal injection", "Prolonged compression during coma, surgery or sitting", "Gluteal or thigh hematoma", "Tumor of the nerve or adjacent tissue", "Piriformis syndrome (contested)"],
 [("Common peroneal neuropathy at the fibular head", "Plantar flexion, inversion and the ankle reflex are normal; sensory loss confined to the dorsum and lateral leg"), ("L5–S1 radiculopathy", "Back pain, gluteal weakness, paraspinal denervation, straight leg raise positive"), ("Lumbosacral plexopathy", "Gluteal muscles and other plexus nerves involved")],
 ["Ankle-foot orthosis and physiotherapy; monitor for recovery over 6–18 months", "Urgent decompression for hematoma or an identifiable compressive lesion", "EMG at 3–4 weeks to define the lesion and prognosis"],
 [R("sp-sciatic-nerve"), R("sp-sciatica"), R("sp-peripheral-nerve-injury")], nerve("sciatic-nerve-l"), hint("coronal", -90, -50, -220, "sciatic nerve at the greater sciatic notch (virtual)")))

E.append(mono("syn-peroneal-palsy-foot-drop", "Common peroneal neuropathy (foot drop)", "entrapment", ["nerve-common-peroneal", "nerve-sciatic", "roots-l2-s1"],
 "A thin patient who has lost weight, or who has been crossing the legs or lying with the leg against a bed rail, trips over the toes of one foot and lifts the knee high to clear it. The foot cannot be dorsiflexed or everted and the toes cannot be extended, but inversion and plantar flexion are strong, the ankle reflex is normal, and sensation is lost over the dorsum of the foot and the lateral lower leg. Tapping the nerve at the fibular neck tingles into the foot.",
 [D("motor", "ipsilateral", "tibialis anterior, extensor hallucis and digitorum longus, peroneus longus and brevis", "Foot drop with weak eversion; steppage gait", "nerve-common-peroneal"), D("motor", "n/a", "tibialis posterior, gastrocnemius", "Inversion and plantar flexion spared, ankle reflex normal", "nerve-tibial"), D("sensory-light-touch", "ipsilateral", "dorsum of the foot and lateral leg", "Sensory loss in the superficial and deep peroneal distribution", "nerve-common-peroneal")],
 "The common peroneal nerve leaves the sciatic nerve above the knee, winds around the neck of the fibula just beneath the skin and passes through the fibrous tunnel of the peroneus longus origin to divide into the superficial branch, which everts the foot and supplies the lateral leg and most of the dorsum, and the deep branch, which dorsiflexes the ankle and toes and supplies the first web space. At the fibular neck the nerve lies on bone with no muscle cover, so it is compressed by crossing the legs, squatting, a tight cast, a bed rail during coma or surgery, or a ganglion, and rapid weight loss removes the fat that protected it. The result is weakness of dorsiflexion, toe extension and eversion with sensory loss on the dorsum and lateral leg. The muscles that separate it from the other causes of foot drop are those that share the same roots but travel by other nerves: the tibialis posterior (L5, tibial nerve), which inverts the foot, and the gluteus medius (L5, superior gluteal nerve), which abducts the hip, are weak in an L5 radiculopathy and normal in a peroneal palsy, and the plantar flexors and ankle reflex (S1, tibial nerve) are weak or absent in a sciatic lesion. The lesion is peripheral and ipsilateral. Conduction studies show slowing or block across the fibular head, and a preserved superficial peroneal sensory response with a foot drop points instead to a root lesion, where the dorsal root ganglion is spared.",
 [EMG("Conduction block or focal slowing of the peroneal nerve across the fibular head with denervation of the tibialis anterior and peroneus longus but not the tibialis posterior or short head of biceps; superficial peroneal sensory response reduced."), pathol("Fibular neck compression or ganglion", "US", "Swollen nerve at the fibular neck or an intraneural ganglion arising from the tibiofibular joint.", sequence="n/a"), pathol("Knee or fibular injury", "MRI", "Fracture, knee dislocation or hematoma with nerve involvement; denervation edema in the anterior compartment.", sequence="STIR")],
 ["Habitual leg crossing, squatting, weight loss", "Compression during surgery or coma", "Tight cast or bandage", "Fibular neck fracture or knee dislocation", "Intraneural ganglion", "Vasculitis, diabetes, hereditary neuropathy with pressure palsies (recurrent)"],
 [("L5 radiculopathy", "Back pain, weak inversion and hip abduction, sensory loss extending to the big toe and lateral thigh, paraspinal denervation"), ("Sciatic neuropathy", "Weak plantar flexion, absent ankle jerk, sole numb"), ("Anterior horn or motor neuron disease", "No sensory loss, fasciculation, spreads"), ("Upper motor neuron foot drop", "Spasticity, brisk reflexes, extensor plantar")],
 ["Remove the compression and protect the fibular head; ankle-foot orthosis", "Nerve conduction studies to localize and to establish conduction block (good prognosis) versus axonal loss", "Surgical decompression for a ganglion or a persistent lesion"],
 [R("sp-foot-drop"), R("sp-calf-common-peroneal-nerve"), R("sp-peroneal-nerve-injury")], nerve("common-peroneal-nerve-l"), hint("axial", -80, -40, -300, "common peroneal nerve at the fibular neck (virtual)")))

E.append(mono("syn-tarsal-tunnel", "Tarsal tunnel syndrome", "entrapment", ["nerve-tibial", "nerve-sciatic"],
 "A patient describes burning pain and tingling in the sole of the foot and the toes, worse after prolonged standing or walking and sometimes at night, with relief on resting or removing shoes. Sensation may be reduced on the sole while the dorsum of the foot and the heel are normal, and in long-standing cases the small muscles of the foot are wasted and the toes clawed. Tapping behind the medial malleolus reproduces the tingling.",
 [D("sensory-light-touch", "ipsilateral", "sole of the foot and toes (medial and lateral plantar nerves)", "Burning paresthesias and sensory loss of the sole, sparing the dorsum; heel sometimes spared", "nerve-tibial"), D("pain", "ipsilateral", "ankle and sole", "Pain worse with standing and walking, Tinel sign at the flexor retinaculum", "nerve-tibial"), D("motor", "ipsilateral", "intrinsic foot muscles", "Weakness and wasting of the abductor hallucis and toe flexors with clawing in chronic cases; calf muscles and ankle reflex normal", "nerve-tibial")],
 "Behind the medial malleolus the tibial nerve passes beneath the flexor retinaculum in the tarsal tunnel, with the tendons of the tibialis posterior, flexor digitorum longus and flexor hallucis longus and the posterior tibial vessels, and there divides into the medial and lateral plantar nerves for the sole and the intrinsic muscles and the calcaneal branch for the heel. Compression within the tunnel by tenosynovitis, a ganglion, varicosities, a bony spur after an ankle fracture, hindfoot valgus or a tight retinaculum produces the plantar sensory symptoms and, later, intrinsic muscle weakness. The muscles of the calf and the ankle reflex are supplied by the tibial nerve above the tunnel and are unaffected, which separates the syndrome from a proximal tibial or sciatic lesion, and the dorsum of the foot is supplied by the peroneal nerves and is spared, which separates it from a polyneuropathy that would involve the whole foot symmetrically on both sides. The calcaneal branch often leaves the nerve above the retinaculum, so heel sensation may be preserved. An S1 radiculopathy affects the sole too but adds calf weakness, an absent ankle reflex and back pain. The deficit is peripheral and ipsilateral. Electrodiagnosis is technically demanding, and the diagnosis rests on the clinical pattern, a positive Tinel sign, imaging of the tunnel and the response to a local anesthetic block.",
 [EMG("Prolonged distal latencies of the medial and lateral plantar nerves with denervation of the abductor hallucis and abductor digiti minimi; normal peroneal and proximal tibial conduction."), pathol("Space-occupying lesion in the tunnel", "MRI", "Ganglion, varicosities, tenosynovitis, lipoma or accessory muscle within the tarsal tunnel compressing the nerve on axial T2.", sequence="T2"), pathol("Bony compression", "CT", "Talocalcaneal coalition, exostosis or malunited fracture narrowing the tunnel.", sequence="CT non-contrast")],
 ["Idiopathic with hindfoot deformity", "Ganglion, varicosities, tenosynovitis", "Ankle fracture or sprain", "Rheumatoid arthritis, diabetes, hypothyroidism", "Space-occupying lesions (lipoma, nerve sheath tumor)"],
 [("Plantar fasciitis", "Pain under the heel worst on first steps, no sensory loss or Tinel sign"), ("Distal polyneuropathy", "Bilateral, symmetric, dorsum involved, reduced ankle reflexes"), ("S1 radiculopathy", "Back pain, calf weakness, absent ankle jerk"), ("Morton neuroma", "Pain between the metatarsal heads, focal")],
 ["Orthotics to correct hindfoot valgus, activity modification, anti-inflammatory measures", "Steroid injection into the tunnel for inflammatory causes", "Surgical release for a demonstrable mass or persistent symptoms with electrodiagnostic confirmation"],
 [R("sp-tarsal-tunnel-syndrome"), R("sp-posterior-tarsal-tunnel-syndrome"), R("sp-electrodiagnostic-evaluation-of-tarsal-tunnel-neuropathy")], nerve("tibial-nerve-l"), hint("axial", -70, -50, -420, "tibial nerve behind the medial malleolus (virtual)")))

E.append(syn("syn-length-dependent-polyneuropathy", "Length-dependent sensorimotor polyneuropathy", "metabolic-toxic", ["dorsal-root-ganglion", "nerve-tibial", "nerve-common-peroneal", "nerve-median", "nerve-ulnar"], "bilateral",
 "A patient with long-standing diabetes describes numbness and burning of both feet that began in the toes and has crept up to the ankles over a year or two, with unsteadiness in the dark. The ankle reflexes are absent, vibration sense is lost at the toes and reduced at the ankles, pin-prick is dulled in a stocking distribution, and when the numbness reaches the knees the fingertips begin to tingle. Toe extension is mildly weak and the feet are dry and hairless.",
 [D("sensory-light-touch", "bilateral", "stocking then glove distribution", "Symmetric distal loss of all modalities beginning in the toes; large-fiber loss gives vibration and proprioceptive loss with sensory ataxia, small-fiber loss gives burning pain and reduced pin-prick", "dorsal-root-ganglion"), D("reflex", "bilateral", "ankles first", "Absent ankle reflexes with preserved knee reflexes until late", "nerve-tibial"), D("motor", "bilateral", "intrinsic foot muscles, toe and ankle dorsiflexors", "Mild distal weakness and wasting late in the course", "nerve-common-peroneal"), D("autonomic", "bilateral", "distal", "Dry skin, hair loss, orthostatic hypotension, gastroparesis, erectile dysfunction in small-fiber and autonomic involvement", "sympathetic-trunk")],
 "In a metabolic, toxic or hereditary neuropathy the axon is affected along its whole length, and the longest axons fail first because the distal part of a long axon is farthest from the cell body that maintains it. The longest axons in the body run from the dorsal root ganglia and anterior horns of the lumbosacral cord to the toes, so symptoms begin in the toes of both feet simultaneously and ascend, and when the sensory loss has reached mid-calf the axons of comparable length to the fingertips begin to fail, giving the glove that follows the stocking; the anterior trunk may develop a patch of loss when the intercostal axons reach the threshold length. The process is symmetric because both legs' axons are equally long, and there is no crossed pattern, since the lesion lies entirely in the peripheral nervous system in the ipsilateral nerves. Sensory fibers suffer before motor fibers in most axonal neuropathies, and the ankle reflex, whose afferent limb is the longest sensory arc, disappears first. Large-fiber loss removes vibration and proprioception and causes sensory ataxia and a positive Romberg; small-fiber loss produces burning pain, loss of pin-prick and temperature discrimination and autonomic failure, and may occur alone with normal conduction studies. Asymmetry, proximal onset, marked weakness, a rapid course or cranial nerve involvement argue against a length-dependent process and point to a demyelinating, vasculitic or infiltrative neuropathy.",
 [pathol("Axonal sensorimotor polyneuropathy", "EMG/NCS", "Reduced sural and superficial peroneal sensory amplitudes, then reduced peroneal and tibial motor amplitudes with relatively preserved conduction velocities; distal denervation. Small-fiber neuropathy has normal studies.", sequence="n/a"), pathol("Skin biopsy (small fiber)", "EMG/NCS", "Reduced intraepidermal nerve fiber density at the distal leg compared with the thigh.", sequence="n/a"), pathol("Demyelinating neuropathy (mimic)", "EMG/NCS", "Slowed conduction velocities, prolonged distal latencies and conduction block point to CIDP or hereditary demyelination instead.", sequence="n/a")],
 ["Diabetes mellitus", "Alcohol and nutritional deficiency (B12, thiamine, B6 excess)", "Chemotherapy (platinum, taxanes, vincristine)", "Chronic kidney disease", "Hereditary (Charcot–Marie–Tooth)", "Paraproteinemia, amyloidosis, HIV, hypothyroidism", "Idiopathic in the elderly"],
 [("Lumbar spinal stenosis", "Symptoms with walking relieved by sitting, asymmetric, root pattern"), ("Bilateral tarsal tunnel", "Soles only, dorsum spared"), ("Myelopathy", "Brisk reflexes and extensor plantars with a sensory level"), ("Sensory neuronopathy (ganglionopathy)", "Non-length-dependent, ataxic, arms and face involved early; paraneoplastic or Sjögren")],
 ["Screen: glucose tolerance, B12, serum protein electrophoresis, renal and thyroid function; nerve conduction studies to confirm the axonal length-dependent pattern", "Treat the cause and control pain with gabapentinoids, duloxetine or tricyclics", "Foot care and fall prevention"],
 [R("sp-diabetic-peripheral-neuropathy"), R("sp-neuropathy"), R("sp-electrodiagnostic-evaluation-of-peripheral-neuropathy")], marker=nerve("tibial-nerve-l", "tibial-nerve-r"), imagingHint=hint("axial", 0, -45, -160, "lumbosacral roots and dorsal root ganglia"), preset="anterior"))

E.append(syn("syn-guillain-barre", "Guillain–Barré syndrome", "demyelinating", ["spinal-nerve-root-dermatome", "dorsal-root-ganglion", "cauda-equina", "cn-07-facial", "nerve-phrenic"], "bilateral",
 "Two weeks after a diarrheal illness a young adult develops tingling in the feet and hands and, over the following days, weakness that begins in the legs and climbs to the arms and face, so that within a week they cannot walk and both sides of the face are weak. The reflexes have disappeared, sensation is only mildly reduced, and the pulse and blood pressure swing unpredictably. Breathing becomes shallow, and the vital capacity is measured every few hours.",
 [D("motor", "bilateral", "legs then arms, proximal and distal, ascending", "Rapidly progressive symmetric flaccid weakness reaching a nadir within 4 weeks", "spinal-nerve-root-dermatome"), D("reflex", "bilateral", "generalized", "Areflexia or hyporeflexia", "dorsal-root-ganglion"), D("sensory-light-touch", "bilateral", "distal", "Paresthesias with mild objective loss; back and limb pain from root inflammation", "dorsal-root-ganglion"), D("cranial-nerve", "bilateral", "face, bulbar, ocular", "Bilateral facial weakness in half, dysphagia, ophthalmoplegia in the Miller Fisher variant", "cn-07-facial"), D("autonomic", "bilateral", "cardiovascular, bladder, gut", "Labile blood pressure, arrhythmias, ileus, retention", "sympathetic-trunk"), D("other", "bilateral", "diaphragm and intercostals", "Respiratory failure requiring ventilation in a quarter", "nerve-phrenic")],
 "An infection, most often Campylobacter jejuni, provokes antibodies that cross-react with gangliosides on peripheral nerve myelin or axons, and within weeks the immune attack strips myelin from the spinal roots and peripheral nerves, or in the axonal forms destroys the axons at the nodes of Ranvier. Because the roots are inflamed where they leave the cord and the process is diffuse, weakness is symmetric, involves proximal as well as distal muscles and is not length-dependent, distinguishing it from the toxic and metabolic neuropathies; it ascends because the longest fibers and the most heavily myelinated motor fibers fail first, but it is not a lesion at any level of the cord, so there is no sensory level, no sphincter loss at the outset and no upper motor neuron sign. The reflex arcs run through the demyelinated roots, so all reflexes are lost early, even in muscles that are still strong, which is the sign that most reliably points away from a spinal cord or muscle disease. Cranial nerves are involved because their roots are similarly attacked, the facial nerve most often, and the autonomic fibers in the vagus and sympathetic chain because they are peripheral nerves too. Everything is bilateral and peripheral; there is no crossing to reason about. The CSF protein rises as the inflamed roots leak protein into the lumbar cistern while the cell count stays normal, the albuminocytological dissociation, though this may take a week to appear. Death comes from respiratory failure or autonomic arrhythmia, both preventable with monitoring.",
 [pathol("Nerve root enhancement", "MRI", "Smooth enhancement and thickening of the cauda equina and cranial nerve roots on post-contrast T1; excludes cord compression and myelitis.", sequence="T1+Gd"), pathol("Demyelinating polyradiculoneuropathy", "EMG/NCS", "Prolonged distal latencies, absent or prolonged F waves, conduction block and temporal dispersion in the demyelinating form; reduced amplitudes with preserved velocities in axonal forms. May be normal in the first week.", sequence="n/a"), pathol("Albuminocytological dissociation", "LP/CSF", "Raised CSF protein with a normal cell count after the first week; pleocytosis suggests HIV, Lyme or malignancy.", sequence="n/a")],
 ["Post-infectious (Campylobacter, cytomegalovirus, Epstein–Barr virus, Mycoplasma, Zika)", "Post-vaccination (rare)", "Surgery", "Idiopathic"],
 [("Acute spinal cord lesion (transverse myelitis, compression)", "Sensory level, early sphincter loss, reflexes return brisk; MRI"), ("Myasthenia gravis", "Fatigable ocular and bulbar weakness, normal reflexes and sensation"), ("Botulism", "Descending paralysis with fixed dilated pupils and dry mouth"), ("Acute intermittent porphyria, tick paralysis, hypokalemia", "History, urine porphyrins, tick search, potassium")],
 ["Admit for vital capacity and cardiac monitoring; intubate for falling vital capacity or bulbar failure", "Intravenous immunoglobulin or plasma exchange within 2 weeks of onset; steroids are ineffective", "Thromboprophylaxis, pain control, early physiotherapy; most recover but a fifth remain disabled"],
 [R("sp-guillain-barre-syndrome"), R("sp-electrodiagnostic-evaluation-of-acute-inflammatory-demyelinat")], marker=structs("cauda-equina"), imagingHint=hint("sagittal", 0, -50, -170, "cauda equina roots"), preset="posterior", eponyms=["acute inflammatory demyelinating polyradiculoneuropathy", "Landry ascending paralysis"]))

E.append(syn("syn-myasthenia-gravis", "Myasthenia gravis", "neuromuscular", ["neuromuscular-junction", "motor-unit", "cn-03-oculomotor", "nucleus-ambiguus"], "bilateral",
 "A woman in her twenties, or a man in his sixties, notices that by evening her eyelids droop and she sees double, that chewing tires halfway through a meal and her voice fades to a nasal whisper on the telephone, and that she cannot hold her arms up to dry her hair. In the morning everything is better. Examination shows fatigable ptosis on sustained upgaze, variable ophthalmoplegia that fits no single nerve, weakness of eye closure and neck flexion, normal reflexes, normal sensation and normal pupils.",
 [D("oculomotor", "bilateral", "extraocular muscles and levator, asymmetric", "Fatigable ptosis and diplopia not conforming to a nerve pattern; pupils spared", "neuromuscular-junction"), D("bulbar", "bilateral", "face, jaw, palate, larynx, tongue", "Fatigable chewing, nasal dysarthria, dysphagia, myasthenic snarl", "neuromuscular-junction"), D("motor", "bilateral", "neck flexors and proximal limbs", "Fatigable proximal weakness worse with activity and in the evening", "motor-unit"), D("other", "bilateral", "diaphragm and accessory muscles", "Myasthenic crisis: respiratory failure, often precipitated by infection or drugs", "nerve-phrenic"), D("reflex", "n/a", "preserved", "Normal reflexes, sensation and coordination", "dorsal-root-ganglion")],
 "Antibodies against the acetylcholine receptor, or in a minority against muscle-specific kinase, reduce the number of functioning receptors at the postsynaptic membrane of the neuromuscular junction. Each nerve impulse still releases acetylcholine, but with fewer receptors the endplate potential is closer to the firing threshold, and because the amount of acetylcholine released falls during a train of impulses, successive endplate potentials drop below threshold and muscle fibers fail one by one: weakness that increases with use and recovers with rest, the defining feature. Muscles with a high firing rate and a low safety factor, the extraocular muscles and the levator, fail first, so ptosis and diplopia are the commonest presentation, and the pattern of eye movement weakness varies from hour to hour and fits no nerve or nuclear lesion; the pupil, a smooth muscle supplied by autonomic fibers, is never involved, which distinguishes ocular myasthenia from a third nerve palsy. The disease is a disorder of transmission, not of the nerve or the muscle, so there is no sensory loss, the reflexes are preserved, muscle bulk is normal until late and the nerve conduction velocities are normal, while repetitive stimulation at low frequency shows the decrement of failing junctions and single-fiber EMG shows jitter. Everything is bilateral though often asymmetric, and no crossing logic applies. The thymus is abnormal in most patients, hyperplastic in the young and a thymoma in about a tenth, and its removal helps. Bulbar and respiratory weakness can progress within hours to a crisis, and many drugs, including aminoglycosides, magnesium and beta-blockers, unmask or worsen the disease.",
 [pathol("Thymoma or thymic hyperplasia", "CT", "Anterior mediastinal mass (thymoma) or an enlarged thymus on contrast CT of the chest, required in every new diagnosis.", sequence="CT contrast"), pathol("Neuromuscular transmission defect", "EMG/NCS", "Decrement of more than 10% on 3 Hz repetitive nerve stimulation in a weak muscle; increased jitter and blocking on single-fiber EMG (most sensitive).", sequence="n/a"), pathol("Serology", "EMG/NCS", "Serology alongside electrodiagnosis: acetylcholine receptor antibodies in 85% of generalized and 50% of ocular cases; MuSK antibodies in most of the rest.", sequence="n/a")],
 ["Autoimmune (acetylcholine receptor antibodies)", "MuSK antibody myasthenia", "Thymoma-associated", "Drug-induced (penicillamine, immune checkpoint inhibitors)", "Congenital myasthenic syndromes"],
 [("Lambert–Eaton myasthenic syndrome", "Proximal leg weakness that improves briefly with exercise, areflexia, dry mouth; increment on high-frequency stimulation; small cell lung cancer"), ("Ocular motor nerve palsies", "Fixed pattern, pupil may be involved, no fatigability"), ("Botulism", "Descending, fixed dilated pupils, autonomic failure"), ("Oculopharyngeal or mitochondrial myopathy", "Slowly progressive, non-fluctuating ptosis, no antibodies"), ("Thyroid eye disease", "Restrictive, with proptosis and lid retraction")],
 ["Confirm with antibodies and electrodiagnosis; CT of the chest for thymoma; check thyroid function", "Pyridostigmine for symptoms; corticosteroids and steroid-sparing immunosuppression for generalized disease; thymectomy for thymoma and for young antibody-positive patients", "Crisis: measure vital capacity, intubate early, give intravenous immunoglobulin or plasma exchange; review the drug list for junction-blocking agents"],
 [R("sp-myasthenia-gravis"), R("sp-neonatal-myasthenia-gravis"), R("sp-anesthesia-for-patients-with-myasthenia-gravis")], marker=structs("cn-03-oculomotor-l", "cn-03-oculomotor-r"), imagingHint=hint("coronal", 0, 20, -20, "extraocular muscles and levator (the first muscles to fatigue)"), preset="anterior"))

write(E)
